### DISCUSSION TITLE
KubernetesExecutor: Cannot Pull Image, because Image ist ":"

### DISCUSSION THREAD

**Discussion by Kinchkun** [apache/airflow#13258] [Q&A] [answered]
Hi,

today we upgraded Airflow v.1.10 to v2.0 and our kubernetes config doesn't work anymore.

We have the following pod file for kubernetes:

```
apiVersion: v1
kind: Pod
metadata:
  name: airflow-worker
spec:
  serviceAccountName: airflow-scheduler
  containers:
    - name: airflow-worker
      image: "host.docker.internal:5000/airflow:2"
      imagePullPolicy: Always
      ports:
        - containerPort: 6666
      env:
      # DB Settings
```

and we reference this file in the airflow.cfg:

```
[kubernetes]
# Path to the YAML pod file. If set, all other kubernetes-related fields are ignored.
pod_template_file = /opt/airflow/airflow-worker.yaml
```

This setup, worked fine in v1.10. In v2.0 when we execute a DAG the pod for the tasks cannot be created because of the following error:

```
 containerStatuses:
  - image: ':'
    imageID: ""
    lastState: {}
    name: base
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'Failed to apply default image tag ":": couldn''t parse image reference
          ":": invalid reference format'
        reason: InvalidImageName
```

It seems that the image name from the pod yaml `"host.docker.internal:5000/airflow:2"` isn't used.

It is a local development setup with minikube and based on the docker image `apache/airflow:master-python3.6`.

Thank you.
