### DISCUSSION TITLE
dags.gitSync containerTag in airflow 2.0

### DISCUSSION THREAD

**Discussion by rchojn** [apache/airflow#13758] [Q&A]
Hello, previously in airflow 1.10 I've used 

```
dags:
  gitSync:
    containerRepository: 
    containerTag: 

```
In airflow 2.0 we've got
```
dags:
  gitSync:
    repo: https://github.com/apache/airflow.git
```

I am using custom docker image for pulling dags. How to manage it now?
