### DISCUSSION TITLE
How to run docker command inside docker-compose Airflow2.0?

### DISCUSSION THREAD

**Discussion by alihossein** [apache/airflow#15516] [General] [answered]
I have install  Airflow 2.0  from [docker-compose](https://airflow.apache.org/docs/apache-airflow/2.0.2/docker-compose.yaml).

but I want to some changes and install some python packages.
so I decided to use a helper container inside docker-compose  :
```
 initializer:
    image: apache/airflow:2.0.1
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - airflow-worker
    command: [ "pip3.6 install --no-cache-dir -r requirements.txt"]  
 
``` 

but I get this error : 
```
airflow command error: argument GROUP_OR_COMMAND: invalid choice: 'pip3.6 install --no-cache-dir -r requirements.txt' (choose from 'celery', 'cheat-sheet', 'config', 'connections', 'dags', 'db', 'info', 'kerberos', 'kubernetes', 'plugins', 'pools', 'providers', 'roles', 'rotate-fernet-key', 'scheduler', 'sync-perm', 'tasks', 'users', 'variables', 'version', 'webserver'), see help above.
initializer_1        | usage: airflow [-h] GROUP_OR_COMMAND ...

```

how can I fix this problem? and how can I install my packages inside the image?
thanks.
