### DISCUSSION TITLE
Configuring remote logging on Helm chart

### DISCUSSION THREAD

**Discussion by osuarez84** [apache/airflow#15764] [Q&A]
Hi everyone,

I am trying to deploy Airflow in GKE using the official Helm chart. I want to use GCS as the logging sink so I set up a service account with the required permissions, configured the connector and also the variables related to the remote logging:

![image](https://user-images.githubusercontent.com/22023681/117683824-b8f18e00-b1b4-11eb-8293-3582f7ad0505.png)

The issue here is that although the env variables are correctly configured inside the pods the logs are not being written to the bucket. The Airflow version is 2.0.2.

Can anyone give some help with that? 
Is this the correct way to configure the remote logging using the chart? 

Thanks,

**Comment by ephraimbuddy** [comment]
Looks ok but seems you need to set this https://github.com/apache/airflow/blob/25caeda58b50eae6ef425a52e794504bc63855d1/chart/values.yaml#L890-L891 to True.

I usually do my remote logging configuration on the section above. In your case it would be:

```yaml
  logging:
    remote_logging: 'True'
    colored_console_log: 'False'
    remote_log_conn_id: gcloud_default
    remote_base_log_folder: gs://airflow-remote-logs-fea0a40e/logs
```
