### DISCUSSION TITLE
How install airflow by helm with example_dags from public github?

### DISCUSSION THREAD

**Discussion by patsevanton** [apache/airflow#15910] [Q&A] [answered]
Hello! Thanks for airflow!

I try install airflow by helm to Kubernetes.
How install airflow by helm with example_dags from public github?

Clone airfllow
```
git clone https://github.com/apache/airflow.git
cd airflow/chart/
helm dependency update
kubectl create namespace apatsev
```

I create value.yaml
```
dags:
  gitSync:
    enabled: true
    repo: https://github.com/apache/airflow.git
    branch: master
    rev: HEAD
    root: "/airflow/example_dags"
    dest: "/opt/airflow/dags"
    depth: 1
    maxFailures: 0
    subPath: ""
    wait: 60
    containerName: git-sync
    uid: 65533
    extraVolumeMounts: []
    env: []
```

Install airflow
```
helm install --set webserver.defaultUser.password=password,ingress.enabled=true,ingress.hosts[0]=airflow.192.168.22.8.sslip.io --namespace apatsev airflow -f values.yaml  ./
```
