### DISCUSSION TITLE
Unable to write to Network Volumes via DAGs

### DISCUSSION THREAD

**Discussion by vkandiva** [apache/airflow#16184] [Q&A]
I am unable to write a file to a network share in a DAG. Withing my DAG I am trying to write a result of an operation to a network folder. I am able to read well from the folder but end up with permission denied when trying to write anything.

Below is my docker-compose.yaml file for mapping the drives:
```
version: '3.5'
x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-airflow}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${_AIRFLOW_WWW_USER_USERNAME:-airflow}:${_AIRFLOW_WWW_USER_PASSWORD:-airflow}@postgres/airflow
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    postgres:
      condition: service_healthy
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./notebooks:/opt/airflow/notebooks
    - ./output:/opt/airflow/output
    - netfolder:/usr/local/airflow/netfolder

services:
  postgres:
    image: postgres-ssl
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.cer -c ssl_key_file=/var/lib/postgresql/server.key 
    environment:
      POSTGRES_USER:  ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      POSTGRES_PASSWORD:  ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      POSTGRES_DB: airflow
      POSTGRES_HOST: cube-airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${_AIRFLOW_WWW_USER_USERNAME}"]
      interval: 5s
      retries: 5
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: webserver --ssl-cert  ./server.cer --ssl-key ./server.key --port 443 
    ports:
      - 443:443
    healthcheck:
      test: ["CMD", "curl", "--fail", "https://localhost:443/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'      
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}

volumes:
  postgres-db-volume2:
  netfolder:
          driver: local
          driver_opts:
              type: cifs
              o: username=USER123,password=PASS123,domain=xx
              device: "\\\\xx.xx.xx.xx\\folder$$"
```

It looks like the Airflow user doesnt have permissions when its trying to write to the file. 

Is there a way to grant the user permissions after mapping the volumes?
