### DISCUSSION TITLE
Enable GitSync on Private Repo

### DISCUSSION THREAD

**Discussion by raefezzeldin** [apache/airflow#16607] [Q&A]
When I try to enable GitSync to sync dags from private repo on Github using HTTPS , Username and PAT. it keeps synscing the whole repo , ignoring my subPath configuration and always create this folders in dags foolder:
![image](https://user-images.githubusercontent.com/1645929/123010719-74fec500-d3bf-11eb-84c3-d972ec8ec3d7.png)

```
  dags: 
    gitSync: 
      repo: "https://XXXXXXXXs"
      subPath: "dags"
      enabled: true
      branch: "main"
      credentialsSecret: git-credentials
```
