### DISCUSSION TITLE
flower does not work when it is installed via helm with ingress.

### DISCUSSION THREAD

**Discussion by nijkah** [apache/airflow#16879] [Q&A] [answered]
I am trying to install airflow server on k8s cluster by helm charts.

my custom values are like this.

```
airflow:
  config:
    AIRFLOW__WEBSERVER__BASE_URL: "http://my.custom_server.kr/airflow"
    AIRFLOW__CELERY__FLOWER_URL_PREFIX: "/airflow/flower"

ingress:
  enabled: true

  web:
    path: "/airflow"
    host: "my.custom_server.kr"

  flower:
    path: "/airflow/flower"
    host: "my.custom_server.kr"

config:
  webserver:
    base_url: 'my.custom_server.kr/airflow'
```

helm install airflow apache-airflow/airflow --namespace airflow -f my_values.yaml

Airflow webserver works fine.
but, when I entered "my.custom_server.kr/airflow/flower"

I got this.

![image](https://user-images.githubusercontent.com/25769408/124886329-15cfc000-e00f-11eb-9fc7-8f27e58c4f1f.png)

When I open terminal in develop mode, I think it cannot find js and css files.
What I am missing ?

**Comment by nijkah** [comment, marked as answer]
I found that I was using older airflow.cfg

**Reply by nijkah** [reply]
Solution

```  
ingress:
  enabled: true

  web:
    path: "/airflow"
    host: "my.custom_server.kr"

  flower:
    path: "/airflow/flower"
    host: "my.custom_server.kr"

config:
  webserver:
    base_url: 'my.custom_server.kr/airflow'
  celery:
    flower_url_prefix: "/airflow/flower"
```
