### DISCUSSION TITLE
Official Helm chart gitsync with PVC (existingClaim)

### DISCUSSION THREAD

**Discussion by KIRY4** [apache/airflow#17262] [Q&A]
Hello everyone! Currently I'm using PVC with Azure file share under the hood for dags. Is it possible to use gitsync with PVC simultaneously?

```
persistence:
    enabled: true
    size: 1Gi
    existingClaim: my-dag-pvc

    gitSync:
       enabled: true
```
