### DISCUSSION TITLE
In Airflow v2.0.1 worker pods are not able to connect to postgres pod

### DISCUSSION THREAD

**Discussion by jaydeepdosi-vonage** [apache/airflow#17844] [General]
**Apache Airflow version:**

Version: v2.0.1

**What happened:**

Airflow is deployed on kubernetes, on deployment 3 pods are spun up - postgres, scheduler, webserver. Scheduler and Webserver pods are able to connect to postgres pod.
When a dag is triggered, the worker pod is failing and its logs show 

```
Mon 23 Aug 2021 02:30:35 PM UTC - waiting for Postgres... 6/20
Mon 23 Aug 2021 02:30:40 PM UTC - waiting for Postgres... 7/20
Mon 23 Aug 2021 02:30:45 PM UTC - waiting for Postgres... 8/20
Mon 23 Aug 2021 02:30:50 PM UTC - waiting for Postgres... 9/20
Mon 23 Aug 2021 02:30:55 PM UTC - waiting for Postgres... 10/20
Mon 23 Aug 2021 02:31:00 PM UTC - waiting for Postgres... 11/20
Mon 23 Aug 2021 02:31:05 PM UTC - waiting for Postgres... 12/20
Mon 23 Aug 2021 02:31:10 PM UTC - waiting for Postgres... 13/20
Mon 23 Aug 2021 02:31:15 PM UTC - waiting for Postgres... 14/20
Mon 23 Aug 2021 02:31:20 PM UTC - waiting for Postgres... 15/20
Mon 23 Aug 2021 02:31:25 PM UTC - waiting for Postgres... 16/20
Mon 23 Aug 2021 02:31:30 PM UTC - waiting for Postgres... 17/20
Mon 23 Aug 2021 02:31:35 PM UTC - waiting for Postgres... 18/20
Mon 23 Aug 2021 02:31:40 PM UTC - waiting for Postgres... 19/20
Mon 23 Aug 2021 02:31:45 PM UTC - postgres:5432 still not reachable, giving up
```

The pod_template.yaml file was working properly for Airflow v1.10.15. The values of environment variables in worker pods are also correct.
pod_template.yaml file 

```
    apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam*******************
      labels: {}
    spec:
      containers:
      - args: []
        command: []
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: AIRFLOW_HOME
          value: /usr/local/airflow
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: /usr/local/airflow/dags
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              name: {{ template "airflow.fullname" . }}-env
        - name: AIRFLOW_HOME
          valueFrom:
            secretKeyRef:
              key: AIRFLOW_HOME
              name: {{ template "airflow.fullname" . }}-env
        envFrom: []
        image: ******************
        imagePullPolicy: Always
        name: base
        ports: []
        volumeMounts:
        - mountPath: /usr/local/airflow/dags
          name: airflow-dags
          readOnly: true
        - mountPath: /usr/local/airflow/logs
          name: airflow-logs
        - mountPath: /usr/local/airflow/airflow.cfg
          name: airflow-config
          readOnly: true
          subPath: airflow.cfg
      hostNetwork: false
      imagePullSecrets: []
      initContainers: []
      nodeSelector:
        kops.k8s.io/instancegroup: airflow-nodes
      restartPolicy: Never
      securityContext:
        runAsUser: 500
      serviceAccountName: {{ template "airflow.fullname" . }}-sa
      tolerations:
      - effect: NoSchedule
        key: dedicated
        value: airflow
      volumes:
      - name: airflow-dags
        persistentVolumeClaim:
          claimName: {{ template "airflow.fullname" . }}-dags
      - name: airflow-logs
        persistentVolumeClaim:
          claimName: {{ template "airflow.fullname" . }}-logs
      - configMap:
          name: {{ template "airflow.fullname" . }}-config
        name: airflow-config
```

**What you expected to happen:**

Worker pods should be able to connect to the postgres pod.
