### DISCUSSION TITLE
Not able to see logs in the webserver while executing the DAGS

### DISCUSSION THREAD

**Discussion by chanduchama** [apache/airflow#17982] [Q&A]
### Official Helm Chart version

1.1.0 (latest released)

### Apache Airflow version

2.1.3 (latest released)

### Kubernetes Version

GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"

### Helm Chart configuration

```
env:
  - name: "AIRFLOW__WEBSERVER__SECRET_KEY"
    value: "airflow_webserver_secret_key"

webserverSecretKey: {{set_to_secret_key}}
webserverSecretKeySecretName: {{set_to_secret_name}}
```

### Docker Image customisations

No

### What happened

**Issue:** Not able to see logs in the webserver while executing the DAGS.
**Webserver Error:** 
*** Log file does not exist: /opt/airflow/logs/tutorial/templated/2021-08-26T18:29:03.649140+00:00/1.log
*** Fetching from: http://airflow-test-worker-688489557c-q2w9h:8793/log/tutorial/templated/2021-08-26T18:29:03.649140+00:00/1.log
*** Failed to fetch log file from worker. [Errno -3] Temporary failure in name resolution
**Airflow Version:** 2.1.3
**Helm chart version:** 1.1.0

We understand that we need to set the secrets for both webserver and worker but the instructions are not clear on setting up the secret configurations for worker and webserver for log access.

It would be of great help if someone can provide more inputs on this.

### What you expected to happen

View logs on the Webserver UI

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
