### DISCUSSION TITLE
spark-submit with KubernetesPodOperator vs SparkKubernetesOperator

### DISCUSSION THREAD

**Discussion by RomHartmann** [apache/airflow#17999] [Q&A]
What I'm trying to do:
- Run (py)spark jobs on Kubernetes
- Use Airflow as scheduler
  - Failed spark jobs should be reflected as a failed Airflow task
  - I'd like to see logs from the driver in the Airflow UI task log view

My question here is which approach is better for running spark - `spark-submit` using the `KubernetesPodOperator` or `spark-on-k8s-operator` with `SparkKubernetesOperator`?  I've looked at quite a lot of documentation, but I can't figure out which approach makes what I want to do easier/better. 

---

My setup:
- Kubernetes 1.21.1 (via AKS)
- Airflow version 2.1.1
  - deployed via [apache helm chart 1.0.0](https://airflow.apache.org/docs/helm-chart/stable/index.html)
  - Deployed with Kubernetes Executor
  - `/dags` and `/logs` are mounted volumes (`ReadWriteMany` Azure Files)

---

### `spark-submit` using the `KubernetesPodOperator`

For this approach I'd have a docker image that contains spark 3.1.1, my code and supporting installs. 

It would look something like 

```python
KubernetesPodOperator(
    name="job-name",
    task_id="job-name",
    image="<repo_url>/repo-name:latest",
    arguments=[
        "spark-submit",
        "--master", "k8s://https://<k8s_hostname>:443",
        "--deploy-mode", "cluster",
        "--name", "job-name",
        "--conf", f"spark.executor.instances=1",
        ...
        "--conf", f"spark.kubernetes.container.image=<repo_url>/repo-name:latest",
        "--conf", "spark.kubernetes.container.image.pullSecrets=acr-auth",
        "--conf", "spark.kubernetes.namespace=spark-jobs",
        "--conf", "spark.kubernetes.authenticate.driver.serviceAccountName=spark-sa",
        f"local:///path/to/script.py"
    ]
)
```

It has problems though. Primarily is the very long chain of spawned pods to get to the spark driver, which:
- Increases execution time (not critical)
- Marks the task as successful even if the driver fails (critical)
- Driver pod logs are not visible in the Airflow UI. The logs are of the pod that ran the `spark-submit`, which makes sense, but isn't helpful for understanding what happened during a job.  It also looks like it's not possible to pipe the driver pod to that scope (or at least I haven't figured out how)  (critical)

### `spark-on-k8s-operator` with `SparkKubernetesOperator`

This approach requires installing [spark-on-k8s-operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator), and it would look something like

```python
os.environ["AIRFLOW_CONN_KUBERNETES_DEFAULT"] = 'kubernetes://?extra__kubernetes__in_cluster=True'
SparkKubernetesOperator(
    task_id="job-name",
    namespace="spark-jobs",
    application_file="spark_app.yaml",
    kubernetes_conn_id="kubernetes_default",
    do_xcom_push=True
)
```
With `spark_app.yaml`:
```yaml
---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "job-name-{{ ds }}-{{ task_instance.try_number }}"
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  sparkVersion: "3.1.1"
  mode: cluster
  image: image_name
  mainApplicationFile: "local:///path/to/script.py"
  restartPolicy:
    type: Never
  driver:
    serviceAccount: spark-sa
  executor:
    instances: 1
```

It has the same problems though:
- Driver task in Airflow is marked as success even if job fails
- Driver logs aren't visible in Airflow UI

The first problem does have a provided workaround with a sensor:

```python
SparkKubernetesSensor(
        task_id='job-name.sensor',
        namespace="spark-jobs",
        application_name="{{ task_instance.xcom_pull(task_ids='job-name')['metadata']['name'] }}",
        kubernetes_conn_id="kubernetes_default"
    )
```
While I think it's a bit clunky, it's good enough.

---

So the question I'm left with is which approach to invest in?  Both approaches work in a similar manner, and seem to have the same major drawbacks.  _What is the recommended way to run spark jobs from Airflow?_

And most importantly for me, is there a way around those two problems (wrong logs & misleading state) with either of these approaches?
