### DISCUSSION TITLE
Not able to see logs | Log file does not exist: /opt/airflow/logs/hello_world/hello_world/2020-07-28T00:00:00+00:00/1.log

### DISCUSSION THREAD

**Discussion by scalaenthu** [apache/airflow#18325] [Q&A]
I am using a compose file to run the airflow.

My DAG is running fine, the tasks are able to push the data to airflow as well, but i want to see the logs.

**What happened:**

 **Log file does not exist: /opt/airflow/logs/hello_world/hello_world/2020-07-28T00:00:00+00:00/1.log
*** Fetching from: http://fef16ec26222:8793/log/hello_world/hello_world/2020-07-28T00:00:00+00:00/1.log
*** Failed to fetch log file from worker. HTTPConnectionPool(host='fef16ec26222', port=8793): Max retries exceeded with url: /log/hello_world/hello_world/2020-07-28T00:00:00+00:00/1.log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3406532e80>: Failed to establish a new connection: [Errno 111] Connection refused',))**

fef16ec26222 is the container id of my scheduler
I suspected that it was a port issue 5793, i created a docker file and exposed the port 5793 also i tried putting everything in the bridge network.

My compose file is:

```
version: "2.1"
services:
  airflow_postgres:
    image: postgres:12
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
    ports:
        - "5432:5432"
    networks:
      - airflow-backend

  meta_postgres:
    image: postgres:12
    environment:
        - POSTGRES_USER=developer
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=meta
    ports:
        - "5433:5432"
    networks:
      - airflow-backend

  scheduler:
    build: .
    restart: always
    depends_on:
      - airflow_postgres
      - meta_postgres
      - webserver
    env_file:
      - .env
    volumes:
        - ./dags:/opt/airflow/dags
    command: scheduler
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3
    networks:
      - airflow-backend

  webserver:
    build: .
    restart: always
    depends_on:
        - airflow_postgres
        - meta_postgres
    env_file:
      - .env
    volumes:
        - ./dags:/opt/airflow/dags
        - ./scripts:/opt/airflow/scripts
    ports:
        - "8080:8080"
    entrypoint: ./scripts/airflow-entrypoint.sh
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3
    networks:
      - airflow-backend
networks:
  airflow-backend:
    driver: bridge


```

The env is:

```
AIRFLOW_HOME=/opt/airflow
AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@airflow_postgres:5432/airflow
AIRFLOW__CORE__FERNET_KEY=*************
AIRFLOW_CONN_METADATA_DB=postgres://developer:secret@meta_postgres:5432/meta
AIRFLOW__VAR__METADATA_DB_SCHEMA=meta

```

Dockerfile:

```
FROM apache/airflow
ENV AIRFLOW_HOME=/opt/airflow
EXPOSE 5555 8793
```
**How to reproduce it:**
Use the docker file, env and compose file. Can be tested on any DAG.

**What you expected to happen:**
Able to see logs on webserver UI

I am using a sequencial operator (by default), I do not want to go with celery right now.
