### DISCUSSION TITLE
Airflow 2.1.3 scheduler fails to pick up new DAGs and throws ERROR - DagFileProcessorManager when there are a lot of DAGs

### DISCUSSION THREAD

**Discussion by augusten** [apache/airflow#18430] [Q&A]
Hi, I have been trying to scale out Airflow due to increasing amount of DAGs, however, have been unsuccessful in my attempts.

This is the config and information about the Airflow instance:

**Apache Airflow version**
2.1.3

**Deployment**
Azure Kubernetes Service 1.19.6

**Deployment details**
Helm chart from the branch `v2-1-stable` in this repo
Some config changes in the values.yaml:
```
extraEnv: |
  - name: AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL
    value: '900'
  - name: AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL
    value: '300'
  - name: AIRFLOW__SCHEDULER__NUM_RUNS
    value: '-1'
  - name: AIRFLOW__SCHEDULER__PROCESSOR_POLL_INTERVAL
    value: '1'
  - name: AIRFLOW__SCHEDULER__SCHEDULE_AFTER_TASK_EXECUTION
    value: 'True'
  - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
    value: 'False'
  - name: AIRFLOW__SCHEDULER__FILE_PARSING_SORT_MODE
    value: 'modified_time'
  - name: AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT
    value: '600'
  - name: AIRFLOW__SCHEDULER__PARSING_PROCESSES
    value: '4'
...
config:
  core:
    ...
    parallelism: 64
    ...
  celery:
    worker_concurrency: 32
    ...
```

I am using a PVC to hold the DAGs, and a PostgresQL database. The executor is a CeleryExecutor.
There are 2 schedulers and 3 workers. I initially tried using 1 scheduler and 3 workers.

**What happened**
We reached a ceiling (at around 600 DAGs) when the performance is Airflow degraded: the DAGs took hours to appear in the UI or did not appear at all, and the scheduler stopped scheduling some tasks (for instance, hourly tasks would have gaps of 5 hours, then start again. Or at some point it would stop scheduling tasks for a DAG altogether)

The above deployment configs were something I came up with after finding this [PR](https://github.com/apache/airflow/pull/16075) and [thread](https://github.com/apache/airflow/issues/17437) about `min_file_process_interval`.  I also thought increasing the `parsing_processes` parameter could help but it did not.

Looking into the postgres db I see that not all DAGs appear in the `dag` table. Also, if I run `airflow dags list` in the worker pod I see all the DAGs but their `paused` property is `None` (instead of True or False).

I tried re-deploying from scratch and recreating the database and DAGs, and it still ends up being stuck.

I checked that resources-wise AKS is not being utilized too much. The limits/request of cpu and memory for the scheduler, worker and webserver are also not too small.

I looked at the scheduler DAGs and I see that it keeps throwing errors like below:
```
[2021-09-22 10:59:51,654] {manager.py:417} ERROR - DagFileProcessorManager (PID=1749) last sent a heartbeat 50.40 seconds ago! Restarting it
```

When searching for this issue I saw [this](https://github.com/apache/airflow/discussions/18234) and [this](https://github.com/apache/airflow/discussions/18206), but in my case the upgrading to a newer version did not solve the issue. Also, my logs in `child_process_log_directory` are empty - I see the folder created but no files there to help me debug.

I saw that people are able to run thousands of DAGs, so I think it must be my configuration that is causing the problems, so I wanted to ask if anyone has tips on where else to look or how to fix it? Let me know if more details are needed
Thanks!
