### DISCUSSION TITLE
Can not write log to GCS by k8s

### DISCUSSION THREAD

**Discussion by Kiollpt** [apache/airflow#18529] [Q&A]
Hello, 

I create the connection `google_cloud` and set `KeyFile JSON` with the content of my service account. 

```
logging:
    remote_logging: 'True'
    colored_console_log: 'True'
    remote_log_conn_id: 'google_cloud'
    remote_base_log_folder: 'gs://airflow-harry/logs'

```

but I got  the error in the log 
```
Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credential and  re-run the application. For more information, please see
```
