### DISCUSSION TITLE
Cannot apply inter-pod affinity to scheduler

### DISCUSSION THREAD

**Discussion by benedikt-mue** [apache/airflow#19352] [Q&A]
Hi,
I am encountering a weird behavior when I try to attach `podAffinity` to the scheduler deployment, like:

```
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app 
            operator: In
            values:
            - postgresql
        topologyKey: "kubernetes.io/hostname"
```
which results in: 
`NotTriggerScaleUp:  pod didn't trigger scale-up: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't match pod affinity rules`

**However, applying the same config to the Webserver deployment works just fine.** 

It does not seem to be any resource limitation issue since I already tried various configs, every time with the same result.
I do not use any custom configurations apart from node affinity. 

Has anyone encounter the same or has any idea what I might do wrong?

Setup:
- AKS cluster
- helm chart 1.1.0
- Airflow 1.10.15 (but I don´t think this matters)
- kubectl client (1.22.1) and server (1.20.7)
