### DISCUSSION TITLE
Helm chart with custom xcom_backend error

### DISCUSSION THREAD

**Discussion by jmaldon1** [apache/airflow#19947] [Q&A] [answered]
I am unable to complete the Helm chart install if I add the following to the values.yaml file.

```yaml
config:
  core:
    xcom_backend: example_xcom_backend.custom_xcom_backend.BaseXCom
```

The path to the custom backend is a PVC that exists on the scheduler, webserver, and worker pods.

```yaml
# This is added for scheduler, webserver, and worker pods
extraVolumes:
  - name: airflow-xcom-backend-storage
    persistentVolumeClaim:
      claimName: airflow-xcom-backend
extraVolumeMounts:
  - mountPath: "/opt/example_xcom_backend"
    name: airflow-xcom-backend-storage
```

Each of these pods have the following env variable set to make sure python can see these files:

```yaml
# Environment variables for all airflow containers
env:
  - name: "PYTHONPATH"
    value: "/opt/example_xcom_backend
```
The database migrations pod seems to fail. Its not outputting any logs when I run `kubectl logs <pod-name> -n airflow`.

Is it failing because the migration pod does not have access to the PVC that contains the custom xcom backend class? I am not sure of the correct way of adding a custom xcom backend in that case.

**Comment by Francesko90** [comment, marked as answer]
I solved in different way

I created a new Dockerfile for airflow in this way

```
FROM apache/airflow:2.1.4-python3.8

COPY s3_xcom_backend.py /home/airflow/.local/lib/python3.8/site-packages/airflow/mycom/s3_xcom_backend.py
```

And changed the helm configuration 

```
airflow:
  image:
    repository: <registry>/airlfow
    tag: 2.1.4-python3.8
    pullPolicy: Always

  extraEnv: 
    - name: AIRFLOW__CORE__XCOM_BACKEND
      value: "airflow.myxcom.s3_xcom_backend.S3XComBackend"
```

Now the failure on DB migration disappear
