### DISCUSSION TITLE
Command to run in a task does not update when a DagRun is in progress

### DISCUSSION THREAD

**Discussion by piyush-daga** [apache/airflow#20129] [Q&A]
Executor: `KubernetesExecutor`
Platform: `EKS`
Deployment Technique: `Helm Chart (Git-sidecar)`
Tasks talked about below are all `BashOperators`

Suppose there are 3 tasks in a DagRun: `task1 -> task2 -> task3` While the dag is running and task1 is being executed. If a merge happens in the git deployment branch that changes task2 and task3's commands, and task1 is still not complete.
Task2 and task3 will run with the updated commands and not the older ones.

```yaml
dag1:
  task1:
     command1: tag:100
     command2: tag:200

# Someone changes command2 -> tag:200 -> tag:250 and pushes while the dag is running.
dag1:
  task1:
     command1: tag:100 (ran)
     command2: tag:250 (this ran, instead of tag:200)
```

Is there a way to say that once a DagRun has started the tasks stay consistent and they only change after the dagrun is complete?
