### DISCUSSION TITLE
Faced the error "ModuleNotFoundError: No module named 'airflow'" during deploy Apache Airflow on OpenShift

### DISCUSSION THREAD

**Discussion by iBalag** [apache/airflow#20551] [Q&A] [answered]
Hi,
I tried to deploy Apache Airflow (v2.2.3) on corp OpenShift cluster (3.11) and run `airflow kerberos` command, but faced with issue:
```
Traceback (most recent call last):
File "/home/airflow/.local/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
    ModuleNotFoundError: No module named 'airflow'
```

I found mentioned about [similar issue](https://github.com/apache/airflow/issues/14111). It seems this issue is related to UID\GID. But in [airflow docs](https://airflow.apache.org/docs/docker-stack/entrypoint.html#allowing-arbitrary-user-to-run-the-container) says:

> Airflow image is Open-Shift compatible, which means that you can start it with random user ID and the group id 0 (root).

So, I checked UID and GID and they are fine (line 1):
![oc](https://user-images.githubusercontent.com/17710791/147650274-4850c107-d133-4630-a1d0-8084853e5662.PNG)

Below example of my OpenShift template. Here I try to run `airflow kerberos` for refreshing kerberos token. I know, it is not a "whole airflow", but I guess the command `airflow kerberos` should work in this container without other airflow services around, shouldn't it?

```
apiVersion: v1
kind: Pod
metadata:
  name: airflow-kerberos
  labels:
    name: ${APPLICATION_NAME}
spec:
  volumes:
    - name: keytab-shared-volume
      persistentVolumeClaim:
        claimName: ${PERSISTENT_VOLUME_KRB5}
    - name: airflow-dags
      persistentVolumeClaim:
        claimName: ${PERSISTENT_VOLUME_CLAIM_DAG}
    - name: airflow-logs
      persistentVolumeClaim:
        claimName: ${PERSISTENT_VOLUME_CLAIM_LOG}
  containers:
    - name: airflow-kerberos
      image: apache/airflow:2.2.3
      env:
        - name: AIRFLOW__KERBEROS__KEYTAB
          value: ${KEYTAB_FILE}
      imagePullPolicy: Always
      resources:
        requests:
          cpu: 1
          memory: "512Mi"
      volumeMounts:
        - name: keytab-shared-volume
          mountPath: ${KRB5_SHARED_DIR}
        - name: airflow-dags
          mountPath: "/opt/airflow/dags"
        - name: airflow-logs
          mountPath: "/opt/airflow/logs"
      command: ["sh", "-c", "airflow kerberos"]
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: docker-hub-secret
  restartPolicy: Always
  serviceAccount: default
```
