### DISCUSSION TITLE
Setting up Connection to S3 bucket when deploying with Helm

### DISCUSSION THREAD

**Discussion by davidnateberg** [apache/airflow#21129] [Q&A]
I am struggling to figure out how to set an AWS S3 connection for logging when deploying Airflow with helm. 

I am deploying the latest `1.4.0` version of the helm chart with airflow version `2.2.3-python3.7`

I have the following in my `values.yaml` file

```
config:  
  logging:
    remote_logging: "True"
    remote_base_log_folder: s3://bucket-name/logs
    remote_log_conn_id: stage-s3-logs
    encrypt_s3_logs: "False"
```

when trying to view logs I can see its referencing the connection because the error says "no connection with id stage-s3-logs", 

I have tried adding it with the env variable `AIRFLOW_CONN` in the environment variable section of the helm chart, but that did not seem to work, and I'm also not sure how to pass the extra parameters for the connection that need to go along with it. 

For instance if I added the following env variable

```
env:
  - name: "AIRFLOW_CONN_STAGE_S3_LOGS"
    value: ""
```

I'm not sure what I would even pass as the value of it to create the connection as I would manually in the UI.

I know this connection works because I tested it out by manually adding the connection in the UI. The connection looks like this. 

__Connection Id__
stage-s3-logs

__Connection Type__
S3

__Extra__
{"aws_access_key_id": "access key", "aws_secret_access_key": "secret"}

When adding this manually everything is logged correctly, however I'd like to configure this during the deployment. Thanks!

**Comment by davidnateberg** [comment]
If anyone comes back to this post, I did eventually figure out how to do this with the environment variable I mentioned before and I set it as a secret in the helm chart. Example 

```
secret:
  - envName: "AIRFLOW_CONN_S3_BUCKET_URI"
    secretName: "airflow-s3-secret"
    secretKey: "AIRFLOW_CONN_S3_BUCKET_URI"
 ```
 
 The I got the URI by first manually setting the connection in the UI, as I showed in the initial post. Then I exec'd into a container and ran `airflow connections get my_connection_id` and one of the things it outputs is the URI. I used that as the secret.
