### DISCUSSION TITLE
Not all worker pods get nodeSelector and Tolerations values

### DISCUSSION THREAD

**Discussion by DanishKhakwani** [apache/airflow#21317] [Q&A]
Using KubernetesExecutor.

I have created a separate node pool for worker/task pods to run. Only some of the task pods are running on a separate node pool because when I looked at the manifest they had the nodeSelector and tolerations as I defined in the Chart for workers. The other task pods of the same DAG didn't have the nodeSelector and tolerations and hence were being scheduled on a non desired node pool.

**Comment by DanishKhakwani** [comment]
Actually the problem looks like:
- The main pod which triggers the DAG gets scheduled on the specified node - respects nodeSelector and tolerations
```  
containers:
    - name: base
      image: apache/airflow:2.2.3
      args:
        - airflow
        - tasks
        - run
        - ***
        - ***
        - scheduled__2022-02-04T08:00:00+00:00
        - '--local'
        - '--subdir'
        - DAGS_FOLDER/***.py
```


The pods that gets created in response to the above doesn't get the nodeSelector and Tolerations.
