### DISCUSSION TITLE
Shift airflow dags to Persistent Volume

### DISCUSSION THREAD

**Discussion by becash143** [apache/airflow#22276] [Ideas]
Previously we deliver dags inside airflow image. Now we would like to use persistent volume to deliver the dags. We want to achieve by retaining previous dags. Is this achievable from the existing chart, or do I need to add some job or init-containers to achieve this? 
I have enabled persistent volume in values.yaml
```
 dags:
  persistence:
    # Enable persistent volume for storing dags
    enabled: true
    # Volume size for dags
    size: 1Gi
    # If using a custom storageClass, pass name here
    #storageClassName:
    # access mode of the persistent volume
    accessMode: ReadWriteOnce
    ## the name of an existing PVC to use
    #existingClaim: ~
```
