### DISCUSSION TITLE
[SOLVED] Help: 100% of our tasks are stuck in "scheduled" state this morning

### DISCUSSION THREAD

**Discussion by p-hebert** [apache/airflow#22282] [General]
Hi,

We are running Airflow 2.2.3 on Kubernetes 1.21 and we haven't had any changes in the code since Friday (our ELT runs daily), and no changes in configuration/environment or any other code that could impact the scheduler since at least a month.
Symptoms seem to have started at some point yesterday but only stopped the entirety of the scheduling process this morning.

Here are the symptoms:

1. All of our tasks are either in "scheduled" or "queued"

![image](https://user-images.githubusercontent.com/31741972/158371066-d1bbba0b-9757-4d52-83ce-7fa8760e546a.png)

![image](https://user-images.githubusercontent.com/31741972/158370973-c6866504-3e91-4669-8378-e2bdd5abef27.png)

2. All of our DAGs are stuck in running:

![image](https://user-images.githubusercontent.com/31741972/158371232-00486d2a-2b15-405d-83d7-3f526d9a4bc5.png)

3. Triggering a new DAG results in having the next task for the new DagRun fall in "scheduled". The scheduler logs:

```
[2022-03-15 11:31:26,335] {scheduler_job.py:345} INFO - DAG pinkdolphin-update-staging-db has 1/1 running and queued tasks
[2022-03-15 11:31:26,335] {scheduler_job.py:352} INFO - Not executing <TaskInstance: pinkdolphin-update-staging-db.start scheduled__2022-03-14T00:00:00+00:00 [scheduled]> since the number of tasks running or queued from DAG pinkdolphin-update-staging-db is >= to the DAG's max_active_tasks limit of 1
[2022-03-15 11:31:26,335] {scheduler_job.py:345} INFO - DAG pinkdolphin-check-sla has 10/10 running and queued tasks
[2022-03-15 11:31:26,335] {scheduler_job.py:352} INFO - Not executing <TaskInstance: pinkdolphin-check-sla.check_env scheduled__2022-03-15T10:50:00+00:00 [scheduled]> since the number of tasks running or queued from DAG pinkdolphin-check-sla is >= to the DAG's max_active_tasks limit of 10
[2022-03-15 11:31:26,335] {scheduler_job.py:345} INFO - DAG pinkdolphin-clinicinfo-schedule has 10/10 running and queued tasks
[2022-03-15 11:31:26,335] {scheduler_job.py:352} INFO - Not executing <TaskInstance: pinkdolphin-clinicinfo-schedule.trigger_clinicinfo_dagruns scheduled__2022-03-15T06:30:00+00:00 [scheduled]> since the number of tasks running or queued from DAG pinkdolphin-clinicinfo-schedule is >= to the DAG's max_active_tasks limit of 10
[2022-03-15 11:31:26,335] {scheduler_job.py:345} INFO - DAG pinkdolphin-clinicinfo-schedule has 10/10 running and queued tasks
[2022-03-15 11:31:26,335] {scheduler_job.py:352} INFO - Not executing <TaskInstance: pinkdolphin-clinicinfo-schedule.trigger_clinicinfo_dagruns scheduled__2022-03-15T07:00:00+00:00 [scheduled]> since the number of tasks running or queued from DAG pinkdolphin-clinicinfo-schedule is >= to the DAG's max_active_tasks limit of 10
```

4. Killing the scheduler via `kubectl delete pod airflow-scheduler-78b976bc8d-brrqb` does not resolve the issue (nor did I really expect it to, but there was a non-zero chance).

5. Marking all the running DagRuns as failed does not change the state of the tasks from scheduled to failed. Current next step is to manually fail all scheduled task and see if that unclogs the pipeline.

---

Any help is really welcome because this is stopping our operations and affecting our clients.

@potiuk @ephraimbuddy @uranusjr: Any source you could think of? This seems different from the bug patched by #21556.

I'll keep posting my attempts & investigation steps on this thread.

**Comment by p-hebert** [comment]
OK, so we were able to resolve the situation by completely redeploying the airflow cluster.
NB that the database content was not modified. It seems like restarting all of the pods in a short time span does the thing but restarting the scheduler alone does not.

**Reply by potiuk** [reply]
I think it would be great to make some observations  if it happens again - including seeing if there are still pods runnig . It almost looks like somehere, the pods were not "finishing" properly and scheduler thought they are still running. Possibly that could be caused by a problem which made (for example) the pods to save the state in the DB or some other "infinite hanging".

When scheduler gets restarted it tries to adopt the running PODs and if they are not there, it will simply retry the failed tasks (or fail them) so apparently the PODs running the tasks were actually still "running". 

If it happens again, I tihnk some kind of a dump of running PODs from the K8S cluster would be useful.

**Reply by p-hebert** [reply]
It may not be too late. I'm not sure but there may be some logs saved by GKE?
This being said, I don't fully understand what you mean. What do you mean by "When scheduler gets restarted it tries to adopt the running PODs and if they are not there"?

**Reply by potiuk** [reply]
Maybe, I assume you use K8S executor. When scheduler starts it queries the K8S and if it sees tasks  as "running" (as reported by K8S) , it will assume they are sill "running" and if the limits are reached (as in your case) it will not schedule new tasks - it will wait for the running tasks to complete. So it really looked like your tasks were actually "running" (I.e PODS for the tasks were reporting themself as running when queried") -  if restarting schediuler did not help.

**Reply by potiuk** [reply]
At least that how I understand it SHOULD work - maybe @uranusjr and @ephraimbuddy and @ashb can tell more and maybe I do not get it 100% right (or maybe there were some bugs in 2.2.3 that could cause some edge cases here)

**Reply by p-hebert** [reply]
I'm not the data engineer who built our current setup - so I'm not entirely sure whether we are using the K8S Executor or not.
From what I gather, I don't think we are - I think we are using Celery and an HorizontalPodAutoscaler using CPU to autoscale. In our deployments we have several mentions of AIRFLOW__CELERY__RESULT_BACKEND as part of the env.

**Reply by p-hebert** [reply]
We seem to have some tasks that are still stuck in scheduled in the non-critical path of our daily operations.
Now's your time if you have specific things you want me to check I'm all ears :)

**Reply by potiuk** [reply]
I tihnk then you should rather look at flower and celery status - maybe you will be able to find some anomalies in logs tehre?

**Reply by p-hebert** [reply]
I have literally zero knowledge of flower/celery. But if you give me the necessary info on how to get what you want I will be happy to be the typing monkey and bring back the info

**Reply by p-hebert** [reply]
This being said, I'd understand if you prefer to wait for another unaltered breakage event to get clearer logs.
In either case, I'll need some kind of reference of what you want me to dump for your analysis so that when the time comes I have some clear instructions to bring the logs back to you.

**Reply by potiuk** [reply]
I have not much operational knowledge either :( unfortunately. I know flower is an option (depends how you deploy it) where you can monitor running celery tasks via UI and there for sure are worker logs from celery in your K8S Pods (but how to access them are rather per-deployment stuff).

**Reply by p-hebert** [reply]
OK, I found a way to have access using `kubectl port-forward {pod} 5555`.

![Screen Shot 2022-03-15 at 9 42 29 AM](https://user-images.githubusercontent.com/31741972/158390726-0d0eac79-71be-4fd0-a9db-159c26f28dbf.png)

What do you want to know?

**Reply by potiuk** [reply]
Antything that looks wrong :) . I have no "ready-recipes" what to look for - as I said I have very little "operational" knowledge. Maybe others can help (who know celery better). But generally any errors showing why tasks could "hang" is a thing to check,

**Reply by p-hebert** [reply]
Will do! 😄 
I'm also thinking that this could be related to #13542 (thanks @kristoffern for the ref).
I'll read some logs and see if anything springs out as weird.

**Reply by p-hebert** [reply]
I am getting a few `AirflowException: Celery command failed on host: [...]` in flower, but not nearly as many as the number of tasks currently or previously stuck in scheduled state:

![Screen Shot 2022-03-15 at 10 16 08 AM](https://user-images.githubusercontent.com/31741972/158397592-58ed8a3c-35d5-4575-82eb-700c5cafb884.png)

Not sure if related, but #16025 talks about this specific error message.

**Reply by p-hebert** [reply]
Looking at the timestamp of all these similar errors, this seems to be around the time of the deployment done earlier today, and could be, as maxcountryman points out, just related to the act of deployment itself (see comment [here](https://github.com/apache/airflow/issues/16025#issuecomment-855250292)).

**Reply by p-hebert** [reply]
I have one worker that doesn't have any further details besides "Unknown worker 'celery@airflow-worker-89b4d55bf-fwsqd'" when clicking on it. Worker has a few failures, but not enough information to make something out of it.

![Screen Shot 2022-03-15 at 10 29 33 AM](https://user-images.githubusercontent.com/31741972/158400518-78618cf7-99e1-4770-b470-e74873913346.png)

**Reply by p-hebert** [reply]
I have a few workers which have more "successful" tasks than "processed" task. I don't have enough knowledge about the Celery model to actually know if this is a flag or something OK, but at first that looks weird to me.
Unfortunately the UI doesn't provide a means to read more info from the tasks/or even list the tasks

**Reply by p-hebert** [reply]
I'm unfortunately at the end of the information I can provide through flower UI
One thing that's interesting though is that I still have a DAG that is stuck, and the scheduler does not restart the tasks:

![Screen Shot 2022-03-15 at 10 36 31 AM](https://user-images.githubusercontent.com/31741972/158401889-6b458941-f8e3-4483-a433-eeb72ba06034.png)
.

**Comment by p-hebert** [comment]
On this note I will sign off.
@uranusjr and @ephraimbuddy and @ashb: this seems to be related to a recurring, elusive issue (#13542). If by some chance you have some clear idea of steps to do to collect enough information to find and correct the source of the issue, please comment below and next time we face this issue we'll dump the results of the collection here, before redeploying the cluster.

If we are lucky/unlucky, this will happen sooner than later.

**Comment by p-hebert** [comment]
Well hello there @potiuk , @uranusjr , @ephraimbuddy , @ashb.

I'm experiencing similar issues while testing a deployment to staging. Guess it was sooner than later.
In this case, all tasks are stuck in queue, and none are scheduled. So in a sense it could be said to be different from the previous case where all tasks were stuck in scheduled.

Let's start by clarifying our setup:

## Overview of our configuration

```
airflow-scheduler-cc5f6f8b4-96nvj        1/1     Running   2          28m
airflow-webserver-ffb4d9d46-g2vxb        2/2     Running   0          28m
airflow-worker-5845f7bd45-7dxf5          1/1     Running   0          28m
postgres-f6d9b5cf-vsmr2                  1/1     Running   0          25m
redis-5494f48848-rqhhg                   1/1     Running   0          25m
... some other pods that are not related to airflow
```

**`airflow-scheduler-*`: K8S manifest (shortened):**

```
image: gcr.io/project/airflow:{TAG} # apache/airflow:2.2.3-python3.8, 
                                    # with some modifications for installing deps and configuring airflow
name: scheduler
imagePullPolicy: Always
env:
  - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
    ...
  - name: AIRFLOW__CELERY__RESULT_BACKEND
    ...
  - name: AIRFLOW__CORE__DAG_FILE_PROCESSOR_TIMEOUT
    value: "120"
volumeMounts:
  - name: airflow-sa-creds
    mountPath: /secrets
    readOnly: true
envFrom:
  - configMapRef:
      name: airflow-cfg
resources:
  requests:
    cpu: 1500m
    memory: 500Mi
    ephemeral-storage: "5Gi"
  limits:
    cpu: 3000m
    memory: 1Gi
command: ["airflow"]
args: ["scheduler"]
```

**`airflow-webserver-*`: K8S manifest (shortened):**

```
- image: gcr.io/project/airflow:{TAG} # apache/airflow:2.2.3-python3.8, see above
  name: webserver
  imagePullPolicy: Always
  env:
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      ...
    - name: AIRFLOW__CELERY__RESULT_BACKEND
      ...
  envFrom:
    - configMapRef:
        name: airflow-cfg
  volumeMounts:
    - name: airflow-sa-creds
      mountPath: /secrets
      readOnly: true
  ports:
    - containerPort: 8080
      name: webserver
  command: ["/bin/bash"]
  args: ["-c", "airflow webserver"]
  readinessProbe:
    httpGet:
      path: /health
      port: 8080
  resources:
    requests:
      cpu: 1250m
      memory: 1536Mi

- image: gcr.io/project/airflow:{TAG} # apache/airflow:2.2.3-python3.8, see above
  name: flower
  imagePullPolicy: Always
  env:
    ### Server ###
    - name: AIRFLOW__CELERY__RESULT_BACKEND
      ...
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      ...
  envFrom:
    - configMapRef:
        name: airflow-cfg
  ports:
    - containerPort: 5555
      name: flower
  command: ["airflow"]
  args: ["celery", "flower"]
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
```

**`airflow-scheduler-*`: K8S manifest (shortened):**

```
- image: gcr.io/project/airflow:{TAG} # apache/airflow:2.2.3-python3.8, see above
  name: scheduler
  imagePullPolicy: Always
  env:
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      ...
    - name: AIRFLOW__CELERY__RESULT_BACKEND
      ...
    - name: AIRFLOW__CORE__DAG_FILE_PROCESSOR_TIMEOUT
      value: "120"
  volumeMounts:
    - name: airflow-sa-creds
      mountPath: /secrets
      readOnly: true
  envFrom:
    - configMapRef:
      name: airflow-cfg
  resources:
    requests:
      cpu: 1500m
      memory: 500Mi
      ephemeral-storage: "5Gi"
    limits:
      cpu: 3000m
      memory: 1Gi
  command: ["airflow"]
  args: ["scheduler"]
```

**`airflow-postgres-*`: K8S manifest (shortened):**

_Run of the mill postgres:11, used as backend db for airflow_

```
- image: postgres:11
  name: postgres
  ports:
  - containerPort: 5432
    name: postgres
    protocol: TCP
  resources:
    limits:
      cpu: 500m
      ephemeral-storage: 1Gi
      memory: 2Gi
    requests:
      cpu: 500m
      ephemeral-storage: 1Gi
      memory: 2Gi
  ...
```

**`airflow-redis-*`: K8S manifest (shortened):**

```
- image: redis:6
  name: redis
  ports:
    - containerPort: 6379
      name: redis 
 
  resources:
    requests:
      cpu: 250m
      memory: 250Mi
```
