### DISCUSSION TITLE
Unable to configure remote logging for Airflow 2.2.4 on GCS

### DISCUSSION THREAD

**Discussion by mrn-aglic** [apache/airflow#22728] [Q&A]
I successfully deployed airflow 2.2.4 to GCP Kubernetes engine using the official Helm chart.
However, I have an issue with displaying task logs in the Airflow webserver UI. 
I am using a Celery Executor. 

**I can confirm that the connection id has the permissions to GCS since the same id is used in the tasks and one of them stores files to GCS**. 

However, when looking at the task logs in the UI, the following error is ever present:
```
*** Unable to read remote log from gs://airflow_logs_marin/airflow/logs/gcp_movie_ranking/import_in_bigquery/2019-03-01T00:00:00+00:00/14.log
*** 403 GET https://storage.googleapis.com/download/storage/v1/b/airflow_logs_marin/o/airflow%2Flogs%2Fgcp_movie_ranking%2Fimport_in_bigquery%2F2019-03-01T00%3A00%3A00%2B00%3A00%2F14.log?alt=media: Caller does not have storage.objects.get access to the Google Cloud Storage object.: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

*** Log file does not exist: /opt/airflow/logs/gcp_movie_ranking/import_in_bigquery/2019-03-01T00:00:00+00:00/14.log
*** Fetching from: http://airflow-worker-6974d49bb7-r99kc:8793/log/gcp_movie_ranking/import_in_bigquery/2019-03-01T00:00:00+00:00/14.log
*** Failed to fetch log file from worker. [Errno -2] Name or service not known
```

 I can confirm with the UI that remote logging is enabled and that the remote base log is set:

```
[logging]
colored_console_log = False
remote_base_log_folder = gs://airflow_logs_marin/airflow/logs/
remote_log_conn_id = google_cloud
remote_logging = True
```

The helm chart yaml is overriden with the following values:
```
config:
  logging:
    remote_logging: 'True'
    remote_base_log_folder: 'gs://airflow_logs_marin/airflow/logs/'
    remote_log_conn_id: 'google_cloud'
```

The same remote_log_conn_id is used in the tasks. 

Any suggestions?

**Comment by potiuk** [comment]
`Caller does not have storage.objects.get access to the Google Cloud Storage object.
: ('Request failed with status code', 403)`

Clearly says the service account you use does not have read permissions to the bucket/objects.

My suggestion is to fix permissions.

**Reply by mrn-aglic** [reply]
Thanks for the reply. But the account is set as Admin. And can be used inside the task (I wrote in my question).

**Reply by potiuk** [reply]
And READ permission has nothing to do wiht WRITE permission. You can easily have WRITE-only permission

**Reply by mrn-aglic** [reply]
Any permission I might be missing? I have manually created the bucket. 

![image](https://user-images.githubusercontent.com/2858231/161568800-bdbfbb18-24c3-4905-aa1a-2150eec65f1e.png)

**Reply by potiuk** [reply]
Did you try to pull the logs using the account? Did it work?

**Reply by mrn-aglic** [reply]
No, but no logs are create in `airflow_logs_marin/airflow/logs`. The bucket is empty.

**Reply by potiuk** [reply]
This is what I would do at least. 

And then I would try to check which service account is actually used when you run webserver. 
Maybe you alsio have some other account used accidentally ? Maybe configuration of your webserver is done in the way that different service account is used?

Just verify this step by step and try to see where the assumptions break (this is the debug process I usually use).

**Reply by mrn-aglic** [reply]
I manually add the service account through the UI. Could that be an issue? Does the service account have to be created/injected during deployment? 
The connection is shared with the scheduler and workers, right?

**Reply by potiuk** [reply]
Ah so your problem is differen then - your problem is that logs are not WRITTEN to the bucket. 
This is completely different problem than you described initially.

See the first point in the documentation - it shoudl explain the problem. Yoy configure writing logs sepearately (this is a security feature - only your tasks should be able to write the logs so the conn id is only used to read the logs:

https://airflow.apache.org/docs/apache-airflow-providers-google/stable/logging/gcs.html

> By default Application Default Credentials are used to obtain credentials. You can also set google_key_path option in [logging] section, if you want to use your own service account.

**Reply by mrn-aglic** [reply]
I tried by adding the json key as a secret:
`kubectl create secret generic gac --from-file=key.json=key.json -n airflow `

And then override helm:

```

config:
  logging:
    remote_logging: 'True'
    remote_base_log_folder: 'gs://airflow_logs_marin/airflow/logs/'
    remote_log_conn_id: 'google_cloud'
    google_key_path:  "/opt/airflow/secrets/key.json"
  webserver:
    expose_config: 'True'

webserver:
  service:
    type: LoadBalancer
  extraVolumeMounts:
    - name: google-cloud-key
      mountPath: /opt/airflow/secrets
  extraVolumes:
    - name: google-cloud-key
      secret:
        secretName: cad


workers:
  keda:
    enabled: True
  persistence:
    enabled: False
  extraVolumeMounts:
    - name: google-cloud-key
      mountPath: /opt/airflow/secrets
  extraVolumes:
    - name: google-cloud-key
      secret:
        secretName: cad

scheduler:
  extraVolumeMounts:
    - name: google-cloud-key
      mountPath: /opt/airflow/secrets
  extraVolumes:
    - name: google-cloud-key
      secret:
        secretName: cad

triggerer:
  extraVolumeMounts:
    - name: google-cloud-key
      mountPath: /opt/airflow/secrets
  extraVolumes:
    - name: google-cloud-key
      secret:
        secretName: cad

env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: "/opt/airflow/secrets/key.json"
```

but now the pods can't start... I probably made a mistake with mounting volumes.
