### DISCUSSION TITLE
Task stuck in "scheduled" or "queued" state, pool has all slots queued, nothing is executing

### DISCUSSION THREAD

**Discussion by Overbryd** [apache/airflow#24180] [General]
**Apache Airflow version**: `2.0.0`

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-gke.1600", GitCommit:"7c407f5cc8632f9af5a2657f220963aa7f1c46e7", GitTreeState:"clean", BuildDate:"2020-12-07T09:22:27Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
  - Airflow metadata database is hooked up to a PostgreSQL instance

**What happened**:

* Airflow 2.0.0 running on the `KubernetesExecutor` has many tasks stuck in "scheduled" or "queued" state which never get resolved.
* The setup has a `default_pool` of 16 slots.
* Currently no slots are used (see Screenshot), but all slots are queued.
* No work is executed any more. The Executor or Scheduler is stuck.
* There are many many tasks stuck in "scheduled" state
  * Tasks in "scheduled" state say `('Not scheduling since there are %s open slots in pool %s and require %s pool slots', 0, 'default_pool', 1)`
    That is simply not true, because there is nothing running on the cluster and there are always 16 tasks stuck in "queued".
* There are many tasks stuck in "queued" state
  * Tasks in "queued" state say `Task is in the 'running' state which is not a valid state for execution. The task must be cleared in order to be run.`
    That is also not true. Nothing is running on the cluster and Airflow is likely just lying to itself. It seems the KubernetesExecutor and the scheduler easily go out of sync.

**What you expected to happen**:

* Airflow should resolve scheduled or queued tasks by itself once the pool has available slots
* Airflow should use all available slots in the pool
* It should be possible to clear a couple hundred tasks and expect the system to stay consistent

**How to reproduce it**:

* Vanilla Airflow 2.0.0 with `KubernetesExecutor` on Python `3.7.9`
* `requirements.txt`

  ```
  pyodbc==4.0.30
  pycryptodomex==3.9.9
  apache-airflow-providers-google==1.0.0
  apache-airflow-providers-odbc==1.0.0
  apache-airflow-providers-postgres==1.0.0
  apache-airflow-providers-cncf-kubernetes==1.0.0
  apache-airflow-providers-sftp==1.0.0
  apache-airflow-providers-ssh==1.0.0
  ```

* The only reliable way to trigger that weird bug is to clear the task state of many tasks at once. (> 300 tasks)

**Anything else we need to know**:

Don't know, as always I am happy to help debug this problem.
The scheduler/executer seems to go out of sync and never back in sync again with the state of the world.

We actually planned to upscale our Airflow installation with many more simultaneous tasks. With these severe yet basic scheduling/queuing problems we cannot move forward at all.

Another strange, likely unrelated observation, the scheduler always uses 100% of the CPU. Burning it. Even with no scheduled or now queued tasks, its always very very busy.

**Workaround**:

The only workaround for this problem I could find so far, is to manually go in, find all tasks in "queued" state and clear them all at once. Without that, the whole cluster/Airflow just stays stuck like it is.

**Comment by mfjackson** [comment]
@Overbryd I'm not sure if this helps, but I was dealing with a similar issue with our self-managed Airflow instance on GKE when we upgraded to 2.0.0 a couple of weeks ago. Are you using `gitSync`? If so, are you receiving an error in your logs surrounding the `knownHosts`?

If so, we found that updating the [pod-template-file](https://github.com/apache/airflow/blob/master/chart/files/pod-template-file.kubernetes-helm-yaml) to this:

```
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
apiVersion: v1
kind: Pod
metadata:
  name: dummy-name
spec:
{{- if .Values.dags.gitSync.enabled }}
  initContainers:
{{- include "git_sync_container" (dict "Values" .Values "is_init" "true") | indent 8 }}
{{- end }}
  containers:
    - args: []
      command: []
      envFrom:
      {{- include "custom_airflow_environment_from" . | default "\n  []" | indent 6 }}
      env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
{{- include "standard_airflow_environment" . | indent 6}}
{{- include "custom_airflow_environment" . | indent 6 }}
      image: {{ template "pod_template_image" . }}
      imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
      name: base
      ports: []
      volumeMounts:
        - mountPath: {{ template "airflow_logs" . }}
          name: airflow-logs
        - name: config
          mountPath: {{ template "airflow_config_path" . }}
          subPath: airflow.cfg
          readOnly: true
{{- if .Values.scheduler.airflowLocalSettings }}
        - name: config
          mountPath: {{ template "airflow_local_setting_path" . }}
          subPath: airflow_local_settings.py
          readOnly: true
{{- end }}
{{- if .Values.dags.gitSync.knownHosts }}
        - mountPath: /etc/git-secret/known_hosts
          name: config
          subPath: known_hosts
          readOnly: true
{{- end }}
{{- if .Values.dags.gitSync.sshKeySecret }}
        - mountPath: /etc/git-secret/ssh
          name: git-sync-ssh-key
          subPath: ssh
{{- end }}
{{- if or .Values.dags.gitSync.enabled .Values.dags.persistence.enabled }}
        - mountPath: {{ include "airflow_dags_mount_path" . }}
          name: dags
          readOnly: true
{{- if .Values.dags.persistence.enabled }}
          subPath: {{.Values.dags.gitSync.dest }}/{{ .Values.dags.gitSync.subPath }}
{{- end }}
{{- end }}
  hostNetwork: false
  {{- if or .Values.registry.secretName .Values.registry.connection }}
  imagePullSecrets:
    - name: {{ template "registry_secret" . }}
  {{- end }}
  restartPolicy: Never
  securityContext:
    runAsUser: {{ .Values.uid }}
  nodeSelector: {{ toYaml .Values.nodeSelector | nindent 4 }}
  affinity: {{ toYaml .Values.affinity | nindent 4 }}
  tolerations: {{ toYaml .Values.tolerations | nindent 4 }}
  serviceAccountName: '{{ .Release.Name }}-worker'
  volumes:
  {{- if .Values.dags.persistence.enabled }}
  - name: dags
    persistentVolumeClaim:
      claimName: {{ template "airflow_dags_volume_claim" . }}
  {{- else if .Values.dags.gitSync.enabled }}
  - name: dags
    emptyDir: {}
  {{- end }}
  {{- if and  .Values.dags.gitSync.enabled  .Values.dags.gitSync.sshKeySecret }}
{{- include "git_sync_ssh_key_volume" . | indent 2 }}
  {{- end }}
  - emptyDir: {}
    name: airflow-logs
  - configMap:
      name: {{ include "airflow_config" . }}
    name: config
```

The changes to the original file are as follows:

- Line 56: set "name: config"
- Line 58: insert "readOnly: true"
- Delete lines 98-103

This allowed gitSync to work (after also passing a `knownHosts` value in the `values.yaml` file, along with the other necessary configurations) and processes to move from a persistent "queued" state to a "running" state.

If this isn't the issue, the other area that you may want to look into is making sure that your service account binding annotations are properly set for you scheduler, webserver, and workers in your `values.yaml` file. If they're not properly bound to a GCP service account with adequate pod creation permissions, the initial task may queue, but won't run.
