### DISCUSSION TITLE
Airflow task error from utils/log/file_task_handler.py file

### DISCUSSION THREAD

**Discussion by HaozhiTan** [apache/airflow#25057] [Q&A]
I am running a simple dag to test custom operator in airflow 2.3.3 version. 

The first task runs successfully but the second task got the error shown below.

Does anyone know why this error happens and how to resolve this? Thanks!

![image](https://user-images.githubusercontent.com/47723210/178972666-70dfeed3-e972-4f4b-96ae-08eb4572b2a1.png)

The dag files are shown below:

```
from airflow import DAG
from datetime import datetime, timedelta
from operators.sample_custom_operator import SampleCustomOperator
from sensors.sample_custom_sensor import SampleCustomSensor

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2018, 1, 1),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

with DAG(
    'example_dag',
    max_active_runs=3,
    schedule_interval='@once',
    tags=['example'],
    default_args=default_args
) as dag:
    sens = SampleCustomSensor(
        task_id='sample_sensor_task'
    )

    op = SampleCustomOperator(
        task_id='sample_operator_task',
        my_field='some text'
    )

    sens >> op
```

SampleCustomSensor:
```
from airflow.hooks.base import BaseHook


class SampleCustomHook(BaseHook):

    def my_method(self):
        print("Hello World")
```
SampleCustomOperator:
```
from airflow.operators.bash import BaseOperator
from hooks.sample_custom_hook import SampleCustomHook


class SampleCustomOperator(BaseOperator):

    def __init__(self, my_field, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.my_field = my_field

    def execute(self, context):
        hook = SampleCustomHook('my_conn')
        hook.my_method()
```

**Comment by potiuk** [comment]
I believe. Your worker uses different airlfow version. You need to make sure airflow version is the same for all components.

The line 286 in fille_task_handler in 2.3.3 is diffferent one (the line your error shows is 295 not 285 in 2.3.3):


![image](https://user-images.githubusercontent.com/595491/178975642-3483c2fa-ba1a-451c-9ed2-62a9874b3fa2.png)

**Reply by HaozhiTan** [reply]
Thanks for that. I checked the airflow version. It is strange that I used the below code the build the airflow image, but looks like airflow version 2.3.2 is installed rather than 2.3.3 as expected.

![image](https://user-images.githubusercontent.com/47723210/179091873-e89261b9-f6c7-4a0b-ade3-4d4100526649.png)

```
FROM apache/airflow:2.3.3-python3.9
```

**Reply by HaozhiTan** [reply]
Just did a further testing that if I downgrade to airflow 2.2.5 using the below code to build the image. No errors again.
```
FROM apache/airflow:2.2.5-python3.9
```

**Reply by potiuk** [reply]
You are likely doing something in your image that effective downgrades airflow in one of the next steps. But what it can be hard to say. It might be for example a provider that is not compatible with Airlfow 2.3 if you are forcing a specific version.

Look at the output of `pip` when you install stuff in your next steps and you will see when it happens. You can run your build with `--progress plain` to see it better.

**Reply by potiuk** [reply]
I am curious to see what was the root cause BTW.

**Reply by HaozhiTan** [reply]
Thanks for your prompt reply! I finally successfully install airflow 2.3.3 without installing any other packages including providers. 

I only used `FROM apache/airflow:2.3.3-python3.9` when building the airflow image. But I still got the same error shown below.

![image](https://user-images.githubusercontent.com/47723210/179187821-62b26342-8dd2-4b8d-b73b-ba5df8c64a78.png)

**Reply by potiuk** [reply]
It looks like you have some custom logging configuration that causes it. There were a few changes in logging templates recently - but I am not very familiar with those @uranusjr and @dstandish might be better people to look at it (though I am not sure if it is related), Do you have any customisation/custom dags/custom logging configuration, and if so - can you share it with us here?

**Reply by HaozhiTan** [reply]
Below shows all the code files used for airflow setup. The DAG file and operator code can be found above. 

airflow.yaml 
```
version: "3.7"
# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-airflow-common: &airflow_common
  build:
    context: .
    cache_from:
      - docker_airflow-init
    dockerfile: Dockerfile.dev
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    # For backward compatibility, with Airflow <2.3
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__STORE_DAG_CODE: 'true'
    AIRFLOW__CORE__STORE_SERIALIZED_DAGS: 'true'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    AIRFLOW__WEBSERVER__RBAC: 'false'
    AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW: 'graph'
    AIRFLOW__WEBSERVER__SECRET_KEY: 'lnz'
  volumes:
    - ../dp_airflow/dags:/opt/airflow/dags
    - ../dp_airflow/plugins:/opt/airflow/plugins
    - ../.local/airflow_logs:/opt/airflow/logs
  networks:
    - airflow
  depends_on: &airflow-common-depends-on
    postgres:
      condition: service_healthy
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================
services:
  airflow-init:
    <<: *airflow_common
    entrypoint: /bin/bash
    container_name: local_airflow_docker_init
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
    depends_on:
      - postgres
    networks:
      - airflow
    command:
      - -c
      - exec /entrypoint airflow version

  airflow-webserver:
    <<: *airflow_common
    command: webserver
    container_name: local_airflow_webserver
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init

  airflow-scheduler:
    <<: *airflow_common
    command: scheduler
    container_name: local_airflow_scheduler
    restart: always
    depends_on:
      - airflow-init

  postgres:
    image: postgres:13-alpine
    container_name: local_airflow_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    networks:
      - airflow
    volumes:
      - ../.local/airflow_db:/var/lib/postgresql/data

networks:
  airflow:
    name: airflow
```

Dockerfile.dev
```
FROM apache/airflow:2.3.3-python3.9
```
