### DISCUSSION TITLE
GitSync does not seem to respect dags.gitSync.subPath

### DISCUSSION THREAD

**Discussion by hazelrah-qr** [apache/airflow#25940] [General] [answered]
### Official Helm Chart version

1.6.0 (latest released)

### Apache Airflow version

2.3.2

### Kubernetes Version

1.20.11

### Helm Chart configuration

```
dags.gitSync.branch=develop
dags.gitSync.subPath=dags
```

```
dags:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: "file-dr-off-pdc1"
    accessMode: ReadWriteMany
  gitSync:
    enabled: true
    branch: master
    rev: HEAD
    depth: 1
    maxFailures: 3
    env:
      - name: GIT_SYNC_SUBMODULES
        value: 'off'
```

### What happened

When applying the provided values.yml the whole repository is still synced, not just the dags folder in the repository.
```
airflow@ci-airflow-scheduler-4k4gn:/opt/airflow/dags/repo$ ls
README.md  dags  docker-compose.yaml  docker-compose.yml  pyproject.toml  tests
```

### What you think should happen instead

Only the provided subPath would be synced in to `/opt/airflow/dags/repo`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
