### DISCUSSION TITLE
Could not fork new process for connection: Resource temporarily unavailable

### DISCUSSION THREAD

**Discussion by thaiOnpoint** [apache/airflow#26041] [Q&A]
**Apache Airflow version**
2.2.4

**What happened**
Scheduler some times report that some problem in Postgres (built-in) databases (and after that Scheduler pod was restarted)
Could not fork new process for connection: Resource temporarily unavailable (image below).

This image is the log from postgres pod:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/101542486/187251694-053bac5d-56ce-4718-babd-60506cd34045.png">

**Deployment**
Official Apache Airflow Helm Chart v1.5.0 

**Deployment details**
Airflow-scheduler, web, workers, redis are on our EKS, deployed via official helm chart with customize config.yaml (below).

We have also RDS (postgresql).

**_We config to use RDS (postgresql) as an external database (to save Airflow webserver metadata as i understand), but database backend still using postgres sql pod on K8s_**. 
Please correct me if i'm wrong (I know that best practice is set database backend to use RDS also, but what problem if I use database backend on postgres pod ?).

Config.yaml file (i removed all environment variables and node selector, ...)
```
show_templated_fields: none

hide_sensitive_variable_fields: True

dags:
  gitSync:
    branch: main
    depth: 1
    enabled: true
    maxFailures: 0
    repo: git@github.com:xxx/yyy
    rev: HEAD
    sshKeySecret: airflow-ssh-git-secret
    subPath: airflow
    wait: 20

data:
  metadataSecretName: airflow-dev # where I store credential of external database using for Airflow Webserver metadata

executor: CeleryKubernetesExecutor

flower:
  enabled: true

migrateDatabaseJob:

webserver:
  defaultUser:
    email: admin@example.com
    enabled: true
    firstName: admin
    lastName: user
    password: admin
    role: Admin
    username: admin

workers:
  keda:
    cooldownPeriod: 30
    enabled: true
    maxReplicaCount: 1
    minReplicaCount: 1
    namespaceLabels: {}
    pollingInterval: 5
  persistence:
    enabled: false
  replicas: 1
  resources:
    limits:
      cpu: 2500m
      memory: 12Gi
    requests:
      cpu: 500m
      memory: 6Gi

config:
  celery:
    worker_concurrency: 16
```
