### DISCUSSION TITLE
Airflow pod template image is not running

### DISCUSSION THREAD

**Discussion by aydinmirac** [apache/airflow#26430] [Q&A]
Hi everyone, 

I installed airflow kubernetes for our K8s cluster. Also, I prepared a custom task pod image (including cuda and other AI libs) for GPU workload. In this image, there are some embedded binaries but when I tried to run this image with pod template file, the corresponding dag gives file not found error.
```
[2022-09-14T12:06:54.603+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/***/dags/test_dw_dag_pcd.py
[2022-09-14T12:06:54.886+0000] {task_command.py:371} INFO - Running <TaskInstance: test_dw_dag_PCD.TS_extractor manual__2022-09-14T12:06:48.310430+00:00 [queued]> on host testdwdagpcdtsextractor-218da12016ab4785b7f4f9790765a974
sh: 1: /home/dgxuser/LidarSample: not found
```  
But this image is working fine and seeing those binaries when I run with "docker run" command explicitly. Here is my pod_template in values.yaml of Airflow Helm Chart:

```
podTemplate: |
  apiVersion: v1
  kind: Pod
  metadata:
    name: airflow-task-pod
    labels:
      tier: airflow
      component: worker
      release: airflow
  spec:
    containers:
      - envFrom:
          []
        env:
          - name: AIRFLOW__CORE__EXECUTOR
            value: KubernetesExecutor
          # Hard Coded Airflow Envs
          - name: AIRFLOW__CORE__FERNET_KEY
            valueFrom:
              secretKeyRef:
                name: airflow-fernet-key
                key: fernet-key
          # For Airflow <2.3, backward compatibility; moved to [database] in 2.3
          - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            valueFrom:
              secretKeyRef:
                name: airflow-airflow-metadata
                key: connection
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            valueFrom:
              secretKeyRef:
                name: airflow-airflow-metadata
                key: connection
          - name: AIRFLOW_CONN_AIRFLOW_DB
            valueFrom:
              secretKeyRef:
                name: airflow-airflow-metadata
                key: connection
          - name: AIRFLOW__WEBSERVER__SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: airflow-webserver-secret-key
                key: webserver-secret-key
          # Dynamically created environment variables
          # Dynamically created secret envs
          # Extra env
        image: airflow_pod_image:kubernetes_executor (This is my custom image)
        imagePullPolicy: IfNotPresent
        name: base
        resources:
          {}
        volumeMounts:
          - mountPath: "/opt/airflow/logs"
            name: logs
          - name: config
            mountPath: "/opt/airflow/airflow.cfg"
            subPath: airflow.cfg
            readOnly: true
          - name: config
            mountPath: "/opt/airflow/config/airflow_local_settings.py"
            subPath: airflow_local_settings.py
            readOnly: true
          - name: dags
            mountPath: /opt/airflow/dags
            readOnly: False
          - name: lustre-path
            mountPath: /mnt/lustre/dgxuser/CIF_data
            readOnly: false
    restartPolicy: Never
    securityContext:
      fsGroup: 1001
      runAsGroup: 0
      runAsUser: 1001
    nodeSelector:
      {}
    affinity:
      {}
    tolerations:
      []
    topologySpreadConstraints:
      []
    serviceAccountName: airflow-worker
    volumes:
    - name: dags
      persistentVolumeClaim:
        claimName: airflow-dags
    - name: logs
      persistentVolumeClaim:
        claimName: airflow-logs
    - configMap:
        name: airflow-airflow-config
      name: config
    - name: lustre-path
      hostPath:
        path: /mnt/lustre/dgxuser/CIF_data
        #type: Directory 
```
As you can see from the template, my image is custom built image, `image: airflow_pod_image:kubernetes_executor` . But I think Airflow is not starting our task pods with this image.
Do you have any suggestions?
