### DISCUSSION TITLE
How to use DOCKER_CONTEXT_FILES with docker compose

### DISCUSSION THREAD

**Discussion by marvinfretly** [apache/airflow#26594] [Q&A]
I'm trying to move my requirements.txt file from my dockerfile to use the docker context files but I can't manage how to use it.
It seems that the arg is ignored when building.

Here is my docker compose file:
```
version: "3"
x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: airflow-dockerfile
    args:
      DOCKER_CONTEXT_FILES: "./docker-context-files"
  environment: &airflow-common-env
    AIRFLOW__WEBSERVER__BASE_URL: "${ETL_URL}:8080"
    AIRFLOW__CORE__DEFAULT_TIMEZONE: "Europe/Paris"
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    # Scan for DAGs every 60 seconds
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "7"
    AIRFLOW__WEBSERVER__SECRET_KEY: "key"
    # Prevent airflow from reloading the dags all the time and set:
    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "10"
    # 2 * NUM_CPU_CORES + 1
    AIRFLOW__WEBSERVER__WORKERS: "2"
    # Kill workers if they don't start within 5min instead of 2min
    AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: "300"

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./output:/output:z

  env_file:
    - ./.env
  user: "${AIRFLOW_UID:-1000}:${AIRFLOW_GID:-0}"
  mem_limit: 16000m
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
  networks:
    - etl_network
```

I tried multiple ways to write the arg with value with and without double quotes, also with and without the "./" .
I created a folder named "docker-context-files" at the root of my repo with the requirements.txt inside.

To start my container I use theses methods:
```
docker compose  -f airflow-docker-compose.yml up  --force-recreate --build airflow-init
docker compose  -f airflow-docker-compose.yml up --force-recreate -d
```

But none of my packages are installed.

I use airflow 2.4.0
