### DISCUSSION TITLE
How to automatically move all DAG files to Airflow Docker and not just have only the latest added file moved and renamed to 'example_python_operator'?

### DISCUSSION THREAD

**Discussion by stromal** [apache/airflow#26656] [Q&A]
# PROBLEM

- How to automatically move all DAG files to Airflow Docker
- and not just have only the latest added file moved
- and renamed to 'example_python_operator'?

# Guides That I have Tried

# 1.
docker run -d -p 8080:8080 -v /home/user/airflow/dags:/usr/local/airflow/dags  puckel/docker-airflow webserver
- Is this my actual local path -> ```:/usr/local/airflow/dags``` ?
- Is this a standard parth ```:/usr/local/airflow/dags```?
- Is this the container name of the webserver or some internal routing ```puckel/docker-airflow webserver```?
docker run -d -p 8080:8080 -v /MY_ACTUAL_PATH_BASED_ON_PWD/dags:/usr/local/airflow/dags my_IMAGE_name_of_webserver

# 2.
I can not put this to the config file because I use docker-compose so I dont get one after the 1st start.
```dags_folder = /usr/local/airflow/dags```

# 3.
This just plane doesn't pushes my DAGs in to docker  ```docker-compose up -d --build```

#4.
added the volume but again I dont have a config file generated.
1. 

webserver:         image: puckel/docker-airflow:1.10.0-2         ...         volumes:             - ./airflow:/usr/local/airflow 
2.edit the dags folder configuration in the airflow configuration file(it do not needs edit by default, as it is under the airflow folder)
3.every time, check if the dag name appeared by following command:airflow list_dags

My question ask how to add them automatically. I dont what to write commands for it every time. Also non of this answers even gets the file to the folder. - https://stackoverflow.com/questions/52358255/airflow-in-docker-how-to-add-dags-to-airflow

# All my code

# COMMANDS

    docker build -t my-image-apache/airflow:latest-python3.8 .
    docker-compose up airflow-init
    docker-compose up -d

# FILES

airflow/Dockerfile

    FROM apache/airflow:latest-python3.8
    COPY requirements.txt .
    RUN pip install -r requirements.txt

airflow/requirements.txt

    apache-airflow==2.4.0
    pandas==1.4.2
    numpy==1.20.3
    pendulum==2.1.2

airflow/docker-compose.yml   (THIS IS FROM THE OFFICIAL AIRFLOW SITE)

    --- version: '3' x-airflow-common:   &airflow-common   # In order to add custom dependencies or upgrade provider packages you can use your extended image.   # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml   # and uncomment the "build" line below, Then run `docker-compose build` to build the images.   image: ${AIRFLOW_IMAGE_NAME:-my-image-apache/airflow:latest-python3.8}   # build: .   environment:
        &airflow-common-env
        AIRFLOW__CORE__EXECUTOR: CeleryExecutor
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
        # For backward compatibility, with Airflow <2.3
        AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
        AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
        AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
        AIRFLOW__CORE__FERNET_KEY: ''
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
        AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
        AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
        _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}   volumes:
        - ./dags:/opt/airflow/dags
        - ./logs:/opt/airflow/logs
        - ./plugins:/opt/airflow/plugins   user: "${AIRFLOW_UID:-50000}:0"   depends_on:
        &airflow-common-depends-on
        redis:
          condition: service_healthy
        postgres:
          condition: service_healthy
    
    services:   postgres:
        image: postgres:13
        environment:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        volumes:
          - postgres-db-volume:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD", "pg_isready", "-U", "airflow"]
          interval: 5s
          retries: 5
        restart: always
    
      redis:
        image: redis:latest
        expose:
          - 6379
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 5s
          timeout: 30s
          retries: 50
        restart: always
    
      airflow-webserver:
        <<: *airflow-common
        command: webserver
        ports:
          - 8080:8080
        healthcheck:
          test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
          interval: 10s
          timeout: 10s
          retries: 5
        restart: always
        depends_on:
          <<: *airflow-common-depends-on
          airflow-init:
            condition: service_completed_successfully
    
      airflow-scheduler:
        <<: *airflow-common
        command: scheduler
        healthcheck:
          test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
          interval: 10s
          timeout: 10s
          retries: 5
        restart: always
        depends_on:
          <<: *airflow-common-depends-on
          airflow-init:
            condition: service_completed_successfully
    
      airflow-worker:
        <<: *airflow-common
        command: celery worker
        healthcheck:
          test:
            - "CMD-SHELL"
            - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
          interval: 10s
          timeout: 10s
          retries: 5
        environment:
          <<: *airflow-common-env
          # Required to handle warm shutdown of the celery workers properly
          # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
          DUMB_INIT_SETSID: "0"
        restart: always
        depends_on:
          <<: *airflow-common-depends-on
          airflow-init:
            condition: service_completed_successfully
    
      airflow-triggerer:
        <<: *airflow-common
        command: triggerer
        healthcheck:
          test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
          interval: 10s
          timeout: 10s
          retries: 5
        restart: always
        depends_on:
          <<: *airflow-common-depends-on
          airflow-init:
            condition: service_completed_successfully
    
      airflow-init:
        <<: *airflow-common
        entrypoint: /bin/bash
        # yamllint disable rule:line-length
        command:
          - -c
          - |
            function ver() {
              printf "%04d%04d%04d%04d" $${1//./ }
            }
            airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
            airflow_version_comparable=$$(ver $${airflow_version})
            min_airflow_version=2.2.0
            min_airflow_version_comparable=$$(ver $${min_airflow_version})
            if (( airflow_version_comparable < min_airflow_version_comparable )); then
              echo
              echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
              echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
              echo
              exit 1
            fi
            if [[ -z "${AIRFLOW_UID}" ]]; then
              echo
              echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
              echo "If you are on Linux, you SHOULD follow the instructions below to set "
              echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
              echo "For other operating systems you can get rid of the warning with manually created .env file:"
              echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#setting-the-right-airflow-user"
              echo
            fi
            one_meg=1048576
            mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
            cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
            disk_available=$$(df / | tail -1 | awk '{print $$4}')
            warning_resources="false"
            if (( mem_available < 4000 )) ; then
              echo
              echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
              echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
              echo
              warning_resources="true"
            fi
            if (( cpus_available < 2 )); then
              echo
              echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
              echo "At least 2 CPUs recommended. You have $${cpus_available}"
              echo
              warning_resources="true"
            fi
            if (( disk_available < one_meg * 10 )); then
              echo
              echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
              echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
              echo
              warning_resources="true"
            fi
            if [[ $${warning_resources} == "true" ]]; then
              echo
              echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
              echo "Please follow the instructions to increase amount of resources available:"
              echo "   https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#before-you-begin"
              echo
            fi
            mkdir -p /sources/logs /sources/dags /sources/plugins
            chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
            exec /entrypoint airflow version
        # yamllint enable rule:line-length
        environment:
          <<: *airflow-common-env
          _AIRFLOW_DB_UPGRADE: 'true'
          _AIRFLOW_WWW_USER_CREATE: 'true'
          _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
          _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
          _PIP_ADDITIONAL_REQUIREMENTS: ''
        user: "0:0"
        volumes:
          - .:/sources
    
      airflow-cli:
        <<: *airflow-common
        profiles:
          - debug
        environment:
          <<: *airflow-common-env
          CONNECTION_CHECK_MAX_COUNT: "0"
        # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
        command:
          - bash
          - -c
          - airflow
    
      # You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up   # or by explicitly targeted on the command line e.g. docker-compose up flower.   # See: https://docs.docker.com/compose/profiles/   flower:
        <<: *airflow-common
        command: celery flower
        profiles:
          - flower
        ports:
          - 5555:5555
        healthcheck:
          test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
          interval: 10s
          timeout: 10s
          retries: 5
        restart: always
        depends_on:
          <<: *airflow-common-depends-on
          airflow-init:
            condition: service_completed_successfully
    
    volumes:   
        postgres-db-volume:

# Tried to solve the problem

## 1.

- I have tried adding to x-airflow-common environment
- ```AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags```
- I have deleted all my images and containers.
- Rebuilt all images and docker-compse up the project
- but it still did not works.

**Comment by Taragolis** [comment]
I confuse do you use https://github.com/puckel/docker-airflow?

`puckel/docker-airflow` image didn't updated since the official docker image created (airflow 1.10.10). You should avoid to use this image nowadays.

By default modern Airflow expected  [dag_folder](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#dags-folder) in `${AIRLOW_HOME}/dags`, official docker image set AIRFLOW_HOME as `/opt/airflow/`, so default dag_folder for official image is `/opt/airflow/dags`

And if you do not want to change anything you need to mount dags from local folder to `/opt/airflow/dags`

**Reply by stromal** [reply]
@Taragolis that is just a guide that I have tried. I need solution whit my actual code bellow.

**Reply by stromal** [reply]
@Taragolis  I have also mentioned at the very bottom  that I have tried adding
I have tried adding to x-airflow-common environment
```AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags```

**Reply by Taragolis** [reply]
And you need mount your local DAG directory to the scheduler and workers, because webserver since Airflow 2.0.0 do not parse DAGs anymore and read DAGs metadata directly from DB

https://airflow.apache.org/docs/apache-airflow/stable/dag-serialization.html

**Reply by stromal** [reply]
@Taragolis  It always copies over 1 the latest python file from the local dags folder to the container  updates it in a few seconds after I make it in my local machine. But than deletes the previous latest in the container and replace it with my actual latest dag file in the docker container.

**Reply by Taragolis** [reply]
If your `dag` directory not in the same directory as `docker-compose.yml` than you need specify path

Replace `./dags:/opt/airflow/dags` by `/path/to/your/dags/in-host-machine:/opt/airflow/dags`

**Reply by stromal** [reply]
@Taragolis why the original official latest image not automatically routs this in the original guide. it even mentions to create these folders ```mkdir -p ./dags ./logs ./plugins``` https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html

**Reply by stromal** [reply]
@Taragolis  

Folder structure based on documentation:

airflow/ docker-compose.yml
airflow/ dag / ALL_MY_DAG_PYTHON_FILES

this is form the original [documentation](https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html) :
1. ```curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.4.0/docker-compose.yaml' ```
2. ```mkdir -p ./dags ./logs ./plugins```

**Reply by Taragolis** [reply]
Because in documentation it mention that this `docker-compose.yaml` just a sample which can help quick start work with airflow.
And it expected that this your files will created in  `./dags ./logs ./plugins`

```
This procedure can be useful for learning and exploration. 
However, adapting it for use in real-world situations can be complicated. 
Making changes to this procedure will require specialized expertise in Docker & Docker Compose, and the Airflow community may not be able to help you.
```

It can not handle all use cases. So if you have something customisation like location of dag directory you need to change it in `docker-compose.yaml`

**Reply by stromal** [reply]
@Taragolis 
1.) ok than in to what environments does this exact command goes inside the official original airflow docker-compose.yml file?
2.) and in the following case whow should that 1 liner look like?
airflow/ docker-compose.yml
airflow/ dag / ALL_MY_DAG_PYTHON_FILES

Like this?: 
A.) ```/airflow/dags/:/opt/airflow/dags```
B.) ```./airflow/dags/:/opt/airflow/dags```

**Reply by Taragolis** [reply]
First of all lets clarify which docker image you use and which version of airflow you try to use.

**Reply by stromal** [reply]
@Taragolis 

ARIFRLOW 2.4.0

airflow/Dockerfile
```
FROM apache/airflow:latest-python3.8
COPY requirements.txt .
RUN pip install -r requirements.txt
```

airflow/docker-compose.yml
```
version: '3'
x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-my-image-apache/airflow:latest-python3.8} 
```

**Reply by Taragolis** [reply]
Ok, that is fine.

As I understand you correctly than you have some structure like this 
```
/airflow/
├─ logs/
├─ dags/
│  ├─ .airflowignore
│  ├─ dag_1.py
│  ├─ dag_2.py
├─ plugins/
├─ docker-compose.yaml
```

In this case both should work:
1. Relative to docker-compose.yaml directory - `./dags/:/opt/airflow/dags`
2. Absolute path from the root directory `/airflow/dags/:/opt/airflow/dags`

If you expected problems that changes in your dag folder not appear immediately you could change this parameters:

`AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL`  - https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#dag-dir-list-interval , by default Airflow scan for new files only once per 5 minutes
`AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL` - https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#min-file-process-interval
`AIRFLOW__CORE__MIN_SERIALIZED_DAG_FETCH_INTERVAL` - https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#min-serialized-dag-fetch-interval
`AIRFLOW__CORE__MIN_SERIALIZED_DAG_UPDATE_INTERVAL ` - https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#min-serialized-dag-update-interval

**Reply by stromal** [reply]
@Taragolis 
- correct folder structure
- I have deleted everything via ```docker-compose down --volumes --rmi all``` than rebuilt my image and restarted the container with the new .yml file

```
---
version: '3'
x-airflow-common:
  &airflow-common
  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  image: ${AIRFLOW_IMAGE_NAME:-my-image-apache/airflow:latest-python3.8} 
  ### SAME AS IN MY DOCKERFILE "FROM apache/airflow:latest-python3.8" BUT I CAN MODIFY IT AS THE IAMGE THAT I GNERATE IS THE IMPORTANT ONE
  # my-image-apache/airflow:latest-python3.8}
  # build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    # For backward compatibility, with Airflow <2.3
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}

    # I have added these
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'true'
    #AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    #connect local and docker conatiner DAGS folers
    #AIRFLOW__CORE__DAGS_FOLDER: ./dags
  

    # AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
    # AIRFLOW__CORE__LOGGING_CONFIG_CLASS: airflow.utils.log.logging_config.DEFAULT_LOGGING_CONFIG
    # AIRFLOW__CORE__LOGGING_LEVEL: INFO

  volumes:
    - ./dags/:/opt/airflow/dags
    - ./logs/:/opt/airflow/logs
    - ./plugins/:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

```

NEW (I have added the extra / just before the :    )
```
  volumes:
    - ./dags/:/opt/airflow/dags
    - ./logs/:/opt/airflow/logs
    - ./plugins/:/opt/airflow/plugins
```

ORIGINAL 
```
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
```

It did not made any difference even after 5 min
