### DISCUSSION TITLE
airflow flower not working properly

### DISCUSSION THREAD

**Discussion by iRecursion** [apache/airflow#26956] [Q&A]
# Environment
`ubuntu 20.04 lts` `apache/airflow:2.4.1-python3.9`

# Redis
```shell
127.0.0.1:6379> keys *
1) "_kombu.binding.celery.pidbox"
2) "_kombu.binding.celeryev"
3) "_kombu.binding.default"
127.0.0.1:6379> acl list
1) "user default on #2a5a461eb2ae9494652f5ebf5920f9ff8cbbf3ff4e42f3b1ee67593ead0027af ~* &* +@all"
2) "user redis_user on #2a5a461eb2ae9494652f5ebf5920f9ff8cbbf3ff4e42f3b1ee67593ead0027af ~* &* +@all"
127.0.0.1:6379> 
```

# docker-compose.yaml
```yaml
  redis: 
    restart: always
    privileged: true
    image: redis:705
    container_name: airflow-redis705
    ports: 
      - 6379:6379
    volumes: 
      - /opt/middleware/redis705/data:/data
      - /opt/middleware/redis705/conf:/usr/local/etc/redis
    command: /usr/local/bin/redis-server /usr/local/etc/redis/redis.conf
    healthcheck: 
      test: ["CMD", "redis-cli","-a","redis_pass", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5

  flower: 
    <<: *airflow-common
    command: celery flower
    container_name: airflow-flower
    profiles:
      - flower
    ports:
      - 5555:5555
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

x-airflow-common:
  &airflow-common
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.4.1-python3.9}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://airflow_user:airflow_cipher@192.168.9.108:3307/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://redis_user:redis_pass@192.168.9.108:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+mysql://airflow_user:airflow_cipher@192.168.9.108:3307/airflow
    AIRFLOW__CELERY__FLOWER_BASIC_AUTH: flower_user:flower_cipher
    AIRFLOW__CELERY__FLOWER_HOST: 0.0.0.0
    AIRFLOW__CELERY__FLOWER_PORT: 5555
    AIRFLOW__CELERY__FLOWER_URL_PREFIX: /flower
```

# Container Status
```shell
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS                      PORTS                                                  NAMES
59777976ed8c   airflow_generic:0.0.1   "/usr/bin/dumb-init …"   23 minutes ago   Up 22 minutes (healthy)     8080/tcp                                               airflow-airflow-triggerer-1
1fdc8a42b40b   airflow_generic:0.0.1   "/usr/bin/dumb-init …"   23 minutes ago   Up 22 minutes (healthy)     0.0.0.0:8080->8080/tcp, :::8080->8080/tcp              airflow-webserver
ccdd17b5b619   airflow_generic:0.0.1   "/usr/bin/dumb-init …"   23 minutes ago   Up 22 minutes (unhealthy)   0.0.0.0:5555->5555/tcp, :::5555->5555/tcp, 8080/tcp    airflow-flower
aeaee260b5c2   airflow_generic:0.0.1   "/usr/bin/dumb-init …"   23 minutes ago   Up 22 minutes (healthy)     8080/tcp                                               airflow-scheduler
f25428a26521   airflow_generic:0.0.1   "/usr/bin/dumb-init …"   23 minutes ago   Up 22 minutes (healthy)     8080/tcp                                               airflow-worker
21caceceea24   airflow_generic:0.0.1   "/bin/bash -c 'funct…"   23 minutes ago   Exited (0) 22 minutes ago                                                          airflow-airflow-init-1
c42892513f36   redis:7.0.5             "docker-entrypoint.s…"   23 minutes ago   Up 22 minutes (healthy)     0/tcp, 0.0.0.0:6379->6379/tcp, :::6379->6379/tcp       airflow-redis705
13f25c183d1e   mysql:8.0.30            "docker-entrypoint.s…"   23 minutes ago   Up 22 minutes (healthy)     33060/tcp, 0.0.0.0:3307->3306/tcp, :::3307->3306/tcp   airflow-mysql8030
```

# airflow flower logs
```shell
# docker logs airflow-flower

airflow-flower  | [[34m2022-10-09 23:46:39,801[0m] {[34mmixins.py:[0m225} INFO[0m - Connected to redis://redis_user:**@192.168.9.108:6379/0[0m
airflow-flower  | [[34m2022-10-09 23:46:40,878[0m] {[34minspector.py:[0m42} WARNING[0m - Inspect method active_queues failed[0m
airflow-flower  | [[34m2022-10-09 23:46:40,882[0m] {[34minspector.py:[0m42} WARNING[0m - Inspect method registered failed[0m
airflow-flower  | [[34m2022-10-09 23:46:40,885[0m] {[34minspector.py:[0m42} WARNING[0m - Inspect method active failed[0m
airflow-flower  | [[34m2022-10-09 23:46:40,888[0m] {[34minspector.py:[0m42} WARNING[0m - Inspect method scheduled failed[0m
airflow-flower  | [[34m2022-10-09 23:46:40,890[0m] {[34minspector.py:[0m42} WARNING[0m - Inspect method conf failed[0m
airflow-flower  | [[34m2022-10-09 23:46:40,900[0m] {[34minspector.py:[0m42} WARNING[0m - Inspect method revoked failed[0m
airflow-flower  | [[34m2022-10-09 23:46:40,902[0m] {[34minspector.py:[0m42} WARNING[0m - Inspect method stats failed[0m
airflow-flower  | [[34m2022-10-09 23:46:40,903[0m] {[34minspector.py:[0m42} WARNING[0m - Inspect method reserved failed[0m
airflow-flower  | [[34m2022-10-10 09:51:08,698[0m] {[34mweb.py:[0m1219} ERROR[0m - Uncaught exception in write_error[0m

airflow-flower  | During handling of the above exception, another exception occurred:
airflow-flower  | 
airflow-flower  | Traceback (most recent call last):
airflow-flower  |   File "/home/airflow/.local/lib/python3.9/site-packages/flower/views/__init__.py", line 73, in get_current_user
airflow-flower  |     basic, credentials = auth_header.split()
airflow-flower  | ValueError: not enough values to unpack (expected 2, got 0)
airflow-flower  | 
airflow-flower  | During handling of the above exception, another exception occurred:
airflow-flower  | Traceback (most recent call last):
airflow-flower  |   File "/home/airflow/.local/lib/python3.9/site-packages/tornado/web.py", line 1217, in send_error
airflow-flower  |     self.write_error(status_code, **kwargs)
airflow-flower  |   File "/home/airflow/.local/lib/python3.9/site-packages/flower/views/__init__.py", line 43, in write_error
airflow-flower  |     self.render('404.html', message=message)
airflow-flower  |   File "/home/airflow/.local/lib/python3.9/site-packages/flower/views/__init__.py", line 36, in render
airflow-flower  |     super(BaseHandler, self).render(*args, **kwargs)
airflow-flower  |   File "/home/airflow/.local/lib/python3.9/site-packages/tornado/web.py", line 863, in render
airflow-flower  |     html = self.render_string(template_name, **kwargs)
airflow-flower  |   File "/home/airflow/.local/lib/python3.9/site-packages/tornado/web.py", line 1010, in render_string
airflow-flower  |     namespace = self.get_template_namespace()
airflow-flower  |   File "/home/airflow/.local/lib/python3.9/site-packages/tornado/web.py", line 1026, in get_template_namespace
airflow-flower  |     current_user=self.current_user,
airflow-flower  |   File "/home/airflow/.local/lib/python3.9/site-packages/tornado/web.py", line 1340, in current_user
airflow-flower  |     self._current_user = self.get_current_user()
airflow-flower  |   File "/home/airflow/.local/lib/python3.9/site-packages/flower/views/__init__.py", line 78, in get_current_user
airflow-flower  |     raise tornado.web.HTTPError(401)
airflow-flower  | tornado.web.HTTPError: HTTP 401: Unauthorized
```

but airflow works well

[![](https://raw.githubusercontent.com/iRecursion/repo-discussion/main/Image/Discussion/airflow-hw.png)]()

what's wrong with flower,or where the flower is incorrectly configured?it is impossible to connect to Redis,cause authorization failure？
