### DISCUSSION TITLE
Installing Airflow using helm charts

### DISCUSSION THREAD

**Discussion by tkansara** [apache/airflow#27121] [General]
Hello All

I have following configuration using the airflow-helm.github.io/charts which works however when I change the repository to as below show, i get the error 
```
release/airflow helmVersion=v3 error="failed to prepare chart for release: chart unavailable: looks like \"https://github.com/apache/airflow/tree/master/chart\" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/apache/airflow/tree/master/chart/index.yaml : 404 Not Found"
```

Here is the yaml file that I am installing on eks:

```

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: airflow
  namespace: flux
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: airflow-dev1
  chart:
    #repository: airflow-helm.github.io/charts
    #name: airflow
    #version: 8.6.1
    repository:  https://github.com/apache/airflow/tree/master/chart
    name: airflow
    version: 1.7.0

  values:
      ..............................
```

Any suggestions on what should be the values for repository and name If i wanted to use the apache/airflow git repo ?

Thanks
