### DISCUSSION TITLE
Helm Chart fails on EKS

### DISCUSSION THREAD

**Discussion by KishinNext** [apache/airflow#27311] [General]
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.4.1

### Kubernetes Version

v4.5.7

### Helm Chart configuration

The last helm char for Airflow

### Docker Image customisations

None

### What happened

I'm using the last helm chart of Airflow, and I used this configuration for the cluster on EKS... but I get this error

### Error
```
nstall.go:192: [debug] Original chart version: ""
install.go:209: [debug] CHART PATH: /home/ec2-user/.cache/helm/repository/airflow-1.7.0.tgz

client.go:310: [debug] Starting delete for "airflow-broker-url" Secret
client.go:339: [debug] secrets "airflow-broker-url" not found
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airflow-fernet-key" Secret
client.go:339: [debug] secrets "airflow-fernet-key" not found
client.go:128: [debug] creating 1 resource(s)
client.go:310: [debug] Starting delete for "airflow-redis-password" Secret
client.go:339: [debug] secrets "airflow-redis-password" not found
client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 30 resource(s)
client.go:310: [debug] Starting delete for "airflow-run-airflow-migrations" Job
client.go:339: [debug] jobs.batch "airflow-run-airflow-migrations" not found
client.go:128: [debug] creating 1 resource(s)
client.go:540: [debug] Watching for changes to Job airflow-run-airflow-migrations with timeout of 10m0s
client.go:568: [debug] Add/Modify event for airflow-run-airflow-migrations: ADDED
client.go:607: [debug] airflow-run-airflow-migrations: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:568: [debug] Add/Modify event for airflow-run-airflow-migrations: MODIFIED
client.go:607: [debug] airflow-run-airflow-migrations: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition
helm.go:84: [debug] failed post-install: timed out waiting for the condition
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:141
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1571
```

### PostgreSQL describe pod

```
Name:             airflow-postgresql-0
Namespace:        airflow
Priority:         0
Service Account:  default
Node:             <none>
Labels:           app.kubernetes.io/component=primary
                  app.kubernetes.io/instance=airflow
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=postgresql
                  controller-revision-hash=airflow-postgresql-d9b49657b
                  helm.sh/chart=postgresql-10.5.3
                  role=primary
                  statefulset.kubernetes.io/pod-name=airflow-postgresql-0
Annotations:      kubernetes.io/psp: eks.privileged
Status:           Pending
IP:
IPs:              <none>
Controlled By:    StatefulSet/airflow-postgresql
Containers:
  airflow-postgresql:
    Image:      docker.io/bitnami/postgresql:11.12.0-debian-10-r44
    Port:       5432/TCP
    Host Port:  0/TCP
    Requests:
      cpu:      250m
      memory:   256Mi
    Liveness:   exec [/bin/sh -c exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/sh -c -e exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
[ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                        false
      POSTGRESQL_PORT_NUMBER:               5432
      POSTGRESQL_VOLUME_DIR:                /bitnami/postgresql
      PGDATA:                               /bitnami/postgresql/data
      POSTGRES_USER:                        postgres
      POSTGRES_PASSWORD:                    <set to the key 'postgresql-password' in secret 'airflow-postgresql'>  Optional: false
      POSTGRESQL_ENABLE_LDAP:               no
      POSTGRESQL_ENABLE_TLS:                no
      POSTGRESQL_LOG_HOSTNAME:              false
      POSTGRESQL_LOG_CONNECTIONS:           false
      POSTGRESQL_LOG_DISCONNECTIONS:        false
      POSTGRESQL_PGAUDIT_LOG_CATALOG:       off
      POSTGRESQL_CLIENT_MIN_MESSAGES:       error
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES:  pgaudit
    Mounts:
      /bitnami/postgresql from data (rw)
      /dev/shm from dshm (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-58lzq (ro)
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-airflow-postgresql-0
    ReadOnly:   false
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  kube-api-access-58lzq:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
```

The pods never run

![image](https://user-images.githubusercontent.com/45041472/198188198-ab0bd75f-f04e-4c93-8651-f299f267e241.png)

### What you think should happen instead

No idea, on the local environment (Kubernetes using Docker) the helm char works fine.

### Comand used
```
 helm install airflow apache-airflow/airflow --namespace airflow --debug --timeout 10m0s
```

### Cluster Config

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: airflow
  region: us-east-1
  version: "1.23"

managedNodeGroups:
  - name: workers
    instanceType: t3.medium
    privateNetworking: true
    minSize: 1
    maxSize: 3
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: airflow-workstation
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        externalDNS: true
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by boring-cyborg** [comment]
Thanks for opening your first issue here! Be sure to follow the issue template!

**Comment by potiuk** [comment]
This is at most a discussion - you should see what logs and errors and warnings you get on the k8s level (not airflow) and you should see what's wrong. There can be multiple reasons (and you need to learn how to find them in particular k8s deployment you use).

You most likely lack some resources (for example your Postgres DB has not started - which means that most likely your K8S cluster does not have enough memory to start the pod.

**Reply by KishinNext** [reply]
I understand when you refer to the logs, but the problem is that the implementation does not give me more information about the problem, neither logs nor relevant information about why it fails, regarding the memory, I do not think it is the solution, I just tried with an xlarge cluster size that gives me 4 vCPU and 16 GB of RAM and fails with the same log, when I implement the same helm in local it does not request more than 4 GB of RAM.

**Reply by potiuk** [reply]
Yes it does not give you more information because you need to look at logs of K8S. This is how Airflow works. Helm chart merely prepares and uploads K8S resources and in order to manage and monitor your application deployed to K8S you need to learn on your own how to do it. If you do not want to learn how to monitor your app on K8S, simply don't use it. But you have no other choice if you chose K8S is to learn how to get and look at logs and understand problems, I am afraid. 

You cannot treat K8S as black box and assume that Airflow team will handle your deployment issues :). This is not a helpdesk, we try to help our users in our free time, but managing Airflow deployment, looking at logs and trying to understand what configuration you should apply is something likely your employer pays you to do (or if not then probably somoene else in your team is paid for it so consult it with them). We are very clear about skils you need and expectations of things you should handle (and what is being handled by sofware published from Airflow)  for each deploymentt type you chose -  https://airflow.apache.org/docs/apache-airflow/stable/installation/index.html#using-official-airflow-helm-chart - Managing your K8S cluster is not something we can do for you. 

As the first step I can recommend `k9s` tool - it's a great to tool to start learning K8S. It helps to learn aa good deal about Pods, Containers,   Other resource types - allows to navigate your installation  to get logs  - this is indespensible tool of everyone who is new to K8S.

**Reply by potiuk** [reply]
Really just check why your pods are Pending.

K8S BTW has very good troubleshooting documentation - you just need to google it and follow. For example here you have a recipe what to do if your pods are Pending: https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/#:~:text=My%20pod%20stays%20pending,or%20another%20that%20prevent%20scheduling.

**Comment by mconigliaro** [comment]
I'm having this same issue. What I've noticed is that if you wait long enough, the events section for `airflow-postgresql-0`, `airflow-redis-0`, and `airflow-worker-0` changes from the unhelpful `Events: <none>` to:

```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  3m7s  default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: timed out waiting for the condition
```

I'll follow up with more when I figure out what this means.

**Reply by mconigliaro** [reply]
Funny, searching this repo for `VolumeBinding` only returns my previous comment. 😂

**Reply by mconigliaro** [reply]
Ah ha, I just discovered three persistent volume claims with a `Pending` status (one for each of the pending pods above), but I don't have the EBS CSI driver installed on this cluster. I'll get that set up and report back...

**Reply by mconigliaro** [reply]
Yup, that fixed it. 👍

**Reply by r-gautam** [reply]
EBS CSI driver does not support READWRITEMANY mode, i am wondering how you have configured logging for worker pods? NFS?

**Comment by r-gautam** [comment]
i did face such issues as well, but i was able to discover the actual cause most of the time while running 
`kubectl get events --watch` on the side terminal while installing airflow using helm.

**Comment by r4881t** [comment]
I am in a similar situation. I am using a service [Qovery](https://qovery.com) that manages my Kube Clusters. I am trying to deploy **Airflow using helm on a K3S**  and I am getting issues. 

I am using Chart version `1.12.0`

My overridden values.yaml looks like below

```yaml
executor: LocalExecutor

postgresql:
    enabled: false 

redis:
    enabled: false 

useStandardNaming: true

statsd:
  enabled: false

images:
  useDefaultImageForMigration: true

webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: admin100
    email: admin@mydomain.com
    firstName: Admin
    lastName: Kumar
    password: changeme


scheduler:
  resources:
   limits:
    cpu: 100m
    memory: 128Mi
   requests:
    cpu: 100m
    memory: 128Mi


data:
  metadataConnection:
    user: qovery.env.AFLOW_DB_USER
    pass: qovery.env.AFLOW_DB_PASS
    protocol: postgresql
    host: qovery.env.AFLOW_DB_HOST
    port: qovery.env.AFLOW_DB_PORT
    db: qovery.env.AFLOW_DB_DATABASE_NAME
    sslmode: allow

# The qovery.env.<ENV_VAR> is a macro that replaces this with the actual
# env variable set in Qovery
fernetKey: qovery.env.AIRFLOW__CORE__FERNET_KEY

webserverSecretKey: qovery.env.WEBSERVER_SECRET_KEY

env:
  - name: AIRFLOW__LOGGING__LOGGING_LEVEL
    value: DEBUG

```

On streaming events I see the following

![Screenshot 2024-02-23 at 3 08 16 PM](https://github.com/apache/airflow/assets/81687400/60d293d4-6de5-414d-a1fa-c9aebb3ffda5)


It seems like the database migration Job is not getting started. Any clues what could be wrong? I am  very sure that the env values for database connection are correct & working
