### DISCUSSION TITLE
How correct dependencies install in Airflow in Kubernetes

### DISCUSSION THREAD

**Discussion by Romsik788** [apache/airflow#27549] [Q&A] [answered]
Hi, 
I need to deploy Apache Airflow in Kubernetes with some dependencies. These dependencies are spelled out in the requirements.txt file. During deployment, I run the pip install command to install the dependencies, but in the end Apache Airflow doesn't see them. To deploy Apache Airflow, I use [Helm](https://artifacthub.io/packages/helm/apache-airflow/airflow/1.6.0) version 1.6.0 with the following settings:
```
elasticsearch:
  enabled: true
workers:
  persistence:
    storageClassName: oci-bv
  args:
    - "bash"
    - "-c"
    - |-
      pip install --no-cache-dir -r /opt/airflow/dags/repo/accounting/requirements/requirements.txt && \
      airflow {{ semverCompare ">=2.0.0" .Values.airflowVersion | ternary "celery worker" "worker" }}
redis:
  persistence:
    storageClassName: oci-bv
images:
  useDefaultImageForMigration: true
createUserJob:
  useHelmHooks: false
migrateDatabaseJob:
  useHelmHooks: false
dags:
  gitSync:
    enabled: true
    repo: ***
    branch: master
    credentialsSecret: dev-ipaas-env-secrets-airflow-git-auth-user
    subPath: "/"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    storageClassName: oci-bv
webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: ***
    firstName: admin
    lastName: user
config:
  elasticsearch:
    write_stdout: 'True'
```
P.S. I am not very experienced with Apache Airflow, so I would like to hear some reasoned answers.
