### DISCUSSION TITLE
airflow db upgrade hangs against aws

### DISCUSSION THREAD

**Discussion by Frank-T-Johansen** [apache/airflow#27919] [General]
### Apache Airflow version

2.4.3

### What happened

I tried to run "airflow db upgrade" after ugprading airflow from 2.4.2 to 2.4.3, but the command just hung.

When I did strace it was trying to connect to AWS ssm, which is odd as my airflow installation is on a local server.

[root@<hostname> ~]# ps -ef|grep "db upgrade"
airflow   819024  819023  0 09:43 pts/1    00:00:02 /data01/airflow/.pyenv/versions/3.9.12/bin/python3.9 /data01/airflow/.pyenv/versions/3.9.12/bin/airflow db upgrade
root@<hostname> ~]# strace -f -p 819024
strace: Process 819024 attached with 8 threads
[...]
[pid 819024] connect(6, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("52.95.123.56")}, 16) = -1 EINPROGRESS (Operation now in progress)

[airflow@<hostname> ~]$ host ssm.eu-west-1.amazonaws.com
ssm.eu-west-1.amazonaws.com has address 52.95.123.56

Anyone have any clue as to why airflow would try to talk to AWS SSM from a local server?  Could hackers have injected code to steal our secrets?

Btw, AWS is configured on this local server on the account where airflow is running, as it is being used for sending logs to s3.
But we don't use SSM for anything related to Airflow.

### What you think should happen instead

"airflow db upgrade" shouldn't talk to AWS, and should not hang.

### How to reproduce

Install 2.4.2, upgrade to 2.4.3, run airflow db upgrade

### Operating System

RedHat 8.6

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==6.1.0
apache-airflow-providers-common-sql==1.3.0
apache-airflow-providers-ftp==3.2.0
apache-airflow-providers-hashicorp==3.2.0
apache-airflow-providers-http==4.1.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-odbc==3.1.2
apache-airflow-providers-oracle==3.5.0
apache-airflow-providers-slack==7.0.0
apache-airflow-providers-snowflake==4.0.0
apache-airflow-providers-sqlite==3.2.1
apache-airflow-providers-ssh==3.3.0

### Deployment

Virtualenv installation

### Deployment details

Python 3.9.12, using usual constraint file for airflow

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Frank-T-Johansen** [comment]
It looks like the upgrade failed also, so I didn't need db upgrade:

[airflow@<server> ~]$ /data01/airflow/.pyenv/versions/3.9.12/bin/pip install 'apache-airflow[odbc]' --constraint file:///data01/airflow/airflow/constraints.txt
[lots of output that looks OK, until:]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
apache-airflow-providers-snowflake 4.0.0 requires apache-airflow-providers-common-sql>=1.3.0, but you have apache-airflow-providers-common-sql 1.2.0 which is incompatible.
apache-airflow-providers-slack 7.0.0 requires apache-airflow-providers-common-sql>=1.3.0, but you have apache-airflow-providers-common-sql 1.2.0 which is incompatible.
apache-airflow-providers-oracle 3.5.0 requires apache-airflow-providers-common-sql>=1.3.0, but you have apache-airflow-providers-common-sql 1.2.0 which is incompatible.
apache-airflow-providers-amazon 6.1.0 requires apache-airflow-providers-common-sql>=1.3.0, but you have apache-airflow-providers-common-sql 1.2.0 which is incompatible.
Successfully installed apache-airflow-providers-common-sql-1.2.0 apache-airflow-providers-ftp-3.1.0 apache-airflow-providers-http-4.0.0
[airflow@<server> ~]$ echo $?
0
Why would it give exit value 0 (which is why I didn't discover it)

[airflow@<server> ~]$ airflow version
2.4.2

And its still 2.4.2, it seems.  I succeeded in upgrading dev environment to 2.4.3 using same method a week ago.

**Comment by Frank-T-Johansen** [comment]
I managed to upgrade to 2.4.3 by modifying constraint on apache-airflow-providers-common-sql from 1.2.0 to 1.3.0 and adding ==2.4.3 to the pip command, and after that the db upgrade also worked as intended

**Comment by Taragolis** [comment]
@Frank-T-Johansen That is a bit strange. 
Airflow might use [Secrets Backend](https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/secrets-backend/index.html) for retrieve some configurations but it might only happen if you setup [AWS SSM Parameter Store Secrets Backend](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/secrets-backends/aws-ssm-parameter-store.html).

**Comment by Frank-T-Johansen** [comment]
I guess someone should check if that gets called regardless of being configured or not.  Or maybe there is no such local config file, and the test to see if it is configured is to talk to AWS SSM backend

**Comment by Taragolis** [comment]
> I guess someone should check if that gets called regardless of being configured or not. 

This is a part of unit tests which as far as I know pass successfully.

From your side you might check your airflow configuration by
1. If expose config enabled than you might check it in the UI: Admin -> Configurations
2. By cli: `airflow config get-value secrets backend`

**Comment by Frank-T-Johansen** [comment]
That gives no output, I guess because its not configured

**Comment by Taragolis** [comment]
Unfortunetly I've unable to reproduce this.
Airflow do not required internet access for `upgrade db` in case if Secrets Backends not uses. 
AWS SSM client only use in one place if it specified as secrets backend.

```yaml
version: '3'

networks:
  no-internet-access:
    driver: bridge
    internal: true

volumes:
  postgres-db-volume:

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: insecurepassword
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow", "-d", "airflow"]
      interval: 5s
      retries: 5
    restart: on-failure
    networks:
      - no-internet-access

  airflow-upgrade:
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.4.3}
    environment:
      CONNECTION_CHECK_MAX_COUNT: "0"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:insecurepassword@postgres/airflow
      # AIRFLOW__SECRETS__BACKEND: 'airflow.providers.amazon.aws.secrets.systems_manager.SystemsManagerParameterStoreBackend'
      # AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_SECRET: boom
    command: ["db", "upgrade"]
    networks:
      - no-internet-access
    depends_on:
      postgres:
        condition: service_healthy

  airflow-version:
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.4.3}
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:insecurepassword@postgres/airflow
    command: version
    networks:
      - no-internet-access
    depends_on:
      airflow-upgrade:
        condition: service_completed_successfully
```
