### DISCUSSION TITLE
Airflow/Kubernetes podTemplate issue: MountVolume.SetUp failed for volume "airflow-ssh-secret" (or any other volume)

### DISCUSSION THREAD

**Discussion by ginwakeup** [apache/airflow#28383] [Q&A]
Hello everybody,

I am fighting with a tricky issue on airflow/kubernetes.

I want to run DAGs using a podTemplate, but I am getting the following error on pod startup:

```MountVolume.SetUp failed for volume "airflow-ssh-secret" : object "airflow"/"airflow-ssh-secret" not registered```

The DAG code:

```python
import logging
import sys
import tempfile
import pendulum

from airflow import DAG
from airflow.decorators import task

log = logging.getLogger(__name__)


with DAG(
    dag_id="example_external_python_operator",
    schedule=None,
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
    catchup=False
) as dag:

    @task(task_id="check_mount", executor_config={
            "pod_template_file": "/opt/airflow/dags/repo/podTemplates/test.yaml",
        },)
    def check_mount():
        import os

        log.info(f"Venvs are mounted: {os.path.exists('/mnt/venvs')}")

    check_mount()
```

The podTemplate:

```
apiVersion: v1
kind: Pod
metadata:
  name: airflow-worker
  labels:
    tier: airflow
    component: worker
    release: airflow
spec:
  initContainers:
    - name: git-sync
      image: "k8s.gcr.io/git-sync/git-sync:v3.4.0"
      env:
        - name: GIT_SYNC_BRANCH
          value: "testing"
        - name: GIT_SYNC_REPO
          value: "..."
        - name: GIT_SYNC_DEPTH
          value: "1"
        - name: GIT_SYNC_SSH_KEY_FILE
          value: "/run/secrets/airflow-ssh-secret"
        - name: GIT_SYNC_ROOT
          value: "/git"
        - name: GIT_SYNC_DEST
          value: "repo"
        - name: GIT_SYNC_ADD_USER
          value: "true"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
      volumeMounts:
        - name: airflow-dags
          mountPath: /git
        - name: airflow-ssh-secret
          mountPath: "/run/secrets/airflow-ssh-secret"
  containers:
    - name: airflow-worker
      image: apache/airflow:2.5.0
      volumeMounts:
        - mountPath: "/opt/airflow/logs"
          name: airflow-logs
        - mountPath: "/mnt/venvs"
          name: airflow-venvs-pv
        - mountPath: /opt/airflow/dags
          name: airflow-dags
          subPath: repo/airflow/
          readOnly: false

  restartPolicy: Never
  securityContext:
    runAsUser: 50000
    fsGroup: 50000
  serviceAccountName: airflow-worker
  volumes:
    - name: airflow-ssh-secret
      secret:
        secretName: airflow-ssh-secret
    - name: airflow-venvs-pv
      persistentVolumeClaim:
        claimName: airflow-venvs-pv-claim
    - name: airflow-dags
      emptyDir: { }
    - name: airflow-logs
      emptyDir: { }
```

Basically the error appears for any kind of volume that I try to use in this podTemplate.
Am I missing something?
