### DISCUSSION TITLE
Airflow URL returning 404

### DISCUSSION THREAD

**Discussion by NolusindisoMakosa** [apache/airflow#28826] [General]
### Official Helm Chart version

1.4.0

### Apache Airflow version

2.3.4

### Kubernetes Version

2.12.0

### Helm Chart configuration

```
env:
  - name: "AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX"
    value: "true"
  - name: AIRFLOW__WEBSERVER__BASE_URL
    value: "http://localhost:8080/user1"

config:
  webserver:
    base_url: https://users.******************.co.za/$user1

```

### What happened

I have deployed Airflow using the helm chart. When checking on the pods, all pods seem to be running fine, including webserver. When I try to use base_url: https://users.*******.co.za/user1 to access airflow, I get the airflow 404 page. And when I use the AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8080/user1, no page shows up. This is the error I keep getting. 

![IMG-5200](https://user-images.githubusercontent.com/70475434/211515005-4bf8bfb7-a975-486b-b530-15329cfafc78.jpg)

### What you think should happen instead

Be able to access Airflow using the base_url: https://users.*******.co.za/user1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
