### DISCUSSION TITLE
Losing logs from Task

### DISCUSSION THREAD

**Discussion by PhoenixChamb** [apache/airflow#28918] [Q&A]
Hello,

Hello, 

**Apache Airflow version**
The versions of postgres and airflow that we currently have are the following ones:
- Postgresql: **15.1**
- Airflow:       **2.5.0**

**What happened**
We are randomly losing some task logs for our tasks

-------------------------------------------

As the following example:
`*** Log file does not exist: /opt/airflow/logs/dag_id=tca_*****_loader/run_id=scheduled__2022-02-14T00:00:00+00:00/task_id=data-fetch/attempt=2.log
*** Fetching from: http://********/log/dag_id=tca_*****_loader/run_id=scheduled__2022-02-14T00:00:00+00:00/task_id=data-fetch/attempt=2.log
*** Failed to fetch log file from worker. Client error '404 NOT FOUND' for url 'http://******/log/dag_id=tca_*********_loader/run_id=scheduled__2022-02-14T00:00:00+00:00/task_id=data-fetch/attempt=2.log'
For more information check: https://httpstatuses.com/404
`
The hostname is correctly assigned
![image](https://user-images.githubusercontent.com/122443108/212293737-3aae1476-aef7-4161-8326-400aa3f3f131.png)

As we can see here the route is correctly created but no logs are there (is empty).
![image](https://user-images.githubusercontent.com/122443108/212294023-d1e56920-0728-497c-8f10-d7b163ffcef6.png)

If the retries occur immediately, the same error of not finding the logs continues to occur, however if we relaunch a few hours later the task is executed correctly

**How to reproduce**
It occurs randomly in the executions of our tasks, we do not observe a logical pattern. 

**Deployment details**

```
containers:
        # Always run the main scheduler container.
        - name: scheduler
          image: {{ template "airflow_image" . }}
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - -c
                  - "/opt/airflow/dags/*****/workflow/*_entity_dags_generate.bash || echo 'cannot generate dags' >> /opt/airflow/logs/*_entities_dags_generation.log"
          imagePullPolicy: IfNotPresent
          args: ["scheduler"]
          env:
            - name: IMAGE_TAG
              value: *****
            {{- if and .Values.smtp.password .Values.smtp.user }}
            - name: AIRFLOW__SMTP__SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: *****
                  name: *****
            - name: AIRFLOW__SMTP__SMTP_USER
              valueFrom:
                secretKeyRef:
                  key: *****
                  name: *****
            {{- end }}
            - name: POSTGRES_HOST
              value: ******
            - name: POSTGRES_DB
              value: ******
            - name: POSTGRES_USER
              value: ******
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: ******
                  name: ******
          {{- if .Values.scheduler.env }}
          {{- toYaml .Values.scheduler.env | nindent 12 }}
          {{- end }}
          {{- include "custom_airflow_environment" . | indent 10 }}
          {{- include "standard_airflow_environment" . | indent 10 }}
          # If the scheduler stops heartbeating for 5 minutes (10*30s) kill the
          # scheduler and let Kubernetes restart it
          livenessProbe:
            timeoutSeconds: {{ .Values.scheduler.livenessProbe.timeoutSeconds }}
            failureThreshold: 10
            periodSeconds: 30
            exec:
              command:
              - /usr/bin/env
              - AIRFLOW__CORE__LOGGING_LEVEL=ERROR
              - python3
              - -Wignore
              - -c
              - |
                from airflow.jobs.scheduler_job import SchedulerJob
                from airflow.utils.net import get_hostname
                import sys

                job = SchedulerJob.most_recent_job()
                sys.exit(0 if job.is_alive() and job.hostname == get_hostname() else 1)
```

**What you think should happen instead**
The log files are created correctly for each attempt

**Versions of Apache Airflow Providers**
Also comment that we are using for all these jobs the library from 'airflow.contrib.operators.kubernetes_pod_operator import KubernetesPodOperator'.
Not PGBouncer used.
LocalExecutor used.

**Are you willing to submit PR?**
 Yes I am willing to submit a PR!
