### DISCUSSION TITLE
All the Airflow Pods are failing with SIGTERM Error

### DISCUSSION THREAD

**Discussion by wpwiukyjks** [apache/airflow#29222] [Q&A]
Hello Guys,
We are running production airflow setup and all the DAG's are failing with SIGTERM error. Most of them failing on 4min 45 seconds. Below are the details. Please help since production is impacted and none of the DAG's are completing run.
we tried multiple versions of helm charts even used 14 as well.
Also we upgraded from 2.3.2 to 2.3.4 but same issue persist. Any help is appreciated.
Example:

airflow values

```yaml
## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass

## @section Common parameters
# Following environment variables will be added into all the pods (scheduler, web, worker)
extraEnvVars:
  - name: DAP_ENVIRONMENT
    value: "#{ENVIRONMENT}#"
  - name: DAP_AUTH_SPN_CLIENT_ID
    value: "#{AUTH-SERVICE-PRINICIPAL-CLIENT-ID}#"
  - name: DAP_AUTH_SPN_CLIENT_SECRET
    value: "#{AUTH-SERVICE-PRINICIPAL-CLIENT-SECRET}#"
  - name: AIRFLOW__WEBSERVER__SECRET_KEY
    value: "xxxx"
  - name: AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX
    value: "True"
  - name: AIRFLOW__WEBSERVER__BASE_URL
    value: "https://#{NGINX_REVERSE_PROXY_SERVER_DNS}#/airflowv3"
  - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
    value: "True"
  - name: AIRFLOW__WEBSERVER__INSTANCE_NAME
    value: "Dap Airflow-V3 (#{ENVIRONMENT}#)"
    # Setting python path with following value will ensure that python modules from extras and libs folder are accessible globally inside scheduler, worker and web containers
  - name: PYTHONPATH
    value: "/opt/bitnami/airflow/config:/opt/bitnami/airflow/extras:/opt/bitnami/airflow/dags/git_airflow-dags/libs"
    # Following AZURE_* env vars are required for python package 'azure-identity' which can be used in the custom dag utils
  - name: AZURE_CLIENT_ID
    value: "#{INFRA-SERVICE-PRINICIPAL-CLIENT-ID}#"
  - name: AZURE_TENANT_ID
    value: "xxx"
  - name: AZURE_CLIENT_SECRET
    value: "#{INFRA-SERVICE-PRINICIPAL-CLIENT-SECRET}#"
    # Email related overrides
    # Airflow will replace default backend with send_email_smtp method in custom_utils/email.py
  - name: AIRFLOW__EMAIL__EMAIL_BACKEND
    value: "custom_utils.email.send_email_smtp"
  - name: AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_FAILURE
    value: "False"
  - name: AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_RETRY
    value: "False"
  - name: AIRFLOW__EMAIL__SUBJECT_TEMPLATE
    value: "/opt/bitnami/airflow/extras/email_template_helpers/subject.j2"  
  - name: AIRFLOW__EMAIL__HTML_CONTENT_TEMPLATE
    value: "/opt/bitnami/airflow/extras/email_template_helpers/body_content.j2"  
  - name: AIRFLOW__LOGGING__LOGGING_LEVEL
    value: "INFO"
  - name: AIRFLOW__LOGGING__FAB_LOGGING_LEVEL
    value: "ERROR"

    # This defines the maximum number of task instances that can run concurrently in Airflow
  - name: AIRFLOW__CORE__PARALLELISM
    value: "128"
  - name: AIRFLOW__CORE__DAG_FILE_PROCESSOR_TIMEOUT
    value: "200"
  - name: AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT
    value: "190"
  - name: AIRFLOW__CORE__DAG_CONCURRENCY
    value: "32"    
  # - name: AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG
  #   value: "32"
  - name: AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG
    value: "32"    
  - name: AIRFLOW__KUBERNETES__WORKER_PODS_CREATION_BATCH_SIZE
    value: "10"
  # - name: AIRFLOW__SCHEDULER__PARSING_PROCESSES
  #   value: "10"
  # - name: AIRFLOW__CORE__KILLED_TASK_CLEANUP_TIME
  #   value: "604800"
  # - name: AIRFLOW__SCHEDULER__SCHEDULE_AFTER_TASK_EXECUTION
  #   value: "False"
  - name: AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC
    value: "60"
  - name: AIRFLOW__SCHEDULER__SCHEDULER_HEALTH_CHECK_THRESHOLD
    value: "130"
  - name: AIRFLOW__SCHEDULER__JOB_HEARTBEAT_SEC
    value: "60"    
  - name: AIRFLOW__CORE__HOSTNAME_CALLABLE
    value: "socket.gethostname"     


    # Schedule all the worker pod in airflow-v3 namespace
  - name: AIRFLOW__KUBERNETES__NAMESPACE
    value: "airflow-v3"
    # Following environment variables are requied to enable remote logging. When worker pod  does it'a job and exits succesfully it will push logs to blob storage,
  - name: AIRFLOW__LOGGING__REMOTE_LOGGING
    value: "True"
  - name: AIRFLOW__LOGGING__LOGGING_CONFIG_CLASS
    value: "log_config.DEFAULT_LOGGING_CONFIG"
  - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
    value: "airflowlogs_wasb_conn"
  - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
    value: "wasb-airflowv3logs"
  - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
    value: "True"    
    # Following details are received from team. Password CSSON-EXT-SMTP-PASSWORD is downlaoded from shared keyvault and pipeline replaces this token #{SSON-EXT-SMTP-PASSWORD}# with the value from key vault.
  - name: AIRFLOW__SMTP__SMTP_HOST
    value: "smtp.eri.net"
  - name: AIRFLOW__SMTP__SMTP_PORT
    value: "587"
  - name: AIRFLOW__SMTP__SMTP_STARTTLS
    value: "True"
  - name: AIRFLOW__SMTP__SMTP_SSL
    value: "False"
  - name: AIRFLOW__SMTP__SMTP_MAIL_FROM
    value: "dataa@erixyz.com"
  - name: AIRFLOW__SMTP__SMTP_USER
    value: "xyz@org.com"
  - name: AIRFLOW__SMTP__SMTP_PASSWORD
    value: "#{ERI-EXT-SMTP-PASSWORD}#"
  - name: AIRFLOW__SCHEDULER__PARSING_PROCESSES
    value: "#{AIRFLOW_SCHEDULER_PARSING_PROCESSES}#"
  #enabling REST using basic auth  
  - name: AIRFLOW__API__AUTH_BACKENDS
    value: "airflow.api.auth.backend.basic_auth"
  - name: AIRFLOW_APIUSER_PASSWORD
    value: "#{AIRFLOW-APIUSER-PASSWORD}#"
  - name: AIRFLOW_OPERATIONS_APIUSER_PASSWORD
    value: "#{AIRFLOW-OPERATIONS-APIUSER-PASSWORD}#"


## Role Based Access
## Ref: https://kubernetes.io/docs/admin/authorization/rbac/
## @param rbac.create If true, create & use RBAC resources
##
rbac:
  create: true

## Pods Service Account
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
## @param serviceAccount.annotations Annotations for service account. Evaluated as a template. Only used if `create` is `true`.
## @param serviceAccount.create Specifies whether a ServiceAccount should be created
##
serviceAccount:
  annotations: {}
  create: true
  ## The name of the service account to use. If not set and create is true, a name is generated using the fullname template.
  # name:

## @section Airflow common parameters

## Authentication
## @param auth.existingSecret Name of an existing secret containing password and fernet key ('airflow-password and 'airflow-fernetKey' keys)
## @param auth.fernetKey Fernet key to secure connections
## @param auth.forcePassword Force users to specify a password
## @param auth.password Password to access web UI
## @param auth.username Username to access web UI
##
auth:
  existingSecret:
  ## More info about the fernet key at:
  ## - https://airflow.readthedocs.io/en/stable/howto/secure-connections.html
  ## - https://bcb.github.io/airflow/fernet-key
  ##
  fernetKey: "#{AIRFLOW_FERNET_KEY}#"
  ## This is required for 'helm upgrade' to work properly.
  ## If it is not forced, a random password will be generated.
  ##
  forcePassword: false
  password: password
  username: user

## @param executor Airflow executor, it should be one of 'SequentialExecutor', 'LocalExecutor', 'CeleryExecutor', 'KubernetesExecutor', 'CeleryKubernetesExecutor'
## ref: http://airflow.apache.org/docs/stable/executor/index.html
##
executor: "KubernetesExecutor"

## @param loadExamples Switch to load some Airflow examples
##
# Pipeline sets AIRFLOW_LOAD_EXAMPLES to True for development and False for production deployment
loadExamples: #{AIRFLOW_LOAD_EXAMPLES}#

## @section Airflow web parameters

web:
  ## Bitnami Airflow image version
  ## ref: https://hub.docker.com/r/bitnami/airflow/tags/
  ## @param web.image.registry Airflow image registry
  ## @param web.image.repository Airflow image repository
  ## @param web.image.tag Airflow image tag (immutable tags are recommended)
  ## @param web.image.pullPolicy Airflow image pull policy
  ## @param web.image.pullSecrets Airflow image pull secrets
  ## @param web.image.debug Enable image debug mode
  image:
    registry: docker.io
    repository: bitnami/airflow
    tag: 2.3.2-debian-11-r0
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    debug: true
  ## @param web.replicaCount Number of web replicas
  ##
  replicaCount: 1
  ## @param web.baseUrl URL used to access to airflow web ui
  ##
  baseUrl: "https://#{NGINX_REVERSE_PROXY_SERVER_DNS}#/airflowv3"
  containerPort: 8080
  ## @param web.extraVolumeMounts Add extra volume mounts
  ##
  # Refer to pipeline to understand how following configmaps are created.
  extraVolumeMounts:
    - name: airflow-log-config
      mountPath: /opt/bitnami/airflow/config
    - name: airflow-webserver-config
      mountPath: /opt/bitnami/airflow/webserver_config.py
      subPath: webserver_config.py
    - name: airflow-custom-utils
      mountPath: /opt/bitnami/airflow/extras/custom_utils
    - name: airflow-email-template-helpers
      mountPath: /opt/bitnami/airflow/extras/email_template_helpers
    - name: airflow-pip-dependencies
      mountPath: /bitnami/python
  ## @param web.extraVolumes Add extra volumes
  ##
  extraVolumes:
    - name: airflow-log-config
      configMap:
        name: airflow-log-config
    - name: airflow-webserver-config
      configMap:
        name: airflow-webserver-config
    - name: airflow-custom-utils
      configMap:
        name: airflow-custom-utils
    - name: airflow-email-template-helpers
      configMap:
        name: airflow-email-template-helpers  
    - name: airflow-pip-dependencies
      configMap:
        name: airflow-pip-dependencies
  ## Web container' resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  ## @param web.resources.limits The resources limits for the Web container
  ## @param web.resources.requests The requested resources for the Web container
  ##
  resources:
    ## Example:
    ## limits:
    ##    cpu: 200m
    ##    memory: 1Gi
    limits: {}
    ## Examples:
    ## requests:
    ##    memory: 256Mi
    ##    cpu: 250m
    requests: {}
  ## Configure extra options for Web containers' liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
  ## @param web.livenessProbe.enabled Enable livenessProbe
  ## @param web.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  ## @param web.livenessProbe.periodSeconds Period seconds for livenessProbe
  ## @param web.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  ## @param web.livenessProbe.failureThreshold Failure threshold for livenessProbe
  ## @param web.livenessProbe.successThreshold Success threshold for livenessProbe
  ##
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  ## @param web.readinessProbe.enabled Enable readinessProbe
  ## @param web.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  ## @param web.readinessProbe.periodSeconds Period seconds for readinessProbe
  ## @param web.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  ## @param web.readinessProbe.failureThreshold Failure threshold for readinessProbe
  ## @param web.readinessProbe.successThreshold Success threshold for readinessProbe
  ##
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1
  ## @param web.customLivenessProbe Custom liveness probe for the Web component
  customLivenessProbe: {}
  ## @param web.customReadinessProbe Custom rediness probe for the Web component
  ##
  customReadinessProbe: {}
  ## Enable PodDisruptionBudget for Web pods
  ## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  ## @param web.podDisruptionBudget.enabled Enable PodDisruptionBudget for web pods
  ## @param web.podDisruptionBudget.minAvailable Minimum available instances; ignored if there is no PodDisruptionBudget
  ##
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    # maxUnavailable: 1

## Airflow service parameters. For minikube, set this to NodePort, elsewhere use LoadBalancer
## @param service.type Airflow service type
## @param service.port Airflow service HTTP port
## @param service.nodePort Airflow service NodePort
## @param service.annotations Additional custom annotations for Airflow service
##
service:
  type: ClusterIP
  port: 8080
  ## NodePort
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  nodePort:
  ## Use loadBalancerIP to request a specific static IP,
  # loadBalancerIP:
  annotations:

## @section Airflow scheduler parameters

scheduler:
  ## Bitnami Airflow Scheduler image version
  ## ref: https://hub.docker.com/r/bitnami/airflow-scheduler/tags/
  ## @param scheduler.image.registry Airflow Scheduler image registry
  ## @param scheduler.image.repository Airflow Scheduler image repository
  ## @param scheduler.image.tag Airflow Scheduler image tag (immutable tags are recommended)
  ## @param scheduler.image.pullPolicy Airflow Scheduler image pull policy
  ## @param scheduler.image.pullSecrets Airflow Scheduler image pull secrets
  ## @param scheduler.image.debug Enable image debug mode
  ##
  image:
    registry: docker.io
    repository: bitnami/airflow-scheduler
    tag: 2.3.2-debian-11-r0
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    debug: true
  ## @param scheduler.replicaCount Number of scheduler replicas
  ##
  replicaCount: 1
  ## @param scheduler.extraVolumeMounts Add extra volume mounts
  ##
  # Refer to pipeline to understand how following configmaps are created.
  extraVolumeMounts:
    - name: airflow-log-config
      mountPath: /opt/bitnami/airflow/config
    - name: airflow-webserver-config
      mountPath: /opt/bitnami/airflow/webserver_config.py
      subPath: webserver_config.py
    - name: airflow-custom-utils
      mountPath: /opt/bitnami/airflow/extras/custom_utils
    - name: airflow-email-template-helpers
      mountPath: /opt/bitnami/airflow/extras/email_template_helpers  
    - name: airflow-pip-dependencies
      mountPath: /bitnami/python
  ## @param scheduler.extraVolumes Add extra volumes
  ##
  extraVolumes:
    - name: airflow-log-config
      configMap:
        name: airflow-log-config
    - name: airflow-webserver-config
      configMap:
        name: airflow-webserver-config
    - name: airflow-custom-utils
      configMap:
        name: airflow-custom-utils
    - name: airflow-email-template-helpers
      configMap:
        name: airflow-email-template-helpers    
    - name: airflow-pip-dependencies
      configMap:
        name: airflow-pip-dependencies
  ## Scheduler containers' resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube.
  ## @param scheduler.resources.limits The resources limits for the Scheduler container
  ## @param scheduler.resources.requests The requested resources for the Scheduler container
  ##
  resources:
    ## Example:
    ## limits:
    ##    cpu: 200m
    ##    memory: 1Gi
    limits: {}
    ## Example:
    ## requests:
    ##    memory: 256Mi
    ##    cpu: 250m
    requests: {}
  ## @param scheduler.customLivenessProbe Custom Liveness probe
  ##
  customLivenessProbe:
    exec:
      command:
      - /bin/bash
      - -c
      - airflow jobs check
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1 

  customReadinessProbe: {}
  ## Enable PodDisruptionBudget for scheduler pods
  ## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  ## @param scheduler.podDisruptionBudget.enabled Enable PodDisruptionBudget for scheduler pods
  ## @param scheduler.podDisruptionBudget.minAvailable Minimum available instances; ignored if there is no PodDisruptionBudget
  ##
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    # maxUnavailable: 1

## @section Airflow worker parameters

worker:
  ## Bitnami Airflow Worker image version
  ## ref: https://hub.docker.com/r/bitnami/airflow-worker/tags/
  ## @param worker.image.registry Airflow Worker image registry
  ## @param worker.image.repository Airflow Worker image repository
  ## @param worker.image.tag Airflow Worker image tag (immutable tags are recommended)
  ## @param worker.image.pullPolicy Airflow Worker image pull policy
  ## @param worker.image.pullSecrets Airflow Worker image pull secrets
  ## @param worker.image.debug Enable image debug mode
  ##
  # persistence:
  #   enabled: true
  #   fixPermissions: true

  image:
    registry: docker.io
    repository: bitnami/airflow-worker
    tag: 2.3.2-debian-11-r0
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
    debug: true
  ## @param worker.port Port where the worker will be exposed
  ##
  port: 8793
  ## @param worker.replicaCount Number of worker replicas
  ##
  replicaCount: 1
  ## @param worker.extraVolumeMounts Add extra volume mounts
  ##
  # Refer to pipeline to understand how following configmaps are created.
  extraVolumeMounts:
    - name: airflow-log-config
      mountPath: /opt/bitnami/airflow/config
    - name: airflow-webserver-config
      mountPath: /opt/bitnami/airflow/webserver_config.py
      subPath: webserver_config.py
    - name: airflow-custom-utils
      mountPath: /opt/bitnami/airflow/extras/custom_utils
    - name: airflow-email-template-helpers
      mountPath: /opt/bitnami/airflow/extras/email_template_helpers  
    - name: airflow-pip-dependencies
      mountPath: /bitnami/python
  ## @param worker.extraVolumes Add extra volumes
  ##
  extraVolumes:
    - name: airflow-log-config
      configMap:
        name: airflow-log-config
    - name: airflow-webserver-config
      configMap:
        name: airflow-webserver-config
    - name: airflow-custom-utils
      configMap:
        name: airflow-custom-utils
    - name: airflow-email-template-helpers
      configMap:
        name: airflow-email-template-helpers    
    - name: airflow-pip-dependencies
      configMap:
        name: airflow-pip-dependencies
  ## Worker containers' resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  ## @param worker.resources.limits The resources limits for the Worker container
  ## @param worker.resources.requests The requested resources for the Worker container
  ##
  resources:
    ## Example:
    ## limits:
    ##    cpu: 200m
    ##    memory: 1Gi
    limits: {}
    ## Example:
    ## requests:
    ##    memory: 256Mi
    ##    cpu: 250m
    requests: {}
  ## Configure extra options for liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
  ## @param worker.livenessProbe.enabled Enable livenessProbe
  ## @param worker.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  ## @param worker.livenessProbe.periodSeconds Period seconds for livenessProbe
  ## @param worker.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  ## @param worker.livenessProbe.failureThreshold Failure threshold for livenessProbe
  ## @param worker.livenessProbe.successThreshold Success threshold for livenessProbe
  ##
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  ## @param worker.readinessProbe.enabled Enable readinessProbe
  ## @param worker.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  ## @param worker.readinessProbe.periodSeconds Period seconds for readinessProbe
  ## @param worker.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  ## @param worker.readinessProbe.failureThreshold Failure threshold for readinessProbe
  ## @param worker.readinessProbe.successThreshold Success threshold for readinessProbe
  ##
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  ## @param worker.customLivenessProbe Custom Liveness probe
  ##
  customLivenessProbe: {}
  ## @param worker.customReadinessProbe Custom Liveness probe
  ##
  customReadinessProbe: {}
  ## Enable PodDisruptionBudget for worker pods
  ## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  ## @param worker.podDisruptionBudget.enabled Enable PodDisruptionBudget for worker pods
  ## @param worker.podDisruptionBudget.minAvailable Minimum available instances; ignored if there is no PodDisruptionBudget
  ##
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    # maxUnavailable: 1
  ## Enable HorizontalPodAutoscaler for worker pods
  ## ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  ## @param worker.autoscaling.enabled Whether enable horizontal pod autoscale
  ## @param worker.autoscaling.replicas.min Configure a minimum amount of pods
  ## @param worker.autoscaling.replicas.max Configure a maximum amount of pods
  ## @param worker.autoscaling.targets.cpu Define the CPU target to trigger the scaling actions (utilization percentage)
  ## @param worker.autoscaling.targets.memory Define the memory target to trigger the scaling actions (utilization percentage)
  ##
  autoscaling:
    enabled: false
    replicas:
      min: 1
      max: 3
    targets:
      cpu: 80
      memory: 80
  ## @param worker.updateStrategy StatefulSet controller supports automated updates. There are two valid update strategies: RollingUpdate and OnDelete
  ## ref: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets
  ##
  updateStrategy: RollingUpdate
  ## @param worker.rollingUpdatePartition Partition update strategy
  ## https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions
  ##
  rollingUpdatePartition:

# Disabling redis. Not neeeded for Kubernetes Executor
redis:
  enabled: false

## @section Airflow git sync parameters

## Configure Git to pull dags and plugins
##
git:
  ## Bitnami Git image version
  ## ref: https://hub.docker.com/r/bitnami/git/tags/
  ## @param git.image.registry Git image registry
  ## @param git.image.repository Git image repository
  ## @param git.image.tag Git image tag (immutable tags are recommended)
  ## @param git.image.pullPolicy Git image pull policy
  ## @param git.image.pullSecrets Git image pull secrets
  ##
  image:
    registry: docker.io
    repository: bitnami/git
    tag: 2.32.0-debian-10-r24
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
  ## Get DAG files from git repositories
  ## @param git.dags.enabled Enable in order to download DAG files from git repositories.
  ## @param git.dags.repositories Array of repositories from which to download DAG files
  ##
  dags:
    enabled: true
    ## Name for repositories can be anything unique and must follow same naming conventions as kubernetes.
    ## Kubernetes resources can have names up to 253 characters long. The characters allowed in names are:
    ## digits (0-9), lower case letters (a-z), -, and .
    ## Example:
    ##   - repository: https://github.com/myuser/myrepo
    ##     branch: main
    ##     name: my-dags
    ##     path: /
    ##
    # PAT_AZURE_REPOS is downloaded from devops library varible group dap-devops-pat. 
    repositories:
      - repository: https://#{PAT_AZURE_REPOS}#@dev.azure.com/eri/DAP/_git/airflow_dags
        ## Branch from repository to checkout
        ##
        branch: #{AIRFLOW_DAGS_GIT_REPO_BRANCH}#
        ## An unique identifier for repository, must be unique for each repository
        ##
        name: airflow-dags
        ## Path to a folder in the repository containing the dags
        ##
        path: src
  ## Get Plugins files from git repositories.
  ## @param git.plugins.enabled Enable in order to download Plugins files from git repositories.
  ## @param git.plugins.repositories Array of repositories from which to download DAG files
  ##
  plugins:
    enabled: false
    repositories:
      - repository:
        ## Branch from repository to checkout
        ##
        branch:
        ## An unique identifier for repository, must be unique for each repository
        ##
        name:
        ## Path to a folder in the repository containing the dags
        ##
        path:
  ## Properties for the Clone init container
  ## @param git.clone.command Override cmd
  ## @param git.clone.args Override args
  ## @param git.clone.extraVolumeMounts Add extra volume mounts
  ## @param git.clone.extraEnvVars Add extra environment variables
  ## @param git.clone.extraEnvVarsCM ConfigMap with extra environment variables
  ## @param git.clone.extraEnvVarsSecret Secret with extra environment variables
  ## @param git.clone.resources Clone init container resource requests and limits
  ##
  clone:
    command:
    args:
    extraVolumeMounts:
    extraEnvVars:
    extraEnvVarsCM:
    extraEnvVarsSecret:
    ## Clone init container resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources: {}
  ## Properties for the Sync sidecar container
  ## @param git.sync.interval Interval in seconds to pull the git repository containing the plugins and/or DAG files
  ## @param git.sync.command Override cmd
  ## @param git.sync.args Override args
  ## @param git.sync.extraVolumeMounts Add extra volume mounts
  ## @param git.sync.extraEnvVars Add extra environment variables
  ## @param git.sync.extraEnvVarsCM ConfigMap with extra environment variables
  ## @param git.sync.extraEnvVarsSecret Secret with extra environment variables
  ## @param git.sync.resources Sync sidecar container resource requests and limits
  ##
  sync:
    interval: 60
    command:
    args:
    extraVolumeMounts:
    extraEnvVars:
    extraEnvVarsCM:
    extraEnvVarsSecret:
    ## Sync sidecar container resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources: {}

## @section Airflow database parameters

# Disabling postgresql helm chart to enable external database
postgresql:
  enabled: false

## External PostgreSQL configuration
## All of these values are only used when postgresql.enabled is set to false
## @param externalDatabase.host Database host
## @param externalDatabase.user non-root Username for Airflow Database
## @param externalDatabase.password Database password
## @param externalDatabase.existingSecret Name of an existing secret resource containing the DB password
## @param externalDatabase.existingSecretPasswordKey Name of an existing secret key containing the DB password
## @param externalDatabase.database Database name
## @param externalDatabase.port Database port number
##
# These settings are for Azure postgresql server. airflow_v3 database should exist in the postgres server.
externalDatabase:
  host: #{POSTGRES-HOST}#
  user: #{POSTGRES-USER}#
  password: #{POSTGRES-PASSWORD}#
  #existingSecret:
  #existingSecretPasswordKey:
  database: airflow_v3
  port: 5432
```

Airflow version: 2.3.2 (have tried upgrading to 2.3.4 as well no luck!)
helm chart version 13.1.3
