### DISCUSSION TITLE
Airflow enable JWT auth

### DISCUSSION THREAD

**Discussion by eclipsetalk** [apache/airflow#29368] [Q&A]
Hello,
I need to enable JWT authentication for Airflow REST API. I've added in the value.yaml for bitmani the fellowing:
```
        - name: AIRFLOW__API__AUTH_BACKEND
          value: "airflow.contrib.auth.backends.jwt_auth"
          config:
            jwt_auth_enabled: "True"
            jwt_header_name: "Authorization"
            jwt_header_type: "Bearer"
            jwt_secret: <your-secret-key>
            jwt_algorithm: "HS256"
 ```
 However it doesn't work, the web Airflow container fails. Any ideas on how to setup JWT auth in Airflow 2.3.4?
Thanks in advance for any pointers
