### DISCUSSION TITLE
Signal worker sidecar to finish

### DISCUSSION THREAD

**Discussion by Subhashini2610** [apache/airflow#29610] [Q&A]
I have fluentbit running as a worker sidecar container to collect DAG logs. However, I am unable to signal the sidecar to stop running once the main conatiner/task is finished. I tried using `ps aux` but the default `airflow` user does not have the necessary permissions. I cannot use `sudo` as I do not know the password to airflow user. Please guide me here.

**Comment by hussein-awala** [comment]
Can you provide some extra information, like the executor you are using (K8S or celery on k8s), how do you deploy the server (the official helm chart or another way), how do you add the sidecar container and what do you get as error?

If you just want to run access the root user, you have two options:
- building the docker image and changing the user to root
  ```dockerfile
  FROM airflow:2.5.1
  USER root
  ```
- adding a security context to your pod:
  ```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: <pod name>
    ....
  spec:
    securityContext:
      runAsUser: 0
    containers:
    - ...
  ```
