### DISCUSSION TITLE
How to load specific DAGs into kubernetes pod when running with k8s executor?

### DISCUSSION THREAD

**Discussion by harshith-bolar-rapido** [apache/airflow#30512] [Q&A] [answered]
My DAGs are stored in Google Cloud Storage (GCS) and when Airflow spins up a pod during task creation, I am copying all the DAGs from GCS to the pod using an init container like so.

```yaml
  initContainers:
    - name: init-dags
      image: {{ template "airflow_image" . }}
      command: ['sh', '-c', "gsutil cp -r gs://dags-bucket/dags/ /opt/airflow/dags/"]
      volumeMounts:
      - name: dags-folder
        mountPath: /opt/airflow/dags
```

Copying all the DAGs like this is highly inefficient and unnecessary. I am wondering if there is a way to only load the DAG associated with the specific pod instead of everything in the GCS bucket. Maybe a way we can reference the DAG name inside the pod-template-file?
