### DISCUSSION TITLE
KubernetesOperator jobs fail -- [probably NOT] because "pod_template_file.yaml does not exist"

### DISCUSSION THREAD

**Discussion by hanleybrand** [apache/airflow#30805] [Q&A] [answered]
Airflow 2.5.1; Helm chart 1.8.0

I had recently started working with KubernetesOperator to check it out, and initially my jobs were working as I expected, but recently they all fail and it looks like it's because the airflow pod_template is not being applied to the container when it's spun up. The main symptom was anything that relied on a k8s Secret failed -- and then I noticed this in the logs of failed jobs:

```
INFO - Running <TaskInstance: cd2_dr-get-schema-accounts.dap-get-schema-accounts scheduled__2023-03-03T05:00:00+00:00 [running]> on host cd2-dr-get-schema-accounts-dap-ec413a72aedc42d2b19f3edd1eaa18b2
{pod_generator.py:424} WARNING - Model file /opt/airflow/pod_templates/pod_template_file.yaml does not exist
```

Of course, I don't think I changed anything that would have changed this, but it's certainly possible that I did -- the big change I did recently (in the last few weeks) was realize that running airflow as uid/gid 1000/1000 was incorrect and I switched my image and airflow values.yaml to do the default of 50000/0 -- but I don't think this would have changed the pod_template_file from being included

The file exists on the scheduler pod at `/opt/airflow/pod_templates/pod_template_file.yaml` but not on the webserver or triggerer pods (I think this is correct though?)  Regardless, I'm not explicitly doing anything with the pod_template, I just have what I think are the default values in my helm chart:

```yaml
config:
    __stuff_deleted__: 'deleted irrelevant config attributes'
  celery_kubernetes_executor:
    kubernetes_queue: 'kubernetes'
  kubernetes_executor:
    namespace: '{{ .Release.Namespace }}'
    airflow_configmap: '{{ include "airflow_config" . }}'
    airflow_local_settings_configmap: '{{ include "airflow_config" . }}'
    pod_template_file: '{{ include "airflow_pod_template_file" . }}/pod_template_file.yaml'
    worker_container_repository: '{{ .Values.images.airflow.repository | default .Values.defaultAirflowRepository }}'
    worker_container_tag: '{{ .Values.images.airflow.tag | default .Values.defaultAirflowTag }}'
    multi_namespace_mode: '{{ ternary "True" "False" .Values.multiNamespaceMode }}'
```

So if the pod_template_file exists at `/opt/airflow/pod_templates/pod_template_file.yaml` on the scheduler (I'm not sure what causes it to not exist on the other pods, but I've been assuming this is part of the helm chart's workings), I don't know what piece is not able to find the file.

I checked the git history and the only change I've made since the K8sOperator jobs ran successfully was changing  config.kubernetes to config.kubernetes_executor somewhere in there (to stop getting the error messages about how it had been changed), otherwise I think the values.yaml is pretty vanilla (no customization for the template, etc.)

Does this issue ring a bell with anyone?
