### DISCUSSION TITLE
Airflow 2.5.3, unable to specify ssl key and cert for webserver in Docker based installation

### DISCUSSION THREAD

**Discussion by jayramr** [apache/airflow#31089] [General]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

airflow webserver --ssl-cert domain.pem --ssl-key domain.key

### What you think should happen instead

it should server the website with ssl

### How to reproduce

Without ssl works 
$airflow webserver 

With ssl , the webserver not working and no logs even with debug
$airflow webserver --ssl-cert domain.pem --ssl-key domain.key 

### Operating System

ubuntu 20.04

### Versions of Apache Airflow Providers

2.5.3

### Deployment

Virtualenv installation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by boring-cyborg** [comment]
Thanks for opening your first issue here! Be sure to follow the issue template! If you are willing to raise PR to address this issue please do so, no need to wait for approval.

**Comment by jayramr** [comment]
Hi, 

With pypi based installation, below works with ssl.

```
airflow webserver --ssl-cert domain.cer --ssl-key domain.key
```

When I specify in airflow.cfg, the webservice is not starting. 

But on docker setup, i defined in airflow.cfg and also as a variable as follows 

```
AIRFLOW__WEBSERVER__WEB_SERVER_SSL_CERT: /opt/airflow/certs/domain.cer
AIRFLOW__WEBSERVER__WEB_SERVER_SSL_KEY: /opt/airflow/certs/domain.key
```

The webserver service for the container is showing unhealthy. Kindly let me know how can i integrate ssl in docker based installation.

Thanks
Jay

**Reply by potiuk** [reply]
I guess the same. Just use those command switches when running webserver.

**Reply by potiuk** [reply]
But you need to check if you have all the required dependencis added for that in the image - there is no reason of why webserver run locally with the switches work, while in the docker it does not - than some dependencies that might be needed.


Converted it into a discussion as this is deployment question not Airlfow issue (and try not to open issues when things are about configuring and running issues in the future).

**Comment by jayramr** [comment]
Thanks @potiuk for your suggestions. Sure next time i will open as a discussion. 

I already specified the same switch in the docker-compose file as follows

```
  airflow-webserver:
    <<: *airflow-common
    command: webserver --ssl-cert domain.cer --ssl-key domain.key
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
```

The docker compose status shows unhealtly state and even i started with --debug option, still no valid logs found.

I believe the image ```apache/airflow:2.5.3``` comes with all the necessary dependencies.

Please let me know

Thanks
Jay
