### DISCUSSION TITLE
[pytest] not working in PyCharm `_jb_pytest_runner.py: error: unrecognized arguments: --asyncio-mode=strict` (and add dev/requirements.txt)

### DISCUSSION THREAD

**Discussion by seunggabi** [apache/airflow#31361] [General]
### Apache Airflow version

main (development)

### Error

```
ERROR: usage: _jb_pytest_runner.py [options] [file_or_dir] [file_or_dir] [...]
_jb_pytest_runner.py: error: unrecognized arguments: --asyncio-mode=strict
```

I fronted this error message.
So, I excluded this code.
It's works now.

Can I exclude `--asyncio-mode=strict` opt?

<img width="983" alt="스크린샷 2023-05-17 오후 10 08 46" src="https://github.com/apache/airflow/assets/8468371/adedabe9-13e8-4bb7-ae0b-cd1c0f103259">

### as-is 
```toml
# pyproject.toml

[tool.pytest.ini_options]
# * Disable `flaky` plugin for pytest. This plugin conflicts with `rerunfailures` because provide same marker.
# * Disable `nose` builtin plugin for pytest. This feature deprecated in 7.2 and will be removed in pytest>=8
# * And we focus on use native pytest capabilities rather than adopt another frameworks.
addopts = "-rasl --verbosity=2 -p no:flaky -p no:nose --asyncio-mode=strict"
```

### to-be
```toml
# pyproject.toml

[tool.pytest.ini_options]
# * Disable `flaky` plugin for pytest. This plugin conflicts with `rerunfailures` because provide same marker.
# * Disable `nose` builtin plugin for pytest. This feature deprecated in 7.2 and will be removed in pytest>=8
# * And we focus on use native pytest capabilities rather than adopt another frameworks.
# addopts = "-rasl --verbosity=2 -p no:flaky -p no:nose --asyncio-mode=strict"
```

### Operating System

MacOSX

### Deployment

Other

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
