### DISCUSSION TITLE
DAG-level permissions are periodically being deleted

### DISCUSSION THREAD

**Discussion by alexakra** [apache/airflow#32187] [General]
### Apache Airflow version

2.6.2

### What happened

After upgrading to version 2.6.2 from 2.4.3, all the DAG-level permissions (`ab_permission_view_role`) are periodically being deleted.

### What you think should happen instead

The DAG-level permissions should not be deleted once defined as it was in pre-3.6 versions.

### How to reproduce

Define a role with DAG-level permission. The permission will be removed from the role after short period of time.

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Helm Chart 1.9.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
I think this is something on your side - some script that is run periodically. The infoirmation you provided is not nearly detailed enough to act on it. But you if you look at your logs and deployment and try to find the places/logs where you will see some deletions happening, maybe someone will be able to help to solve your issue.

Thanks in advance for more details, for now I converted it into discussion until more details are provided - enough for someone to be able to help you.

**Comment by alexakra** [comment]
When I disable `airflow-dag-processor`, the permissions are not being deleted. So this is somewhere in `airflow-dag-processor` process.

**Reply by alexakra** [reply]
@potiuk This happens every time `airflow-dag-processor` finishes processing all dag files.

**Reply by potiuk** [reply]
Any logs from that showing it happening ?

**Reply by alexakra** [reply]
How to configure `airflow-dag-processor` to log DML operations?
Setting AIRFLOW__LOGGING__LOGGING_LEVEL to 'DEBUG' is not enough.

**Reply by alexakra** [reply]
I see the following lines in the log:
```
{serialized_dag.py:248} DEBUG - Deleting Serialized DAGs (for which DAG files are deleted) from serialized_dag table 
{dag.py:3381} DEBUG - Deactivating DAGs (for which DAG files are deleted) from dag table 
{dagcode.py:137} DEBUG - Deleting code from dag_code table
```

**Reply by potiuk** [reply]
What is configuration of the DAGs and dag file process you have? 
How many of them you have etc? It looks like for some reason your DAGs get periodically deleted as if the 


Also - it might be that you have a problem with synchronization of your DAG files. Maybe the mechanism of synchronizing your DAGs will have "gaps". If your synchronization process will have moments in time that your DAG folder is emptied or just single dag files of yours (for example it deletes and recreates the file using some remote synchronization tools, then you will see exactly the problem you describe. DAG file processor will see missing files, it will assume they were deleted and it will remove them from "active" DAGS (also removing their permission). 

What kind of synchronization mechanism do you use and is it possible that there are moments in time that your DAG files are gone from the DAG folder?

**Reply by alexakra** [reply]
I will check. But this didn't happened at least until Airflow 2.4.3 and the synchronization mechanism was not changed after Airflow upgrade.

**Reply by potiuk** [reply]
It could be that it was masked by some other changes (which does not make it less likely as hypothesis what could be wrong)

**Reply by potiuk** [reply]
And yes. Sometimes things work "accidentally" and the fact that they stop working after upgrade does not make them "less wrong".
I am not talking this is the case now, just trying to help you with diagnosis and guide you where to look for. In order to diagnose and fix the problem we need to find the root cause simply.

**Reply by potiuk** [reply]
And yes I looked at the code - this would be exactly what would happen if you get listing of the directory and it misses some of the files that were there previously - indicating that it **might** be the problem that has been hidden before simply (but was there).

There is also an option that you have accidentally running more than one dag-file-processor (wrongly configured) - for example from older installation or staging systems etc (those things happen and happened in the past for our users). So that's something also worth checking on your side.

**Reply by alexakra** [reply]
I see. This input is helpful. Thanks.

**Reply by potiuk** [reply]
Though - on the other hand this log file will not indicate "deletion" is happening, so that might be red-herring

**Reply by kaifeur** [reply]
@alexakra please let me know if you find the issue and tell how you resolved it. It seems that we bumped into the same problem (or related to it) but I can’t really investigate on it because of some internal restrictions.

**Reply by alexakra** [reply]
I didn't find the root cause yet, but I have the following observations:

- According to the log, there is always the same number of file, i.e. the file are not being deleted:
```
{manager.py:758} INFO - Searching for files in /opt/airflow/dags
{manager.py:761} INFO - There are 363 files in /opt/airflow/dags
```

- The way the permissions are being deleted is not aligned with the Airflow way of handling DAGs. While the files are not being deleted, they are defenetely being overwritten periodically. I don't know if this the root cause, but if you would like to remove permission, you should do soft delete rather then hard delete by adding `is_active` column into `ab_permission_view_role` table, the same way as having `dag.is_active`. Having hard delete makes DAG-level permissions useless, because even if assuming that file was not available in the file system for short period of time, it should not permanently delete the predefined permission, but rather make it active.

**Reply by potiuk** [reply]
I do not know if this is because of deletion - that was hypothesis while trying to investigate why.

Any news about the setup of your dag-file-processor(s)?

**Reply by potiuk** [reply]
Also - are you using 'sync-perm' ? If so, how?

**Reply by alexakra** [reply]
We are not using `sync-perm`.
We generate DAGs dynamically.

Setup of your `dag-file-processor`:
```
# Airflow Dag Processor Config
dagProcessor:
  enabled: true
  # Number of airflow dag processors in the deployment
  replicas: 1
  # Max number of old replicasets to retain
  revisionHistoryLimit: ~

  # Command to use when running Airflow dag processors (templated).
  command: ~
  # Args to use when running Airflow dag processor (templated).
  args: ["bash", "-c", "exec airflow dag-processor"]

  # Update Strategy for dag processors
  strategy:
    type: Recreate
    rollingUpdate: null
#      maxSurge: "100%"
#      maxUnavailable: "50%"

  # If the dag processor stops heartbeating for 5 minutes (5*60s) kill the
  # dag processor and let Kubernetes restart it
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 20
    failureThreshold: 5
    periodSeconds: 60
    command: ~

  # Create ServiceAccount
  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
    # The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the release name
    name: ~

    # Annotations to add to dag processor kubernetes service account.
    annotations: {}

  # When not set, the values defined in the global securityContext will be used
  securityContext: {}
  #  runAsUser: 50000
  #  fsGroup: 0
  #  runAsGroup: 0

  # Detailed default security context for dagProcessor for container and pod level
  securityContexts:
    pod: {}
    container: {}

  resources:
    limits:
     cpu: 2000m
     memory: 4Gi
    requests:
     cpu: 200m
     memory: 2Gi

  # Grace period for dag processor to finish after SIGTERM is sent from kubernetes
  terminationGracePeriodSeconds: 60

  # This setting tells kubernetes that its ok to evict
  # when it wants to scale a node down.
  safeToEvict: true

  # Launch additional containers into dag processor.
  extraContainers: []
  # Add additional init containers into dag processors.
  extraInitContainers: []

  # Mount additional volumes into dag processor. It can be templated like in the following example:
  #   extraVolumes:
  #     - name: my-templated-extra-volume
  #       secret:
  #          secretName: '{{ include "my_secret_template" . }}'
  #          defaultMode: 0640
  #          optional: true
  #
  #   extraVolumeMounts:
  #     - name: my-templated-extra-volume
  #       mountPath: "{{ .Values.my_custom_path }}"
  #       readOnly: true
  extraVolumes: []
  extraVolumeMounts: []

  # Select certain nodes for airflow dag processor pods.
  nodeSelector: {}
  affinity: {}
  # default dag processor affinity is:
  #  podAntiAffinity:
  #    preferredDuringSchedulingIgnoredDuringExecution:
  #    - podAffinityTerm:
  #        labelSelector:
  #          matchLabels:
  #            component: dag-processor
  #        topologyKey: kubernetes.io/hostname
  #      weight: 100
  tolerations: []
  topologySpreadConstraints: []

  priorityClassName: ~

  # annotations for the dag processor deployment
  annotations: {}

  podAnnotations: {}

  logGroomerSidecar:
    # Whether to deploy the Airflow dag processor log groomer sidecar.
    enabled: true
    # Command to use when running the Airflow dag processor log groomer sidecar (templated).
    command: ~
    # Args to use when running the Airflow dag processor log groomer sidecar (templated).
    args: ["bash", "/clean-logs"]
    # Number of days to retain logs
    retentionDays: 15
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 128Mi

  waitForMigrations:
    # Whether to create init container to wait for db migrations
    enabled: true
    env: []

  env: []
```
