### DISCUSSION TITLE
Cannot connect external postgresql database to airflow on kubernetes

### DISCUSSION THREAD

**Discussion by Braondn** [apache/airflow#32273] [Q&A]
I am new to airflow, and I deployed airflow onto Kubernetes using the official apache/airflow helm chart. I am editing the values.yaml file to connect my external backend to airflow, but there is a timeout error with the run-airflow-migrations job after upgrading the Helm chart. This is how I am editing my values.yaml file:
```
data:
      metadataConnection:
          user: postgres
          pass: postgres
          protocol: postgresql
          host: localhost
          port: 5432
          db: NewDB
          sslmode: disable
```

This is my error:
```
client.go:734: [debug] Add/Modify event for airflow-run-airflow-migrations: MODIFIED
client.go:773: [debug] airflow-run-airflow-migrations: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:734: [debug] Add/Modify event for airflow-run-airflow-migrations: MODIFIED
client.go:773: [debug] airflow-run-airflow-migrations: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
upgrade.go:442: [debug] warning: Upgrade "airflow" failed: post-upgrade hooks failed: 1 error occurred:
	* timed out waiting for the condition


Error: UPGRADE FAILED: post-upgrade hooks failed: 1 error occurred:
	* timed out waiting for the condition
```

I also disabled the postgresql paramater to prevent the default psotgresql database container from starting. How can I fix this issue and connect my external database to Airflow?
