### DISCUSSION TITLE
Postgre subchart is not deployed 1.10.0

### DISCUSSION THREAD

**Discussion by TheGthr** [apache/airflow#32423] [Q&A]
Hello,
Can someone please help me with the latest version of Airflow Helm chart 1.10.0? I want to deploy it and use the "embedded" postgresql instance, so I used these values:

```yaml
# Configuration for postgresql subchart
# Not recommended for production
postgresql:
  enabled: true
  image:
    tag: "11"
  auth:
    enablePostgresUser: true
    postgresPassword: postgres
    username: ""
    password: ""
```
but, there is not a single Pod of postgresql deployed when I install the release. Is someone facing the same issue ?
