### DISCUSSION TITLE
Task set queue can not run in LocalKubernetesExecutor

### DISCUSSION THREAD

**Discussion by chuxiangfeng** [apache/airflow#32595] [Q&A]
As `https://airflow.apache.org/docs/apache-airflow/stable/_modules/airflow/example_dags/example_local_kubernetes_executor.html#log`
the follow is my task, in cfg, my conf is executor = LocalKubernetesExecutor, i set queue to task, just want task run this python function in KubernetesExecutor,
```
@task(
        queue="kubernetes",
        task_id="create_partitions"
    )
    def create_partitions():
      ************
```

but in ui page:
[2023-07-14, 15:02:27 CST] {pod_generator.py:529} WARNING - Model file /opt/airflow/pod_templates/pod_template_file.yaml does not exist
finally the task still run as a local task not a kubernetes task.

**Comment by chuxiangfeng** [comment]
anyone can help ?

**Reply by potiuk** [reply]
You need to have pod_template_file created. https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html#pod-template-file - look at the docs, that usually helps.

**Reply by chuxiangfeng** [reply]
this is my air.cfg:
```
[kubernetes]
airflow_configmap = airflow-airflow-config
airflow_local_settings_configmap = airflow-airflow-config
multi_namespace_mode = False
namespace = airflow-schedule
pod_template_file = /opt/airflow/pod_templates/pod_template_file.yaml
worker_container_repository = **********************
worker_container_tag = v2.6.3-python3.9
```
with pod named airflow-scheduler-0 in k8s, file names pod_template_file.yaml exists in /opt/airflow/pod_templates path, but in pod trigger the file not exists, i don`t konw the pod_template_file should exists in all pods or just in specific pod be satisfied ?, i install airflow with helm-chart 1.7, this is all content in values.yaml, Please take a look at it. Thank you:
```
webserverSecretKey: **************************
executor: LocalKubernetesExecutor
images:
  pod_template:
    tag: apache/airflow:2.6.3-python3.9
  gitSync:
    repository: **************************
    tag: git-sync-v3.6.3
    pullPolicy: IfNotPresent
  airflow:
    repository: **************************
    tag: v2.6.3-python3.9
    pullPolicy: IfNotPresent
logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: true
    # Volume size for logs
    size: 100Gi
    # If using a custom storageClass, pass name here
    storageClassName: alibabacloud-nas-cnfs
    ## the name of an existing PVC to use
    existingClaim: airflow-logs-cnfs
extraSecrets:
  airflow-ssh-secret:
    data: |
      gitSshKey: '**************************'
dags:
  gitSync:
    enabled: true
    repo: **************************
    branch: master
    subPath: ""
    sshKeySecret: airflow-ssh-secret
  persistence:
    enabled: false
    existingClaim: airflow-dags-cnfs
    storageClassName: alibabacloud-nas-cnfs
data:
  metadataSecretName: airflow-database
postgresql:
  enabled: false
pgbouncer:
  serviceAccount:
    name: default
    create: False
  enabled: true
  # The maximum number of connections to PgBouncer
  maxClientConn: 100
  # The maximum number of server connections to the metadata database from PgBouncer
  metadataPoolSize: 10
  # The maximum number of server connections to the result backend database from PgBouncer
  resultBackendPoolSize: 5
#env:
# - name: "PYTHONPATH"
#   value: "/opt/airflow/config/"
config:
  operators:
    allow_illegal_arguments: True
  scheduler:
    catchup_by_default: False
  #    job_heartbeat_sec: 10
  core:
    default_task_retries: 3
    max_active_runs_per_dag: 1
  logging:
    logging_level: INFO
#    logging_config_class: config.log_config.LOGGING_CONFIG
#    base_log_folder: ""
# `airflow_local_settings` file as a string (can be templated).
airflowLocalSettings: |-
  cninfoapi_server = '**************************'
  oss_key = '**************************'
  oss_pd = '**************************'
statsd:
  serviceAccount:
    name: default
    create: False
scheduler:
  #  env:
  #    - name: AIRFLOW__CORE__HOSTNAME_CALLABLE
  #      value: 'airflow.utils.net.get_hostname'

  resources:
    requests:
      cpu: 1
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 120
    failureThreshold: 5
    periodSeconds: 60
    command:
      - sh
      - -c
      - |
        CONNECTION_CHECK_MAX_COUNT=0 AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR exec /entrypoint \
        airflow jobs check --job-type SchedulerJob --hostname $(hostname -f)
  serviceAccount:
    name: default
    create: False
webserver:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
  defaultUser:
    password: **************************
  serviceAccount:
    name: default
    create: False
workers:
  serviceAccount:
    name: default
    create: False
triggerer:
  livenessProbe:
    timeoutSeconds: 120
    command:
      - sh
      - -c
      - |
        CONNECTION_CHECK_MAX_COUNT=0 AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR exec /entrypoint \
        airflow jobs check --job-type TriggererJob
  serviceAccount:
    name: default
    create: False
dagProcessor:
  serviceAccount:
    name: default
    create: False
flower:
  serviceAccount:
    name: default
    create: False
redis:
  serviceAccount:
    name: default
    create: False
cleanup:
  serviceAccount:
    name: default
    create: False
createUserJob:
  serviceAccount:
    name: default
    create: False
migrateDatabaseJob:
  serviceAccount:
    name: default
    create: False
```
