### DISCUSSION TITLE
Problem with DolphinDBOperator pre-commit check

### DISCUSSION THREAD

**Discussion by peeyee** [apache/airflow#33024] [Q&A] [answered]
I'm trying to develop an provider for dolphindb database. When setting up pre-commit checks, comes with the Problem:

1. **pre-commit**

`Found 1 errors in providers
Error: The `airflow.providers.dolphindb.hooks.dolphindb` object in hooks list in airflow/providers/dolphindb/provider.yaml does not exist or is not a module: No module named 'pydolphindb'`

2. **provider.yaml** :

```yaml
---
package-name: apache-airflow-providers-dolphindb
name: DolphinDB
description: |
    `DolphinDB <https://www.dolphindb.com/>`__

dependencies:
  - apache-airflow-providers-common-sql>=1.3.1
  - pydolphindb>=1.0.0

suspended: false
versions:
  - 1.0.0


integrations:
  - integration-name: DolphinDB
    external-doc-url: https://www.dolphindb.com/help/index.html
    how-to-guide:
      - /docs/apache-airflow-providers-dolphindb/operators.rst
    logo: /integration-logos/dolphindb/DolphinDB.png
    tags: [software]

operators:
  - integration-name: DolphinDB
    python-modules:
      - airflow.providers.dolphindb.operators.dolphindb

hooks:
  - integration-name: DolphinDB
    python-modules:
      - airflow.providers.dolphindb.hooks.dolphindb

connection-types:
  - hook-class-name: airflow.providers.dolphindb.hooks.dolphindb.DolphinDBHook
    connection-type: dolphindb

```
