### DISCUSSION TITLE
Logs from Celery Worker Does not Show

### DISCUSSION THREAD

**Discussion by hbc-acai** [apache/airflow#33409] [Q&A] [answered]
Hello community, 

I am setting up a small simple airflow celery worker cluster where all the celery workers are on different hosts than the major airflow services. I intend to serve the logs from the celery workers directly indicated by [this section](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/logging-tasks.html#serving-logs-from-workers-and-triggerer) 

But I am getting errors displaying the logs. 

- For a success task, I see this error  "Temporary failure in name resolution" returned by webserver. 

```
airflow-airflow-webserver-1  | [2023-08-15T14:41:23.047+0000] {file_task_handler.py:522} ERROR - Could not read served logs
airflow-airflow-webserver-1  | Traceback (most recent call last):
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
airflow-airflow-webserver-1  |     yield
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 94, in connect_tcp
airflow-airflow-webserver-1  |     sock = socket.create_connection(
airflow-airflow-webserver-1  |   File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
airflow-airflow-webserver-1  |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
airflow-airflow-webserver-1  |   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
airflow-airflow-webserver-1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
airflow-airflow-webserver-1  | socket.gaierror: [Errno -3] Temporary failure in name resolution
airflow-airflow-webserver-1  |
airflow-airflow-webserver-1  | During handling of the above exception, another exception occurred:
airflow-airflow-webserver-1  |
airflow-airflow-webserver-1  | Traceback (most recent call last):
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
airflow-airflow-webserver-1  |     yield
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
airflow-airflow-webserver-1  |     resp = self._pool.handle_request(req)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
airflow-airflow-webserver-1  |     raise exc
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
airflow-airflow-webserver-1  |     response = connection.handle_request(request)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
airflow-airflow-webserver-1  |     raise exc
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
airflow-airflow-webserver-1  |     stream = self._connect(request)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 111, in _connect
airflow-airflow-webserver-1  |     stream = self._network_backend.connect_tcp(**kwargs)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 93, in connect_tcp
airflow-airflow-webserver-1  |     with map_exceptions(exc_map):
airflow-airflow-webserver-1  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
airflow-airflow-webserver-1  |     self.gen.throw(typ, value, traceback)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
airflow-airflow-webserver-1  |     raise to_exc(exc)
airflow-airflow-webserver-1  | httpcore.ConnectError: [Errno -3] Temporary failure in name resolution
airflow-airflow-webserver-1  |
airflow-airflow-webserver-1  | The above exception was the direct cause of the following exception:
airflow-airflow-webserver-1  |
airflow-airflow-webserver-1  | Traceback (most recent call last):
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 505, in _read_from_logs_server
airflow-airflow-webserver-1  |     response = _fetch_logs_from_service(url, rel_path)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 90, in _fetch_logs_from_service
airflow-airflow-webserver-1  |     response = httpx.get(
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_api.py", line 189, in get
airflow-airflow-webserver-1  |     return request(
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_api.py", line 100, in request
airflow-airflow-webserver-1  |     return client.request(
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 821, in request
airflow-airflow-webserver-1  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 908, in send
airflow-airflow-webserver-1  |     response = self._send_handling_auth(
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 936, in _send_handling_auth
airflow-airflow-webserver-1  |     response = self._send_handling_redirects(
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
airflow-airflow-webserver-1  |     response = self._send_single_request(request)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 1009, in _send_single_request
airflow-airflow-webserver-1  |     response = transport.handle_request(request)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
airflow-airflow-webserver-1  |     with map_httpcore_exceptions():
airflow-airflow-webserver-1  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
airflow-airflow-webserver-1  |     self.gen.throw(typ, value, traceback)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
airflow-airflow-webserver-1  |     raise mapped_exc(message) from exc
airflow-airflow-webserver-1  | httpx.ConnectError: [Errno -3] Temporary failure in name resolution

```

- For the failed tasks, I see this error "httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol." Log is below.

```
airflow-airflow-webserver-1  | [2023-08-15T14:53:34.644+0000] {file_task_handler.py:522} ERROR - Could not read served logs
airflow-airflow-webserver-1  | Traceback (most recent call last):
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
airflow-airflow-webserver-1  |     yield
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
airflow-airflow-webserver-1  |     resp = self._pool.handle_request(req)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 208, in handle_request
airflow-airflow-webserver-1  |     raise UnsupportedProtocol(
airflow-airflow-webserver-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
airflow-airflow-webserver-1  |
airflow-airflow-webserver-1  | The above exception was the direct cause of the following exception:
airflow-airflow-webserver-1  |
airflow-airflow-webserver-1  | Traceback (most recent call last):
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 505, in _read_from_logs_server
airflow-airflow-webserver-1  |     response = _fetch_logs_from_service(url, rel_path)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/log/file_task_handler.py", line 90, in _fetch_logs_from_service
airflow-airflow-webserver-1  |     response = httpx.get(
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_api.py", line 189, in get
airflow-airflow-webserver-1  |     return request(
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_api.py", line 100, in request
airflow-airflow-webserver-1  |     return client.request(
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 821, in request
airflow-airflow-webserver-1  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 908, in send
airflow-airflow-webserver-1  |     response = self._send_handling_auth(
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 936, in _send_handling_auth
airflow-airflow-webserver-1  |     response = self._send_handling_redirects(
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
airflow-airflow-webserver-1  |     response = self._send_single_request(request)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_client.py", line 1009, in _send_single_request
airflow-airflow-webserver-1  |     response = transport.handle_request(request)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
airflow-airflow-webserver-1  |     with map_httpcore_exceptions():
airflow-airflow-webserver-1  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
airflow-airflow-webserver-1  |     self.gen.throw(typ, value, traceback)
airflow-airflow-webserver-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
airflow-airflow-webserver-1  |     raise mapped_exc(message) from exc
airflow-airflow-webserver-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
```

Do you have any advice what I am missing? Architecture-wise, I am not sure how webserver knows which celery worker to request logs from? 

Below is my docker-compose.yml  derived from the provided one. The only env variable I set outside the docker-compose is the `export AIRFLOW_MASTER_NODE=address_to_the_master` so the celery workers know the redis address. 

``` yaml
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Basic Airflow cluster configuration for CeleryExecutor with Redis and PostgreSQL.
#
# WARNING: This configuration is for local development. Do not use it in a production deployment.
#
# This configuration supports basic configuration using environment variables or an .env file
# The following variables are supported:
#
# AIRFLOW_IMAGE_NAME           - Docker image name used to run Airflow.
#                                Default: apache/airflow:2.6.1
# AIRFLOW_UID                  - User ID in Airflow containers
#                                Default: 50000
# AIRFLOW_PROJ_DIR             - Base path to which all the files will be volumed.
#                                Default: .
# Those configurations are useful mostly in case of standalone testing/running Airflow in test/try-out mode
#
# _AIRFLOW_WWW_USER_USERNAME   - Username for the administrator account (if requested).
#                                Default: airflow
# _AIRFLOW_WWW_USER_PASSWORD   - Password for the administrator account (if requested).
#                                Default: airflow
# _PIP_ADDITIONAL_REQUIREMENTS - Additional PIP requirements to add when starting all containers.
#                                Use this option ONLY for quick checks. Installing requirements at container
#                                startup is done EVERY TIME the service is started.
#                                A better way is to build a custom image or extend the official image
#                                as described in https://airflow.apache.org/docs/docker-stack/build.html.
#                                Default: ''
#
# Feel free to modify this file to suit your needs.
---
version: '3.10'
x-airflow-common:
  &airflow-common
  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.6.3-python3.10}
  # build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow    
    #AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mssql+pyodbc://airflow_user:airflow_pass123%@HudsonUATDB/Airflow?odbc_connect=Driver={ODBC Driver 18 for SQL Server};Server=HUDSONUATDB;Database=airflow;Uid=airflow_user;Pwd=airflow_pass123%;Encrypt=yes;TrustServerCertificate=yes
    #AIRFLOW__DATABASE__SQL_ALCHEMY_SCHEMA: 'airflow'
    # For backward compatibility, with Airflow <2.3
    #AIRFLOW__CORE__SQL_ALCHEMY_CONN: mssql+pyodbc:///?odbc_connect=Driver={ODBC Driver 18 for SQL Server};Server=HudsonUATDB;Database=Airflow;Uid=airflow_user;Pwd=airflow_pass123%;Encrypt=yes;TrustServerCertificate=yes
    # Do we have to set result backend ? 
    # https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#result-backend
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CELERY__WORKER_CONCURRENCY: 4
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__WEBSERVER__SECRETE_KEY: 'XBmkjR7dv0w0h1bpzKCbSQ=='
    # yamllint disable rule:line-length
    # Use simple http server on scheduler for health checks
    # See https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/check-health.html#scheduler-health-check-server
    # yamllint enable rule:line-length
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    # WARNING: Use _PIP_ADDITIONAL_REQUIREMENTS option ONLY for a quick checks
    # for other purpose (development, test and especially production usage) build/extend Airflow image.
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_LOGS_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    profiles:
      - master

  redis:
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
    profiles:
      - master

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "80:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    profiles:
      - master

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

    profiles:
      - master  

  

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    profiles:
      - master
    

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    # yamllint disable rule:line-length
    command:
      - -c
      - |
        function ver() {
          printf "%04d%04d%04d%04d" $${1//./ }
        }
        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
        airflow_version_comparable=$$(ver $${airflow_version})
        min_airflow_version=2.2.0
        min_airflow_version_comparable=$$(ver $${min_airflow_version})
        if (( airflow_version_comparable < min_airflow_version_comparable )); then
          echo "airflow version is" $airflow_version
          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
          echo
          exit 1
        fi
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    # The "chown g+w /process-data-volume-dir" seems useless
    # yamllint enable rule:line-length
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources
    profiles:
      - master

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      # Required to handle warm shutdown of the celery workers properly
      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
      DUMB_INIT_SETSID: "0"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@${AIRFLOW_MASTER_NODE:-localhost}:5432/airflow    
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@${AIRFLOW_MASTER_NODE:-localhost}:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@${AIRFLOW_MASTER_NODE:-localhost}:6379/0
    ports:
      - "8793:8793" # https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/logging-tasks.html#serving-logs-from-workers-and-triggerer
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    profiles:
      - workers

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
    command:
      - bash
      - -c
      - airflow
      
      
  # You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up
  # or by explicitly targeted on the command line e.g. docker-compose up flower.
  # See: https://docs.docker.com/compose/profiles/
  flower:
    <<: *airflow-common
    command: celery flower
    profiles:
      - flower
    ports:
      - "5555:5555"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    profiles:
      - master

volumes:
  postgres-db-volume:

```

**Comment by hbc-acai** [comment]
After querying task_instance table, I found the hostname e.g. 05b35495d9e6, which can also be found on the flower page. Is there a way to override this to the real host name or IP?

**Comment by hbc-acai** [comment, marked as answer]
It looks like the 05b35495d9e6 is the celery worker name which is the docker host name by default. I ended up fixing this by setting the docker hostname from a environment variable like below

```
  airflow-worker:
    <<: *airflow-common
    command: celery worker
    hostname: ${CELERY_WORKER_HOSTNAME:-.}
    healthcheck:

```
