### DISCUSSION TITLE
How to dynamically setup worker queue in docker airflow

### DISCUSSION THREAD

**Discussion by yeangPan** [apache/airflow#34047] [Q&A] [answered]
I have downloaded official docker compose file from airflow official web.

Things I want to do: I want to dynamically create worker queue through variables like
```
docker compose run -e WORKER_QUEUE=basedata airflow-worker 
```

Here is what ```airflow-worker``` looks like：
```
airflow-worker:
    <<: *airflow-common
    command: airflow celery worker -q ${WORKER_QUEUE:-default}
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      # Required to handle warm shutdown of the celery workers properly
      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
      DUMB_INIT_SETSID: 0
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
```
As I passed the variable ```WORKER_QUEUE```, it didn't work. I googled it, and tried another way to config:
```
airflow-worker:
    <<: *airflow-common
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      # Required to handle warm shutdown of the celery workers properly
      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
      AIRFLOW__OPERATORS__DEFAULT_QUEUE: ${WORKER_QUEUE:-default}
      DUMB_INIT_SETSID: 0
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
```
That didn't work either, both ways can only create default worker queue, the variable didn't work. After that I changed the config to this:
```
airflow-worker:
    <<: *airflow-common
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      <<: *airflow-common-env
      # Required to handle warm shutdown of the celery workers properly
      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
      AIRFLOW__OPERATORS__DEFAULT_QUEUE: $${WORKER_QUEUE:-default}
      DUMB_INIT_SETSID: 0
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
```

the variable I passed to the worker did work, but the default worker queue became ${WORKER_QUEUE:-default} 

Can someone help with it? Many thanks
