### DISCUSSION TITLE
Command line to update changed or added dags/tasks into airflow

### DISCUSSION THREAD

**Discussion by zygias** [apache/airflow#34193] [Q&A]
Hello, i have increased automatic dag updates into airflow.cfg:

```
min_serialized_dag_update_interval = 600
min_serialized_dag_fetch_interval = 300
min_file_process_interval = 600
processor_poll_interval = 5
parsing_processes = 2
```

This cfg was changed to decrease CPU usage (https://github.com/apache/airflow/issues/13637#issuecomment-892768703)

I want to refresh all updated dags after deployment. I found this solution (https://stackoverflow.com/a/50356956):
`python -c "from airflow.models import DagBag; d = DagBag();"`
ansible:
```
- name: Load New Dags
  command:
    chdir: "{{ airflow_home }}"
    cmd: ./venv/bin/python -c "from airflow.models import DagBag; d = DagBag();"
```
but this command is not updating updated dags/tasks immediately.

As i understand it will update new added dags, but i need to immediately update changes after updates into existing tasks.

In general i want to turn off automatically new dag import/existing dag updates and add logic into deployment for manual full dags update.
