### DISCUSSION TITLE
Latest airflow version 2.7.1-python3.11 occurs gunicorn fail

### DISCUSSION THREAD

**Discussion by andyfcx** [apache/airflow#34267] [General]
### Official Helm Chart version

1.10.0 (latest released)

### Apache Airflow version

2.7.1

### Kubernetes Version

v1.27.3-gke.100

### Helm Chart configuration

values.yml:
```
airflow:
  legacyCommands: false
  image:
    repository: apache/airflow
    tag: 2.7.1-python3.11 # I also used 2.7.1-python3.10, same

  executor: KubernetesExecutor

  fernetKey: "omitted"

  webserverSecretKey: "omitted"

  config:
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"

  users:
    - username: andy
      password: omitted
      role: Admin
      email: 
      firstName: Andy
      lastName: Huang
      connections: []

  variables: []

  pools: []

  extraPipPackages: []

variables.md
  extraEnv: []

  extraVolumeMounts: []

  extraVolumes: []

  kubernetesPodTemplate:

    stringOverride: ""

    resources: {}

    extraPipPackages: []

    extraVolumeMounts: []

    extraVolumes: []

scheduler:
  replicas: 1
  logCleanup:
    enabled: true
    retentionMinutes: 21600

  livenessProbe:
    enabled: true
    taskCreationCheck:
      enabled: false
      thresholdSeconds: 300
      schedulerAgeBeforeCheck: 180

web:
  replicas: 1
  service:
    type: ClusterIP
    externalPort: 8080

  
    stringOverride: |
      from airflow import configuration as conf
      from flask_appbuilder.security.manager import AUTH_DB
      
      SQLALCHEMY_DATABASE_URI = conf.get("core", "SQL_ALCHEMY_CONN")
      
      AUTH_TYPE = AUTH_DB

    existingSecret: ""

workers:
  enabled: false


triggerer:
  enabled: true
  replicas: 1
  
  resources: {}
  capacity: 1000


flower:
  enabled: false

logs:
  path: /opt/airflow/logs
  persistence:
    enabled: false

dags:
  path: /opt/airflow/dags
  
  persistence:
    enabled: false
  
  gitSync:
    enabled: true
    repo: git@github.com:doublethinklab/FactoryStream.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"
    sshSecret: "airflow-ssh-secret"
    sshSecretKey: gitSshKey


ingress:
  enabled: true

serviceAccount:
  create: true
  name: "airflow-dtl-gcp"
  annotations: {}

extraManifests: []

pgbouncer:
  enabled: true
  resources: {}
  authType: md5

postgresql:
  enabled: false
  persistence:
    enabled: true
    storageClass: ""
    size: 8Gi

externalDatabase:
  type: postgres
  host: myhost
  port: 5432
  database: airflow1234
  user: airflow
  password: mypassword
  properties: ""

redis:
  enabled: false

externalRedis:
  host: localhost
```

### Docker Image customizations

I used official images of 2.7.1-python3.11, I also used 2.7.1-python3.10, same.

### What happened

Completed in airflow-db-migrations, sync-users, dags-git-clone, checkdb, wait-for-db-migration,
but web Pods CrashLoopBackoff.
Gunicorn Received signal: 15

logs:
```
/home/airflow/.local/lib/python3.11/site-packages/airflow/configuration.py:2104 FutureWarning: section/key [core/sql_alchemy_conn] has been deprecated, you should use[database/sql_alchemy_conn] instead. Please update your `conf.get*` call to use the new name
/home/airflow/.local/lib/python3.11/site-packages/flask_limiter/extension.py:336 UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
Running the Gunicorn Server with:
Workers: 4 sync
Host: 0.0.0.0:8080
Timeout: 120
Logfiles: - -
Access Logformat:
=================================================================
[2023-09-11T03:31:01.746+0000] {webserver_command.py:440} INFO - Received signal: 15. Closing gunicorn.
```

### What you think should happen instead

web server container should work fine

### How to reproduce

Start with the values.yml with a new database

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by boring-cyborg** [comment]
Thanks for opening your first issue here! Be sure to follow the issue template! If you are willing to raise PR to address this issue please do so, no need to wait for approval.

**Comment by csp33** [comment]
hey @andyfcx, have you tried to increase the resources for the webserver pods? In the past I've had the same error and I fixed it like that.
You can specify it in the chart:
```yaml
webserver:
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 4Gi
```

BTW, I just updated to Airflow 2.7.1 and it's working fine for me
