### DISCUSSION TITLE
Metrics missing from statsd

### DISCUSSION THREAD

**Discussion by oleksandrfatikov** [apache/airflow#34847] [General]
Hi!
I'm using airflow deployed in k8s cluster.
Version of airflow is 2.5.3.
Currently I have following metrics missing from statsd (mapping samples):
```
    - match: "*.dagrun.duration.success.*"
      match_metric_type: observer
      name: "af_agg_dagrun_duration_success"
      labels:
        airflow_id: "$1"
        dag_id: "$2"

    - match: "*.dagrun.duration.failed.*"
      match_metric_type: observer
      name: "af_agg_dagrun_duration_failed"
      labels:
        airflow_id: "$1"
        dag_id: "$2"

    - match: "*.dag.*.*.duration"
      match_metric_type: observer
      name: "af_agg_dag_task_duration"
      labels:
        airflow_id: "$1"
        dag_id: "$2"
        task_id: "$3"

    - match: "*.dagrun.schedule_delay.*"
      match_metric_type: observer
      name: "af_agg_dagrun_schedule_delay"
      labels:
        airflow_id: "$1"
        dag_id: "$2"
```

Please let me know what I'm doing wrong.
