### DISCUSSION TITLE
Issue with Airflow Webserver when Configured with External DB (Airflow's webserver fails to start, `signal: 15`)

### DISCUSSION THREAD

**Discussion by ylnsnv** [apache/airflow#35383] [General]
### Official Helm Chart version

1.11.0 (latest released)

### Apache Airflow version

airflowVersion: 2.7.1

### Kubernetes Version

minikube version: v1.31.1

### Helm Chart configuration

values.yaml -
```
logs:
  persistence:
    size: 8Gi

workers:
  persistence:
    size: 8Gi

triggerer:
  persistence:
    size: 8Gi

webserverSecretKey: someSecretKey

webserver:
  livenessProbe:
        timeoutSeconds: 30
postgresql:
  enabled: false

pgbouncer:
  enabled: true

data:
  metadataSecretName: mydatabase
```

### What happened

I am experiencing a challenge with the Airflow webserver when it is configured to use an external database. It appears that every other component functions as expected, except for the webserver. The logs repetitively show the following entries:
```
[2023-11-02T06:44:34.683+0000] {configuration.py:2066} INFO - Creating new FAB webserver config file in: /opt/airflow/webserver_config.py
/home/airflow/.local/lib/python3.8/site-packages/flask_limiter/extension.py:336 UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
Running the Gunicorn Server with:
Workers: 4 sync
Host: 0.0.0.0:8080
Timeout: 120
Logfiles: - -
Access Logformat: 
=================================================================
[2023-11-02T06:45:27.301+0000] {webserver_command.py:440} INFO - Received signal: 15. Closing gunicorn.
```
To further diagnose, I overrode the default webserver commands in `values.yaml` as follows:
```
command: ["sleep"]
args: ["infinity"]
``` 
Upon SSHing into the webserver pod, running `airflow db check` yielded a successful response (albeit with a duration of approximately 10 seconds). However, initiating the airflow webserver command produced the following logs:
```
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
Running the Gunicorn Server with:
Workers: 4 sync
Host: 0.0.0.0:8080
Timeout: 120
Logfiles: - -
Access Logformat: 
=================================================================
/home/airflow/.local/lib/python3.8/site-packages/flask_limiter/extension.py:336 UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
command terminated with exit code 137
```
It is worth mentioning that the webserver runs flawlessly when it is not configured with the external DB settings. Specifically, when the values.yaml is set to:
```
logs:
  persistence:
    size: 8Gi

workers:
  persistence:
    size: 8Gi

triggerer:
  persistence:
    size: 8Gi
```
I am trying to ascertain why an external DB connection might lead to an exit code of 137, which is indicative of an Out-of-Memory (OOM) condition. Furthermore, I have explored various resource allocation strategies, ranging from increasing the memory allocation up to 5Gi to not specifying it, but the issue persists.

I would greatly appreciate insights or solutions to this challenge.

### What you think should happen instead

I think the airflow webserver should start successfully.

### How to reproduce

Create the postgres configMap-
```
apiVersion: v1
kind: ConfigMap
metadata:
    name: postgres-config-map
data:
    postgres-host: "somehost.com"
    postgres-port: "someport"
```
Create the postgres secret-
```
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
stringData:
    postgres-user: pgUserVale
    postgres-password: pgPasswordValue
    postgres-db: pgdb
    postgres-ssl: -----BEGIN CERTIFICATE-----\n.....values....==\n-----END CERTIFICATE-----

```
Run the script to create the `mydatabase` connection string secret-
```
#!/bin/bash

# Get values from ConfigMap and Secret
PG_HOST=$(kubectl get configmap postgres-config-map -o=jsonpath='{.data.postgres-host}')
PG_PORT=$(kubectl get configmap postgres-config-map -o=jsonpath='{.data.postgres-port}')
PG_USER=$(kubectl get secret postgres-secret -o=jsonpath='{.data.postgres-user}' | base64 -d)
PG_PASS=$(kubectl get secret postgres-secret -o=jsonpath='{.data.postgres-password}' | base64 -d)
PG_DB=$(kubectl get secret postgres-secret -o=jsonpath='{.data.postgres-db}' | base64 -d)

# Create connection string and create a Secret
CONNECTION_STRING="postgresql://${PG_USER}:${PG_PASS}@${PG_HOST}:${PG_PORT}/${PG_DB}?sslmode=require&sslrootcert=/etc/secrets/pg-ssl/postgres-ssl.crt"
kubectl create secret generic mydatabase --from-literal=connection=${CONNECTION_STRING}
```
and apply the values.yaml from above.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jscheffl** [comment]
Error code 137 is raised by docker usually when a process runs out of memory. Can you check adding more memory in your helm chart if this helps? 
e.g. via `webserver.resources`parameter in helm chart
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

**Comment by potiuk** [comment]
Yes, 137 is memory. Converting it to a  discussion, as this is really troubleshooting question.

**Comment by ylnsnv** [comment]
Well, as I've mentioned, I even tried to add memory up to 5Gi with no help... so I do not think it's actually about increasing the memory... maybe there's some sort of memory leakage? or any other idea you have?

@potiuk @jens-scheffler-bosch

**Reply by potiuk** [reply]
Maybe you have some other limits set. What does your monitoring says? Do you have any graph or charts showing specific memory usage of all your components? This is something that you should always set up as part of the deployment in order to deal with any issues of that kind. What does your monitoring say?

**Reply by ylnsnv** [reply]
I'm monitoring closely the memory usage and it doesn't look like there are any spikes what so ever in memory...
As you can see below, 250 Mi are being used out of the 3Gi I gave it, so it doesn't look like a memory issue at all.
![Screenshot at 2023-11-06 15-42-31](https://github.com/apache/airflow/assets/42522942/dc057676-f863-4696-a50c-e321b6927c6c)

**Reply by potiuk** [reply]
Do you see your memory growing over time when the component start? 

BTW. Yes. It could be that a driver you use in a version you use with the DB you use has incontrollable memory growth. also there could be this is caused or triggered by things like gevent or greenlets in your gunicorn configuration - you might play with webserver configuration - there are various ways you can configure webserver concurrency mechanisms and in some specific configurations and combinations of libraries / system this might cause problems. 

BTW. I was asking about **real** monitoring solution you might have but if you use minikube, then I suggest you switch to something mre serious with serious monitoring implemented so that you can see more than just "current" state but also observer what happens. You are talking about "hobbyist" setup here - so the most we can tell you is to experiment, if there is no real data and monitoring results.

Also there were some problems with one of the libraries in some versions causing uncontrollable growth on certain configuration aand choices of some kubernetes/kernel configuration https://github.com/apache/airflow/issues/29841 - so it migh also be that this is something your minikube/k8s version triggers. 

What I could recommend - if none of that help - upgrade to latest versions of everything you have and try maybe with more "production ready" version of k8s as well.

**Reply by ylnsnv** [reply]
Before I use the airflow on my production cluster I need to develop some stuff to wrap around it hence I'm deploying it on my minikube first.
I'd like to reiterate that the Airflow deployment functions correctly when I use the Helm chart without specifying the following values in values.yaml:
```
postgresql:
  enabled: false

pgbouncer:
  enabled: true

data:
  metadataSecretName: mydatabase
```
To ensure that I am following the correct installation procedure, this is the command I use to install the Helm chart:

```
#!/usr/bin/env bash
helm repo add apache-airflow https://airflow.apache.org
helm upgrade --install airflow apache-airflow/airflow -f values.yaml
```
Here is my complete `values.yaml`:

```
logs:
  persistence:
    size: 8Gi

workers:
  persistence:
    size: 8Gi

triggerer:
  persistence:
    size: 8Gi

webserverSecretKey: somevalue

webserver:
  extraVolumes:
    - name: pg-ssl-cert
      secret:
        secretName: postgres-secret
        items:
        - key: postgres-ssl-airflow-format
          path: postgres-ssl.crt

  extraVolumeMounts:
    - name: pg-ssl-cert
      mountPath: "/tmp/secrets/pg-ssl"
      readOnly: true
  resources:
    limits:
      cpu: 500m
      memory: 3Gi
    requests:
      cpu: 300m
      memory: 1Gi
  livenessProbe:
        timeoutSeconds: 30
postgresql:
  enabled: false

pgbouncer:
  enabled: true

data:
  metadataSecretName: mydatabase

statsd:
  enabled: true
```
Additionally, this is the script I use for creating the mydatabase secret:

```
#!/bin/bash

PG_HOST=$(kubectl get configmap postgres-config-map -o=jsonpath='{.data.postgres-host}')
PG_PORT=$(kubectl get configmap postgres-config-map -o=jsonpath='{.data.postgres-port}')
PG_USER=$(kubectl get secret postgres-secret -o=jsonpath='{.data.postgres-user}' | base64 -d)
PG_PASS=$(kubectl get secret postgres-secret -o=jsonpath='{.data.postgres-password}' | base64 -d)
PG_DB=$(kubectl get secret postgres-secret -o=jsonpath='{.data.postgres-db}' | base64 -d)

CONNECTION_STRING="postgresql://${PG_USER}:${PG_PASS}@${PG_HOST}:${PG_PORT}/${PG_DB}?sslmode=require&sslrootcert=/tmp/secrets/pg-ssl/postgres-ssl.crt"
kubectl create secret generic mydatabase --from-literal=connection=${CONNECTION_STRING}
```
So to be honest I don't know what else I could try (I've made sure that the certificate file on the pod is proper already) and I'm just completely lost... 
I would also like to say that I appreciate your time and effort in trying to help me, it's really not obvious!

**Reply by potiuk** [reply]
I thiink we tried what we could. If there are no more evidences, our guesses run out. 

You might want to look at your deployment - or better monitor the memory usage and see what minikube logs tell you, 137 is definitely a sign of memory problem. But without more evidences, and you experimenting with the things we suggested so far, there is not much we can do. We are only volunteers spending our free time on trying to help you diagnose it, and it's only as far as we can get.

**Reply by ylnsnv** [reply]
Could someone guide me on setting up a connection between Airflow and a certificate-authenticated PostgreSQL? I suspect my current approach to specifying the certificate is incorrect and may be causing issues. I've consulted the [Airflow Helm Chart documentation](https://airflow.apache.org/docs/helm-chart/stable/production-guide.html), but it doesn't detail how to specify the certificate. I also came across another resource that mentioned specifying a file containing the certificate, but it wasn't a comprehensive tutorial. Any assistance with a step-by-step guide would be greatly appreciated.

**Reply by potiuk** [reply]
I personally have no such experience so can't help from the top of my head. And unless there is someone who already did it and can help here, I don't think there is one in airflow docs. But if/when you figure it out, contributing such step-by-step guide would be nice in https://airflow.apache.org/docs/helm-chart/stable/production-guide.html 

This is basically as those docs are built - the many contributors of ours who went through the process are contributing back any examples and guides of this sort. Maybe also someone did it before and can help here.

But yeah I think it might be that the configuration of yours is caussing the client to crash, that would explain what you observe actually.

**Reply by jscheffl** [reply]
I am also not an expert in DB certs and connectivity, if you use a certificate to authenticate, I just saw that PGBouncer as DB Proxy which is used per default in the helm chart support such options: https://airflow.apache.org/docs/helm-chart/stable/parameters-ref.html#pgbouncer --> `pgbouncer.ssl.key` - might this be of help? (We use just user+password in our postgres, sorry, have no experience in key-based auth for DB access)

**Comment by alucryd** [comment]
Got the same issue with the included postgres database, so it's not limited to external DB, and I can also confirm it's not a resource issue, I am nowhere close to the limits and still gunicorn gets killed.

**Reply by potiuk** [reply]
Then. I suggest you open an issue with your logs and details of your setup and any observations you can make - including trying to figure out who and why is killing gunicorn @alucryd . Without it. there is absolutely no way anyone can do anything with it.

**Reply by alucryd** [reply]
I did, it was demoted to a discussion :/ New piece of information, this happens on GKE autopilot, not in a standard cluster. So gunicorn is probably using a syscall that isn't allowed on Autopilot. Will amend the discussion.

**Comment by daJynxxed** [comment]
I was able to solve by giving the pod a longer startup probe.... e.g. in helm override yaml
```
webserver:
  startupProbe:
    periodSeconds: 10
    failureThreshold: 20
  allowPodLogReading: true
```
The long and short of it was that kubernetes was killing the pod before it had a chance to initialize. 
This should be added to the helm template but I don't know how to make this happen.
