### DISCUSSION TITLE
WARNING - Model file /opt/airflow/pod_templates/pod_template_file.yaml does not exist

### DISCUSSION THREAD

**Discussion by ampx-mg** [apache/airflow#35419] [General]
### Official Helm Chart version

1.11.0 (latest released)

### Apache Airflow version

2.7.1

### Kubernetes Version

1.23

### Helm Chart configuration

```
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 20m
      memory: 64Mi

webserverSecretKey: "${webserver_key}"
useStandardNaming: true

executor: KubernetesExecutor

data:
  metadataConnection:
    host: "${db_host}"
    db: "${db_name}"
    user: "${db_username}"
    pass: "${db_password}"

dags:
  gitSync:
    enabled: true
    repo: REDACTED
    subPath: ""
    branch: master
    sshKeySecret: REDACTED
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

defaultAirflowTag: "2.7.1"

config:
  logging:
    remote_logging: "True"
    remote_base_log_folder: REDACTED
    remote_log_conn_id: aws_conn
  kubernetes_executor:
    worker_container_repository: REDACTED
    worker_container_tag: REDACTED

ingress:
  web:
    enabled: true
    pathType: Prefix
    host: "${ingress_hostname}"
    ingressClassName: "nginx"

pgbouncer:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  metricsExporterSidecar:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 64Mi

scheduler:
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 1Gi
  
  extraVolumes:
    - name: airflow-pod-templates
      projected:
        sources:
        - configMap:
            name: airflow-pod-templates-cm

  extraVolumeMounts:
    - name: airflow-pod-templates
      mountPath: /opt/airflow/custom_pod_templates
      readOnly: true

  logGroomerSidecar:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 64Mi

workers:
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 256Mi
  serviceAccount:
    create: false
    name: "${service_account_name}"
  persistence:
    enabled: false
  logGroomerSidecar:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 64Mi

webserver:
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 300m
      memory: 1Gi
  serviceAccount:
    create: false
    name: "${service_account_name}"
  livenessProbe:
      initialDelaySeconds: 30

triggerer:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  persistence:
    enabled: false
  logGroomerSidecar:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 64Mi

postgresql:
  enabled: false

statsd:
  enabled: false

redis:
  enabled: false

extraConfigMaps:
  airflow-pod-templates-cm:
    data: |
      common_template.yaml: |-
        ${template_path}

```

### Docker Image customizations

None, using the default `apache/airflow:2.7.1`

### What happened

In the logs I constantly see this warning message, for every task that I run
```
{pod_generator.py:539} WARNING - Model file /opt/airflow/pod_templates/pod_template_file.yaml does not exist
```

### What you think should happen instead

I don't think I should be seeing this message, when I exec into the scheduler pod I can see the folder and the pod template inside
```
airflow@airflow-scheduler-57f77575d4-pkxx9:/opt/airflow$ ls -l
total 4
-rw-r--r-- 1 root root 1646 Nov  3 14:59 airflow.cfg
drwxr-xr-x 2 root root   39 Nov  3 14:59 config
drwxrwsrwt 3 root root  100 Nov  3 14:59 custom_pod_templates
drwxrwsrwx 4 root root   78 Nov  3 14:59 dags
drwxrwsrwx 4 root root   52 Nov  3 15:00 logs
drwxr-xr-x 2 root root   36 Nov  3 14:59 pod_templates
airflow@airflow-scheduler-57f77575d4-pkxx9:/opt/airflow$ cd pod_templates/
airflow@airflow-scheduler-57f77575d4-pkxx9:/opt/airflow/pod_templates$ ls -l
total 8
-rw-r--r-- 1 root root 4304 Nov  3 14:59 pod_template_file.yaml
airflow@airflow-scheduler-57f77575d4-pkxx9:/opt/airflow/pod_templates$ whoami
airflow
airflow@airflow-scheduler-57f77575d4-pkxx9:/opt/airflow/pod_templates$ id -u airflow
50000
airflow@airflow-scheduler-57f77575d4-pkxx9:/opt/airflow/pod_templates$ id -g airflow
0
```
and I didn't make any changes to the user/group permissions at all, using the default airflow image and I would expect this to work out of the box. Also `airflow` user is able to read the file
```
airflow@airflow-scheduler-57f77575d4-pkxx9:/opt/airflow$ test -r pod_templates/pod_template_file.yaml; echo "$?"
0
airflow@airflow-scheduler-57f77575d4-pkxx9:/opt/airflow$ test -w pod_templates/pod_template_file.yaml; echo "$?"
1
```

### How to reproduce

We deploy this helm chart using terraform `helm_release`, but I doubt this is playing any significant role, so I assume basic `helm install` will do. Then run a DAG and check logs for its tasks.

### Anything else

I found a couple of similar threads like https://github.com/apache/airflow/discussions/32043 or https://github.com/apache/airflow/discussions/30805, but in both of these threads there are hints at wrong user/group permissions, which I would expect to set only if I had messed around with them in the first place, which I hadn't.  
The only unusual thing I am doing in my values files is mounting extra volume with additional pod templates, but I am not using them anywhere, therefore I don't think this should have any impact on the default `pod_templates` folder.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
