### DISCUSSION TITLE
Does it make sense for the triggerer to have persistence enabled in k8s while using remote logging?

### DISCUSSION THREAD

**Discussion by slmg** [apache/airflow#35851] [Q&A] [answered]
Hi, is the below appropriate? Setting

* `persistence: false` renders a Deployment
* `persistence: true` renders a StatefulSet defining a `logs` PVC.
 
As I am using remote logging, it would feel redundant to persists logs into a volume.  Butt since I am unfamiliar with the internals of the triggerer, I am wondering if I missed anything else which would justify to set `persistence: true`?

Thanks

helm chart version: `1.10.0`

values.yaml
```yaml
# Config settings to go into the mounted airflow.cfg
config:
  logging:
    remote_logging: "True"
    remote_base_log_folder: s3://bucket/path/to/logs

triggerer:
  persistence:
    enabled: false
```
