### DISCUSSION TITLE
Postgres `keepalives_idle` in helm chart

### DISCUSSION THREAD

**Discussion by slmg** [apache/airflow#35853] [Q&A] [answered]
Hi, in [setting-up-a-postgresql-database](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-up-database.html#setting-up-a-postgresql-database) is recommended to set the below connection parameters for Amazon RDS (which I am using).

```python
keepalive_kwargs = {
    "keepalives": 1,
    "keepalives_idle": 30,
    "keepalives_interval": 5,
    "keepalives_count": 5,
}
```

Is this needed in the context of a K8s deployment using the`KubernetesExecutor`? If so. how could I add this config via the helm chart?
Digging in the chart [values.yaml](https://github.com/apache/airflow/blob/helm-chart/1.10.0/chart/values.yaml), it seems it could potentially be achieved with something like the below.

```yaml
airflowLocalSettings: |-
  keepalive_kwargs = {
      "keepalives": 1,
      "keepalives_idle": 30,
      "keepalives_interval": 5,
      "keepalives_count": 5,
  }

config:
  database:
    sql_alchemy_connect_args = airflow_local_settings.keepalive_kwargs
```

Though the chart does not handle `.Values.config.database` at the moment (version `1.10.0`) so that does not result in any change in `airflow.cfg`.

Thanks

**Comment by potiuk** [comment, marked as answer]
You can set any config that is not set in config file by an environment variable (they override whatever is set in config file). See:

https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html

Helm Chart allows you to set any env variable easily (including the `AIRFLOW__` ones).

**Comment by slmg** [comment]
Thanks. For future ref, I did

```yaml
airflowLocalSettings: |-
  keepalive_kwargs = {
      "keepalives": 1,
      "keepalives_idle": 30,
      "keepalives_interval": 5,
      "keepalives_count": 5,
  }

# Environment variables for all airflow containers
env:
  - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONNECT_ARGS
    value: airflow_local_settings.keepalive_kwargs
```
