### DISCUSSION TITLE
Failed scheduler liveness check on GKE during Kubernetes master upgrade

### DISCUSSION THREAD

**Discussion by ryandutton** [apache/airflow#35918] [General] [answered]
When running airflow on GKE, the liveness check fails whenever there is a Kubernetes master upgrade. This is a controlled event and it would be good to have Airflow handle the master unavailability more gracefully if it can't do so already. 

I'm not sure whether others are having issues similar when running on GKE but it seems unnecessary to restart the pod due to an upgrade, knowing that the restart won't have any affect on the liveness of the scheduler.

I am using the airflow cli as part of the liveness check. Here is the liveness configuration:

``` yaml
livenessProbe:
  exec:
    command:
      - /bin/sh
      - -c
      - airflow jobs check --job-type SchedulerJob --allow-multiple --limit 100
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 8
```

I'm running Airflow v2.7.1

Happy to provider more detail.
