### DISCUSSION TITLE
KubernetesPodOperator failed to write on mounted path in airflow cluster

### DISCUSSION THREAD

**Discussion by yeangPan** [apache/airflow#36021] [Q&A]
I started a airflow cluster using Helm chart, and choose KubernetesPodOperator as in my worker. I launched a task but failed with error msg:
```
[2023-12-02, 11:48:21 CST] {pod_manager.py:401} INFO - [base] Traceback (most recent call last):
[2023-12-02, 11:48:21 CST] {pod_manager.py:401} INFO - [base]   File "entry.py", line 5, in <module>
[2023-12-02, 11:48:21 CST] {pod_manager.py:401} INFO - [base]     from S_backtest_eod_data_update import bod_data_update_main
[2023-12-02, 11:48:21 CST] {pod_manager.py:401} INFO - [base]   File "/app/S_backtest_eod_data_update.py", line 5, in <module>
[2023-12-02, 11:48:21 CST] {pod_manager.py:401} INFO - [base]     from utils.config_data_update import final_trading_factors, trade_data_StartDate, trade_data_path, trade_log_path
[2023-12-02, 11:48:21 CST] {pod_manager.py:401} INFO - [base]   File "/app/utils/config_data_update.py", line 1, in <module>
[2023-12-02, 11:48:21 CST] {pod_manager.py:401} INFO - [base]     from utils.config_dev import *
[2023-12-02, 11:48:21 CST] {pod_manager.py:401} INFO - [base]   File "/app/utils/config_dev.py", line 38, in <module>
[2023-12-02, 11:48:21 CST] {pod_manager.py:401} INFO - [base]     os.mkdir(total_path+l)
[2023-12-02, 11:48:21 CST] {pod_manager.py:401} INFO - [base] PermissionError: [Errno 13] Permission denied: '/app/portfolio/bod_data'
```

here 's what my operator looks like:

```
opt = KubernetesPodOperator(
        namespace="airflow",
        image="harbor.cluster.com/strategy/test:latest",
        pod_template_file=os.path.join(AIRFLOW_HOME, "dags/test.yaml"),
        name="sunyt_combo.opt",
        is_delete_operator_pod=True,
        cmds=["/root/.local/bin/poetry", "run", "python", "entry.py", "opt", f"{DATE}"],
        in_cluster=True,
        task_id="sunyt_combo.opt",
        get_logs=True,
        log_events_on_failure=True,
        dag=dag,
    )

opt

```

the pod_template_file was:

```
apiVersion: v1
kind: Pod
metadata:
  name: airflow-worker
  labels:
    tier: airflow
    component: worker
    release: airflow
spec:
  containers:
    - name: airflow-worker
      image: harbor.cluster.com/strategy/test:0.0.1
      volumeMounts:
        - mountPath: "/scratch"
          name: scratch
        - mountPath: "/app/portfolio"
          name: test
          readOnly: false
  volumes:
    - name: scratch
      hostPath:
        path: /scratch
        type: Directory
    - name: test
      hostPath:
        path: /mnt/test
        type: Directory
```

I tested to write a file in scheduler pod on the mounted path, it worked normally,

![image](https://github.com/apache/airflow/assets/21076543/941cfad8-99fb-4aa7-8706-ea2fb0459b4d)

the questions were:
1. what's the best practice to mount personal path to all worker pods(not through pod_template_file, because I have to mount this path for all pods). 
2. how to config the pod_template_file to make pod in KubernetesPodOperator can write.

many thanks!
