### DISCUSSION TITLE
How to create variables with docker-compose airflow?

### DISCUSSION THREAD

**Discussion by johndickson2** [apache/airflow#36979] [Q&A] [answered]
Is there a way to create a variable in airflow without using the UI and instead adding the variable during the docker compose step?

![Screenshot 2024-01-23 at 1 25 52 PM](https://github.com/apache/airflow/assets/156930365/af1248b3-7bee-45ff-8493-10b8ecf9f7b4)

**Comment by Taragolis** [comment, marked as answer]
If you talk about [sample docker compose file](https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#fetching-docker-compose-yaml),then you could place in the same folder as docker-compose.yaml file with variables `variables.json` and add service similar to docker-compose.yaml which basically use [`airflow variables import`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#import_repeat4) cli command

```yaml
  airflow-variables:
    <<: *airflow-common
    command: 
      - variables
      - import
      - -a
      - overwrite
      - /tmp/variables.json
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/variables.json:/tmp/variables.json:ro
    restart: on-failure
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
```

Another option add your Airflow variables as [environment variables](https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html#storing-variables-in-environment-variables), in this case it wouldn't show into the U
