### DISCUSSION TITLE
airflow in docker can't control celery workers task running parallel number exactly

### DISCUSSION THREAD

**Discussion by weiye-Lee** [apache/airflow#37022] [Q&A]
hi everyone~

I found the Concurrency capability of celery workers doesn't depend on `AIRFLOW__CELERY__WORKER_CONCURRENCY`  but `AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG ` in my airflow. I wonder is this a feature or something wrong in my airflow installation.

This is my configuration below, I set the `AIRFLOW__CELERY__WORKER_CONCURRENCY: 256` and `AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 8`. When I start **some DAG** by manual, there are only about 8 tasks can run at same time not 256.
``` yaml
    AIRFLOW__CELERY__WORKER_CONCURRENCY: 256 
    AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 1 
    AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: 8
    AIRFLOW__CORE__PARALLELISM: 256 
    AIRFLOW__SCHEDULER__PARSING_PROCESSES: 32

```

[see also](https://stackoverflow.com/questions/77870485/airflow-installed-in-docker-is-unable-to-execute-the-tasks-of-multiple-dags-in-p)
