### DISCUSSION TITLE
[HELM] How do I pass checksum as value to workers.podAnnotation

### DISCUSSION THREAD

**Discussion by sappusaketh** [apache/airflow#37374] [Q&A]
I want to pass my custom secret yaml checksum to worker pod annotation like [these](https://github.com/apache/airflow/blob/main/chart/templates/workers/worker-deployment.yaml#L90-L97)
but when I do this
```yaml
# values.yaml for main chart

workers:
  # other worker values here
  podAnnotations:
    checksum/exampleSecret: {{ include (print $.Template.BasePath "/example_secret.yaml") . | sha256sum }}
```
I get 

```error
Error: failed to parse values-dev.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"include (print $.Template.BasePath \"/example_secret.yaml\") . | sha256sum":interface {}(nil)}
```
because of I cannot use helm inbuilt functions in values.yaml. Is there any way we can pass template strings from values and render it in the linked CRD.

I think only option I m left with is by using --set. I manage my app with argo so I cannot use --set any way this can be solved with values yaml
