### DISCUSSION TITLE
Tasks taking too long to fail

### DISCUSSION THREAD

**Discussion by pedro-cf** [apache/airflow#39809] [Q&A] [answered]
Greetings,

Recently I've been having an issue with my local deployment for development using docker-compose.

Tasks that fail (exceptions in python operators f.e.) take very long to fail and this randomly started happening... I've re-deployed everything (deleted containers/volumes completely; `docker-system prune --force`)  and it still happens...

I'm running this deployment on `"Ubuntu 22.04.4 LTS` on `WSL2`

Regarding my configuration I use:

```yml
environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: '' ## python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    # yamllint disable rule:line-length
    # Use simple http server on scheduler for health checks
    # See https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/check-health.html#scheduler-health-check-server
    # yamllint enable rule:line-length
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    # WARNING: Use _PIP_ADDITIONAL_REQUIREMENTS option ONLY for a quick checks
    # for other purpose (development, test and especially production usage) build/extend Airflow image.
    _PIP_ADDITIONAL_REQUIREMENTS: '${_PIP_ADDITIONAL_REQUIREMENTS}'
    AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
    AIRFLOW__EMAIL__SUBJECT_TEMPLATE: /opt/airflow/email_templates/email_subject_template.jinja2
    AIRFLOW__EMAIL__HTML_CONTENT_TEMPLATE: /opt/airflow/email_templates/email_html_content_template.jinja2
    AIRFLOW__EMAIL__FROM_EMAIL: ${AIRFLOW__EMAIL__FROM_EMAIL}
    AIRFLOW__SMTP__SMTP_HOST: ${AIRFLOW__SMTP__SMTP_HOST}
    AIRFLOW__SMTP__SMTP_STARTTLS: ${AIRFLOW__SMTP__SMTP_STARTTLS}
    AIRFLOW__SMTP__SMTP_SSL: ${AIRFLOW__SMTP__SMTP_SSL}
    AIRFLOW__SMTP__SMTP_USER: ${AIRFLOW__SMTP__SMTP_USER}
    AIRFLOW__SMTP__SMTP_PASSWORD: ${AIRFLOW__SMTP__SMTP_PASSWORD}
    AIRFLOW__SMTP__SMTP_PORT: ${AIRFLOW__SMTP__SMTP_PORT}
    AIRFLOW__SMTP__SMTP_MAIL_FROM: ${AIRFLOW__SMTP__SMTP_MAIL_FROM}
    AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW: graph
    AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT: 'false'
    # AIRFLOW__CORE__PARALLELISM: '3'
    AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: '1'
    AIRFLOW__WEBSERVER__AUTO_REFRESH_INTERVAL: '1'
    AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: '5'
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: '5'
    AIRFLOW__CORE__EXECUTE_TASKS_NEW_PYTHON_INTERPRETER: 'true'
    PYTHONUNBUFFERED: 1
    GITLAB_TOKEN: ${GITLAB_TOKEN}


  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR:-.}/resources:/opt/airflow/resources
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/airflow:/tmp
```

Any help would be appreciated.
