### DISCUSSION TITLE
CAN'T INSTALL GIT ON THE AIRFLOW IMAGE

### DISCUSSION THREAD

**Discussion by Powerostad** [apache/airflow#40188] [Q&A]
I'm trying to clone a repository in my airflow DAG and i'm using Git python library  to interact with my repository.
The problem i'm encountering is that the git is not installed on the container.

This is my Dockerfile:

```
FROM apache/airflow:2.9.1
USER root

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
     python3 \
     python3-pip \
     gcc \
     g++ \
     python3-dev \
     build-essential libssl-dev libffi-dev libmariadb-dev\
     git\
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /
USER 1001
RUN pip install -r /requirements.txt

# Copy the .env file to the airflow user's home directory
USER 1001
COPY .env /home/airflow
USER 1001
```
I read the airflow main Dockerfile and there is one place that airflow install git and then remove all dependencies and it seems like it is removing the Git from the container.
for further information, i use the image from my Dockerfile in airflow official docker-compose.yaml:

```
x-airflow-common:
  &airflow-common
  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  #image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.9.1}
  #command: ["sh", "-c", "apt-get update && apt-get install -y default-libmysqlclient-dev"]
  #build: .
  image: edr-airflow 
  environment:
...
```
How can i install Git in my container?
