### DISCUSSION TITLE
Airflow on KIND Bad url redirect after login

### DISCUSSION THREAD

**Discussion by reisub83** [apache/airflow#40687] [General]
I have an Airflow installed in a KIND k8s cluster with an nginx ingress controller, to istall it I used the official helm release 1.14.0
Airflow version 2.9.2

My kind cluster has this port publish configuration:

```
  extraPortMappings:
  - containerPort: 80
    hostPort: 10110
    protocol: TCP
  - containerPort: 443
    hostPort: 10473
    protocol: TCP
```

In values file I have the ingress configured this way

```
ingress:
  web:
    enabled: true
    hosts: ["dockerhostname.mydomain"]
    ingressClassName: "nginx"
  flower:
    path: "/airflow/flower"
```

when I point my browser to `http://dockerhostname.mydomain:10110/` I get the login page, but when I click on "Sign In" I get redirect to `http://dockerhostname.mydomain/home`

It misses the port in the URI

After this, if I manually change the URI to `http://dockerhostname.mydomain:10110/home`, I'm able to access the Airflow dashboard

Same problem appear when I try to add a variable from the Admin section, I get the wrong redirect after clicking on "save".

I tried following configurations in my values file to fix the redirect problem, without success:

```
extraEnv: |
  - name: AIRFLOW__WEBSERVER__BASE_URL
    value: "http://dockerhostname.mydomain:10110"
  - name: AIRFLOW__WEBSERVER__DEFAULT_UI_URL
    value: "http://dockerhostname.mydomain:10110"
  - name: AIRFLOW__WEBSERVER__EXTERNAL_URL
    value: "http://dockerhostname.mydomain:10110"
```

```
config:
  webserver:
    base_url: "http://dockerhostname.mydomain:10110"
```

**Versions of Apache Airflow**
2.9.2

Deployment
Official Apache Airflow Helm Chart 1.4.0 on kind version 0.22.0 (k8s v1.29.4)

Thanks for any help
