### DISCUSSION TITLE
Make OpenLineage facets more compatible with spec

### DISCUSSION THREAD

**Discussion by dolfinus** [apache/airflow#40886] [Ideas]
OpenLineage v1.9.0 integration for Airflow produces following facets:
DAG run:
```yaml
job:
  facets:
    airflow:
      # AiflowJobFacet
      tasks:
      taskGroups:
      taskTree:
run:
  facets:
    airflowState:
      # AirflowStateRunFacet
      dagRunState:
      tasksState:
```

Task run:
```yaml
job:
  facets: {}
run:
  airflow:
    # AirflowRunFacet
    dag:  # dag_id, description, owner, schedule, start_date and so on
    dagRun: # run_id, run_type and so on
    task:  # task_id, queue, trigger_rule, operator properties and so on
    taskInstance:  # duration, try_number, log_url
    taskUuid:
```

There are few drawbacks with this approach:
* DAG and DAG run information is present only in task run events, but not in DAG run events #40798.
* DAG and Task information like `dag_id`, `task_id`, `description`, `owner` is present only as run facet, not job facet, although this information is not related to a particular DAG/Task run, and describes the DAG/Task itself.

While implementing #40854, I've also got issues with `"airflow"` key of all these facets. For example, adding a DAG run facet leads to sending events like:
```yaml
job:
  facets:
    airflow:
      # AiflowJobFacet
      tasks:
      taskGroups:
      taskTree:
run:
  facets:
    airflow:
      dag:
      dagRun:
      # task, taskInstance, taskUuid fields are missing
```
So OpenLineage events send by Airflow for DAG run and Task run have the facet with the same key `"airflow"`, which has quite different content. This is not very comfortable to handle on OpenLineage backend side.

My proposal is:
* Make facet schema names more descriptive:
* * `AirflowRunFacet` -> `AirflowTaskRunFacet`
* * `AirflowJobFacet` -> `AirflowDagInfoJobFacet`
* * `AirflowStateRunFacet` -> `AirflowDagStateRunFacet`
* Use specific key for each facet type, instead of generic `"airflow"` which may lead to conflicts.
* Move `dag` and `task` fields from run facet to job facet.
* Drop `taskUuid` field as it just copies `runId`, and has no meaning for Airflow

This how the result can look like:
<details>

<summary>Option 1 - nested facets</summary>

DAG run:
```yaml
job:
  facets:
    airflow_dagInfo:
      # AirflowDagInfoJobFacet
      dag:  # dag_id, description, owner, schedule, start_date and so on
      tasks:  # list of task names and UI options
      taskGroups:  # list of task groups
      taskTree:  # tree of tasks and groups
run:
  facets:
    airflow_dagRun:
      # AirflowDagRunFacet
      dagRun: # run_id, run_type and so on
    airflow_dagState:
      # AirflowDagStateRunFacet
      dagRunState:
      tasksState:
```

Task run:
```yaml
job:
  facets:
    airflow_taskInfo:
      # AirflowTaskInfoJobFacet
      task:  # task_id, queue, trigger_rule, operator properties and so on
run:
  airflow_taskRun:
    # AirflowTaskRunFacet
    taskInstance:  # duration, try_number, log_url
```
</details>

<details>

<summary>Option 2 - flat facets</summary>

DAG run:
```yaml
job:
  facets:
    airflow_dagInfo: # dag_id, description, owner, schedule, start_date and so on
    airflow_tasksDescription: # list of task names and UI options
    airflow_taskGroups:  # list of task groups
    airflow_taskTree:  # tree of tasks and groups
run:
  facets:
    airflow_dagRun: # run_id, run_type and so on
    airflow_dagState:
    airflow_taskStates:
```

Task run:
```yaml
job:
  facets:
    airflow_taskInfo: # task_id, queue, trigger_rule, operator properties and so on
run:
  airflow_taskRun: # duration, try_number, log_url
```
</details>

The concern is:
* Is that something that should be done? That could be only my point of view, but other users may be completely fine with current approach.
* What about backward compatibility?
