### DISCUSSION TITLE
Task concurrency stuck on 16

### DISCUSSION THREAD

**Discussion by andormarkus** [apache/airflow#41169] [Q&A]
Hi All,

I have enabled Keda on our Airflow on Kubernetes deployment (using celery executors).
I'm using the following env variables to increase parallelism:
```yaml
  extraEnv: |
    - name: AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG
      value: "1"
    - name: AIRFLOW__CORE__PARALLELISM
      value: "50"
    - name: AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG
      value: "50"
    - name: AIRFLOW__SCHEDULER__MAX_TIS_PER_QUERY
      value: "40"   
    - name: AIRFLOW__CELERY__WORKER_CONCURRENCY
      value: "50"   
```

However somehow my parallelism does not increases and only 16 tasks are actively running and rest of the tasks are getting into `scheduled` state instead of into the `queued` state which would trigger Keda to scale up my worker nodes.
![image](https://github.com/user-attachments/assets/2b0527b9-9cd2-4799-b86f-d92e522df2f8)

I'm using the following dag to test Worker auto scaling.
```python
from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime, timedelta
import time

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2024, 7, 30),
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}


def sleep_task():
    time.sleep(600)


with DAG(
        'parallel_sleep_dag',
        default_args=default_args,
        description='A DAG with 50 parallel sleep tasks',
        concurrency=40,
        schedule_interval=timedelta(days=1),
):
    tasks = []
    for i in range(50):
        task = PythonOperator(
            task_id=f'sleep_task_{i}',
            python_callable=sleep_task,
        )
        tasks.append(task)

    # Define task dependencies (in this case, all tasks run in parallel)
    # You can remove this line if you don't need any specific dependencies
    tasks
```

Thank you so much you help.
