### DISCUSSION TITLE
Webserver CrashLoopBackOff

### DISCUSSION THREAD

**Discussion by ChrisBobotsis** [apache/airflow#41204] [Q&A] [answered]
Hi,

I'm trying to setup the official airflow helm chart using microk8s and the webserver never seems to work.

The webserver pod keeps restarting and eventually has a status of `CrashLoopBackOff`

This is the events output from `microk8s kubectl describe pods <pod-name> -n airflow`

```
Events:
  Type     Reason   Age                     From     Message
  ----     ------   ----                    ----     -------
  Warning  BackOff  3m13s (x639 over 3h1m)  kubelet  Back-off restarting failed container webserver in pod airflow-webserver-7594cbb95b-d5zrc_airflow(be48d561-9a5a-48f9-b979-5dfab1032ad0)
```

I'm having a hard time debugging this, any help would be appreciated.

### Steps Taken

These are the exact steps I have taken:

1. Installed microk8s

`sudo snap install microk8s --classic`

`sudo ufw allow in on cni0 && sudo ufw allow out on cni0`

`sudo ufw default allow routed`

`sudo usermod -a -G microk8s $USER`
`mkdir -p ~/.kube`
`chmod 0700 ~/.kube`

`newgrp microk8s`

`microk8s enable dns dashboard storage`

2. Installed Airflow Helm Chart

```
microk8s helm3 repo add apache-airflow https://airflow.apache.org
microk8s helm3 upgrade --install airflow apache-airflow/airflow --namespace airflow --create-namespace
```

### Attempted Fixes:

1. I tried increasing the resources as follows (by altering the values.yaml file):

```
webserver:
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 4Gi
```

Then ran `microk8s helm3 upgrade --install airflow apache-airflow/airflow -n airflow -f values.yaml --debug`

This didn't fix the issue.

**Comment by ChrisBobotsis** [comment, marked as answer]
I managed to find a solution.

First you need to get the `values.yaml` file to edit it:

```
microk8s helm3 show values apache-airflow/airflow > values.yaml
```

Then in the `webserver:` section I added/edited the following:

```
webserver:
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 4Gi

  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 120
    failureThreshold: 20
    periodSeconds: 60
    scheme: HTTP

  readinessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 120
    failureThreshold: 20
    periodSeconds: 60
    scheme: HTTP

  startupProbe:
    timeoutSeconds: 20
    failureThreshold: 6
    periodSeconds: 120
    scheme: HTTP
```

Finally, to use these new changes you can run the following command:

```
microk8s helm3 upgrade --install airflow apache-airflow/airflow -n airflow -f values.yaml
```
