### DISCUSSION TITLE
Airflow webserver and scheduler do not host properly, inconclusive logs

### DISCUSSION THREAD

**Discussion by brunolnetto** [apache/airflow#41293] [General]
I would like to host airflow stack with below docker-compose. When I run command `docker compose up -d`, the container `airflow-webserver` exits without recognizable error,  and I am also unable to see the logs from another container, `airflow-scheduler`, since command run `docker logs -f airflow-scheduler` outputs nothing.

airflow-webserver
```
DB: postgresql+psycopg2://airflow:***@postgres/airflow
[2024-08-06T20:37:03.010+0000] {migration.py:207} INFO - Context impl PostgresqlImpl.
[2024-08-06T20:37:03.011+0000] {migration.py:214} INFO - Will assume transactional DDL.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> 98ae134e6fff
Initialization done
```

```
services:
  postgres:
    image: postgres:13
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: airflow-redis
    image: redis:6

  airflow-webserver:
    image: apache/airflow:2.6.0
    container_name: airflow-webserver
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: 'c427SJeq2ijIIuJwCd-kuZUbTzhRh7n5AZQDmCsBlDo='
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    command: airflow db init && airflow webserver

  airflow-scheduler:
    image: apache/airflow:2.6.0
    container_name: airflow-scheduler
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: 'c427SJeq2ijIIuJwCd-kuZUbTzhRh7n5AZQDmCsBlDo='
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    depends_on:
      - postgres
      - redis
    command: airflow db init && airflow scheduler


  airflow-worker-0:
    image: apache/airflow:2.6.0
    container_name: airflow-worker-0
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: 'c427SJeq2ijIIuJwCd-kuZUbTzhRh7n5AZQDmCsBlDo='
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    depends_on:
      - postgres
      - redis
    command: airflow celery worker

  airflow-worker-1:
    image: apache/airflow:2.6.0
    container_name: airflow-worker-1
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: 'c427SJeq2ijIIuJwCd-kuZUbTzhRh7n5AZQDmCsBlDo='
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    depends_on:
      - postgres
      - redis
    command: airflow celery worker

  airflow-worker-2:
    image: apache/airflow:2.6.0
    container_name: airflow-worker-2
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: 'c427SJeq2ijIIuJwCd-kuZUbTzhRh7n5AZQDmCsBlDo='
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    depends_on:
      - postgres
      - redis
    command: airflow celery worker

  airflow-worker-3:
    image: apache/airflow:2.6.0
    container_name: airflow-worker-3
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: 'c427SJeq2ijIIuJwCd-kuZUbTzhRh7n5AZQDmCsBlDo='
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    depends_on:
      - postgres
      - redis
    command: airflow celery worker

  airflow-worker-4:
    image: apache/airflow:2.6.0
    container_name: airflow-worker-4
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: 'c427SJeq2ijIIuJwCd-kuZUbTzhRh7n5AZQDmCsBlDo='
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    depends_on:
      - postgres
      - redis
    command: airflow celery worker


volumes:
  postgres_data:
```
