### DISCUSSION TITLE
Permission Denied Error on InitContainer Using AWS CLI in Airflow Scheduler Pod on EKS v1.30 (ISRA)

### DISCUSSION THREAD

**Discussion by Thamban777** [apache/airflow#41917] [Q&A] [answered]
```
Hi Team,
Am getting Permission denied: '/.aws' on InitContainer.  I have followed the Documentation.
[Ref](https://github.com/apache/airflow/blob/main/docs/apache-airflow-providers-amazon/logging/s3-task-handler.rst)

EKS Version: 1.30
Chart version: 1.13.1

my values.yaml:

scheduler:
  enabled: true
  # Create ServiceAccount
  serviceAccount:
    # default value is true
    # ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
    automountServiceAccountToken: true
    # Specifies whether a ServiceAccount should be created
    create: false
    # The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the release name
    name: test20

    # Annotations to add to scheduler kubernetes service account.
 #   annotations:
#      eks.amazonaws.com/role-arn: arn:aws:iam::111222333444:role/eks-s3-access-role1


  resources: {}

  extraContainers:
    - name: sync-dags
      image: amazon/aws-cli:2.1.34
      command: ["/bin/bash", "-c", "--"]
      args:
        - >
          while true; do
            aws s3 sync --exact-timestamps --delete 's3://test-s3/apps/airflow/dags/' '/opt/airflow/dags';
            sleep 300;
          done;
      volumeMounts:
        - mountPath: /opt/airflow/dags
          name: dags

  extraInitContainers:
    - name: copy-dags
      image: amazon/aws-cli:2.1.34
      args:
        - s3
        - cp
        - --recursive
        - s3://test-s3/apps/airflow/dags/
        - /opt/airflow/dags
      env:
        - name: AWS_REGION
          value: us-east-2
        - name: AWS_DEFAULT_REGION
          value: us-east-2

      volumeMounts:
        - mountPath: /opt/airflow/dags
          name: dags

  extraVolumes: 
    - name: airflow-home
      emptyDir: {}
  extraVolumeMounts: []

```

**Comment by rraghunathan-exelixis** [comment]
@Thamban777 have you fixed this error? If yes, how did you solve it

**Comment by Thamban777** [comment, marked as answer]
@rraghunathan-exelixis 
I fixed this issue by adding securityContext to the extraInitContainers. Here's the working configuration that solved the problem for me.

```
extraInitContainers:
  - name: copy-dags
    image: amazon/aws-cli:2.1.34
    env:
      - name: S3_BUCKET_NAME
        valueFrom:
          configMapKeyRef:
            name: aws-config
            key: s3BucketName
    command: ["/bin/bash", "-c", "--"]
    args:
      - >
        aws s3 cp --recursive $S3_BUCKET_NAME/apps/airflow/dags/ /opt/airflow/dags;
        chown -R 50000:0 /opt/airflow/dags;
    volumeMounts:
      - mountPath: /opt/airflow/dags
        name: dags
    securityContext:
      runAsUser: 0
      runAsGroup: 0
```
The key fix was adding this part

```
securityContext:
  runAsUser: 0
  runAsGroup: 0
```

If this doesn't fix it for you, happy to share my full values.yaml. Just ping me.
