### DISCUSSION TITLE
Enabling Ingress leads to 502 Bad Gateway

### DISCUSSION THREAD

**Discussion by necromancerthedark** [apache/airflow#41989] [Q&A] [answered]
Airflow version: 2.9.3
Helm chart version: 1.15.0

I have enabled ingress in airflow using the `ingress` block present in helm chart `values.yaml`, and made following changes:

```
ingress:
  # Enable all ingress resources (deprecated - use ingress.web.enabled and ingress.flower.enabled)
  enabled: ~

  # Configs for the Ingress of the web Service
  web:
    # Enable web ingress resource
    enabled: true

    # Annotations for the web Ingress
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ip-address-type: dualstack
      alb.ingress.kubernetes.io/certificate-arn: some-cert
      alb.ingress.kubernetes.io/tags: some-tag
      alb.ingress.kubernetes.io/group.name: some-group
      alb.ingress.kubernetes.io/healthcheck-path: /health

    # The path for the web Ingress
    path: "/"

    # The pathType for the above path (used only with Kubernetes v1.19 and above)
    pathType: "Prefix"

    # The hostname for the web Ingress (Deprecated - renamed to `ingress.web.hosts`)
    host: ""

    # The hostnames or hosts configuration for the web Ingress
    hosts:
      - airflow.company.com
    #   # The hostname for the web Ingress (can be templated)
    # - name: ""
    #   # configs for web Ingress TLS
    #   tls:
    #     # Enable TLS termination for the web Ingress
    #     enabled: false
    #     # the name of a pre-created Secret containing a TLS private key and certificate
    #     secretName: ""

    # The Ingress Class for the web Ingress (used only with Kubernetes v1.19 and above)
    ingressClassName: "alb"

    # configs for web Ingress TLS (Deprecated - renamed to `ingress.web.hosts[*].tls`)
    tls:
      # Enable TLS termination for the web Ingress
      enabled: false
      # the name of a pre-created Secret containing a TLS private key and certificate
      secretName: ""

    # HTTP paths to add to the web Ingress before the default path
    precedingPaths: []

    # Http paths to add to the web Ingress after the default path
    succeedingPaths: []
```

and I have added the `base_url` to be same as our `hosts`

```
  webserver:
    enable_proxy_fix: 'True'
    base_url: 'https://airflow.company.com'
    # For Airflow 1.10
    rbac: 'True'
```

- After applying the helm chart, everything is working fine, we are able to access UI via port-forwarding on the `svc` and the `pod` as well but whenever we try to access the `https://airflow.company.com` (after making a record in route53) we are getting `502 bad gateway` . We are using AWS ALB as load balancer. 
- We are also not able to set gunicorn to work on IPv6, we are trying to set it because our liveness and readiness probes are failing. We are using IPv6 on our EKS cluster.
