### DISCUSSION TITLE
Got Error when add root path 'AIRFLOW__WEBSERVER__BASE_URL' enviroment  in the airflow

### DISCUSSION THREAD

**Discussion by PatricYan** [apache/airflow#43210] [General]
Hi, 
# Action
- follow https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html
- dowload https://airflow.apache.org/docs/apache-airflow/2.10.2/docker-compose.yaml
- run the command, all is right

# Question
- add a new **environment** '**AIRFLOW__WEBSERVER__BASE_URL**' in the '**airflow-webserver**' field, like below
- got error 'airflow-webserver-1  | ERROR: You need to initialize the database. Please run `airflow db init`. Make sure the command is run using Airflow version 2.8.3.'
- I am confused about this. How can I configure it correctly?

```
airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

    environment:
      AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8080/airflow/v1


    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/airflow/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

```
