### DISCUSSION TITLE
Airflow ci/cd pipeline to rebuild airflow

### DISCUSSION THREAD

**Discussion by V4kodin** [apache/airflow#47149] [Q&A]
I configured airflow pipeline, but have question about pipeline to restart airflow properly.

So this part of gitlab ci/cd pipeline should restart airflow after core changes in airflow configuration:
```
rebuild_project:
  stage: rebuild
  script:
    - ssh ${DEPLOY_USER}@${DEPLOY_SERVER} "cd ${DEPLOY_PATH} && docker compose down && docker compose build --no-cache && docker compose up -d"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - requirements.txt
        - start.sh
        - docker-compose.yaml
        - Dockerfile
        - plugins/**/*
        - config/**/* 
```
But I had issue with `docker compose down`, once I used, it I got endless shutting down on worker, So I was forced to stop docker service and manually remove worker container. 

Is there any proper way to rebuild Airflow via pipeline? Or I just should always do it manually? 
It would be nice if pipeline would have an opportunity to pause all dags, when wait until all dags completed and restart after that (maybe unpause all pause dags after start).

**Comment by andresitorusz** [comment]
If you want to pause DAGs in your CI/CD pipeline, you can use this [CLI](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#pause).

It will be something like the following. You can use `docker compose up --build -d` instead of separating the build and restart command.
```yaml
rebuild_project:
  stage: rebuild
  script:
    - ssh ${DEPLOY_USER}@${DEPLOY_SERVER} << 'EOF'
      cd ${DEPLOY_PATH}

      # Pause all DAGs
      docker compose exec airflow-webserver airflow dags pause <regex-for-your-dags> --treat-dag-id-as-regex

      # Wait until all tasks are finished
      while docker compose exec airflow-webserver airflow tasks list_instances | grep -q running; do
        echo "Waiting for running tasks to finish..."
        sleep 10
      done

      # Stop Airflow cleanly
      docker compose down

      # Rebuild and restart
      docker compose up --build -d

      # Unpause previously paused DAGs
      docker compose exec airflow-webserver airflow dags unpause <regex-for-your-dags> --treat-dag-id-as-regex
    EOF
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - requirements.txt
        - start.sh
        - docker-compose.yaml
        - Dockerfile
        - plugins/**/*
        - config/**/*
```
