### DISCUSSION TITLE
Syncing with ArgoCD using Helm deletes and recreates secrets.

### DISCUSSION THREAD

**Discussion by mqsoh** [apache/airflow#47151] [Q&A]
Every time I sync the Airflow App in ArgoCD the secrets are deleted and recreated. I've configured the chart per [the guidelines](https://airflow.apache.org/docs/helm-chart/stable/index.html#installing-the-chart-with-argo-cd-flux-rancher-or-terraform):

```
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false
          jobAnnotations:
            "argocd.argoproj.io/hook": Sync
        useStandardNaming: true
```

There's still a pre-sync hook for the `airflow-broker-url` and `airflow-fernet-key` secrets. I tried creating my own, differently named secrets (managed outside ArgoCD) but I'm not able to configure the various components to use them. I tried this:

```
        fernetSecretName: fernet-key
        broker:
          brokerUrlSecretName: broker-url
        redis:
          passwordSecretName: redis-password
```

But everything is still using the secrets prefixed with `airflow-`. This is a problem for me because the Airflow Variables are encrypted and when the fernet key is recreated with a new value they break. Is anyone able to point me in a direction?
