### DISCUSSION TITLE
Custom secrets backend issue

### DISCUSSION THREAD

**Discussion by Yomna-Sabah** [apache/airflow#49211] [General]
I'm trying to use a custom secrets backend in Airflow 2.6.3, but I'm encountering a `ModuleNotFoundError`. I'd appreciate any help in resolving this.
**Problem**

- Airflow fails to load my custom secrets backend with the following error:
`ModuleNotFoundError: No module named 'plugins'`

**My Setup**

- **_Airflow version:_** 2.6.3
- **_Helm Chart:_** airflow-helm
- **_Chart Version:_** 8.8.0
- **_Helm values:_**
```
airflow:
  config:
    AIRFLOW__SECRETS__BACKEND: "plugins.oracle_vault_secrets.OracleVaultSecretsBackend"
    AIRFLOW__CORE__PLUGINS_FOLDER: "/opt/airflow/dags/repo/dags/plugins"
```

- **_Directory structure (inside container):_**
```
/opt/airflow/dags/repo/dags/
├── __init__.py
└── plugins/
    ├── __init__.py
    └── oracle_vault_secrets.py
```

**Confirmations**

- The file `oracle_vault_secrets.py` exists at the specified location.
- I've tried several paths in `AIRFLOW__SECRETS__BACKEND`:
```
oracle_vault_secrets.OracleVaultSecretsBackend
plugins.oracle_vault_secrets.OracleVaultSecretsBackend
airflow.plugins.oracle_vault_secrets.OracleVaultSecretsBackend
opt.airflow.dags.repo.dags.plugins.oracle_vault_secrets.OracleVaultSecretsBackend
```
