### ISSUE TITLE
Cannot connect to external PostgreSQL database

### ISSUE THREAD

**Issue by jordi-crespo** [apache/airflow#11418]
I am deploying airflow in Kubernetes with this chart: https://github.com/apache/airflow/tree/master/chart and I am using:

 - AKS Kubernetes version: 1.16.13
- PostgreSQL hosted in Azure Database for PostgreSQL version: 10

If I use the PostgreSQL database sub chart it works perfectly.

I modify the values.yml to connect to the external PostgreSQL database:

```yml
# Airflow database config
data:
  # If secret names are provided, use those secrets
  metadataSecretName: ~
  resultBackendSecretName: ~

  # Otherwise pass connection values in
  metadataConnection:
    user: <Myuser>
    pass: <Mypass>
    host: <server>
    port: 5432
    db: airflow
    sslmode: disable
  resultBackendConnection:
    user: <Myuser>
    pass: <Mypass>
    host: <server>
    port: 5432
    db: airflow
    sslmode: disable
```
When I deploy it the scheduler and webserver pods fail. I have checked the connection string and using it manually works fine
