### ISSUE TITLE
Use named volumes in breeze

### ISSUE THREAD

**Issue by turbaszek** [apache/airflow#11625]
**Description**

Currently, breeze uses unnamed volumes for persisting data (mysql redis, postgres). It would be nice to have named volumes so users can easily delete them.

Example for redis:
```yaml
version: "2.2"
services:
  redis:
    image: redis:5.0.1
    volumes:
      - /dev/urandom:/dev/random   # Required to get non-blocking entropy source
      - breeze-redis:/data
  airflow:
    environment:
      - INTEGRATION_REDIS=true
    depends_on:
      - redis

volumes:
  # named volumes can be managed easier using docker-compose
  breeze-redis:
```

**Use case / motivation**

Easier maintenance of docker volumes.

**Related Issues**

N/A
