### ISSUE TITLE
Docs: Integration documentation gets cut off

### ISSUE THREAD

**Issue by kennethstoltz-db** [apache/airflow#11967]
There are many wide tables in the documentation, for example here:
https://airflow.readthedocs.io/en/latest/operators-and-hooks-ref.html#id19

On a very wide browser the width is still fixed. It is not obvious that the table is cut off and I was very confused that I never found the operator reference documentation I was looking for.
<img width="1801" alt="Screenshot 2020-10-30 at 13 36 57" src="https://user-images.githubusercontent.com/72079612/97705839-fdd59300-1ab4-11eb-817f-62822d319474.png">

I would suggest either:
* refactoring the table into many separate tables either by provider or by column
* reformatting the tables into nested lists
* truncating the long token names that push the table wide
* choosing a theme that is responsive

I'm new to the project and docs so I don't want to force my formatting decisions, but I'm happy to make a PR if someone can suggest what to do.

**Comment by mik-laj** [comment]
> reformatting the tables into nested lists

Can you prepare a little POC that would show what it would look like?

**Comment by VBhojawala** [comment]
![Before](https://user-images.githubusercontent.com/11897651/98566937-61da3180-22d5-11eb-9ed8-426f145d4539.png)


In my humble opinion this issue can be fixed with following css changes :+1: 



``` css
/* override the maximum width restriction for large screen */
.wy-nav-content {
   max-width: none;
} 

/* override table width restrictions and allow multiple line td  */
@media screen and (min-width: 720px) {
   .wy-table-responsive table td {
      white-space: normal !important;
   }
}
```
Screen shoot of 1080p screen web browser after applying above changes

![After](https://user-images.githubusercontent.com/11897651/98566965-69013f80-22d5-11eb-896a-92b06e94acd7.png)

Same can be tested inside developer option of browser 
On firefox
1. Press F12 on documentation site page
2. Go to style editor
3. Choose css and add above code and test the changes.


![Firefox](https://user-images.githubusercontent.com/11897651/98567753-520f1d00-22d6-11eb-8a57-1bb0742b557d.png)
