### ISSUE TITLE
keda scaledobject not created even though keda enabled in helm config

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#13181]
In brand new cluster using k3d locally, I first installed keda:
```bash
helm install keda \
    --namespace keda kedacore/keda \
    --version "v1.5.0"
```

Next, I installed airflow using this config:

```yaml
executor: CeleryExecutor
defaultAirflowTag: 2.0.0-python3.7
airflowVersion: 2.0.0
workers:
  keda:
    enabled: true 
  persistence:
    enabled: false
pgbouncer:
  enabled: true
```

I think this should create a scaled object `airflow-worker`.  

But it does not.

@turbaszek and @dimberman you may have insight ...
