### ISSUE TITLE
Airflow Google oAuth failing with Invalid response from google on 1.10.12-python3.6

### ISSUE THREAD

**Issue by mdcsaenz** [apache/airflow#13573]
Greetings, I am currently using dockerfile 1.10.12-python3.6 from ya'll. With the helmchart https://github.com/airflow-helm/charts/tree/main/charts/airflow. 

I currently get this error
![Screen Shot 2021-01-08 at 12 12 18 PM](https://user-images.githubusercontent.com/8727557/104049565-c8cb7800-51aa-11eb-89d5-7ba850d681aa.png)

My setup is this for my webserver config
```
 from flask_appbuilder.security.manager import AUTH_OAUTH
    AUTH_TYPE = AUTH_OAUTH
    AUTH_USER_REGISTRATION = False
    #AUTH_USER_REGISTRATION_ROLE = "Admin"
    AUTH_ROLE_ADMIN = 'Admin'
    OAUTH_PROVIDERS = [{
        'name':'google',
        'token_key':'access_token',
        'icon':'fa-google',
        'remote_app': {
            'base_url':'https://www.googleapis.com/oauth2/v2/',
            'request_token_params':{
                'scope': 'email profile'
            },  
            'access_token_url':'https://oauth2.googleapis.com/token',
            'authorize_url':'https://accounts.google.com/o/oauth2/auth',
            'request_token_url': None,
            'consumer_key': '<client_id_from_google>',
            'consumer_secret': '<client_secret_from_google>,
```

My config for airflow is:
```
  config:
      ## Security
      AIRFLOW__CORE__SECURE_MODE: "True"
      AIRFLOW__WEBSERVER__AUTH_BACKEND: "airflow.contrib.auth.backends.google_auth"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
      AIRFLOW__WEBSERVER__RBAC: "True"
      AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
      AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "False"
      ## DAGS
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "40"
      ## GCP Remote Logging
      AIRFLOW__CORE__REMOTE_LOGGING: "True"
      AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "gs://airflow-logs"
      AIRFLOW__CORE__REMOTE_LOG_CONN_ID: "google_cloud_airflow"
      ## Disable noisy "Handling signal: ttou" Gunicorn log messages
      GUNICORN_CMD_ARGS: "--log-level WARNING"
      ## GOOGLE TEST
      AIRFLOW__GOOGLE__OAUTH_CALLBACK_ROUTE: "/oauth2callback"
      AIRFLOW__GOOGLE__DOMAIN: "mycompany.com"
```

This issue was also mentioned here: https://stackoverflow.com/questions/64654884/airflow-google-oauth-failing
I followed this: https://airflow.apache.org/docs/apache-airflow/1.10.12/security.html  to do my setup.
