### ISSUE TITLE
Docs: Segment `external-doc-url` links to Dingtalk API

### ISSUE THREAD

**Issue by griffincosgrove** [apache/airflow#13634]
On file `master:airflow/providers/segment/provider.yaml`

```
integrations:
  - integration-name: Segment
    external-doc-url: https://oapi.dingtalk.com
    tags: [service]
```

That is the API for Dingtalk, which is an unrelated Alibaba owned service. The docs for Twilio Segment can be found at [(https://segment.com/docs/)](url)
I am not sure if this issue is the result of an issue somewhere else, but I identified this will adding integration logos.

Not sure any of this is relevant because but it appears I must add this information
**Apache Airflow version**: 2.0.0

**Environment**: GNU/Linux

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Ubuntu
- **Kernel** (e.g. `uname -a`): 20.4
- **Install tools**: PIP

**What happened**: `external-doc-url` is mapped to dingtalk API

**What you expected to happen**: `external-doc-url` to be mapped to Segment docs

**How to reproduce it**: Observe code at `master:airflow/providers/segment/provider.yaml`

```
integrations:
  - integration-name: Segment
    external-doc-url: https://oapi.dingtalk.com
    tags: [service]
```

New to Apache Airflow, but please bear with me 😄
