### ISSUE TITLE
SQL Syntax errors on startup

### ISSUE THREAD

**Issue by msardana94** [apache/airflow#13679]
**Apache Airflow version**: 2.0.0

**What happened**:

While investigating issues relating to task getting stuck, I saw this sql error in postgres logs. I am not entirely sure of what it impacts but I thought of letting you know.

```
ERROR:  column "connection.password" must appear in the GROUP BY clause or be used in an aggregate function at character 8
STATEMENT:  SELECT connection.password AS connection_password, connection.extra AS connection_extra, connection.id AS connection_id, connection.conn_id AS connection_conn_id, connection.conn_type AS connection_conn_type, connection.description AS connection_description, connection.host AS connection_host, connection.schema AS connection_schema, connection.login AS connection_login, connection.port AS connection_port, connection.is_encrypted AS connection_is_encrypted, connection.is_extra_encrypted AS connection_is_extra_encrypted, count(connection.conn_id) AS count_1 
        FROM connection GROUP BY connection.conn_id 
        HAVING count(connection.conn_id) > 1
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:  SELECT connection.password AS connection_password, connection.extra AS connection_extra, connection.id AS connection_id, connection.conn_id AS connection_conn_id, connection.conn_type AS connection_conn_type, connection.description AS connection_description, connection.host AS connection_host, connection.schema AS connection_schema, connection.login AS connection_login, connection.port AS connection_port, connection.is_encrypted AS connection_is_encrypted, connection.is_extra_encrypted AS connection_is_extra_encrypted 
        FROM connection 
        WHERE connection.conn_type IS NULL
```

**How to reproduce it**:
1. Run `docker-compose run initdb`
2. Run `docker-compose run upgradedb`

<details> <summary> Here's my docker-compose </summary>

```
version: "3.2"
networks:
    airflow:

services:
    postgres:
        container_name: af_postgres
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_DB=airflow
            - POSTGRES_PASSWORD=airflow
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        command: >
            postgres
            -c listen_addresses=*
            -c logging_collector=on
            -c log_destination=stderr
        networks:
            - airflow
    initdb:
        container_name: af_initdb
        image: docker.io/apache/airflow:2.0.0-python3.7
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        depends_on:
            - postgres
        entrypoint: /bin/bash
        command: -c "airflow db init"
        networks:
            - airflow
    upgradedb:
        container_name: af_upgradedb
        image: docker.io/apache/airflow:2.0.0-python3.7
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        depends_on:
            - postgres
        entrypoint: /bin/bash
        command: -c "airflow db upgrade"
        networks:
            - airflow
 ```
</details>

**Anything else we need to know**:

Upon looking the code, I believe having `Connection.conn_id` [here](https://github.com/apache/airflow/blob/ab5f770bfcd8c690cbe4d0825896325aca0beeca/airflow/utils/db.py#L613) will resolve the sql syntax error.

**Comment by kaxil** [comment]
What version of Postgres do you use?

**Comment by msardana94** [comment]
```
airflow=# select version();
                                                               version
--------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.6.20 on x86_64-pc-linux-gnu (Debian 9.6.20-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
(1 row)
```
Using the `postgres:9.6` docker image.

**Comment by mik-laj** [comment]
@msardana94  are you willing to submit a PR? Please note that the behavior may be different depending on the migration state. see: https://github.com/apache/airflow/blob/master/airflow/migrations/versions/8d48763f6d53_add_unique_constraint_to_conn_id.py

**Comment by msardana94** [comment]
Sure I can give it a try. I will take a look at contribution quick start since this will be my first time and will reach out over slack with any questions.

> Please note that the behavior may be different depending on the migration state. see: https://github.com/apache/airflow/blob/master/airflow/migrations/versions/8d48763f6d53_add_unique_constraint_to_conn_id.py

I will take a look at the code to see what that means for this bug.

**Comment by msardana94** [comment]
> @msardana94 are you willing to submit a PR? Please note that the behavior may be different depending on the migration state. see: https://github.com/apache/airflow/blob/master/airflow/migrations/versions/8d48763f6d53_add_unique_constraint_to_conn_id.py

@mik-laj can you elaborate on what you meant here? Isn't it safe to say that as long as sql syntax is accurate, it will check for conn duplicates appropriately?

Also, any thoughts on how to test this issue after adding a bug fix? I can take a look at the logs after running `airflow upgrade db` but didn't see any unit tests for this in `tests_db.py`.

**Comment by mik-laj** [comment]
> can you elaborate on what you meant here? Isn't it safe to say that as long as sql syntax is accurate, it will check for conn duplicates appropriately?

We do not write SQL queries, but use an ORM that generates queries based on the model stored in the code. The model is identical to the database schema in most cases, so everything works fine. The problem arises when the model is different from the database schema because you have not done all the migrations. Then ORM can generate SQL queries that conform to the new database schema, but does not work properly with the older versions.  This is just my guess and I am not sure if this is the cause of these problems.

`airflow upgrade db` works fine if there are no entries in the database. If you would like to test it well, you should migrate the database version compatible with Airflow 1.10. Add a few entries, and then run database migrations to see if the problem was detected.

**Comment by msardana94** [comment]
> We do not write SQL queries, but use an ORM that generates queries based on the model stored in the code. The model is identical to the database schema in most cases, so everything works fine. The problem arises when the model is different from the database schema because you have not done all the migrations. Then ORM can generate SQL queries that conform to the new database schema, but does not work properly with the older versions. This is just my guess and I am not sure if this is the cause of these problems.

Yes I get that. I should have specified in the PR description that the issue is with the ORM code itself which generates an invalid SQL. I don't believe the error itself has anything to do with version of database schema.

> `airflow upgrade db` works fine if there are no entries in the database. If you would like to test it well, you should migrate the database version compatible with Airflow 1.10. Add a few entries, and then run database migrations to see if the problem was detected.

I will give that a try and see how that goes.

**Comment by kaxil** [comment]
I was not able to reproduce the issue. Your docker-compose file contains issues like duplicate contain name: `af_initdb` and it contains no scheduler, and does not create an admin account. And I am not sure why you had initdb and upgradedb both

```yaml
version: "3.2"
networks:
    airflow:
        driver: bridge

volumes:
  postgres_data:
    driver: local

services:
    postgres:
        container_name: af_postgres
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_DB=airflow
            - POSTGRES_PASSWORD=airflow
        volumes:
            - postgres_data:/var/lib/postgresql/data
        command: >
            postgres
            -c listen_addresses=*
            -c logging_collector=on
            -c log_destination=stderr
        networks:
            - airflow
    webserver:
        container_name: af_webserver
        image: docker.io/apache/airflow:2.0.0-python3.7
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        ports:
            - 80:8080
        depends_on:
            - postgres
        command: bash -c 'airflow db upgrade && airflow users  create --role Admin --username admin --email admin --firstname admin --lastname admin --password admin && airflow webserver'
        networks:
            - airflow
```
