### ISSUE TITLE
Default user is not working with AUTH_LDAP - Airflow 2.0

### ISSUE THREAD

**Issue by rchojn** [apache/airflow#13818]
**Apache Airflow version**: 2.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Using LDAP  and airflow 2.0 Admin is not working
```
defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user
    password: admin
```

**What you expected to happen**:
Manually created users (or default users) are able to log in.

**How to reproduce it**:

**Anything else we need to know**:
