### ISSUE TITLE
KubernetesPodOperator raises exception when pod_template_file contains multiple objects

### ISSUE THREAD

**Issue by everglory99** [apache/airflow#14307]
In Airflow 2.0.1, we are trying to use `pod_template_file` in `KubernetesPodOperator`. The `pod_template_file` contains several sections specifying `ConfigMap`, `Service` and `Deployment` etc.. However, I am seeing this error from Airflow
```
raise ComposerError("expected a single document in the stream",
yaml.composer.ComposerError: expected a single document in the stream
but found another document
```

**Comment by dimberman** [comment]
@everglory99 can you please post the YAML file you're using?

**Comment by everglory99** [comment]
The YAML file is generated by a helm chart our team developed by running `helm template`. The YAML file looks like
```
---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: dev-configmap

data:
  SOME_KEY: "SOME_VALUE"
---
apiVersion: v1
kind: Service
metadata:
  name: dev-engine
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: engine
    app.kubernetes.io/instance: dev
---
SOME MORE OBJECTS...
```
