### ISSUE TITLE
"dag_id could not be found" when running airflow on KubernetesExecutor on Airflow 1.10.14

### ISSUE THREAD

**Issue by sakaia** [apache/airflow#14409]
**Apache Airflow version**:
1.10.14 with helm

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.18.5

**Environment**:

- **Cloud provider or hardware configuration**: local
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS
- **Kernel** (e.g. `uname -a`): 4.15.0-128-generic
- **Install tools**: helm for airflow, kubeadm for kubernetes 
- **Others**:

**What happened**:

Failed execution, even in tutorial sample.

**What you expected to happen**:

tutorial.py runs successfully

**How to reproduce it**:

```
###################################
# Airflow - Common Configs
###################################
airflow:
  image:
    tag: 1.10.14-python3.6
  ## the airflow executor type to use
  ##
  executor: "KubernetesExecutor"
  ## environment variables for the web/scheduler/worker Pods (for airflow configs)
  ##
  config:
    AIRFLOW__CORE__DONOT_PICKLE: "True"
    AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "False"
    AIRFLOW__KUBERNETES__DAGS_VOLUME_SUBPATH: "repo/"
    AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: "airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
    AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.14-python3.8"
    AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"
    AIRFLOW__KUBERNETES__LOGS_VOLUME_CLAIM: "airflow-logs"

workers:
  enabled: false # true is required for Celery executors

redis:
  enabled: false # true is required for Celery executors

###################################
# Airflow - WebUI Configs
###################################
web:
  ## configs for the Service of the web Pods
  ##
  service:
    type: NodePort

###################################
# Airflow - Logs Configs
###################################
# Expand size (default 1Gi)
logs:
  persistence:
    enabled: true
    storageClass: basic-csi
    size: 4Gi

###################################
# Airflow - DAGs Configs
###################################
dags:
  git:
    #ssh://git@example.com:22/REPOSITORY.git
    url: git@example.com:ai_soft/sakaiatest.git
    ref: master
    secret: airflow-git-keys
    privateKeyName: id_rsa
    repoHost: example.com
    repoPort: 22
    sshKeyscan: true

    gitSync:
      enabled: true
      refreshTime: 60
```

**Anything else we need to know**:

Error message is same as following issue (on Airflow 2.0.0). but call trace is different

https://github.com/apache/airflow/issues/13680

```
[2021-02-24 03:36:27,859] {__init__.py:50} INFO - Using executor LocalExecutor
[2021-02-24 03:36:27,860] {dagbag.py:417} INFO - Filling up the DagBag from /opt/airflow/dags/tutorial.py
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 37, in <module>
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 81, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/bin/cli.py", line 614, in run
    dag = get_dag(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/bin/cli.py", line 166, in get_dag
    raise AirflowException(
airflow.exceptions.AirflowException: dag_id could not be found: tutorial. Either the dag did not exist or it failed to parse.
```
