### ISSUE TITLE
Static file not being loaded in web server in docker-compose

### ISSUE THREAD

**Issue by akihiro-inui** [apache/airflow#14991]
Apache Airflow version: apache/airflow:master-python3.8

Environment:

Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release): Mac OS 10.16.5
Kernel (e.g. uname -a): Darwin Kernel Version 19.6.0

Browser:
Google Chrome Version 89.0.4389.90

What happened:
I am having an issue with running `apache/airflow:master-python3.8` with docker-compose.
The log of the webserver says` Please make sure to build the frontend in static/ directory and restart the server` when it is running. Due to static files not being loaded, login and dags are not working.

What you expected to happen:
static files being loaded correctly.

How to reproduce it:
My docker-compose is based on the official example.
https://github.com/apache/airflow/blob/master/docs/apache-airflow/start/docker-compose.yaml

Anything else we need to know:
It used to work until 2 days ago when the new docker image was released. Login prompt looks like this.
![Screenshot 2021-03-24 at 21 54 16](https://user-images.githubusercontent.com/28846850/112381987-90d4cb00-8ceb-11eb-9324-461c6eae7b01.png)

**Comment by uranusjr** [comment]
Can confirm, this is also a problem when running `breeze start-airflow` on a freshly built image.

**Comment by potiuk** [comment]
I don't recall changing anything in the Dockerfile . I will try to take a look tomorrow but maybe it is something connected to the new UI changes @bbovenzi ?

**Comment by akihiro-inui** [comment]
Thank you very much. I am posting my docker-compose.yml to replicate the issue.
```
version: '3'
x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:master-python3.8}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres/airflow"
    AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://airflow:airflow@postgres/airflow"
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  volumes:
    - ./src:/opt/airflow/src
    - ./src/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - postgres
    restart: always

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    depends_on:
      - postgres
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}

  flower:
    <<: *airflow-common
    command: celery flower
    ports:
      - 5555:5555
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always


volumes:
  postgres-db-volume:

```
