### ISSUE TITLE
Accessing log when using KEDA

### ISSUE THREAD

**Issue by zorzigio** [apache/airflow#15571]
**Apache Airflow version**: 2.0.2

**Kubernetes version (if you are using kubernetes)**:
- Client Version: v1.17.4
- Server Version: v1.18.14

**Environment**:

- **Cloud provider or hardware configuration**: Azure

**What happened**:

Using KEDA, the logs are not accessible.

Trying to access the logs on a task gives an error like the following:

```bash
*** Log file does not exist: /opt/airflow/logs/tutorial_taskflow_api_etl/load/2021-04-28T09:58:43.050614+00:00/1.log
*** Fetching from: http://airflow2-worker-0.airflow2-worker.airflow2.svc.cluster.local:8793/log/tutorial_taskflow_api_etl/load/2021-04-28T09:58:43.050614+00:00/1.log
*** Failed to fetch log file from worker. HTTPConnectionPool(host='airflow2-worker-0.airflow2-worker.airflow2.svc.cluster.local', port=8793): Max retries exceeded with url: /log/tutorial_taskflow_api_etl/load/2021-04-28T09:58:43.050614+00:00/1.log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f761829eda0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

Accessing the logs when the worker is executing a task (hence running) works as expected.

**What you expected to happen**:

To be able to access the logs even when the worker is not running

**How to reproduce it**:

Install Airflow using the Helm chart with the values

```yaml
executor: "CeleryExecutor"
workers:
  keda:
    enabled: true
dags:
  persistence:
    enabled: true
    existingClaim: dags
```

where the persistent volume claim for the dags in 

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dags
  labels:
    tier: airflow
    release: airflow2
    heritage: "Helm"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "azurefile"
```
