### ISSUE TITLE
worker ip missing in webserver logs

### ISSUE THREAD

**Issue by partheshparekh** [apache/airflow#15796]
**Apache Airflow version**: 2.0.1

**Environment**:

- **Helm Chart**: https://github.com/apache/airflow/tree/master/chart
- **Install tools**: helm3

**What happened**:
  worker ip address is missing
```
*** Log file does not exist: /opt/airflow/logs/example-task/snapshot/2021-05-12T12:00:46.658485+00:00/1.log
*** Fetching from: http://:8793/log/example-task/snapshot/2021-05-12T12:00:46.658485+00:00/1.log
*** Failed to fetch log file from worker. Invalid URL 'http://:8793/log/example-task/snapshot/2021-05-12T12:00:46.658485+00:00/1.log': No host supplied
```

**Config**:
```
  core:
    load_examples: 'False'
    hostname_callable: 'airflow.utils.net:get_host_ip_address'
  webserver:
    workers: '4'
    enable_proxy_fix: 'True'
    base_url: 'http://localhost:8080'
    authenticate: 'True'
    log_fetch_timeout_sec: '60'
  cli:
    endpoint_url: 'http://localhost:8080'
```
