### ISSUE TITLE
Chart: Extra mounts with DAG persistence and gitsync

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#15900]
**What happened**:

When you have `dag.persistence` enabled and a `dag.gitSync.sshKeySecret` set, the gitSync container isn't added to the pod_template_file for k8s workers, as expected. However, `volumes` for it still are and maybe worse, the ssh key is mounted into the Airflow worker.

**What you expected to happen**:

When using `dag.persistence` and a `dag.gitSync.sshKeySecret`, nothing gitsync related is added to the k8s workers.

**How to reproduce it**:

Deploy the helm chart with `dag.persistence` enabled and a `dag.gitSync.sshKeySecret`.

e.g:
```
dags:
  persistence:
    enabled: true
  gitSync:
    enabled: true
    repo: {some_repo}
    sshKeySecret: my-gitsync-secret
extraSecrets:
  'my-gitsync-secret':
    data: |
      gitSshKey: {base_64_private_key}
```

**Anything else we need to know**:

After a quick look at CeleryExecutor workers, I don't think they are impacted, but worth double checking.
