### ISSUE TITLE
Airflow UI displays \n instead of line break

### ISSUE THREAD

**Issue by DylanCuure** [apache/airflow#15985]
**Apache Airflow version**: v2.0.1

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): v1.19.7

**What happened**:

Using remote logging, logs are correctly sent to GCS with the right format :
![image](https://user-images.githubusercontent.com/83287186/119143548-01783980-ba48-11eb-91ca-217e5a328e54.png)

But are displayed in airflow UI with no line break : 
![image](https://user-images.githubusercontent.com/83287186/119142499-de995580-ba46-11eb-8b37-2aad7dc60542.png)

**What you expected to happen**:

Line breaks instead of \n

**How to reproduce it**:

Airflow is installed using official helm chart
```YAML
config:
  logging:
    remote_logging: 'True'
    colored_console_log: 'False'
    remote_log_conn_id: google_cloud_default
```
