### ISSUE TITLE
[v2.1.0] Tree View "Refresh" uses Wrong Endpoint

### ISSUE THREAD

**Issue by fraciril** [apache/airflow#16307]
**Apache Airflow version**:
v2.1.0

**Environment**:

- **Cloud provider or hardware configuration**: GCP
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04
- **Server**: nginx 1.19.10

**What happened**:

When refreshing the tree view, both with auto-refresh and with the refresh button, the tree view is not refreshed and the empty message "error:" is displayed.

The issue is that the request being made when refreshing the tree view is:

> GET https://{IP}/object/tree_data?dag_id={DAG_ID}

However, I'm serving Airflow in 
> https://{IP}**/airflow** 
> (See the added `/airflow` endpoint, read how to reproduce for more info)

So the correct request should be:
> GET https://{IP}**/airflow**/object/tree_data?dag_id={DAG_ID}
> (with the base /airflow/ endpoint)

I believe my configuration is correct, as *the graph view however does use the correct request* when refreshing:
> GET https://{IP}/airflow/object/task_instances?dag_id={DAG_ID}...

**What you expected to happen**:

The tree view refresh request uses the correct base url so the tree view is refreshed

**How to reproduce it**:

Serve Airflow v2.1.0 using Ngninx as a reverse proxy with and docker-compose, with these configurations:

*nginx.conf*:
```
...
location /airflow/ {
        proxy_pass http://<airflow-webserver-container-name>:8080;
...
```

*docker-compose.yml*:
```
...
airflow-webserver:
    environment:
      AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: 'true'
      AIRFLOW__WEBSERVER__BASE_URL: 'http://${AIRFLOW_URL}/airflow'
    ports:
      - 8080:8080
...
```

**Anything else we need to know**:

- This started happening with version 2.1.0
- The Graph Refresh works correctly
