### ISSUE TITLE
Chart: remote_logging keeps evaluating to False

### ISSUE THREAD

**Issue by kasteph** [apache/airflow#16895]
**Apache Airflow version**: 2.0.2

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): v1.19.10

**Environment**: GKE

- **Cloud provider or hardware configuration**: GCP
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- **Kernel** (e.g. `uname -a`): x86_64 GNU/Linux
- **Install tools**: Helm
- **Others**:

**What happened**: Configured `values.yaml` to enable remote logging for task pods (running KubernetesExecutor)
with Google Stackdriver [using docs here](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/logging/stackdriver.html) but running `airflow show` shows the `task_logging_handler` to still be `FileTaskHandler` instead of the `StackdriverHandler`.

Relevant `values.yaml` section below:

```
...
config:
  core:
    executor: KubernetesExecutor
  logging:
    remote_logging: "True"
    remote_base_log_folder: stackdriver://airflow
....
```

When I check my configmap, these are the results:

```
Data
====
airflow.cfg:
----
...
[logging]
colored_console_log = False
remote_base_log_folder = stackdriver://airflow
remote_logging = True
...
```

But when I exec into a scheduler or webserver pod and check the values there with `airflow config list`, I get:

```
[logging]
base_log_folder = /opt/airflow/logs
remote_logging = False
remote_log_conn_id =
google_key_path =
remote_base_log_folder = stackdriver://airflow
```

or `airflow config get-value logging remote_logging`, I get `False`.

**What you expected to happen**:

`airflow config get-value logging remote_logging` should return `True`.

**How to reproduce it**:

In your `values.yaml`, add the following section:

```
config:
  core:
    executor: KubernetesExecutor
  logging:
    remote_logging: "True"
    remote_base_log_folder: stackdriver://airflow
```

Then run ` helm install --generate-name airflow apache-airflow/airflow --namespace airflow --debug -f values.yaml`

**Comment by jedcunningham** [comment]
@stephsamson, can you check if you have an `AIRFLOW__LOGGING__REMOTE_LOGGING` env var set? That would be the easy explanation.

**Comment by stephsamson** [comment]
@jedcunningham I do not but as a workaround for now I am using the following as a workaround:

```
env:
  - name: AIRFLOW__LOGGING__REMOTE_LOGGING
    value: 'True'
  - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
    value: 'stackdriver://airflow'
```
