### ISSUE TITLE
Loading Variables from ENV does not work?

### ISSUE THREAD

**Issue by p-hebert** [apache/airflow#17872]
**Apache Airflow version**: Docker image `apache/airflow:2.0.2-python3.8`

**OS**: MacOS Big Sur 11.2.3, 
**Browser**: Chrome Version 92.0.4515.131 (Official Build) (x86_64)

**Apache Airflow Provider versions**:

Not sure if that's what you want, but here's my pyproject.toml deps:

```
[tool.poetry.dependencies]
python = ">=3.8,<3.9"
pip = ">=21"
aenum = "^3.1.0"
anytree = "^2.8.0"
apache-airflow = {extras = ["celery", "papermill"], version = "~2.0.2"}
Babel = "~2.9.1"
cattrs = "~1.8.0"
crontab = "^0.23.0"
deepmerge = "^0.3.0"
gitapi = "^1.0.1"
google-api-python-client = "~1.12.8"
google-auth-oauthlib = "^0.4.5"
google-cloud-core = "~1.6.0"
google-cloud-bigquery = {extras = ["bqstorage", "pandas"], version = "==1.28.0"}
google-cloud-pubsub = "^2.6.0"
google-cloud-storage = ">=1.37.0"
jsonpath-ng = "^1.5.2"
jsonpickle = "^2.0.0"
numpy = "^1.20.3"
openpyxl = "^3.0.7"
pandas = "~1.2.4"
pgeocode = "^0.3.0"
pgdatacleaner = "^1.0a5"
psycopg2-binary = "^2.8.6"
PyYAML = "^5.4.1"
ramda = "^0.6.1"
requests = "^2.25.1"
sendgrid = "^6.7.1"
termcolor = "^1.1.0"
oauthlib = "^2.1.0"
oauth2client = "^4.1.3"
colorama = "^0.4.4"
papermill = {version = "^2.3.3", extras = ["gcs"]}
scrapbook = "^0.5.0"
ipykernel = "^6.2.0"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
flake8 = "^3.9.2"
freezegun = "^1.1.0"
invoke = "^1.5.0"
isort = "^5.9.1"
pylint = "^2.8.3"
pyroots = "^0.5.0"
pytest-describe = "^1.0.0"
pytest-mock = "^3.6.1"
pytest-testmon = "^1.1.1"
pytest-watch = "^4.2.0"
pytest = "^6.2.4"
python-dotenv = "^0.17.1"
python-slugify = "^4.0.1"
redis = "^3.5.3"
python-redis-cache = "^1.1.1"
rope = "^0.19.0"
setuptools = "^56.2.0"
snapshottest = "^0.6.0"
tqdm = "^4.62.2"
toml = "^0.10.2"
ipython = "^7.26.0"
ipykernel = "^6.2.0"
```

**Deployment**:

Google Kubernetes Engine 1.20.8-gke.900 (current)
Deployed from local using kubectl version

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-gke.900", GitCommit:"28ab8501be88ea42e897ca8514d7cd0b436253d9", GitTreeState:"clean", BuildDate:"2021-06-30T09:23:36Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:

Given the following `AIRFLOW_VAR_` env vars,

![Screen Shot 2021-08-27 at 10 33 36 AM](https://user-images.githubusercontent.com/31741972/131144164-f062620c-7404-4e3b-8c25-69f3212ac36d.png)

Exposed at boot using a ConfigMap loaded as env in both the worker & webserver deployments:

ConfigMap:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-cfg
  
data:

  AIRFLOW__LOGGING__REMOTE_LOGGING: ---
  AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: ---
  AIRFLOW_VAR_PROJECT: ---
  AIRFLOW_VAR_REPORT_STORAGE_ROOT: ---
  AIRFLOW_VAR_report_gcs_basepath: ---
  AIRFLOW_VAR_environment: ---
  EXTRACTOR_BRANCH: ---
  PROJECT: ---
  EMAIL_DEV_MODE: ---
  ENVIRONMENT: ---
  AIRFLOW__WEBSERVER__BASE_URL: ---
```

worker deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  labels:
    app: airflow-worker
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
        - image: gcr.io/project/airflow:{TAG}
          name: worker
          imagePullPolicy: Always
          ...
          envFrom:
            - configMapRef:
                name: airflow-cfg
          ...
```

webserver:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  labels:
    app: airflow-webserver
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
        - image: gcr.io/project/airflow:{TAG}
          name: webserver
          imagePullPolicy: Always
          ...
          envFrom:
            - configMapRef:
                name: airflow-cfg
          ...
```

The variables do not appear in the UI, nor are they loaded to Variables (or accessible in templating using var). For example, when run, the following operator

![Screen Shot 2021-08-27 at 10 32 30 AM](https://user-images.githubusercontent.com/31741972/131143851-9ae4b6b0-a92c-46d3-9200-3bf9ded10da7.png)

results in:

![image](https://user-images.githubusercontent.com/31741972/131146060-c6fa8319-aa1c-41b3-ba37-38b1ffcd003a.png)

Our data engineer told me that this has been an issue since ancestral times, so we have a script that manually imports vars in Variable using a JSON file instead (in this case it was my first time adding a VAR so I didn't know I had to update the JSON to circumvent the issue).

The script runs this exactly:

```
airflow variables import variables.json
```

**What you expected to happen**:

As per [the docs](https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html), I expected the env variables prefixed with AIRFLOW_VAR_ to be loaded automatically by Variable at boot.

**How to reproduce it**:

I haven't tested on a minimally reproducible setup, but I would think that it would be possible to reproduce this using a minimal docker-compose file with the image apache/airflow:2.0.2-python3.8 and env loaded from a .env file.

**Anything else we need to know**:

Not atm.

**Are you willing to submit a PR?**

No
