### ISSUE TITLE
Helm substitution changes the values for statsd mapping

### ISSUE THREAD

**Issue by kimyen** [apache/airflow#17919]
### Official Helm Chart version

1.1.0 (latest released)

### Apache Airflow version

2.0.2

### Kubernetes Version

1.19.11

### Helm Chart configuration

```
statsd:
  enabled: true
  nodeSelector:
    github.com/poolname: airflow
  extraMappings:
    - match: "airflow.*_start"
       name: "airflow.job.start"
       tags:
          job_name: "$1"
```

### Docker Image customisations

None

### What happened

In `airflow-statsd` configmap in K8s, I see:
```
  - match: airflow.*_start
    name: airflow.job.start
    tags:
      job_name:
```

Double quotes are removed, which is fine. But the `$1` is evaluated to nothing. 

### What you expected to happen

In `airflow-statsd` configmap in K8s, I would see:
```
    - match: "airflow.*_start"
       name: "airflow.job.start"
       tags:
          job_name: "$1"
```

### How to reproduce

See above values

### Anything else

There is a lack of documentation on how to specify data for `extraMappings`. I would imagine if there is an escape character to be used here, it would go in to the doc where we give example on what an extra mapping looks like.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
