### ISSUE TITLE
Dags persistence on MultiNode Kubernetes Cluster

### ISSUE THREAD

**Issue by raefezzeldin** [apache/airflow#18135]
### Apache Airflow version

2.1.3 (latest released)

### Operating System

Official image os

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

Helm chart
Azure Kubernetes Cluster K8s version1.18
Kubernetes executor

### What happened

When enable dag persistence feature on aks with 2 agent pool node and try to use multi node of schedule both scheduler node are created on node as one azure disk is created and doesn’t support multi node connection.
Though all pods are

### What you expected to happen

I am expecting to create another azure disk is created for the other scheduler node on the another node so each node has its own azure disk on each separate node. To distribute the load on the two aks node.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
You need to share the disks between the node. Airflow does not support separate volumes per schedule. Your persistent volume claim has to be one of the distributed fllesystems that are accessible from multiple nodes: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes

**Comment by raefezzeldin** [comment]
hi @potiuk 

I have tried to use AzureFileShare. but I am facing an issue in git-sync-init container (Scheduler)

`MountVolume.SetUp failed for volume "pv-airflowdags" : mount failed: exit status 32 Mounting command: mount Mounting arguments: -t cifs -o file_mode=0777,dir_mode=0777,vers=3.0,gid=0,actimeo=30,mfsymlinks,<masked> //tpaydatasa.file.core.windows.net/fs-airflowdags /var/lib/kubelet/pods/xxxx/volumes/kubernetes.io~azure-file/pv-airflowdags Output: mount: /var/lib/kubelet/pods/xxx/volumes/kubernetes.io~azure-file/pv-airflowdags: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.`

this is the storage class I have created 

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Premium_LRS
```
