### ISSUE TITLE
Bad ownership metadata error for ingress when upgrading from chart version 1.1.0 to 1.2.0 

### ISSUE THREAD

**Issue by dstandish** [apache/airflow#18933]
### Official Helm Chart version

1.2.0 (latest released)

### Apache Airflow version

2.1.4 (latest released)

### Kubernetes Version

20

### What happened

This may not be a bug.

But I tried switching to 1.2.0 from 1.1.0, and got this error:

```
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. 
Unable to continue with update: 
Ingress "airflow-staging-airflow-ingress" in namespace "airflow-staging" exists and cannot be imported into the current release: invalid ownership metadata; 
label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; 
annotation validation error: missing key "meta.helm.sh/release-name": must be set to "airflow-staging"; 
annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "airflow-staging"
```

After adding the label and annotations I was able to do the upgrade.

### Anything else

@jedcunningham should we possibly be populating these in the chart?

```
labels:
      app.kubernetes.io/managed-by: "Helm"
annotations:
      meta.helm.sh/release-name: {{ .Release.Name }}
      meta.helm.sh/release-namespace: {{ .Release.Namespace }}
```

This [one SO post](https://stackoverflow.com/a/69005327/2761682) indicates _maybe_.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
