### ISSUE TITLE
Helm scheduler HA : postgresql error on slot_pool lock

### ISSUE THREAD

**Issue by parisni** [apache/airflow#19811]
### Official Helm Chart version

1.3.0 (latest released)

### Apache Airflow version

2.2.1

### Kubernetes Version

1.21

### Helm Chart configuration

```yaml
airflow:

  env:
    - name: AIRFLOW__SCHEDULER__USE_ROW_LEVEL_LOCKING
      value: "True"

webserver:
  livenessProbe:
    initialDelaySeconds: 100
    timeoutSeconds: 100
    failureThreshold: 20
    periodSeconds: 25

  readinessProbe:
    initialDelaySeconds: 100
    timeoutSeconds: 100
    failureThreshold: 20
    periodSeconds: 25


scheduler:
  replicas: 2

executor: LocalExecutor
```

### What happened

THe postgresql logs this errors:

```
ERROR:  could not obtain lock on row in relation "slot_pool"                                                              
STATEMENT:  SELECT slot_pool.pool AS slot_pool_pool, slot_pool.slots AS slot_pool_slots         
FROM slot_pool FOR UPDATE NOWAIT                          │
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
