### ISSUE TITLE
Helm schduler HA: duplicate key value violates unique constraint "serialized_dag_pkey"

### ISSUE THREAD

**Issue by parisni** [apache/airflow#19822]
### Official Helm Chart version

1.3.0 (latest released)

### Apache Airflow version

2.2.2

### Kubernetes Version

1.2.1

### Helm Chart configuration

```yaml
airflow:

  env:
    - name: AIRFLOW__SCHEDULER__USE_ROW_LEVEL_LOCKING
      value: "True"

webserver:
  livenessProbe:
    initialDelaySeconds: 100
    timeoutSeconds: 100
    failureThreshold: 20
    periodSeconds: 25

  readinessProbe:
    initialDelaySeconds: 100
    timeoutSeconds: 100
    failureThreshold: 20
    periodSeconds: 25


scheduler:
  replicas: 2

executor: CeleryExecutor
```

### What happened

I added 500 dummy dags, and my scheduler/postgres logs are flooded with such error:

```
duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(test_dag_454) already exists.    
 scheduler [SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, last_updated, dag_hash) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, scheduler [parameters: {'dag_id': 'test_dag_454', 'fileloc': '/opt/airflow/dags/repo/test_dag_454.py', 'fileloc_hash': 14390114031793844, 'data': '{"__vers  scheduler (Background on this error at: http://sqlalche.me/e/13/gkpj)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
