### ISSUE TITLE
Change Helm Chart tolerations logic when combining multiple parts of values.yaml

### ISSUE THREAD

**Issue by yehoshuadimarsky** [apache/airflow#20538]
### Official Helm Chart version

1.3.0 (latest released)

### Apache Airflow version

2.2.1

### Kubernetes Version

1.19.14-gke.1900

### Helm Chart configuration

Here are the relevant parts:

```yaml
executor: "KubernetesExecutor"
postgresql:
  enabled: false
data:
  metadataSecretName: airflow-db-creds-secret
pgbouncer:
  enabled: true
flower:
  enabled: false
redis:
  enabled: false

# tolerations for entire chart - use the "core" pool
tolerations:
  - key: airflow-core-pool
    operator: Equal
    value: "true"
    effect: NoSchedule

# want another toleration for only workers to only use the "worker" pool
workers:
  tolerations:
    - key: airflow-worker-pool
      operator: Equal
      value: "true"
      effect: NoSchedule
```

### What happened

I am trying to get all the pods in the Chart to run on a specific node pool by using taints and tolerations, and the workers should run in a different (larger) pool. Each pool has its own specific taint. When setting the tolerations, I assumed that the best way to go was to set a "default" toleration for the whole chart (to the "core" pool), and override/extend that in the workers section to specify a different toleration.

The problem is, when I look at the actual template here, 
https://github.com/apache/airflow/blob/6dfc939833fd3dc477b3971d965ba142d3b8bd77/chart/templates/workers/worker-deployment.yaml#L25
it is using the Helm `or` operator, which I think takes the first not-null value (`.Values.tolerations`), instead of allowing the second one (`.Values.workers.tolerations`) to override or extend it.

See the helm docs at https://helm.sh/docs/chart_template_guide/function_list/#or

Is this a design mistake? I think this should be changed to allow for the intuitive behavior of setting a default toleration for the entire chart and then allowing specific parts to override that.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yehoshuadimarsky** [comment]
But for some reason, the Scheduler has the order reversed:
https://github.com/apache/airflow/blob/6dfc939833fd3dc477b3971d965ba142d3b8bd77/chart/templates/scheduler/scheduler-deployment.yaml#L33

**Comment by potiuk** [comment]
Yeah. I looked at the templates and same case is with .affinity and nodeSelector: it is different sequence for different types of deployments 

Scheduler:

```
{{- $nodeSelector := or .Values.scheduler.nodeSelector .Values.nodeSelector }}
{{- $affinity := or .Values.scheduler.affinity .Values.affinity }}
{{- $tolerations := or .Values.scheduler.tolerations .Values.tolerations }}
```

Triggerer:

```
{{- $nodeSelector := or .Values.nodeSelector .Values.triggerer.nodeSelector }}
{{- $affinity := or .Values.affinity .Values.triggerer.affinity }}
{{- $tolerations := or .Values.tolerations .Values.triggerer.tolerations }}
```

Webserver:

```
{{- $nodeSelector := or .Values.webserver.nodeSelector .Values.nodeSelector }}
{{- $affinity := or .Values.webserver.affinity .Values.affinity }}
{{- $tolerations := or .Values.webserver.tolerations .Values.tolerations }}
```

Workers:

```
{{- $nodeSelector := or .Values.nodeSelector .Values.workers.nodeSelector }}
{{- $affinity := or .Values.affinity .Values.workers.affinity }}
{{- $tolerations := or .Values.tolerations .Values.workers.tolerations }}
```

Also in `values` the only "special" case is "webserver.affinitiy" - all the other have same - empty defaults. It seems indeed as a mistke. I cannot see why we would like to reverse it.

**Comment by potiuk** [comment]
Ah no... I see that workers.afinity and triggerer.affinity are indeed different by default as well:

```
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                component: worker
            topologyKey: "kubernetes.io/hostname"
```
and 
```
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                component: triggerer
            topologyKey: "kubernetes.io/hostname"
```

But tolerations/nodeSelector are not - and since webserver's affinity is also different, I think there is some inconsistency here. Maybe others can shed some light on it.
