### ISSUE TITLE
Elasticsearch connection user and password should be optional

### ISSUE THREAD

**Issue by jedcunningham** [apache/airflow#20560]
### Official Helm Chart version

main (development)

### Apache Airflow version

2.2.3 (latest released)

### Kubernetes Version

1.21.5

### Helm Chart configuration

```yaml
elasticsearch:
  enabled: true
  connection:
    host: elasticsearch-master
    port: 9200
```

### What happened

Secret was created with this connection:

```
http://%3Cno+value%3E:%3Cno+value%3E@elasticsearch-master:9200
```

### What you expected to happen

Secret created with this connection:

```
http://elasticsearch-master:9200
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
