### ISSUE TITLE
With hive-provider installed, but can not be recognized from Airflow Connection Web UI?

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#20709]
### Discussed in https://github.com/apache/airflow/discussions/20380

<div type='discussions-op-text'>

<sup>Originally posted by **ultimateChick** December 17, 2021</sup>
From "Airflow info" command, seem that I've installed hive-provider.
![image](https://user-images.githubusercontent.com/30034544/146555671-dda871d6-9751-4c98-9778-d4d8089eb17f.png)
But in web ui, I can't find the hive conn type.
![image](https://user-images.githubusercontent.com/30034544/146555954-227a5615-7e0b-4f51-8c50-81bb1cafeed6.png)
</div>

**Comment by potiuk** [comment]
cc: @ultimateChick

**Comment by eladkal** [comment]
mmm it works fine for me and I see in the discussion it also worked for josh.

![Screen Shot 2022-01-06 at 18 02 21](https://user-images.githubusercontent.com/45845474/148412390-4dd468e0-3ef5-461d-8578-c01cce9cfc38.png)

**Comment by PApostol** [comment]
This also works fine for me in my testing env with `apache-airflow==2.2.3` and `apache-airflow-providers-apache-hive==2.1.0`.

**Comment by aubdiy** [comment]
@potiuk   @ultimateChick

Finally solved.

First of all, the conclusion is that   No module named '_bz2',  

```
yum install  bzip2-devel
```
then rebuild python3.8,  and  install airflow ,   


The process of investigation;
1. modiry '/usr/local/python3.8/lib/python3.8/site-packages/airflow/providers/apache/hive/get_provider_info.py' append  `traceback.extract_stack()` 
2. restart webserver , then look the  stack log

3. `/usr/local/python3.8/lib/python3.8/site-packages/airflow/www/views.py` line 3341 `choices=sorted(_get_connection_types(), key=itemgetter(1)),` 
4.  fond `provider_info(line 3334)` is none
5.  `/usr/local/python3.8/lib/python3.8/site-packages/airflow/providers_manager.py` line 142 ` import_string(class_name)`  exception, **but the log level is debug**  , i  start webserver use 'airflow webserver -d',  log  nothing.
6.  append code `print(e)`  , restart webserver,    console  writout  `No module named '_bz2',  `




suggest:   modify `providers_manager.py(line  146)`  log level to 'error',  

another question:   why  i  use   'airflow webserver -d'  start webserver ,    the debug level log not  output to  console?

**Comment by potiuk** [comment]
Aaaaah. Yeah. We changed the log level (From INFO  to DEBUG) for that because some of the optional capabilities of providers which wer cluttering the logs. But yeah. I agree this hides exactly the problem that you describe. 

The one case in question was plyveldb unavailability (this is an optional dependency and optional feature of Google Provider).

Unhiding it "blanket" will bring back the clutter (and the problem is that those logs will continuously flood webserver logs because of restarting gunicorn processes. So we have to find a better solution for optional features of some of our providers. Likely only providing a single INFO level log for optional features which miss an import and WARNING for all other failed imports. 

I will think how to solve it best.  Thanks for being so persisting and for the deep investigation!

**Comment by aubdiy** [comment]
1. `/usr/local/python3.8/lib/python3.8/site-packages/airflow/providers_manager.py` line 142  `import_string(class_name)`

2.  the function `import_string`  in the `/usr/local/python3.8/lib/python3.8/site-packages/airflow/utils/module_loading.py`

3.  `/usr/local/python3.8/lib/python3.8/site-packages/airflow/utils/module_loading.py` line 32  `  module = import_module(module_path)`   may    throw   `No module xxx` exception,    use 'try'  protect this line  code,  and log error level log.  

whether it is feasible?

 @potiuk

**Comment by uranusjr** [comment]
I’d recommend the first approach. The second is potentially too confusing for maintainers not familiar with the context (`Error` and `Exception` are kind of interchangeable in Python terminology so `ImportError` and `ImportException` presents a maintenance landmine).

**Comment by potiuk** [comment]
The first one we had initially and the problem was that some of the optional features (plyvel was one example) from the provider will also throw the "No module" errors (when Plyvel Hook is imported). They are essentially indistinguishable from "random" `no import` errors - similarly as you experienced with Hive (and if we convert them into errors, they will also flood the logs. we have to remmber that Providers's manager is initialized and hooks get imported by the webserver every time gunicorn restarts. 

So we really need to hav some way to distinguish the "known import errors" that we should essentially ignore from "unknow import errors" that we shoudl flag as problem.

I think we must have a way to make Provider's developers to flag certain features as optional other than by extras (as is in the case of Plyvel now). Currently Plyvel dependencies are only installed if someone did one of the two:

```
pip install apache-airflow-providers-google[leveldb]
pip install apache-airflow[leveldb]
````
(or manually installed plyvel as dependency)

The library that needs to be installed in order to get LevelDB "work" is `plyvel'. So what we really need to do is find a way that we know that if "plyvel" import fails when we are trying to import "leveldB" Hook, it should be ignored as this optional Hook is not expected in this case. 

The Different Exception is a nice idea, but the problem with it is that we cannot use it in providers if we want to keep Airflow 2.1 compatibility (because we will not have that exception in Airflow 2.1).

I thought about it and the best thing I came up with is to add a new feature in `provider.yaml/provider_info` to mark certain Hooks as optional. I think that might make most sense:

```
connection-types:
  - hook-class-name: airflow.providers.google.common.hooks.base_google.GoogleBaseHook
    connection-type: google_cloud_platform
  - hook-class-name: airflow.providers.google.cloud.hooks.dataprep.GoogleDataprepHook
    connection-type: dataprep
  - hook-class-name: airflow.providers.google.cloud.hooks.cloud_sql.CloudSQLHook
    connection-type: gcpcloudsql
  - hook-class-name: airflow.providers.google.cloud.hooks.cloud_sql.CloudSQLDatabaseHook
    connection-type: gcpcloudsqldb
  - hook-class-name: airflow.providers.google.cloud.hooks.bigquery.BigQueryHook
    connection-type: gcpbigquery
  - hook-class-name: airflow.providers.google.cloud.hooks.compute_ssh.ComputeEngineSSHHook
    connection-type: gcpssh
  - hook-class-name: airflow.providers.google.leveldb.hooks.leveldb.LevelDBHook
    connection-type: leveldb
    optional-when-import-error: 
        - "plyvel"
```

This would allow us to ignore (debug) specific import errors for specific hooks and at the same time we will not have to "hard-code" known import errors. I think that solves all the problems.
