### ISSUE TITLE
TimeoutError: There are still unapplied migrations after 60 seconds

### ISSUE THREAD

**Issue by masshysteria1** [apache/airflow#20803]
### Official Helm Chart version

main (development)

### Apache Airflow version

2.2.3 (latest released)

### Kubernetes Version

1.22

### Helm Chart configuration

```
images:
  airflow:
    repository: ~
    tag: ~
    pullPolicy: IfNotPresent
  # To avoid images with user code, you can turn this to 'true' and
  # all the 'run-airflow-migrations' and 'wait-for-airflow-migrations' containers/jobs
  # will use the images from 'defaultAirflowRepository:defaultAirflowTag' values
  # to run and wait for DB migrations .
  useDefaultImageForMigration: false
  # timeout (in seconds) for airflow-migrations to complete
  migrationsWaitTimeout: 60
  pod_template:
    repository: ~
    tag: ~
    pullPolicy: IfNotPresent
```

# Airflow database migration job settings
migrateDatabaseJob:
  # Annotations on the database migration pod
  annotations: {}
  # jobAnnotations are annotations on the database migration job
  jobAnnotations: {}

### What happened

Hey,

I'm trying to Install Airflow on our Kubernetes cluster and besides statsd and postgres, all other containers fail due to:
`**TimeoutError: There are still unapplied migrations after 60 seconds**`

It seems that the run-airflow-migration job isn't running and so the. The deployment ultimately fails with `back-off restarting failed container` message.

I tried changing the migrationsWaitTimeout: value to 120 instead of 60.
Changed Airflow image versions.
Tried setting --wait=false on the Helm install command.

Nothing works

![image](https://user-images.githubusercontent.com/89924261/148908766-6316e995-27c4-4420-a59e-cf4b7c57d8ab.png)

### How to reproduce

1. Kubernetes version 1.22
2. Airflow version 2.2.3
3. Helm Chart version 1.4
4. Default values

### Anything else

Each deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
