### ISSUE TITLE
Pod Annotations does not be injected in workers when using KubernetesExecutor

### ISSUE THREAD

**Issue by brcps12** [apache/airflow#21386]
### Official Helm Chart version

1.4.0 (latest released)

### Apache Airflow version

2.2.3 (latest released)

### Kubernetes Version

1.21.6

### Helm Chart configuration

```yaml
executor: KubernetesExecutor
workers:
  podAnnotations:
    annotation-name: some value
```

### What happened

Annotations in `workers.podAnnotations` are not injected in workers when executor is `KuberentesExecutor`

### Anything else

In `chart/files/pod-template-file.kubernetes-helm-yaml`, only `.Values.airflowPodAnnotations` is injected.

```yaml
# chart/files/pod-template-file.kubernetes-helm-yaml
apiVersion: v1
kind: Pod
metadata:
  {{- if .Values.airflowPodAnnotations }}
  annotations:
  {{- toYaml .Values.airflowPodAnnotations | nindent 4 }}
  {{- end }}
```

Is this for intended? I think it also needs to insert `podAnnotations` like this:

```yaml
# chart/files/pod-template-file.kubernetes-helm-yaml
apiVersion: v1
kind: Pod
metadata:
  {{- if or (.Values.airflowPodAnnotations) (.Values.workers.podAnnotations) }}
  annotations:
    {{- if .Values.airflowPodAnnotations }}
    {{- toYaml .Values.airflowPodAnnotations | nindent 4 }}
    {{- end }}
    {{- if .Values.workers.podAnnotations}}
    {{- toYaml .Values.workers.podAnnotations | nindent 4 }}
    {{- end }}
  {{- end }}
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
