### ISSUE TITLE
OpenAPI Specs misses a list of securitySchemes defined in 'security' which as result breaks generated OpenAPI client authentication mechanism

### ISSUE THREAD

**Issue by omarsmak** [apache/airflow#22363]
### Apache Airflow version

2.2.4 (latest released)

### What happened

Currently we have this definition in the OpenAPI specs:
```
  securitySchemes:
    Basic:
      type: http
      scheme: basic
    GoogleOpenId:
      type: openIdConnect
      openIdConnectUrl: https://accounts.google.com/.well-known/openid-configuration
    Kerberos:
      type: http
      scheme: negotiate

# The API will provide support for plugins to support various authorization mechanisms.
# Detailed information will be available in the plugin specification.
security: []
```  

When generating the REST APIs client through OpenAPI generator (Java client as an example which the one I am using), the client won't be able to authenticate since is missing the securitySchemes names in the `security: []` array. 

If I include the securitySchemes property names in the `security` property like this:
```
security:
  - Basic: []
  - GoogleOpenId: []
  - Kerberos: []
``` 
This will work as expected.

### Operating System

Linux

### Deployment

Official Apache Airflow Helm Chart

### Anything else

If the maintainers thing this is a valid bug, I will be more than happy to send a PR :)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
