### ISSUE TITLE
Flower is missing extraVolumeMounts

### ISSUE THREAD

**Issue by danielhoherd** [apache/airflow#22413]
### Official Helm Chart version

1.5.0 (latest released)

### Apache Airflow version

2.2.4 (latest released)

### Kubernetes Version

1.19

### Helm Chart configuration

```
flower:
  extraContainers:
  - image: foo
    imagePullPolicy: IfNotPresent
    name: foo
    volumeMounts:
    - mountPath: /var/log/foo
      name: foo
      readOnly: false
  extraVolumeMounts:
  - mountPath: /var/log/foo
    name: foo
  extraVolumes:
  - emptyDir: {}
    name: foo
```

### What happened

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
airflow:
- flower: Additional property extraVolumeMounts is not allowed
```

### What you think should happen instead

The flower pod should support the same extraVolumeMounts that other pods support.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
