### ISSUE TITLE
Wrong apiVersion Detected During Ingress Creation

### ISSUE THREAD

**Issue by Jmdaming** [apache/airflow#22657]
### Official Helm Chart version

1.5.0 (latest released)

### Apache Airflow version

2.2.4 (latest released)

### Kubernetes Version

microk8s 1.23/stable

### Helm Chart configuration

```
executor: KubernetesExecutor

ingress:
  enabled: true

  ## airflow webserver ingress configs
  web:
    annotations:
      kubernetes.io/ingress.class: public
    hosts: 
      -name: "example.com"
    
    path: "/airflow"

## Disabled due to using KubernetesExecutor as recommended in the documentation
flower:
  enabled: false

## Disabled due to using KubernetesExecutor as recommended in the documentation
redis:
  enabled: false
```

### Docker Image customisations

No customization required to recreate, the default image has the same behavior.

### What happened

Installation notes below, as displayed the install fails due to the web ingress chart attempting a semVerCompare to check that the kube version is greater than 1.19 and, if it's not, it defaults back to the v1beta networking version.  The microk8s install exceeds this version so I would expect the Webserver Ingress version to utilize "networking.k8s.io/v1" instead of the beta version.

Airflow installation
```
$: helm install airflow apache-airflow/airflow --namespace airflow --values ./custom-values.yaml
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```

microk8s installation
```
$: kubectl version
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.5-2+c812603a312d2b", GitCommit:"c812603a312d2b0c59687a1be1ae17c0878104cc", GitTreeState:"clean", BuildDate:"2022-03-17T16:14:08Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.5-2+c812603a312d2b", GitCommit:"c812603a312d2b0c59687a1be1ae17c0878104cc", GitTreeState:"clean", BuildDate:"2022-03-17T16:11:06Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

### What you think should happen instead

The Webserver Ingress chart should detect that the kube version is greater than 1.19 and utilize the version ```networking.k8s.io/v1```.

### How to reproduce

On Ubuntu 18.04, run:

1. ```sudo snap install microk8s --classic```
2. ```microk8s status --wait-ready```
3. ```microk8s enable dns ha-cluster helm3 ingress metrics-server storage```
4. ```microk8s helm3 repo add apache-airflow https://airflow.apache.org```
5. ```microk8s kubectl create namespace airflow```
6. ```touch ./custom-values.yaml```
7. ```vi ./custom-values.yaml``` and insert the values.yaml contents from above
8. ```microk8s helm3 install airflow apache-airflow/airflow --namespace airflow --values ./custom-values.yaml```

### Anything else

This problem can be reproduced consistently.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
