### ISSUE TITLE
Amazon S3 for logging using IAM role for service accounts(IRSA)

### ISSUE THREAD

**Issue by vara-bonthu** [apache/airflow#25322]
### What do you see as an issue?

I am using the latest Helm Chart version (see the version below) to deploy Airflow on Amazon EKS and trying to configure S3 for logging. We have few docs that explain how to add logging variables through `values.yaml` but that isn't sufficient for configuring S3 logging with IRSA. I couldn't find any other logs that explains this configuration in detail hence i am adding solution below

Here is the link that i am referring to..

Amazon S3 for Logging https://github.com/apache/airflow/blob/main/docs/apache-airflow-providers-amazon/logging/s3-task-handler.rst

Airflow config
```
apiVersion: v2
name: airflow
version: 1.6.0
appVersion: 2.3.3
```

### Solving the problem

**I have managed to get S3 logging working with IAM role for service accounts(IRSA).** 

# Writing logs to Amazon S3 using AWS IRSA

## Step1: Create IAM role for service account (IRSA)

Create IRSA using `eksctl or terraform`. This command uses eksctl to create IAM role and service account

```sh

eksctl create iamserviceaccount --cluster="<EKS_CLUSTER_ID>" --name="<SERVICE_ACCOUNT_NAME>" --namespace=airflow --attach-policy-arn="<IAM_POLICY_ARN>" --approve

# e.g., 

eksctl create iamserviceaccount --cluster=airflow-eks-cluster --name=airflow-sa --namespace=airflow --attach-policy-arn=arn:aws:iam::aws:policy/AmazonS3FullAccess --approve

```

## Step2:  Update Helm Chart `values.yaml` with Service Account

Add the above Service Account (e.g., `airflow-sa`) to Helm Chart `values.yaml` under the following sections. We are  using the existing `serviceAccount` hence `create: false` with existing name as `name: airflow-sa`. Annotations may not be required as this will be added by **Step1**.  Adding this for readability

```yaml
workers:
  serviceAccount:
    create: false
    name: airflow-sa
    # Annotations to add to worker Kubernetes service account.
    annotations:
      eks.amazonaws.com/role-arn: <ENTER_IAM_ROLE_ARN_CREATED_BY_EKSCTL_COMMAND>

webserver:
  serviceAccount:
    create: false
    name: airflow-sa
    # Annotations to add to worker Kubernetes service account.
    annotations:
      eks.amazonaws.com/role-arn: <ENTER_IAM_ROLE_ARN_CREATED_BY_EKSCTL_COMMAND

config:
  logging:
    remote_logging: 'True'
    logging_level: 'INFO'
    remote_base_log_folder: 's3://<ENTER_YOUR_BUCKET_NAME>/<FOLDER_PATH'
    remote_log_conn_id: 'aws_s3_conn' # notice this name is be used in Step3
    delete_worker_pods: 'False'
    encrypt_s3_logs: 'True'

```

## Step3: Create S3 connection in Airflow Web UI

Now the final step to create connections under Airflow UI before executing the DAGs

- Login to Airflow Web UI and Navigate to `Admin -> Connections`
- Create connection for S3 and select the options as shown in the image

<img width="861" alt="image (1)" src="https://user-images.githubusercontent.com/19464259/181126084-2a0ddf43-01a4-4abd-9031-b53fb4d8870f.png">

## Step4:  Verify the logs

- Execute example DAGs
- Verify the logs in S3 bucket
- Verify the logs from Airflow UI from DAGs log

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Feel free @vara-bonthu - Adding better documentation for that woudl be awesome. Assigned you.

**Comment by vara-bonthu** [comment]
@potiuk @mik-laj I have raised my first [PR](https://github.com/apache/airflow/pull/25931) to Airflow for this issue. 
Looking forward to contribute more. Thanks

**Comment by o-nikolas** [comment]
@vara-bonthu's PR has been merged. Closing this issue as fixed :)

**Comment by Thamban777** [comment]
Hi Team,
Am getting Permission denied: '/.aws' on InitContainer.  I have followed the Documentation mentioned above.

EKS Version: 1.30
Chart version: 1.13.1

my values.yaml:
---------------
scheduler:
  enabled: true
  # Create ServiceAccount
  serviceAccount:
    # default value is true
    # ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
    automountServiceAccountToken: true
    # Specifies whether a ServiceAccount should be created
    create: false
    # The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the release name
    name: test20

    # Annotations to add to scheduler kubernetes service account.
 #   annotations:
#      eks.amazonaws.com/role-arn: arn:aws:iam::111222333444:role/eks-s3-access-role1


  resources: {}

  extraContainers:
    - name: sync-dags
      image: amazon/aws-cli:2.1.34
      command: ["/bin/bash", "-c", "--"]
      args:
        - >
          while true; do
            aws s3 sync --exact-timestamps --delete 's3://mdtlabs-reporting-and-analytics-sl-dev1/apps/airflow/dags/' '/opt/airflow/dags';
            sleep 300;
          done;
      volumeMounts:
        - mountPath: /opt/airflow/dags
          name: dags

  extraInitContainers:
    - name: copy-dags
      image: amazon/aws-cli:2.1.34
      args:
        - s3
        - cp
        - --recursive
        - s3://mdtlabs-reporting-and-analytics-sl-dev1/apps/airflow/dags/
        - /opt/airflow/dags
      env:
        - name: AWS_REGION
          value: us-east-2
        - name: AWS_DEFAULT_REGION
          value: us-east-2

      volumeMounts:
        - mountPath: /opt/airflow/dags
          name: dags

  extraVolumes: 
    - name: airflow-home
      emptyDir: {}
  extraVolumeMounts: []

**Comment by Thamban777** [comment]
```
Hi Team,
Am getting Permission denied: '/.aws' on InitContainer.  I have followed the Documentation mentioned above.

EKS Version: 1.30
Chart version: 1.13.1

my values.yaml:
----------------

scheduler:
  enabled: true
  # Create ServiceAccount
  serviceAccount:
    # default value is true
    # ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
    automountServiceAccountToken: true
    # Specifies whether a ServiceAccount should be created
    create: false
    # The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the release name
    name: test20

    # Annotations to add to scheduler kubernetes service account.
 #   annotations:
#      eks.amazonaws.com/role-arn: arn:aws:iam::111222333444:role/eks-s3-access-role1


  resources: {}

  extraContainers:
    - name: sync-dags
      image: amazon/aws-cli:2.1.34
      command: ["/bin/bash", "-c", "--"]
      args:
        - >
          while true; do
            aws s3 sync --exact-timestamps --delete 's3://test-s3/apps/airflow/dags/' '/opt/airflow/dags';
            sleep 300;
          done;
      volumeMounts:
        - mountPath: /opt/airflow/dags
          name: dags

  extraInitContainers:
    - name: copy-dags
      image: amazon/aws-cli:2.1.34
      args:
        - s3
        - cp
        - --recursive
        - s3://test-s3/apps/airflow/dags/
        - /opt/airflow/dags
      env:
        - name: AWS_REGION
          value: us-east-2
        - name: AWS_DEFAULT_REGION
          value: us-east-2

      volumeMounts:
        - mountPath: /opt/airflow/dags
          name: dags

  extraVolumes: 
    - name: airflow-home
      emptyDir: {}
  extraVolumeMounts: []

```
