### ISSUE TITLE
AWS ALB Ingress not working with URL Prefix

### ISSUE THREAD

**Issue by ghost** [apache/airflow#25601]
### Apache Airflow version

Other Airflow 2 version

### What happened

I set up an ALB Ingress within an AWS EKS Cluster for Apache Airflow via the Helm Chart configuration/values. My goal was to have Airflow available via a URL prefix so that `http://example.com/airflow` would lead to the service. While being able to deploy the ingress successfully without the URL prefix it does not work with the `airflow` prefix. 

When trying to open the Airflow Webserver in my browser the Airflow instance always returns the Airflow 404 screen, so it seems like although it was altered in the ingress config Airflow was not aware of the prefix. Also changing the `base_url` config via env-Variable did not change this.

Here ist my Ingress configuration within the `values.yml`:
```YAML
ingress:
  web:
    enabled: true
    annotations: {
      "alb.ingress.kubernetes.io/target-type": "ip",
      "alb.ingress.kubernetes.io/scheme": "internet-facing",
      "alb.ingress.kubernetes.io/group.name": "proto-external"
    }
    ingressClassName: "alb"
    path: "/airflow/"
    pathType: "Prefix"
```

Thank you very much for your help! :-)

### What you think should happen instead

As I hopefully configured the helm chart values correctly for my setup (at least I did not find documentation suggesting otherwise) - I think the helm chart should configure the Airflow setup so it also supports an URL prefix setup in the `path` parameter of the ingress. 

### Operating System

AWS EKS Cluster

### Versions of Apache Airflow Providers

Airflow Helm Chart - Airflow Version 2.3.0

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
