### ISSUE TITLE
metasecretName is not working anymore

### ISSUE THREAD

**Issue by yc0** [apache/airflow#26340]
### Official Helm Chart version

1.6.0 (latest released)

### Apache Airflow version

2.3.4

### Kubernetes Version

1.20.12

### Helm Chart configuration

postgresql:
  enabled: false
data:
  metadataSecretName: mydatabase
pgbouncer:
  enabled: false

### What happened

as the document mentioned, when you try to access an external database, you should create your connection information in Secret and will use it as metadataSecretName in values.yaml

However, metadataSecretName is not working. It still keeps using <app-name>-airflow-metdata Secret.

### How to reproduce

1. create your own metadata info.
```
kind: Secret
apiVersion: v1
metadata:
  name: mydatabase
type: Opaque
data:
  connection: <xxx>
```
2. upgrade the values.yaml with following configurations
postgresql:
  enabled: false
data:
  metadataSecretName: mydatabase
pgbouncer:
  enabled: false

3. when you run the jobs in Airflow, you will see the error msg from pods
"secret "airflow-airflow-metadata" not found"

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yc0** [comment]
the issue came from podTemplate configuration.
when configuring the podTemplate, you have to modify 3 volumes for using the external database along with `metadataSecretName`.
```
          - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            valueFrom:
              secretKeyRef:
                name: mydatabase
                key: connection
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            valueFrom:
              secretKeyRef:
                name: mydatabase
                key: connection
          - name: AIRFLOW_CONN_AIRFLOW_DB
            valueFrom:
              secretKeyRef:
                name: mydatabase
                key: connection
```
