### ISSUE TITLE
New tasks are spun up when scheduler restarts 

### ISSUE THREAD

**Issue by gfeldman** [apache/airflow#26888]
### Apache Airflow version

Other Airflow 2 version

### What happened

When the scheduler restarts, it deletes existing running task pods and spins up new task pods.

### What you think should happen instead

Task pods that are already running should remain running.

### How to reproduce

1. Deploy using official helm chart. 
2. Run a long running task - we are using a sleep pod
3. kubectl delete pod on the scheduler
4. watch it delete the task pod and create a new one

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

apache-airflow-providers-airbyte==3.0.0
apache-airflow-providers-amazon==4.0.0
apache-airflow-providers-apache-spark==3.0.0
apache-airflow-providers-celery==3.0.0
apache-airflow-providers-cncf-kubernetes==4.1.0
apache-airflow-providers-datadog==3.0.0
apache-airflow-providers-docker==3.0.0
apache-airflow-providers-elasticsearch==4.0.0
apache-airflow-providers-ftp==3.0.0
apache-airflow-providers-google==8.1.0
apache-airflow-providers-grpc==3.0.0
apache-airflow-providers-hashicorp==3.0.0
apache-airflow-providers-http==3.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-jira==3.0.0
apache-airflow-providers-microsoft-azure==4.0.0
apache-airflow-providers-odbc==3.0.0
apache-airflow-providers-pagerduty==3.0.0
apache-airflow-providers-postgres==5.0.0
apache-airflow-providers-redis==3.0.0
apache-airflow-providers-salesforce==4.0.0
apache-airflow-providers-sendgrid==3.0.0
apache-airflow-providers-sftp==3.0.0
apache-airflow-providers-slack==5.0.0
apache-airflow-providers-sqlite==3.0.0
apache-airflow-providers-ssh==3.0.0
apache-airflow-providers-tableau==3.0.0

### Deployment

Official Apache Airflow Helm Chart

### Anything else

every time

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by gfeldman** [comment]
My config
```
config:
  core:
    default_timezone: "America/New_York"
    load_examples: "False"
    plugins_folder: "/git/repo/plugins"
    max_active_runs_per_dag: "1"
    dag_run_conf_overrides_params: "True"
    parallelism: "128"
    dag_discovery_safe_mode: "False"
    dags_are_paused_at_creation: "True"
    executor: '{{ .Values.executor }}'
  webserver:
    default_ui_timezone: "America/New_York"
    session_lifetime_minutes: "1440"
    workers: "1"
  kubernetes:
    delete_worker_pods: "True"
    delete_worker_pods_on_failure: "False"
    namespace: '{{ .Release.Namespace }}'
```
