### ISSUE TITLE
I used the default docker-compose.yaml to setup CeleryExecutor, but SequentialExecutor is set in airflow.cfg

### ISSUE THREAD

**Issue by treyyi** [apache/airflow#27025]
### Apache Airflow version

2.4.1

### What happened

Hi all,

I used the default docker-compose.yaml to setup CeleryExecutor, but SequentialExecutor is set in airflow.cfg.

```
version: '3'
x-airflow-common:
  &airflow-common
  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.4.1}
  # build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    # For backward compatibility, with Airflow <2.3
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
  volumes:
    - ./:/opt/airflow
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
```

I see that `AIRFLOW__CORE__EXECUTOR` is set to `CeleryExecutor`.
However, after running docker-compose up and check the airflow.cfg file in the container, executor is set to `SequentialExecutor`.

In addition to this, should I set the following configurations manually? I thought the docker-compose.yaml replace the settings in the airflow.cfg file..
  - `AIRFLOW__CORE__SQL_ALCHEMY_CONN`
  - `AIRFLOW__CELERY__RESULT_BACKEND`
  - `AIRFLOW__CELERY__BROKER_URL`

The thing is airflow does not load the examples when `AIRFLOW__CORE__LOAD_EXAMPLES` is set to `False` and `load_examples` from airflow.cfg is set to `True`.

Is the settings in docker-compose.yaml just for airflow < 2.3? or did I miss something?

If this is some sort of bugs, I'm willing to check and fix it!

### Operating System

Amazon Linux 2

### Deployment

Docker-Compose

### Deployment details

airflow version 2.4.1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
