### ISSUE TITLE
Scheduler throws an error "Couldn't find dag in DagBag/DB" on each startup.

### ISSUE THREAD

**Issue by aru-trackunit** [apache/airflow#27708]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hi!

Airflow version 2.4.2

On every start of airflow scheduler I am getting an error “Couldn’t find dag %s in DagBag/DB!”. However the error disappears when all dags are processed by DagFileProcessorAgent. I noticed that agent runs in background updating `dag` and `serialized_dag` tables. However when I go through the code I can’t understand why dags are not fetched from a database first rather than waiting for dags to be processed.

### What you think should happen instead

If scheduler is requiring to run an `DagFileProcessorAgent` on each start up then maybe it should sync with the first iteration of agent before being healthy

### How to reproduce

Helm chart 1.7.0.
- dags are present in dag folder before scheduler start up
- dags are present in a database (`dag`, `dag_code`, `serialized_dag` tables are having dags data)

### Operating System

Linux -  official airflow image from docker hub apache/airflow:slim-2.4.2

### Versions of Apache Airflow Providers

apache-airflow[statsd]
apache-airflow-providers-amazon~=6.0.0
apache-airflow-providers-cncf-kubernetes~=4.4.0
apache-airflow-providers-databricks~=3.3.0
apache-airflow-providers-hashicorp~=3.1.0
apache-airflow-providers-postgres~=5.2.2

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

k8s version - 1.23

```
scheduler:
 extraInitContainers:
      - name: init-s3-sync
        image: amazon/aws-cli
        imagePullPolicy: IfNotPresent
        env:
          - name: HOME
            value: /tmp
        volumeMounts:
          - name: airflow-dags
            mountPath: /airflow/dags
        command:
          - /bin/bash
          - -c
        args:
          - aws s3 sync --exact-timestamps --only-show-errors --no-progress --delete 's3://bucket_name/dags' '/airflow/dags';

    # Mount additional volumes into dag processor.
    extraVolumes:
      - name: airflow-dags
    extraVolumeMounts:
      - name: airflow-dags
        mountPath: /opt/airflow/dags
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
