### ISSUE TITLE
Airflow URL returning 404 when using Prefix

### ISSUE THREAD

**Issue by tanmaykansara** [apache/airflow#28362]
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.5

### Kubernetes Version

1.23

### Helm Chart configuration

```
extraEnv: |
  - name: "AIRFLOW_VAR_FOO"
    value: "Develp_foo"
  - name: "AIRFLOW__WEBSERVER__BASE_URL"
    value: "http://localhost:8080/"
ingress:
  enabled: true
  
  
  apiVersion: networking.k8s.io/v1
  
  
  web:
    path: "/airflow-dev"
    host: "k8s-dev-*********************.us-west-2.elb.amazonaws.com"
```

### What happened

 I have EKS where I have deployed Airflow using Helm chart. The pods are running on Fargate. I have ALB installed using helm as well. The UI shows up when accessing the Ingress URL. The issue comes when I am setting up a prefix. If I change the Base_Url value to locahost:8080/airflow-dev/ the webserver Pod keeps restarting. An If I change it back to localhost:8080  I am getting the 404 page when accessing the Ingress URL ?
Here is the error that I get:

![image](https://user-images.githubusercontent.com/119540699/207365625-cf649958-4c45-4512-bb5a-6d5921af94c0.png)

Ideally I want to access the Airflow using the ingress_url/airflow-dev/ . 

### What you think should happen instead

Should be seeing the Airflow URL when using Prefix

### How to reproduce

Set up ingress, ALB on EKS(fargate)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
