### ISSUE TITLE
Missing annotations on Deployments

### ISSUE THREAD

**Issue by sudeepgupta90** [apache/airflow#28604]
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.3.0

### Kubernetes Version

v1.24.x

### What happened

The helm chart is missing `annotations` on Deployment objects. This is not a feature per se, but is a great value add if users want to deploy with extra annotations. Currently, only `podAnnotations` are supported on Deployments

### What you think should happen instead

The helm chart should contain an option to add Deployment annotations. 

Example:

```
webserver:
  # this is missing. This will add to the annotations of the Deployment itself
  annotations: {}
  
  # already present. This adds to the annotations of only the pod
  podAnnotations: {}
```

webserver-deployment.yaml
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-webserver
  labels:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
  annotations:
    {{- with .Values.webserver.annotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
