### ISSUE TITLE
Can't configure Kubernetes and Celery workers in Helm Chart

### ISSUE THREAD

**Issue by csp33** [apache/airflow#28880]
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.4.3

### Kubernetes Version

1.25

### What happened

Current Helm chart uses the "workers" section to configure Kubernetes or Celery workers parameters (resources, affinity, etc.).
However, when using CeleryKubernetesExecutor, the "workers" section is used to configure the Celery ones, making Kubernetes workers settings available only via podTemplateFile, which can be difficult to manage.

I suggest splitting "workers" into "kubernetesWorkers" (used in pod_template_file) and "celeryWorkers" (used by the celery ones)

### What you think should happen instead

Helm Chart should allow to configure both kind of workers in an easy way

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by potiuk** [comment]
Why not - if someoene would like to pick it, i marked it as good first issue.

**Comment by csp33** [comment]
I could take this one. How about this proposal? values defined at the "workers" level will be taken by both celery & k8s.
    ```yaml
    workers:
      safeToEvict: false
      celery:
        resources: 
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
      kubernetes:
        resources:
          limits:
            cpu: 240m
            memory: 875Mi
          requests:
            cpu: 240m
            memory: 875Mi
    ```
@potiuk
