### ISSUE TITLE
Chart config section doesn't add kubernetes_executor to airflow.cfg

### ISSUE THREAD

**Issue by N-ickJones** [apache/airflow#29817]
### Official Helm Chart version

1.8.0 (latest released)

### Apache Airflow version

2.5.0

### Kubernetes Version

1.25.5

### Helm Chart configuration

```yaml
# In our overrides.yml (to solve the issue for now). Essentially a copy of what is under the config kubernetes section in the values.yaml.
config:
  kubernetes_executor:
    namespace: '{{ .Release.Namespace }}'
    airflow_configmap: '{{ include "airflow_config" . }}'
    airflow_local_settings_configmap: '{{ include "airflow_config" . }}'
    pod_template_file: '{{ include "airflow_pod_template_file" . }}/pod_template_file.yaml'
    worker_container_repository: '{{ .Values.images.airflow.repository | default .Values.defaultAirflowRepository }}'
    worker_container_tag: '{{ .Values.images.airflow.tag | default .Values.defaultAirflowTag }}'
    multi_namespace_mode: '{{ ternary "True" "False" .Values.multiNamespaceMode }}'
```

### Docker Image customizations

None

### What happened

The 1.8.0 chart adds a [kubernetes] section by default from the charts values.yaml which then gets added to the airflow.cfg file.

### What you think should happen instead

The 1.8.0 chart should add a [kubernetes_executor] section by default from the charts values.yaml which then gets added to the airflow.cfg file.

### How to reproduce

Deploy the chart normally and the scheduler health check fails.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
