### ISSUE TITLE
Support for providing SHA digest for the image in Helm chart

### ISSUE THREAD

**Issue by elongl** [apache/airflow#30200]
### Description

This is my configuration:
```yaml
images:
  airflow:
    repository: <REPO>
    tag: <TAG>
```

I'd like to be able to do the following:
```yaml
images:
  airflow:
    repository: <REPO>
    digest: <SHA_DIGEST>
```

Additionally, I've tried supplying only the repository, or placing the digest as the tag, but both don't work because of [this](https://github.com/apache/airflow/blob/c44c7e1b481b7c1a0d475265835a23b0f507506c/chart/templates/_helpers.yaml#L252). The formatting is done by `repo:tag` while I need `repo@digest`.

### Use case/motivation

I'm using Terraform to deploy Airflow.
I'm using the data source of [`aws_ecr_image`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ecr_image) in order to pick the `latest` image.
I want to supply to the [`helm_release`](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) of Airflow the image's digest rather than `latest` as according to the docs, it's bad practice.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
