### ISSUE TITLE
Pod Disruption Budget doesn't allow additional properties

### ISSUE THREAD

**Issue by andpozo** [apache/airflow#30247]
### Official Helm Chart version

1.8.0 (latest released)

### Apache Airflow version

2

### Kubernetes Version

>1.21

### Helm Chart configuration

```yaml
webserver:
  podDisruptionBudget:
    enabled: true
    config:
      minAvailable: 1
```

### What happened

if you use the next values the chart you will not ablt to install the chart, the problem is in the schema  in this line

https://github.com/apache/airflow/blob/main/chart/values.schema.json#L3320

### How to reproduce

use the this values

```yaml
webserver:
  podDisruptionBudget:
    enabled: true
    config:
      minAvailable: 1
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
