### ISSUE TITLE
Ability to set automountServiceAccountToken in values.yaml

### ISSUE THREAD

**Issue by fsellecchia** [apache/airflow#30722]
### Official Helm Chart version

1.6.0

### Apache Airflow version

2.3.0

### Kubernetes Version

1.24

### Helm Chart configuration

```
serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
    # The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the release name
    name: ~
   
    automountServiceAccountToken: false

    # Annotations to add to webserver kubernetes service account.
    annotations: {}
```

### Docker Image customizations

No Modifications

### What happened

I'm trying to disable the serviceaccounttoken using this flag `automountServiceAccountToken: false` in my values.yaml, but the value is not considered in the template then the token is still active. 
As far as I understand disable the token is a good practice in case that is not needed.
For example, automountServiceAccountToken is not referenced [here](https://github.com/apache/airflow/blob/main/chart/templates/webserver/webserver-serviceaccount.yaml) for webserver 

### What you think should happen instead

add a parametrization for automountServiceAccountToken so we can enable/disable it from values.yaml

### How to reproduce

Just try to add a the `automountServiceAccountToken: false` parameter on your values.yaml and check that it is not being considered when the service account and the pod is created.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
