### ISSUE TITLE
K8s delete Terminating pod before terminationGracePeriodSeconds with still running tasks

### ISSUE THREAD

**Issue by alvaromaroto** [apache/airflow#32180]
### Official Helm Chart version

1.9.0 (latest released)

### Apache Airflow version

2.3.4

### Kubernetes Version

1.26

### Helm Chart configuration

```yaml
workers:
  # Number of airflow celery workers in StatefulSet
  replicas: 8

  persistence:
    enabled: false

  # Allow KEDA autoscaling.
  # Persistence.enabled must be set to false to use KEDA.
  keda:
    enabled: true
    minReplicaCount: 2
    maxReplicaCount: 10
    pollingInterval: 60

  livenessProbe:
    failureThreshold: 10
    initialDelaySeconds: 30
    timeoutSeconds: 60

  resources:
    requests:
      cpu: 3
      memory: 7Gi
  # not works as expected
  terminationGracePeriodSeconds: 5000
```

### What happened

I've defined a long `terminationGracePeriodSeconds` (more than 1 hour 30 mins) because I've long running tasks (tasks that send long Redshift queries). 

Usually, when KEDA decides to scale-down, some pods are marking as `Terminating`, but K8s is waiting to finish the running tasks in these pods or until `terminationGracePeriodSeconds` have elapsed to finally delete them. This is OK but...

...sometimes, the POD is killed before the tasks finish and before the `terminationGracePeriodSeconds`, so the Airflow tasks fails and have to retry in other worker. I don't know why is happening because there are enough resources in the nodes to allocate the POD so this is not the issue.

Any idea or solution?

Thanks

### What you think should happen instead

For instance, this POD was deleted 10 minutes after scale down with still 10 running tasks. 

![image](https://github.com/apache/airflow/assets/44638467/cc37e5f5-3873-46b8-8645-8180bd9333af)

### How to reproduce

To reproduce the error, you can deploy Airflow in K8s with KEDA.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
