### ISSUE TITLE
Provider apache-airflow-providers-microsoft-azure no longer==6.2.3 expose `account_name`

### ISSUE THREAD

**Issue by utkarsharma2** [apache/airflow#33203]
### Apache Airflow version

2.6.3

### What happened

Till version apache-airflow-providers-microsoft-azure no longer==6.2.2 if you do `WasbHook(wasb_conn_id=self.conn_id).get_conn().account_name` you will get the `account_name` But in version `apache-airflow-providers-microsoft-azure==6.2.3` this is not longer working for below connection:

```
- conn_id: wasb_conn_with_access_key
    conn_type: wasb
    host: astrosdk.blob.core.windows.net
    description: null
    extra:
      shared_access_key: $AZURE_WASB_ACCESS_KEY
```
 

### What you think should happen instead

We should get the `account_name` for `apache-airflow-providers-microsoft-azure==6.2.3`.

### How to reproduce

Try installing the version `apache-airflow-providers-microsoft-azure==6.2.3` and try running below code `WasbHook(wasb_conn_id=self.conn_id).get_conn().account_name` 

### Operating System

Mac

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by eladkal** [comment]
Assuming https://github.com/apache/airflow/pull/32980 is the root cause we can also yank 6.2.3 as this PR is the only code change in the release
@ephraimbuddy @potiuk WDYT?

**Comment by ephraimbuddy** [comment]
> Assuming #32980 is the root cause we can also yank 6.2.3 as this PR is the only code change in the release @ephraimbuddy @potiuk WDYT?

Yes. that's the root cause. It appears that checking that host startswith https is wrong. I think the correct thing would be to use host however it's supplied but that's a breaking change that we fixed in 6.2.2 I think

**Comment by potiuk** [comment]
Yes. We could yank the release.

**Comment by ephraimbuddy** [comment]
> Yes. We could yank the release.

I'm working out a solution but I don't think we should yank this. Specifying a value in connection.login will make the above  connection work e.g:
```
- conn_id: wasb_conn_with_access_key
    conn_type: wasb
    login:astrosdk
    host: astrosdk.blob.core.windows.net
    description: null
    extra:
      shared_access_key:
```
