### ISSUE TITLE
the airflow druid_ingest_default connection test always fails.

### ISSUE THREAD

**Issue by jaegwonseo** [apache/airflow#33795]
### Apache Airflow version

2.7.0

### What happened

the airflow druid_ingest_default connection test always fails.

there is two type of connection types 
1. druid broker : airflow.providers.apache.druid.hooks.druid.DruidDbApiHook
2. druid ingest : airflow.providers.apache.druid.hooks.druid.DruidHook

only druid broker connection is exposed : https://github.com/apache/airflow/blob/main/airflow/providers/apache/druid/provider.yaml#L74

and airflow.providers.apache.druid.hooks.druid.DruidHook dosen't not implement connection test

### What you think should happen instead

.

### How to reproduce

.

### Operating System

m2 mac

### Deployment

Official Apache Airflow Helm Chart

### Anything else

1. expose druid connection type
```yaml
connection-types:
  - hook-class-name: airflow.providers.apache.druid.hooks.druid.DruidDbApiHook
    connection-type: druid_broker
  - hook-class-name: airflow.providers.apache.druid.hooks.druid.DruidHook
    connection-type: druid_ingest
```

2. implement connection test 
```py
    def test_connection(self) -> tuple[bool, str]:
        retrun True, "" 
```
3. modify create_default_connections method
https://github.com/apache/airflow/blob/main/airflow/utils/db.py#L224

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
