### ISSUE TITLE
Pgbouncer not set properly upon using data.metadataSecretName

### ISSUE THREAD

**Issue by Flogue** [apache/airflow#33924]
### Official Helm Chart version

1.10.0 (latest released)

### Apache Airflow version

2.6.2

### Kubernetes Version

1.27

### Helm Chart configuration

```
postgresql:
  enabled: false

data:
  metadataSecretName: rds-postgres

pgbouncer:
  enabled: true
  maxClientConn: 100
  metadataPoolSize: 10
  resultBackendPoolSize: 5
  sslmode: "require"
```

### Docker Image customizations

None

### What happened

The airflow cluster comes up gracefully.
Upon checking the pgbouncer logs, I discovered they were not recording any access.

Checking the Airflow configuration on the web UI, I can see that sql_alchemy_conn point directly to my database:
```postgresql://postgres:mypass@myhost:5432/postgres?sslmode=require```

### What you think should happen instead

I was expecting the Airflow config _sql_alchemy_conn_ to point to pgbouncer

### How to reproduce

It seems using a kubernetes secret (the _data.metadataSecretName_ key) is the problem. If I use:
```
data:
  metadataConnection:
    user: postgres
    pass: mypass
    protocol: postgresql
    host: myhost
    port: 5432
    db: postgres
```

Then sql_alchemy_conn points to pgbouncer:
```postgresql://postgres:postgres@airflow-pgbouncer.airflow:6543/airflow-metadata?sslmode=disable```

### Anything else

For a production system, I would want my database password to be in a kubernetes secret.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
