### ISSUE TITLE
`version_added` field in configuration option doesn't work correctly in providers documentation

### ISSUE THREAD

**Issue by Taragolis** [apache/airflow#34005]
### Apache Airflow version

2.7.0

### What happened

Initial finding: https://github.com/apache/airflow/pull/33960#discussion_r1312748153

Since [Airflow 2.7.0](https://github.com/apache/airflow/pull/32629) we have an ability to store configuration options in providers, everything works fine, except field `version_added`.

The logic around this field expect Airflow version and not Provider version. Any attempt to add in this field any value greater than current version of Airflow (2.7.0 at that moment) will result that configuration option won't rendered in documentation, seem like it not prevented to add this configuration at least `airflow config get-value` command return expected option.

### What you think should happen instead

Various, depend on final solution and decision.

_Option 1_:
In case if we would not like use this field for providers we might ignore this field in providers configurations.
For Community Providers we could always set it to `~`

_Option 2_:
Dynamically resolve depend on what a source of this configuration, Core/Provider

_Option 3_:
Add `provider_version_added` and use for show in which version of provider this configuration added
We could keep `version_added` if configuration option in provider related to Airflow Version

_Option 4_:
Suggest you own 😺
 

### How to reproduce

Create configuration option with `version_added` greater than current version of Airflow, for stable it is 2.7.0 for dev 2.8.0

```yaml
config:
  aws:
    description: This section contains settings for Amazon Web Services (AWS) integration.
    options:
      session_factory:
        description: |
          Full import path to the class which implements a custom session factory for
          ``boto3.session.Session``. For more details please have a look at
          :ref:`howto/connection:aws:session-factory`.
        default: ~
        example: my_company.aws.MyCustomSessionFactory
        type: string
        version_added: 3.1.1
```

### Operating System

n/a

### Versions of Apache Airflow Providers

n/a

### Deployment

Other

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
