### ISSUE TITLE
Use Kubernetes-recommended labels for airflow helm chart

### ISSUE THREAD

**Issue by kimminw00** [apache/airflow#34048]
### Description

Kubernetes offers a [list of recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) for grouping resource objects. The prefix <code>app.kubernetes.io</code> differentiates these recommended labels from custom labels.

Why is it needed?
Enhancing readability and maintainability

References
https://helm.sh/docs/chart_best_practices/labels/#standard-labels
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

### Use case/motivation

https://github.com/apache/airflow/blob/913eff6759bf89d635ef1df1a0db23c157e48c4b/chart/templates/webserver/webserver-deployment.yaml#L36-L40

The above labels would be changed as follows:

```yaml
app.kubernetes.io/part-of: airflow
app.kubernetes.io/component: webserver
app.kubernetes.io/instance: {{ .Release.Name }}
helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
