### ISSUE TITLE
git-sync subPath is not working

### ISSUE THREAD

**Issue by ArnasBalsys** [apache/airflow#34078]
### Official Helm Chart version

1.10.0 (latest released)

### Apache Airflow version

2.7.0

### Kubernetes Version

1.26.7

### Helm Chart configuration

```
dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: https://repo.link/Airflow.git
    branch: main
    subPath: "dags"
    credentialsSecret: airflow-git-credentials
    containerName: airflow-git-sync
```

### Docker Image customizations

Extended official airflow image with additional packages

### What happened

It seems that when using git-sync and specifying a dags folder it's being completely ignored. It instead copies the whole repository and no matter your folder name - subPath value is not taken into account for. 
```
  gitSync:
    enabled: true
    ...
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "dags"
```

The same issue was opened awhile back but unfortunately closed:
https://github.com/apache/airflow/issues/16622

### What you think should happen instead

Only dags folder should be copied when it's specified in subPath

### How to reproduce

just specify a non-existant folder on the subPath value - it will be ignored

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
