### ISSUE TITLE
Support for custom cronjobs

### ISSUE THREAD

**Issue by kimminw00** [apache/airflow#34399]
### Description

https://github.com/apache/airflow/blob/3854264a31ba5c7718c51a034154f12483ad78d3/chart/values.yaml#L2167-L2180

Since airflow helm chart only supports cleanup cronjob, users have to modify templates to add additional maintenance cronjobs

### Use case/motivation

For example, we can create multiple custom cronjobs using <code>values.yaml</code> ​​below

```yaml
cronJobs:
  cleanPods:
    image: apache/airflow
    schedule: "*/15 * * * *"
    command: ~
    args: ["bash", "-c", "exec airflow kubernetes cleanup-pods --namespace={{ .Release.Namespace }}"]
    ...
  cleanDB:
    image: apache/airflow
    schedule: "30 3 1 * *"
    command: ~
    args: ["bash", "-c", "exec airflow db clean"]
    ...
  backupDB:
    image: CUSTOM_IMAGE
    schedule: "0 1 1 * *"
    command: ~
    args: ["bash", "-c", "pg_dump -h HOST -U USER_NAME -Fc DATABASE_NAME | aws s3 cp - s3://<bucket_name>/<database_name>.dump"]
    ...
```

By providing custom cronjobs, we can flexibly respond to additional maintenance tasks as needed.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
