### ISSUE TITLE
Connections and variables are not being created based on extraSecrets and extraConfigMaps

### ISSUE THREAD

**Issue by belaytzev** [apache/airflow#34646]
### Official Helm Chart version

1.10.0 (latest released)

### Apache Airflow version

v2.7.1

### Kubernetes Version

1.27

### Docker Image customizations

install apache-airflow[postgres,amazon,cncf.kubernetes,daskexecutor]

### What happened

I configured extraSecrets and extraConfigMaps for my PostgreSQL connection and some additional variables. I also added extraEnvFrom to attach those extras to Airflow containers.

```YAML
extraSecrets:
  '{{ .Release.Name }}-airflow-connections':
    type: 'Opaque'
    data: |
      AIRFLOW_CONN_MY_DB: 'base64_encoded_my_db_string'

extraConfigMaps:
  '{{ .Release.Name }}-airflow-variables':
    data: |
      AIRFLOW_VAR_MY_VAR: 'my_var_string'

extraEnvFrom: |
  - secretRef:
      name: '{{ .Release.Name }}-airflow-connections'
  - configMapRef:
      name: '{{ .Release.Name }}-airflow-variables'
```

Variables are typically added to containers in Airflow, but they do not affect the parameters.

```shell
airflow@apache-airflow-webserver:/opt/airflow$ airflow connections list
No data found
airflow@apache-airflow-webserver:/opt/airflow$ airflow variables list
No data found
airflow@apache-airflow-webserver:/opt/airflow$ airflow version
2.7.1
airflow@apache-airflow-webserver:/opt/airflow$ printenv | grep AIRFLOW_CONN
AIRFLOW_CONN_MY_DB=postgres://user:pass@host:5432
airflow@apache-airflow-webserver:/opt/airflow$ printenv | grep AIRFLOW_VAR
AIRFLOW_VAR_MY_VAR=my_var
```

### How to reproduce

Install helm chart with extraSecrets, extraConfigMaps and extraEnvFrom

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
