### ISSUE TITLE
logs volume timeout to mount - KubernetesPodOperator

### ISSUE THREAD

**Issue by VictorCallejas** [apache/airflow#34752]
### Official Helm Chart version

1.10.0

### Apache Airflow version

2.6.2

### Kubernetes Version

1.21.6

### Helm Chart configuration

```
logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: true
    # Volume size for logs
    #size:  5Gi
    # Annotations for the logs PVC
    #annotations: {}
    # If using a custom storageClass, pass name here
    #storageClassName:
    ## the name of an existing PVC to use
    existingClaim: airflow-logs-pvc-dlu #airflow-logs-pvc-test-v1 #airflow-logs-test
```

KubernetesPodOperator:
`startup_timeout_seconds=300`
(I increased it with no luck)
### Docker Image customizations

None

### What happened

When I run with **logs not enabled it all works fine**

When the logs are enabled:
**At the beginning all works well and the logs are available**, but after sometime (hours) the logs volumes can not be mounted into the pod of the cronjob of the kubernetes pod operator until it finally timeouts.
![image](https://github.com/apache/airflow/assets/32225250/5fd7a7e0-b033-459e-9614-41e0c39cfa43)

(At the beginning the volume can be mounted in 30 pods in less that 3 seconds with no issues)

- I have check that the volume does not have a bottleneck (cpu, mem, iops...)
- This volume is not an issue on any other deployment on the cluster

### What you think should happen instead

It should work as in the beginning, and the volume should be mounted immediatly on the pods

### How to reproduce

I am currently using portworx volumes
https://docs.portworx.com/portworx-enterprise/operations/operate-kubernetes/storage-operations/create-pvcs

But I really dont think this is the issue, as I have been checking and monitoring grafana and there is no bottleneck on them

### Anything else

- Do we need for Airflow to tune anything like in the K8s Apiserver?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
