### ISSUE TITLE
Cannot install Helm chart via Argo CD

### ISSUE THREAD

**Issue by jmilldotdev** [apache/airflow#35159]
### Official Helm Chart version

1.11.0 (latest released)

### Apache Airflow version

2.7.2

### Kubernetes Version

1.23.x

### Helm Chart configuration

Chart.yaml
```
apiVersion: v2
name: App
description: A Helm chart for Kubernetes
version: 0.1.0

dependencies:
  - name: airflow
    version: "1.11.0"
    repository: "https://airflow.apache.org"
```

values.yaml
```
createUserJob:
  useHelmHooks: false
migrateDatabaseJob:
  useHelmHooks: false
  jobAnnotations:
    "argocd.argoproj.io/hook": Sync
```

### What happened

The database migration jobs do not appear to be run. I have tried both the attached values.yaml, and

values.yaml
```
createUserJob:
  useHelmHooks: false
migrateDatabaseJob:
  useHelmHooks: false
  jobAnnotations:
    "argocd.argoproj.io/hook": Sync
```

from the documentation.

Either way, I get the following in the postgres container:

```
postgresql 15:29:54.98 
35
postgresql 15:29:54.99 Welcome to the Bitnami postgresql container
34
postgresql 15:29:54.99 Subscribe to project updates by watching https://github.com/bitnami/containers
33
postgresql 15:29:54.99 Submit issues and feature requests at https://github.com/bitnami/containers/issues
32
postgresql 15:29:54.99 
31
postgresql 15:29:55.01 INFO  ==> ** Starting PostgreSQL setup **
30
postgresql 15:29:55.02 INFO  ==> Validating settings in POSTGRESQL_* env vars..
29
postgresql 15:29:55.03 INFO  ==> Loading custom pre-init scripts...
28
postgresql 15:29:55.03 INFO  ==> Initializing PostgreSQL database...
27
postgresql 15:29:55.05 INFO  ==> pg_hba.conf file not detected. Generating it...
26
postgresql 15:29:55.05 INFO  ==> Generating local authentication configuration
25
postgresql 15:29:56.07 INFO  ==> Starting PostgreSQL in background...
24
postgresql 15:29:56.20 INFO  ==> Changing password of postgres
23
postgresql 15:29:56.23 INFO  ==> Configuring replication parameters
22
postgresql 15:29:56.26 INFO  ==> Configuring synchronous_replication
21
postgresql 15:29:56.26 INFO  ==> Configuring fsync
20
postgresql 15:29:56.30 INFO  ==> Stopping PostgreSQL...
19
waiting for server to shut down.... done
18
server stopped
17
postgresql 15:29:56.41 INFO  ==> Loading custom scripts...
16
postgresql 15:29:56.41 INFO  ==> Enabling remote connections
15
postgresql 15:29:56.42 INFO  ==> ** PostgreSQL setup finished! **
14
13
postgresql 15:29:56.44 INFO  ==> ** Starting PostgreSQL **
12
2023-10-24 15:29:56.459 GMT [1] LOG:  pgaudit extension initialized
11
2023-10-24 15:29:56.459 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
10
2023-10-24 15:29:56.459 GMT [1] LOG:  listening on IPv6 address "::", port 5432
9
2023-10-24 15:29:56.468 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
8
2023-10-24 15:29:56.483 GMT [127] LOG:  database system was shut down at 2023-10-24 15:29:56 GMT
7
2023-10-24 15:29:56.492 GMT [1] LOG:  database system is ready to accept connections
6
2023-10-24 15:30:06.126 GMT [142] ERROR:  relation "log" does not exist at character 13
5
2023-10-24 15:30:06.126 GMT [142] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2023-10-24T15:30:06.101967+00:00'::timestamptz, 'cli_check', 'airflow', '{"host_name": "airflow4-worker-0", "full_command": "[''/home/airflow/.local/bin/airflow'', ''db'', ''check'']"}') RETURNING log.id
4
2023-10-24 15:30:09.103 GMT [144] ERROR:  relation "log" does not exist at character 13
3
2023-10-24 15:30:09.103 GMT [144] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2023-10-24T15:30:09.089586+00:00'::timestamptz, 'cli_check', 'airflow', '{"host_name": "airflow4-webserver-547c796898-4bkz5", "full_command": "[''/home/airflow/.local/bin/airflow'', ''db'', ''check'']"}') RETURNING log.id
2
2023-10-24 15:30:10.004 GMT [146] ERROR:  relation "log" does not exist at character 13
1
2023-10-24 15:30:10.004 GMT [146] STATEMENT:  INSERT INTO log (dttm, event, owner, extra) VALUES ('2023-10-24T15:30:09.974952+00:00'::timestamptz, 'cli_check', 'airflow', '{"host_name": "airflow4-triggerer-0", "full_command": "[''/home/airflow/.local/bin/airflow'', ''db'', ''check'']"}') RETURNING log.id
```

And when I inspect the namespace i've created in kubernetes, i do not see any job resources created in the namespace.

### How to reproduce

Use the above values and Chart in argoCD

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
