### ISSUE TITLE
Grid view shows wrong task status

### ISSUE THREAD

**Issue by atacank** [apache/airflow#35198]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Apache Airflow version==2.6.3

When a DAG runs, grid view doesn't show the right status of tasks.

this is the screenshot of grid view of running DAG (the last one is currently running):
![image](https://github.com/apache/airflow/assets/8173707/c91c633d-ce41-45e6-add4-fbef5c8cedd6)

this is the screenshot of graph view of running DAG:
![image](https://github.com/apache/airflow/assets/8173707/1ecb0186-09a8-4ad5-86ff-6926ae3ebdec)

I cannot interact with DAG and its task in gridview. Any idea about this issue?

### How to reproduce

This is a production environmet. it works on container.
podman version 4.4.1
Apache Airflow version 2.6.3

### Operating System

RHEL

### Deployment

Docker-Compose

### Deployment details

```yaml
compose.yml:
`x-common: &common
  restart: always
  stop_grace_period: 2s
  healthcheck:
    start_period: 10s
    interval: 10s
    timeout: 10s
    retries: 5

x-airflow-common: &airflow-common
  <<: *common
  image: mydomain.com/internal-docker-app/com/arge/swan/airflow:latest-dev
  volumes:
    - /data/Swan_Datastore/dags/:/opt/airflow/dags/
    - /data/Swan_Datastore/logs/:/opt/airflow/logs/
    - /data/Swan_Datastore/config/:/opt/airflow/config/
    - /data/Swan_Datastore/plugins/:/opt/airflow/plugins/
  depends_on:
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  worker:
    <<: *airflow-common
    command: celery worker
    healthcheck:
      test: ["CMD", "celery", "--app", "airflow.executors.celery_executor.app", "inspect", "ping"]

  scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "airflow", "jobs", "check", "--job-type", "SchedulerJob"]

  triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD", "airflow", "jobs", "check", "--job-type", "TriggererJob"]

  flower:
    <<: *airflow-common
    command: celery flower
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:5555/"]

  postgres:
    <<: *common
    image: mydomain.com/tech-docker/postgres:13.11
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - /data/Swan_Datastore/postgres/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]

  redis:
    <<: *common
    image: mydomain.com/tech-docker/redis:7.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  airflow:
    <<: *airflow-common
    build:
      context: ./airflow/
      args:
        DOCKER_BUILDKIT: 1
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8080/"]
    labels:
      - traefik.enable=true
      - traefik.constraint=swan
      - traefik.http.routers.airflow.rule=Host(`airflow.mydomain.com`)
      - traefik.http.services.airflow.loadbalancer.server.port=8080

  filegator:
    <<: *common
    image: mydomain.com/internal-docker-app/com/arge/swan/filegator:latest-dev
    build:
      context: ./filegator/
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - /data/Swan_Datastore/dags/:/var/www/filegator/repository/airflow/
    depends_on:
      airflow:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8080/"]
    labels:
      - traefik.enable=true
      - traefik.constraint=swan
      - traefik.http.routers.filegator.rule=Host(`filegator.mydomain.com`)
      - traefik.http.services.filegator.loadbalancer.server.port=8080

  homer:
    <<: *common
    image: mydomain.com/internal-docker-app/com/arge/swan/homer:latest-dev
    build:
      context: ./homer/
      args:
        DOCKER_BUILDKIT: 1
    depends_on:
      airflow:
        condition: service_healthy
      filegator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8080/"]
    labels:
      - traefik.enable=true
      - traefik.constraint=swan
      - traefik.http.routers.homer.rule=Host(`mydomain.com`)
      - traefik.http.services.homer.loadbalancer.server.port=8080

  traefik:
    <<: *common
    image: mydomain.com/tech-docker/traefik:2.10
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:ro
    command:
      - --global.sendanonymoususage=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.constraints=Label(`traefik.constraint`, `swan`)
    depends_on:
      homer:
        condition: service_healthy
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
