### ISSUE TITLE
Can't view worker logs for running tasks after disabling worker persistence

### ISSUE THREAD

**Issue by chrisluedtke** [apache/airflow#35388]
### Official Helm Chart version

1.11.0

### Apache Airflow version

2.7.2

### Kubernetes Version

1.26.6

### Helm Chart configuration

A few relevant configs
```yaml
executor: CeleryExecutor  # but we also use KubernetesPodOperator

workers:
  persistence:
    enabled: false

logs:
  persistence:
    enabled: false

config:
  logging:
    base_log_folder: "/opt/airflow/logs"
    remote_logging: "True"
    logging_level: "INFO"
    remote_base_log_folder: "wasb-${local.customer}-${local.tenant}-airflow-logs"
    remote_log_conn_id: "wasb_remote_airflow"
    logging_config_class: "log_config.LOGGING_CONFIG"
```

### What happened

I discovered that our airflow workers were taking ~10 minutes to start up during a helm release. When I investigated the pod logs, I found a couple `FailedMount` errors.

![image](https://github.com/apache/airflow/assets/20371880/7a279df6-2af1-4b28-a069-effd750472e4)

[The docs suggest disabling worker persistence when using celery workers](https://airflow.apache.org/docs/helm-chart/stable/manage-logs.html#no-persistence), so I disabled it.

Now when accessing logs in the UI for a currently running task (either Celery or KubernetesExecutor), I see this error message:

```
airflow-worker-596d48d584-qjtjv
*** No logs found in WASB; ti=%s <TaskInstance: ... [running]>
*** Could not read served logs: [Errno -2] Name or service not known
```

After the task has completed, the logs are successfully loaded from a remote source as expected. If I re-enable worker persistence, I can access logs for running tasks again.

### What you think should happen instead

Even with worker persistence disabled, I expect to be able to retrieve logs of currently running tasks.

### How to reproduce

Deploy airflow to k8s via the official helm chart with the configs shared above. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
