### ISSUE TITLE
git-sync-init resources is too indented

### ISSUE THREAD

**Issue by slmg** [apache/airflow#35815]
### Official Helm Chart version

1.10.0

### Apache Airflow version

2.6.3

### Kubernetes Version

1.27.7

### Helm Chart configuration

values.yaml

```yaml
  # Git sync
  dags:
    gitSync:
      enabled: true

      repo: git@git/path/to/dag.git
      branch: main
      depth: 1
      # subpath within the repo where dags are located
      subPath: "dags"

      # the number of consecutive failures allowed before aborting
      maxFailures: 3

      # credentialsSecret: airflow-github-credentials
      sshKeySecret: airflow-ssh-secret

      knownHosts: |
        my-known-host
      # interval between git sync attempts in seconds
      # high values are more likely to cause DAGs to become out of sync between different components
      # low values cause more traffic to the remote git repository
      wait: 60
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 100Mi
```

### What happened

Resources get too much indented. This is due to this line https://github.com/apache/airflow/blob/a794e0d020f70aca4a0d81b953402a92a430635e/chart/templates/_helpers.yaml#L253

### What you think should happen instead

A simple change should be made to indent one level up the tree

```yaml
resources: {{ toYaml .Values.dags.gitSync.resources | nindent 4 }} # not 6 
```

### How to reproduce

Inflate helm chart with given values.yaml and notice the extra indent everywhere gitsync is templated (e.g. scheduler)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  template:
    spec:
      initContainers:
        - name: git-sync-init
          resources: 
              limits:
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 100Mi
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
