### ISSUE TITLE
Helm chart  install process fails on Openshift OKD 4.13

### ISSUE THREAD

**Issue by maczg** [apache/airflow#36696]
### Official Helm Chart version

1.11.0 (latest released)

### Apache Airflow version

2.7.1

### Kubernetes Version

Openshift OKD 4.13 Kubernetes v1.26

### Helm Chart configuration

Default values or Custom values make no difference

### What happened

Following [docs](https://airflow.apache.org/docs/helm-chart/stable/index.html) in order to install airflow by helm chart, helm hangs completing installation and suddenly fails by timeout. 

### What you think should happen instead

Smooth install of the chart

### How to reproduce

Follow exactly same procedure of [docs](https://airflow.apache.org/docs/helm-chart/stable/index.html)

### Anything else

Openshift has strict secure policy context handling. In the newest version of the chart, i found that scc are resolved from almost all of airflow core components, except for postgres statefulset that it will be managed by default serviceaccount instead of a proper sa with proper scc. 

Manually add a proper scc (e.g `priviledged` or `anyuid`) to default sa and then rolling out statefulset will enable deployment of postgres and consequently all other pods that depends of it

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by cmarteepants** [comment]
Postgres is a subchart, and is only there for convenience only. We strongly do not recommend that you use the postgresql chart for anything other than a POC.

According to the[ bitnami postgres chart readme](https://github.com/bitnami/charts/tree/main/bitnami/postgresql#differences-between-bitnami-postgresql-image-and-docker-official-image), you need to do the following for Openshift 4.11+:

> For OpenShift 4.11 and higher, let set OpenShift the runAsUser and fsGroup automatically. Configure the pod and container security context to restrictive defaults and disable the volume permissions setup: primary. podSecurityContext.fsGroup=null,primary.podSecurityContext.seccompProfile.type=RuntimeDefault,primary.containerSecurityContext.runAsUser=null,primary.containerSecurityContext.allowPrivilegeEscalation=false,primary.containerSecurityContext.runAsNonRoot=true,primary.containerSecurityContext.seccompProfile.type=RuntimeDefault,primary.containerSecurityContext.capabilities.drop=['ALL'],volumePermissions.enabled=false,shmVolume.enabled=false

It may not work due to a [helm bug](https://github.com/helm/helm/issues/12637) with nulls and subcharts, but here are the values you will need to override:
 ```
postgresql:
  primary:
    podSecurityContext:
      fsGroup: null
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      runAsUser: null
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
  volumePermissions:
    enabled: false
  shmVolume:
    enabled: false
```

If you're running into the helm bug, your only other option is to download the chart and subchart, and edit the subchart values directly. 

Since Airflow itself is compatible with Openshift, I will be closing the issue. Good luck!
