### ISSUE TITLE
Airflow Helm chart fails to deploy with ArgoCD

### ISSUE THREAD

**Issue by alex-slynko** [apache/airflow#37399]
### Official Helm Chart version

1.12.0 (latest released)

### Apache Airflow version

latest

### Kubernetes Version

1.29

### Helm Chart configuration

No parameters with the simple ArgoCD deployment (5.51.x).

### Docker Image customizations

no

### What happened

ArgoCD fails to deploy with `Unable to create application: application spec for airflow-test is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = illegal filepath in archive: /tmp/d629b287-bcfd-4ca1-b827-33aa871dae80`

### What you think should happen instead

ArgoCD should be able to create application

### How to reproduce

1. Deploy ArgoCD
2. Create a simple ArgoCD application from UI
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'airflow-test'
spec:
  project: default
  source:
    repoURL: 'https://airflow.apache.org'
    targetRevision: 1.12.0
    helm:
      releaseName: airflow-test
      version: v3
    chart: airflow
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

### Anything else

Issue in ArgoCD https://github.com/argoproj/argo-cd/issues/17182

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
