### ISSUE TITLE
AIRFLOW_HOME doesn't propagate to logGroomerSidecar

### ISSUE THREAD

**Issue by jabbera** [apache/airflow#37579]
### Official Helm Chart version

1.12.0 (latest released)

### Apache Airflow version

2.8.1

### Kubernetes Version

1.28.3

### Helm Chart configuration

values.yaml ->

airflowHome: /tmp/airflow

### Docker Image customizations

None

### What happened

AIRFLOW_HOME is not an environment variable listed on any logGroomerSidecar. This means the wrong directory is being groomed when a custom AIRFLOW_HOME is used:
```
- args:
    - bash
    - /clean-logs
    env:
    - name: AIRFLOW__LOG_RETENTION_DAYS
      value: "15"
    image: <SNIP>/production:test
    imagePullPolicy: Always
    name: scheduler-log-groomer
```

### What you think should happen instead

Variable should be defined

### How to reproduce

Install with values.yaml:
 
airflowHome: /tmp/airflow

Run:
kubectl -n airflow-test get pod -l "component=scheduler" -o yaml  | grep -i "clean-logs" -A 5 -B 5

Notice no AIRFLOW_HOME attached to scheduler:

```
    - args:
      - bash
      - /clean-logs
      env:
      - name: AIRFLOW__LOG_RETENTION_DAYS
        value: "15"
      image: <SNIP>
```

The same happens everywhere the logGroomerSidecar is enabled.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
