### ISSUE TITLE
migrateDatabaseJob: Additional property labels is not allowed

### ISSUE THREAD

**Issue by ikholodkov** [apache/airflow#37776]
### Official Helm Chart version

1.12.0 (latest released)

### Apache Airflow version

-

### Kubernetes Version

-

### What happened

Trying to check template via _helm template airflow apache-airflow/airflow -f values.yml -f override.yml_
I got an error `migrateDatabaseJob: Additional property labels is not allowed`.
I didn't describe migrateDatabaseJob in override.yml
I guess it may be due to this [PR](https://github.com/apache/airflow/pull/37490)

Error occurs even I have labels section in migrateDatabaseJob, 

```
migrateDatabaseJob:
  labels:
    tier: airflow
    component: run-airflow-migrations
```
but disappear when labels described without whitespaces
```
migrateDatabaseJob:
labels:
  tier: airflow
  component: run-airflow-migrations
```

### How to reproduce

helm repo add apache-airflow https://airflow.apache.org

Copy [values](https://github.com/apache/airflow/blob/main/chart/values.yaml)

Create override.yml and try to check template helm template airflow apache-airflow/airflow -f values.yml -f override.yml

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
