### ISSUE TITLE
helm values schemas are built with kubernetes 1.22 resources

### ISSUE THREAD

**Issue by mathiaHT** [apache/airflow#38453]
### Official Helm Chart version

1.13.0 (latest released)

### Apache Airflow version

2.8.2

### Kubernetes Version

1.29

### Helm Chart configuration

```yaml
# Chart.yaml
dependencies:
  - name: airflow
    version: 1.13.0
    repository: https://airflow.apache.org

# values.yaml
airflow:
  executor: KubernetesExecutor
  workers:
    extraInitContainers:
      - name: otel
        image: otel/opentelemetry-collector:0.57.2
        args: ["--config=file:/etc/otelcol/config.yml"]
        restartPolicy: Always
```

### What happened

Error: values don't meet the specifications of the schema(s) in the following chart(s):
airflow:
- workers.extraInitContainers.0: Additional property restartPolicy is not allowed

### How to reproduce

helm install my-chart chart/ -f values.yaml

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
