### ISSUE TITLE
Can't use AIRFLOW__CELERY__BROKER_URL_CMD in the Helm Chart

### ISSUE THREAD

**Issue by chrisluedtke** [apache/airflow#39985]
### Official Helm Chart version

1.13.1 (latest released)

### Apache Airflow version

2.9.1

### Kubernetes Version

1.28.9

### Helm Chart configuration

```yaml
env:
  - name: AIRFLOW__CELERY__BROKER_URL_CMD
    value: |
      python -c '
      import urllib.parse, os
      pw = os.getenv("REDIS_PASSWORD")
      print(urllib.parse.quote_plus(f"redis://:${pw}@data-airflow-redis:6379/0", end="")
      '

envFrom:
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: airflow-redis-password
        key: password

redis:
  enabled: true
  passwordSecretName: airflow-redis-password

enableBuiltInSecretEnvVars:
  AIRFLOW__CELERY__BROKER_URL: false
```

### What happened

[Documentation suggests](https://airflow.apache.org/docs/helm-chart/stable/production-guide.html#built-in-secrets-and-environment-variables) that I can set my broker URL via a bash command. However, I get this error:
```
Error: execution error at (data-airflow/charts/airflow/templates/check-values.yaml:34:11): When using the internal redis of the chart and setting the value redis.passwordSecretName, you must also set the value data.brokerUrlSecretName.
```

### What you think should happen instead

Either the docs should be updated to reflect that developers can't use this env var, or the chart's value checks should be updated to allow setting only `redis.passwordSecretName` and not `redis.brokerUrlSecretName`.

### How to reproduce

The chart is rejecting my inputs as defined here: 
https://github.com/apache/airflow/blob/main/chart/templates/check-values.yaml#L33

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
