### ISSUE TITLE
Support extraInitContainers for migrateDatabaseJob

### ISSUE THREAD

**Issue by Joel-Robinson-Redox** [apache/airflow#40359]
### Official Helm Chart version

1.14.0 (latest released)

### Apache Airflow version

2.8.3

### Kubernetes Version

1.29

### What happened

We had been having problems with getting Airflow workers pods to terminate after the main container finished successfully since we also had a sql proxy that was running in a sidecar. We were able successfully resolve the issue after and update to Helm chart v1.14 and configuring the sql-proxy as an `extraInitContainer`. This allows us to use the new [init containers sidecars for Kubernetes v1.29](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/). 

Unfortunately we are not able to do the same thing for the `migrateDatabaseJob`. We have run into the same issue on the `migrateDatabaseJob` of pods that hang after the main container has finished and it would be greats to be able to use to the pattern described above with these as well to make Airflow version updates go more smoothly. 

### What you think should happen instead

Please add support for creating init containers to the `migrateDatabaseJob` and perhaps the `createUserJob` so that we have the option to use [init containers sidecars for Kubernetes v1.29](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/). 

### How to reproduce

The migrateDatabase job will hang if configured to us cloud-sql-proxy for GCP.  This will affect any other pods configured to `waitForMigrations`. 
```yaml
# Airflow database migration job settings
migrateDatabaseJob:
  enabled: false
  useHelmHooks: false
  command: ~
  args:
    - "bash"
    - "-c"
    - >-
      exec \

      airflow {{ semverCompare ">=2.7.0" .Values.airflowVersion
      | ternary "db migrate" (semverCompare ">=2.0.0" .Values.airflowVersion
      | ternary "db upgrade" "upgradedb") }}

  serviceAccount:
    automountServiceAccountToken: true
    create: false
    name: airflow-default
  extraContainers:
    - name: cloud-sql-proxy
      ports:
      - containerPort: 5432
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
      command: ["/cloud-sql-proxy"]
      args:
        - "--structured-logs"
        - "--address=0.0.0.0"
        - "--private-ip"
        - "--auto-iam-authn"
        - "--quitquitquit"
        - "gcp-server:us-central1:airflow?port=5432"
      securityContext:
        runAsNonRoot: true
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
