### ISSUE TITLE
Mapping key "cluster-autoscaler.kubernetes.io/safe-to-evict" already defined

### ISSUE THREAD

**Issue by elehcim** [apache/airflow#40606]
### Official Helm Chart version

1.14.0 (latest released)

### Apache Airflow version

2.9.2

### Kubernetes Version

1.28

### Helm Chart configuration

```yaml
executor: CeleryKubernetesExecutor
```

### How to reproduce

```yaml
# kustomization.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

helmCharts:
- name: airflow
  releaseName: airflow
  version: "1.14.0"
  repo: https://airflow.apache.org
  valuesInline:
    executor: CeleryKubernetesExecutor
```

```
kustomize build --enable-helm .
```
Resulting in 
```
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 44: mapping key "cluster-autoscaler.kubernetes.io/safe-to-evict" already defined at line 43
```

### Anything else

Similar to #38183

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
