### ISSUE TITLE
Error: INSTALLATION FAILED: YAML parse error on airflow/templates/jobs/create-user-job.yaml: error converting YAML to JSON

### ISSUE THREAD

**Issue by darshanc99** [apache/airflow#40666]
### Official Helm Chart version

1.14.0 (latest released)

### Apache Airflow version

1.14.0

### Kubernetes Version

1.30.0

### Helm Chart configuration

Hi community, I am trying to deploy Airflow to EKS using Helm Charts.
The modifications I have made is only to the values.yaml file.
The modifications I have made:

1. Set-up a connection with ECR to pull the Docker image with DAGs.
2. Set-up a connection with RDS postgres to log metadata.

### What happened

When trying to install, with the command `helm install` to my EKS cluster; the installation failed with the error:

> Error: INSTALLATION FAILED: YAML parse error on airflow/templates/jobs/create-user-job.yaml: error converting YAML to JSON: yaml: line 43: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 43: did not find expected key
YAML parse error on airflow/templates/jobs/create-user-job.yaml

**Note:** I have not made any changes/modifications to any template file except the values.yaml file.

### What you think should happen instead

I should not see the parsing error.

### How to reproduce

1. Set-up a Docker image with the DAGs on your ECR repository, and set-up the connection in values.yaml to pull the Docker image as:
    -   Define ECR Connection in `values.yaml`:
            ```
            env:
              - name: AIRFLOW_CONN_ECR_REGISTRY
                value: '{"conn_type": "docker", "host": "<aws-account-id>.dkr.ecr.<region>.amazonaws.com", "login": "AWS", "password": "your-decoded-password", "extra": "{\"region_name\": \"<region>\"}"}'
            ```
      -   Reference ECR Connection in `values.yaml`:
          ```
          image:
              repository: "{{ conn.AIRFLOW_CONN_ECR_REGISTRY }}"
              tag: latest
              pullPolicy: IfNotPresent
          ```
2. Set-up RDS Connection as in your values.yaml file as:
```
data:
    metadataConnection:
    user: postgres
    password: ""
    protocol: postgresql
    host: HOST.us-east-1.rds.amazonaws.com
    port: 5432
    db: postgres
    sslmode: require
```

3. Change the executor to KubernetesExecutor.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
