### ISSUE TITLE
Setting podAnnotations for workers also adds them to other deployments such as scheduler

### ISSUE THREAD

**Issue by joshuaghezzi** [apache/airflow#40804]
### Official Helm Chart version

1.14.0 (latest released)

### Apache Airflow version

2.9.2

### Kubernetes Version

EKS 1.30

### Helm Chart configuration

```
executor: "KubernetesExecutor"

workers:
  podAnnotations:
    "karpenter.sh/do-not-disrupt": "true"
```

### Docker Image customizations

Yes but not relevant to this I don't think.

### What happened

Configuring podAnnotations for workers results in other deployments such as the scheduler also getting those annotations if using `executor: "KubernetesExecutor"`

### What you think should happen instead

Only the worker pods should get those annotations.

### How to reproduce

Configure the helm chart with executor and worker podAnnotations such as

```
executor: "KubernetesExecutor"

workers:
  podAnnotations:
    "karpenter.sh/do-not-disrupt": "true"
```

### Anything else

We added this annotation in conjunction with updating our helm chart version from `1.13.1` to `1.14.0` so unsure if it occurs on earlier helm chart versions. Having a look at the release notes though it looks like this may potentially be the culprit https://github.com/apache/airflow/pull/37352 since it looks like it overwrites `airflowPodAnnotations` with `workers.podAnnotations`.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by romsharon98** [comment]
I attempted to reproduce the issue in the main branch but was unsuccessful. 
I modified the worker.podAnnotation as you suggested, and this is the result I got in the scheduler deployment annotation section:

```
annotations:
        checksum/metadata-secret: 8c8ccea43b91003b5ed19c1cb7ae904bdbee3fa66010c473b88fb196e3c25e59
        checksum/result-backend-secret: 98a68f230007cfa8f5d3792e1aff843a76b0686409e4a46ab2f092f6865a1b71
        checksum/pgbouncer-config-secret: 1dae2adc757473469686d37449d076b0c82404f61413b58ae68b3c5e99527688
        checksum/airflow-config: af9a572727db12dc95b758037573ef675d45e33c4acf8e5ee7b2d4184e228577
        checksum/extra-configmaps: e862ea47e13e634cf17d476323784fa27dac20015550c230953b526182f5cac8
        checksum/extra-secrets: e9582fdd622296c976cbc10a5ba7d6702c28a24fe80795ea5b84ba443a56c827
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
```

Maybe you have changed your configuration in `airflowPodAnnotations` section?
