### ISSUE TITLE
[helm] - Flower ingress incorrect when fullnameOverride applied

### ISSUE THREAD

**Issue by andormarkus** [apache/airflow#41175]
### Official Helm Chart version

1.15.0 (latest released)

### Apache Airflow version

2.8.3

### Kubernetes Version

1.29

### Helm Chart configuration

`values.yaml`
```yaml
airflow:
  fullnameOverride: "airflow"
```

### What happened

We are sub charting the official airflow chart and for this reason we need to use `fullnameOverride: "airflow"` settings to achieve the desired k8s resource names. However when we are using it the flower ingress becomes invalid because it want's to connect to non existing service name. Root cause are in the ingress.yaml. The webserver ingress can handle it with no problem.

Incorrect code section

`flower-ingress.yaml` - [code section](https://github.com/apache/airflow/blob/daccc75b064c735636027b20f3edb82da69ffab1/chart/templates/flower/flower-ingress.yaml#L75)
```yaml
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}-flower
                port:
                  name: flower-ui
```

While in the correct code section

`webserver-ingress.yaml` - [code section](https://github.com/apache/airflow/blob/daccc75b064c735636027b20f3edb82da69ffab1/chart/templates/webserver/webserver-ingress.yaml#L83)

```yaml
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ $fullname }}-webserver
                port:
                  name: airflow-ui
```

To overcome this issue we need to run this command on every deployment
```bash
kubectl patch ingress airflow-flower-ingress \
    --namespace "airflow" \
    --type='json' \
    -p='[{"op": "replace", "path": "/spec/rules/0/http/paths/0/backend/service/name", "value":"airflow-flower"}]'
```

### What you think should happen instead

The following code should be updated to match how webserver ingress works
`flower-ingress.yaml` - [code section](https://github.com/apache/airflow/blob/daccc75b064c735636027b20f3edb82da69ffab1/chart/templates/flower/flower-ingress.yaml#L75)
```yaml
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ $fullname }}-flower
                port:
                  name: flower-ui
```

### How to reproduce

Sub chart the official chart with this configuration
`values.yaml`
```yaml
airflow:
  fullnameOverride: "airflow"
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
