### ISSUE TITLE
Docker + Kubernetes + HyperV + Helm persistent volume doesn't mount

### ISSUE THREAD

**Issue by SledgeHammer01** [apache/airflow#41269]
### Apache Airflow version

2.9.3

### What happened?

I'm trying to use:

```
        dags:
          persistence:
            enabled: true
            existingClaim: airflow

```

To mount a shared DAG folder. Host machine is Windows 11. I'm running Docker Desktop + Kubernetes + HyperV backend.

My yaml looks like:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /host_mnt/c/users/xxx/.airflow
```

I've tried other formats like `/run/desktop/mnt/host/c/users/xxx/.airflow` (this one works on a WSL backend), `/users/xxx/.airflow, etc`. `/users/xxx/.airflow` has full permissions on the the Windows box.

### How to reproduce

N/A

### Operating System

Windows 11

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
