### ISSUE TITLE
OpenTelemetry metrics are not getting sent

### ISSUE THREAD

**Issue by nazarii-koblai** [apache/airflow#41606]
### Official Helm Chart version

1.15.0 (latest released)

### Apache Airflow version

2.9.3

### Kubernetes Version

1.28.9

### Helm Chart configuration
```
config:
  metrics:
    otel_on: 'True'
    otel_host: opentelemetrycollector-service.observability
    otel_port: '4318'
    otel_prefix: 'airflow'
    otel_debugging_on: 'True'
```
### Docker Image customizations

Yes, I did extend official airflow image with some additional dependencies and minor UI changes.

### What happened

After applying values.yaml configuration I don't see any either logs about metrics or calls to the OTEL collector.

### What you think should happen instead

Logs about metrics should be shown and those metrics should be sent to OTEL collector.

### How to reproduce

Try to change airflow.cfg or use env variables to setup OpenTelemetry metrics.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
