### ISSUE TITLE
Unable to specify env variables using fieldPath

### ISSUE THREAD

**Issue by azadabbasi** [apache/airflow#41655]
### Official Helm Chart version

1.14.0

### Apache Airflow version

2.9.2

### Kubernetes Version

v1.30.2

### Helm Chart configuration

Using Argo CD to deploy the helm chart

### Docker Image customizations

No customization

### What happened

I need to be able to add env variables like the one below to my airflow containers (all of them) but the helm chart does not support these ... or at least I don't know how to do it.

```yaml
env:
    - name: DOGSTATSD_HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: STATSD_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
```

### What you think should happen instead

env should support specifying env variables that reference fieldRef

### How to reproduce

Try adding the env vars above and helm template will fail with:

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm template . --name-template airflow-core-deployment-stage --namespace airflow--core-deployment--stage --kube-version 1.29 --values <path to cached source>/charts/airflow/instances/awscmhstage2/values.yaml <api versions removed> failed exit status 1: Error: values don't meet the specifications of the schema(s) in the following chart(s): airflow: - env.5: value is required - env.5: Additional property valueFrom is not allowed - env.6: value is required - env.6: Additional property valueFrom is not allowed
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by azadabbasi** [comment]
I just found the solution:

```yaml
  extraEnv: |
    - name: DOGSTATSD_HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: STATSD_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
```
