### ISSUE TITLE
AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES  and AIRFLOW__KUBERNETES_SECRETS not working properly

### ISSUE THREAD

**Issue by jordi-crespo** [apache/airflow#42008]
### Apache Airflow Provider(s)

cncf-kubernetes

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes 8.3.4

### Apache Airflow version

2.9.2

### Operating System

Docker - Debian 12

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

I am deploying airlfow in Azure Kubernetes Service version 1.29 using helm chart version 1.15

### What happened

I'm deploying Apache Airflow 2.9.2 with the Kubernetes Executor in an AKS cluster.

KubernetesExecutor will create a pod for each of the tasks to be executed. 

I see that this pod is defined by a pod template. You can use the default pod template or you can create a pod template from the [official helm chart](https://github.com/apache/airflow/blob/main/chart/values.yaml#L2575).

I have created this template in my helm chart:

```yaml
podTemplate: |-
      apiVersion: v1
      kind: Pod
      metadata:
        name: airflow-task-pod
      spec:
        serviceAccountName: airflow-worker
        containers:
          - name: base
            image: {{ .Values.images.airflow.repository }}:{{ .Values.images.airflow.tag }}
            imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
            resources:
              requests:
                cpu: 0.5
                memory: "1Gi"
              limits:
                cpu: 2
                memory: "3Gi"
            env:
              - name: AIRFLOW__CORE__EXECUTOR
                value: LocalExecutor
              {{- include "custom_airflow_environment" . | indent 6 }}
              - name: AIRFLOW_CONN_AIRFLOW_DB
                valueFrom:
                  secretKeyRef:
                    name: airflow-metadata-connection
                    key: connection
              - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
                valueFrom:
                  secretKeyRef:
                    name: airflow-metadata-connection
                    key: connection
              - name: AIRFLOW__CORE__FERNET_KEY
                valueFrom:
                  secretKeyRef:
                    name: airflow-fernet-key
                    key: fernet-key
              
        tolerations:
          - key: "kubernetes.azure.com/scalesetpriority"
            operator: "Equal"
            value: "spot"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "kubernetes.azure.com/scalesetpriority"
                      operator: In
                      values:
                        - "spot"
```

This is working correctly, since I can pass to the pod the env variables that I have defined in the [extraEnv section](https://github.com/apache/airflow/blob/main/chart/values.yaml#370) and the secrets that I have created in the [secret section](https://github.com/apache/airflow/blob/main/chart/values.yaml#287).

```
{{- include "custom_airflow_environment" . | indent 6 }}
```

This will execute the function defined in the [`_helpers.yaml`](https://github.com/apache/airflow/blob/main/chart/templates/_helpers.yaml#L148) from the airflow helm chart.

What I find strange is that when the helm chart detects that it is KubernetesExecutor, in the deployments it executes the same helper function, which creates env variables with the prefix [`AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__`](https://github.com/apache/airflow/blob/main/chart/templates/_helpers.yaml#L154) and secrets with the prefix [`AIRFLOW__KUBERNETES_SECRETS__`](https://github.com/apache/airflow/blob/main/chart/templates/_helpers.yaml#L168).

As you can see in the image, I load this parameters in the configurations

[![enter image description here][1]][1]

I was expecting that this secrets and env variables are passed to the Pod created by KubernetesExecutor, but it is not the case.

I see this [PR from 2019](https://github.com/apache/airflow/pull/4627/files), where there was documentation related to the `kubernetes_environment_variables` and `kubernetes`, but I cannot see it any more in the current master branch in the [airflow github repository](https://github.com/apache/airflow).

In the airflow repository I see that the pod that is generated by the `pod_generator.py` file, and it is creating only one env variable, [in this line of code](https://github.com/apache/airflow/blob/main/airflow/providers/cncf/kubernetes/pod_generator.py#L444).

[![enter image description here][2]][2]

So I wonder, if this is really something that was used before and now it is not used anymore? should it be removed from the helm chart or am I configuring it incorrectly?

  [1]: https://i.sstatic.net/Yj4qINAx.png
  [2]: https://i.sstatic.net/v8mKyICo.png

### What you think should happen instead

The env variables and secrets created by the helm chart with the prefixes `AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__`  and secrets with the prefix `AIRFLOW__KUBERNETES_SECRETS__` should be passed to the pod created by KubernetesExecutor.

There is no documentation on these variables, if they are not used for this purpose, define in the documentation or in the helm chart what they are used for.

### How to reproduce

use the following `values.yaml`

```yaml
executor: "KubernetesExecutor"

env:
  - name: AIRFLOW_HOME
    value: '/usr/local/airflow'
  - name: AIRFLOW__MERCHANT__URL
    value: ${MERCHANT_URL}
  - name: MAILGUN_CUSTOM_EMAIL_BASE_URL
    value: 'emails.tapp.cafe'
  - name: MAILGUN_BASE_URL
    value: 'emails.tapp.cafe'
  - name: AIRFLOW_CONN_INSIGHTS_SA
    value: ${AIRFLOW_CONN_INSIGHTS_SA}
  - name: AIRFLOW_CONN_AZURE_LOGS
    value: ${AIRFLOW_CONN_AZURE_LOGS}
  - name: AIRFLOW_CONN_EVENTHUB
    value: ${AIRFLOW_CONN_EVENTHUB}
  - name: AIRFLOW_CONN_MERCHANT_API
    value: ${AIRFLOW_CONN_MERCHANT_API}
  - name: AIRFLOW_CONN_KNMI
    value: 'https://www.daggegevens.knmi.nl'

podTemplate: |-
  apiVersion: v1
  kind: Pod
  metadata:
    name: airflow-task-pod
    annotations:
      ad.datadoghq.com/airflow-webserver.check_names: '["airflow"]'
      ad.datadoghq.com/airflow-webserver.init_configs: "[{}]"
      ad.datadoghq.com/airflow-webserver.instances: |
        [
          {
            "url": "http://%%host%%:8080",
            "airflow_environment": ${AIRFLOW_CORE_ENV},
            "tags": ["env:${AIRFLOW_CORE_ENV}", "component:worker-pod", "cloud_provider:azure"]
          }
        ]
    labels:
      azure.workload.identity/use: "true"
  spec:
    containers:
      - name: base
        image: {{ .Values.images.airflow.repository }}:{{ .Values.images.airflow.tag }}
        imagePullPolicy: {{ .Values.images.airflow.pullPolicy }}
        resources:
          requests:
            cpu: 0.5
            memory: "1Gi"
          limits:
            cpu: 2
            memory: "3Gi"
    tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "kubernetes.azure.com/scalesetpriority"
                  operator: In
                  values:
                    - "spot"

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
