### ISSUE TITLE
gitSync: allow gitSync.env to take a env var from a secret reference

### ISSUE THREAD

**Issue by connorlwilkes** [apache/airflow#42024]
### Description

Currently the schema for gitSync.env does not allow you to define env from secrets like:
```
env:
        - name: GIT_SYNC_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitsync-secret
              key: username
        - name: GITSYNC_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitsync-secret
              key: username
        - name: GIT_SYNC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitsync-secret
              key: pwd
        - name: GITSYNC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitsync-secret
              key: pwd
```

This is because the schema is overly restrictive and doesn't just reference the upstream [V1EnvVar](https://github.com/apache/airflow/blob/58820a914c9b84c378c9bc1acd4ddbcb4e4a3497/chart/values.schema.json#L8173-L8175). See: https://github.com/apache/airflow/blob/main/chart/values.schema.json#L8557-L8583

### Related issues

https://github.com/apache/airflow/pull/39031

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
