### ISSUE TITLE
unicodecsv dependency makes apache-airflow Python package un-installable

### ISSUE THREAD

**Issue by Chais** [apache/airflow#42892]
### Apache Airflow version

2.10.2

### What happened?

Airflow cannot be installed in a venv with any system that properly solves dependencies and version requirements.

This happens because the lowest supported Python version of `apache-airflow` is 3.8, while the highest supported version of `unicodecsv` is 3.5. So there is no Python version that would be supported by `apache-airflow` and all of its dependencies, making it un-installable.

### What you think should happen instead?

I know `unicodecsv` has been dropped as a dependency very recently, but no new version has been released since then.

### How to reproduce

I encountered the issue with Poetry, but any tool that ensures all requirements for dependency packages are met will encounter the same issue.  
I encountered the issue targeting Python 3.8, but since there is no overlap between supported Python versions between `unicecsv` and `apache-airflow` it doesn't really matter.

Paste the following `pyproject.toml` into an empty directory:
```toml
[tool.poetry]
name = "airflow-dependency-test"
version = "0.1.0"
description = ""
authos = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "~3.8"
apache-airflow = "2.10.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core >= 1.0.0"]
build-backend = "poetry-core.masonry.api"
```

In a terminal navigate to the directory and run `poetry install`

### Operating System

Ubuntu 22.04

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
