### ISSUE TITLE
GitSync Credentials Secret requires 2 different sets of data fields

### ISSUE THREAD

**Issue by johnstonmatt** [apache/airflow#43247]
### Official Helm Chart version

1.15.0 (latest released)

### Apache Airflow version

chart default

### Kubernetes Version

1.28

### Helm Chart configuration

```yaml
targetRevision: 1.15.0
destinationNamespace: airflow
repoURL: 'https://airflow.apache.org'
chart: airflow
values:
  executor: LocalKubernetesExecutor
  data:
    metadataSecretName: postgresql-connection-string-secret
  postgresql:
    enabled: false
  dags:
    gitSync:
      enabled: true
      repo: 'https://github.com/johnstonmatt/demo-dag-bag'
      credentialsSecret: airflow-git-credentials
      branch: main
      wait: 40
      subPath: dags
    # less relevant but true
    enableBuiltInSecretEnvVars:
      AIRFLOW__CORE__FERNET_KEY: false
      AIRFLOW__WEBSERVER__SECRET_KEY: false
    fernetKeySecretName: airflow-fernet-key
    webserverSecretKeySecretName: airflow-webserver-key
    config:
      webserver:
        expose_config: 'True'
        instance_name: Polyseam
        enable_proxy_fix: 'True'
        base_url: 'https://airflow.bug-repro.mj.cndi.link'
      operators:
        default_owner: Polyseam
    logs:
      persistence:
        enabled: true
        size: 15Gi
        storageClassName: rwm
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      applyCustomEnv: false
      useHelmHooks: false
      jobAnnotations:
        "argocd.argoproj.io/hook": Sync      
```
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: airflow-git-credentials
  namespace: airflow
stringData:
  GIT_SYNC_USERNAME: 'foousername'
  GIT_SYNC_PASSWORD: 'barpassword'
  # newly required by airflow-triggerer, in addition to the pre-existing keys above
  GITSYNC_USERNAME: 'foousername'
  GITSYNC_PASSWORD: 'barpassword'
```

### What happened

`airflow-triggerer` needs the gitsync credentials to be formatted as `GITSYNC_USERNAME` and `GITSYNC_PASSWORD`, while the rest of the chart seems to require `GIT_SYNC_USERNAME` and `GIT_SYNC_PASSWORD`

### What you think should happen instead

the airflow helm chart should adhere to only one format rather than requiring both

### How to reproduce

If you need to reproduce:

1. Use [cndi](https://cndi.run/gh?utm_id=5111) to install `airflow` via ArgoCD: `cndi create ghusername/my-repo -t airflow`
2. after cluster is deployed and working, update from `targetRevision: '1.11.0'` to `targetRevision: '1.15.0'`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
