### ISSUE TITLE
Can't add Connections through Helm Official chart

### ISSUE THREAD

**Issue by bmt8** [apache/airflow#45295]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.9.3

### What happened?

I was following the [example of the docs on how to add a connection ](https://airflow.apache.org/docs/helm-chart/stable/adding-connections-and-variables.html), 

I'm trying to add an example conn by uri:
`HTTP_EXAMPLE=http://abc:123@foo`

and so adapted my values.yaml:
```
secret:
  - envName: "AIRFLOW_CONN_HTTP_EXAMPLE"
    secretName: "my-airflow-connections"
    secretKey: "AIRFLOW_CONN_HTTP_EXAMPLE"

extraSecrets:
  my-airflow-connections:
    data: |
      AIRFLOW_CONN_HTTP_EXAMPLE: 'aHR0cDovL2FiYzoxMjNAZm9v'
```

Then checked the envvars of scheduler to see if the conn variable was set and I could see my env there:
`kubectl -n airflow exec -it airflow-scheduler-78fd579f5d-bv895 -- printenv` 
the result was:
```
AIRFLOW_CONN_HTTP_EXAMPLE=http://abc:123@foo
AIRFLOW__KUBERNETES_SECRETS__AIRFLOW_CONN_HTTP_EXAMPLE=my-airflow-connections=AIRFLOW_CONN_HTTP_EXAMPLE
```

But then when I get check the connections throught Web UI or CLI  (`airflow connections list`), it shows `No data found`.
```
$ airflow connections list
/home/airflow/.local/lib/python3.12/site-packages/airflow/metrics/statsd_logger.py:184 RemovedInAirflow3Warning: The basic metric validator will be deprecated in the future in favor of pattern-matching.  You can try this now by setting config option metrics_use_pattern_match to True.
No data found
```

I checked the logs of scheduler but found no clue, 
I'm wondering where to watch for logs of conns or help on how to fix this.

### What you think should happen instead?

A connection be added to the airflow

### How to reproduce

Officla helm chart version: `airflow-1.15.0`
App version: `2.9.3 `
Chart: `https://artifacthub.io/packages/helm/apache-airflow/airflow`

### Operating System

helm airflow-1.15.0

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
