### ISSUE TITLE
Metrics missing in v2.10.1

### ISSUE THREAD

**Issue by iamhritik** [apache/airflow#46805]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

v2.10.1

### What happened?

Currently I have following metrics missing from statsd (mapping samples):

mappings ---
```
  - labels:
      airflow_id: $1
      dag_id: $2
    match: '*.dagrun.duration.success.*'
    match_metric_type: observer
    name: af_agg_dagrun_duration_success
  - labels:
      airflow_id: $1
      dag_id: $2
    match: '*.dagrun.duration.failed.*'
    match_metric_type: observer
    name: af_agg_dagrun_duration_failed
  - labels:
      airflow_id: $1
      dag_id: $2
      task_id: $3
    match: '*.dag.*.*.duration'
    match_metric_type: observer
    name: af_agg_dag_task_duration
  - labels:
      airflow_id: $1
      dag_id: $2
    match: '*.dagrun.schedule_delay.*'
    match_metric_type: observer
    name: af_agg_dagrun_schedule_delay
```

executor = LocalExecutor
statsd-exporter:v0.26.1

Metrics configuration in airflow.cfg
```
[metrics]
statsd_on = True
statsd_host = localhost
statsd_port = 8125
statsd_prefix = airflow

metrics_use_pattern_match = True
```

### What you think should happen instead?

It will expose these metrics as well which is required for Airflow DAGs Grafana dashboard

### How to reproduce

Simply exposed metrics from airflow and then scrape it using prometheus

### Operating System

VERSION="22.04.5 LTS (Jammy Jellyfish)"

### Deployment

Other

### Deployment details

python package installed on aws ec2 instance

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
