### ISSUE TITLE
Missing initialDelaySeconds configuration of startupProbe

### ISSUE THREAD

**Issue by oryanperl** [apache/airflow#47093]
### Official Helm Chart version

1.15.0 (latest released)

### Apache Airflow version

2.9.3

### Kubernetes Version

v1.30.5

### Helm Chart configuration

![Image](https://github.com/user-attachments/assets/e9708aea-d62e-4c64-b601-8425ccb73dc5)

### What happened

Hi!
When running on small clusters sometimes the webserver takes longer period to start up
this causes the startupProbe to kill and restart the web server.

There is a possible workaround solution by configuring startupProbe's failureThreshold and periodSeconds but, as far as i can think of, the correct solution would be to configure initialDelaySeconds to allow slow pods to run the webserver before attempting to hearbeat it. 

![Image](https://github.com/user-attachments/assets/c6113e83-16ed-4a21-bbe4-9b1c92cc7c6d)

### What you think should happen instead

Allow initialDelaySeconds to startupProbes.

configuring initialDelaySeconds is already possible for livenessProbe and readinessProbe, so the addition is only needed for startupProbe

### How to reproduce

1. Running a small kubernetes cluster (e.g. docker desktop's default kubernetes cluster)

2. Run argocd on the cluster
```bash
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
```
3. Have an app of apps in argocd
4. Have app of apps define a child application which uses airflow chart, i.e.:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: 1.15.0
    helm:
      values: |-
        {{- with .Values.airflow }}
        {{- toYaml . | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.airflow.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
```

5. The manifest of startupProbe does not contain initialDelaySeconds

![Image](https://github.com/user-attachments/assets/48020901-fdd6-4baf-aa3e-f3fc2fc55df6)

### Anything else

I Would like to sole this issue and am willing to submit a PR

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
