### ISSUE TITLE
Building Docker image seems to ignore constraints

### ISSUE THREAD

**Issue by kurtrwall** [apache/airflow#47637]
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.10.3

### What happened?

I built an Airflow Docker image using this repo as the docker context on the 2.10.3 tag and I'm running into incompatibility issues with the version of the Celery provider package. The constraints.txt file at `/home/airflow/constraints.txt` baked in the image pins celery at 3.7.2 but `pip` says I have `3.10.2`. 

Docker build configuration of the airflow image:
```
    build:
      context: https://github.com/apache/airflow.git#2.10.3
      dockerfile: Dockerfile
      args:
        ADDITIONAL_DEV_APT_DEPS: gcc
        AIRFLOW_BRANCH: 2.10.3
        AIRFLOW_EXTRAS: apache-hdfs,apache-kafka,apache-spark,atlassian-jira,celery,docker,elasticsearch,http,ldap,postgres,redis,papermill,virtualenv
        AIRFLOW_UID: "2060"
        AIRFLOW_VERSION_SPECIFICATION: ==2.10.3
        INSTALL_MSSQL_CLIENT: "false"
        INSTALL_MYSQL_CLIENT: "false"
        INSTALL_POSTGRES_CLIENT: "true"
        PYTHON_BASE_IMAGE: python:3.12-slim-bookworm
```

Thanks for any assistance!

### What you think should happen instead?

I expect that the constraints file used would constrain the versions of the libraries installed, but that doesn't seem to be the case.

### How to reproduce

Create a compose file with a service that has a build configuration like so:
```
airflow:
    build:
      context: https://github.com/apache/airflow.git#2.10.3
      dockerfile: Dockerfile
      args:
        ADDITIONAL_DEV_APT_DEPS: gcc
        AIRFLOW_BRANCH: 2.10.3
        AIRFLOW_EXTRAS: apache-hdfs,apache-kafka,apache-spark,atlassian-jira,celery,docker,elasticsearch,http,ldap,postgres,redis,papermill,virtualenv
        AIRFLOW_UID: "2060"
        AIRFLOW_VERSION_SPECIFICATION: ==2.10.3
        INSTALL_MSSQL_CLIENT: "false"
        INSTALL_MYSQL_CLIENT: "false"
        INSTALL_POSTGRES_CLIENT: "true"
        PYTHON_BASE_IMAGE: python:3.12-slim-bookworm
```

### Operating System

OSX

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
