### ISSUE TITLE
Not able to deploy logs persistence

### ISSUE THREAD

**Issue by ronaldorcampos** [apache/airflow#48243]
### Apache Airflow version

2.10.5

### What happened?

I have Airflow running in EKS with CeleryKubernetesExecutor and Im unable to set logs persistence to use AWS EBS CSI driver. The PVC errors with 

```
  Normal   Provisioning          48s (x9 over 2m57s)  ebs.csi.aws.com_ebs-csi-controller-746b78965f-4tlrd_a43e92a0-9d72-4dfa-8a26-1bb48b74a19c  External provisioner is provisioning volume for claim "airflow/airflow-logs"
  Warning  ProvisioningFailed    48s (x9 over 2m57s)  ebs.csi.aws.com_ebs-csi-controller-746b78965f-4tlrd_a43e92a0-9d72-4dfa-8a26-1bb48b74a19c  failed to provision volume with StorageClass "gp2": rpc error: code = InvalidArgument desc = Volume capabilities not supported
```
when trying to assign `gp2` as storage class.

Since logs is not able to be provisioned, it holds all the deployment and all other components remain as pending.

### What you think should happen instead?

Like for workers, redis, or triggerer persistence, a PV should automatically be provisioned for the PVC given the AWS EBS CSI driver is correctly setup with proper service account.

### How to reproduce

Setup airflow in EKS using helm charts, enable AWS EBS CSI driver with correctly service account, and enable logs persistence when deploying:
```
logs:

  persistence:
    enabled: true
    storageClassName: "gp2"
    size: 50Gi
```

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

```
workers:
  persistence:
    enabled: true
    storageClassName: "gp2"
    size: 50Gi

redis:
  persistence:
    enabled: true
    storageClassName: "gp2"
    size: 10Gi

triggerer:
  persistence:
    enabled: true
    storageClassName: "gp2"
    size: 10Gi

# this fails
logs:
  persistence:
    enabled: true
    storageClassName: "gp2"
    size: 50Gi
```

### Anything else?

I have experienced the same issue in SUSE rancher as well using the vsphere csi driver where workers, redis, and triggerer persistence works but logs persistence does not.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
