### ISSUE TITLE
Webserver URL returns blank page for airflow standalone for 3.0.0rc1

### ISSUE THREAD

**Issue by dheerajturaga** [apache/airflow#48825]
### Apache Airflow version

3.0.0

### What happened?

Airflow URL returns blank page when running airflow standalone with 3.0.0rc1

What fails:
```
docker run -d -p 8080:8080 --name airflow_container apache/airflow:3.0.0.rc1.post4 airflow standalone
```
![Image](https://github.com/user-attachments/assets/c7451533-bad2-441a-b3ac-28ca12f4d503)

What passes:
```
docker run -d -p 8080:8080 --name airflow_container apache/airflow:2.10.5 airflow standalone
```
![Image](https://github.com/user-attachments/assets/1ec5f7c4-8409-40d5-b9ac-8a034ec34793)

### How to reproduce

```
docker run -d -p 8080:8080 --name airflow_container apache/airflow:3.0.0.rc1.post4 airflow standalone
```
Then open the browser http://0.0.0.0:8080

### Operating System

Ubuntu 24.04

### Deployment

Other Docker-based deployment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by tirkarthi** [comment]
Are you seeing any errors in the browser console as the page is empty?

**Comment by tirkarthi** [comment]
Looks like a CORS issue on loading the assets with `0.0.0.0` resolving to `127.0.0.1` . Can you please try http://localhost:8080 ?

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/static/assets/index-D7eB8u6o.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

**Comment by jscheffl** [comment]
I can confirm - http://127.0.0.1:8080 is not working (CORS) but http://localhost:8080 works.

**Comment by dheerajturaga** [comment]
I can confirm aswell. It would be great if this could be addressed

**Comment by Dev-iL** [comment]
I'd say this is a pretty serious limitation: I'm running docker on one machine and connecting to it from another, so I have no choice but using the hostname in the address.

**Comment by ashb** [comment]
We should change the default BASE_URL to be empty, and then pick the current base default based on the current request.host etc I think.

That will mean it works out of the box for Direct and breeze without needing extra changes.

**Comment by pierrejeambrun** [comment]
CORS  settings can be controlled from the config by:
- access_control_allow_headers
- access_control_allow_methods
-access_control_allow_origins

By default, only `localhost` is allowed.

**Comment by dheerajturaga** [comment]
From further debug, this doesn't seem to be a cors issue. Im still seeing this issue even after setting the following env:
```
AIRFLOW__API__ACCESS_CONTROL_ALLOW_HEADERS = "*"
AIRFLOW__API__ACCESS_CONTROL_ALLOW_METHODS = "*"
AIRFLOW__API__ACCESS_CONTROL_ALLOW_ORIGINS = "*"
```
I see these are passed through correctly to CORSMiddleware in `airflow/api_fastapi/core_api/app.py` init_config

I noticed the browser seems to be attempting to fetch from `localhost` always

**Comment by ashb** [comment]
Yeah, that base URL gets stamped in to the URL we use for the fetching the assets. That's what we should change,so that by default it's relative to the current URL or determined from the request.


Goal should be that the web UI works out of the box if run locally, or If run in a docker image (not breeze which sets up lots of extras already, just a plain `docker run -p 8080:8080` sort of thing)

**Comment by Dev-iL** [comment]
Just tested this on 3.0.0rc2:
- For a local container, the UI works when accessed using `127.0.0.1` or `localhost` (as before).
- For both a local and a remote container, when the host's hostname is used, there's an infinite redirection loop instead of a "simple" blank page.

These are the relevant configs from my `docker-compose.yaml` (which work for a local container with `localhost`; commented settings are unset):

```yaml
    # AIRFLOW__API__BASE_URL: http://${VM_HOSTNAME}:8080
    # AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__CORE__AUTH_MANAGER: airflow.api_fastapi.auth.managers.simple.simple_auth_manager.SimpleAuthManager
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: 'true'
    # AIRFLOW__FAB__AUTH_BACKENDS: 'airflow.providers.fab.auth_manager.api.auth.backend.basic_auth,airflow.providers.fab.auth_manager.api.auth.backend.session' 
    AIRFLOW__WEBSERVER__BASE_URL: http://${VM_HOSTNAME}:8080
```
