### ISSUE TITLE
Logs are not integrating with elasticsearch

### ISSUE THREAD

**Issue by peter-cheon** [apache/airflow#50349]
### Apache Airflow version

3.0.0

### What happened?

Hello,

I tried to set up log integration using the guide at
https://airflow.apache.org/docs/apache-airflow-providers-elasticsearch/stable/logging/index.html#writing-logs-to-elasticsearch,
but the integration is not working.

### How to reproduce

In the Helm chart, I enabled the host as shown below:

```
elasticsearch:
  # Enable elasticsearch task logging
  enabled: true
  # A secret containing the connection
  connection:
    scheme: http
    host: es-example.local
    port: 9200
```

I also added the following configuration:
```
  elasticsearch:
    host: 'es-example.local:9200'
    write_stdout: 'True'
    write_to_es: 'True'
    json_format: 'True'
    log_id_template: "{dag_id}_{task_id}_{execution_date}_{try_number}"
  elasticsearch_configs:
    max_retries: 3
    timeout: 30
    retry_timeout: 'True'
```

When I check inside the container using airflow.cfg, I can see the settings as below:
```
[logging]
colored_console_log = False
remote_logging = True

[elasticsearch]
host = es-example.local:9200
json_format = True
log_id_template = {dag_id}_{task_id}_{execution_date}_{try_number}
write_stdout = True
write_to_es = True

[elasticsearch_configs]
max_retries = 3
retry_timeout = True
timeout = 30
```

Running airflow info also shows:
```
> airflow info

Apache Airflow  
version                | 3.0.1rc1  
executor               | CeleryExecutor  
task_logging_handler   | airflow.providers.elasticsearch.log.es_task_handler.ElasticsearchTaskHandler  
sql_alchemy_conn       | postgresql://..../  
dags_folder            | /opt/airflow/dags/repo/sandbox  
plugins_folder         | /opt/airflow/plugins  
base_log_folder        | /opt/airflow/logs  
remote_base_log_folder | 
```

Everything appears to be configured correctly, but nothing is being written to the task logs.
I’m wondering if there is a problem with Elasticsearch integration in Airflow 3.0.

Thank you.

### Operating System

kubernetes

### Deployment

Other

### Deployment details

I deployed the Helm chart from https://github.com/apache/airflow/tree/main/chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by peter-cheon** [comment]
If Elasticsearch is disabled, the logs are displayed correctly.

**Comment by eladkal** [comment]
is the same configuration works on 2.10?

**Comment by peter-cheon** [comment]
> does the same configuration work on 2.10?

I have never used Airflow 2.1 before and I'm trying to use version 3.0 for the first time. Do I need to use version 2.1 in order to integrate with Elasticsearch?

Thank you.

**Comment by jason810496** [comment]
Hi @peter-cheon, could you try setting `elasticsearch.write_stdout` to `'False'`?

I just checked the condition for when the log handler actually writes logs to Elasticsearch, and it turns out that `write_to_es` needs to be `True` **and** `write_stdout` should be `False`.

https://github.com/apache/airflow/blob/main/providers/elasticsearch/src/airflow/providers/elasticsearch/log/es_task_handler.py#L530

**Comment by peter-cheon** [comment]
> write_to_es

hello, @jason810496 
I added the following configuration, but it still doesn't work.

```
  elasticsearch:
    host: 'es-example.local:9200'
    write_stdout: 'False'
    write_to_es: 'True'
    json_format: 'True'
    log_id_template: "{dag_id}_{task_id}_{execution_date}_{try_number}"
```
