### ISSUE TITLE
incorrect helm chart validation for apiServer.env field

### ISSUE THREAD

**Issue by LucasRoesler** [apache/airflow#51190]
### Official Helm Chart version

main (development)

### Apache Airflow version

3.0.0

### Kubernetes Version

1.31

### Helm Chart configuration

```yaml
airflowVersion: 3.0.0
apiServer:
  env:
    - name: AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS
      value: "true"
    - name: AIRFLOW__API_AUTH__JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: airflow-webserver-secret
          key: webserver-secret-key
```

### What happened

I am currently trying to deploy the latest Airflow. During deployment I ran into an issue with `AIRFLOW__API_AUTH__JWT_SECRET` not being set. This is already reported here https://github.com/apache/airflow/issues/50538

To work around this I decided to pass a custom env variable via the `apiServer.env` value. Because this is a secret value, I wanted to use a `valueFrom` configuration. This is supported by the other components, like `webserver` and th same implementation is used by the templates, however, when executing helm, it produces the following validation error 

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
airflow:
- apiServer.env.1: value is required
- apiServer.env.1: Additional property valueFrom is not allowed
```

### What you think should happen instead

The template supports this feature, only the `values.schema.json` needs to be updated, copying the configuration used for the other components. 

I have already validated that the chart works, once the schema is updated. I am prepared to submit a PR, if it is allowed.

### How to reproduce

You can reproduce using the provided values file and then in the airflow repository run 

```bash
$ helm template local ./chart --values bug-values.yaml
```

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
