### ISSUE TITLE
Azure BlobStorage for logging

### ISSUE THREAD

**Issue by JWDobken** [apache/airflow#51944]
### Apache Airflow version

3.0.2

### What happened?

Installed Airflow 3.0.2 with helm but cannot configure Azure Blobstorage for logging.

```logs
api-server [2025-06-19T20:22:17.871+0000] {chained.py:218} WARNING - DefaultAzureCredential failed to retrieve a token from the included credentials.
api-server Attempted credentials:
api-server     EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
api-server Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
api-server     ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable.
api-server     SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
api-server     AzureCliCredential: Azure CLI not found on path
api-server     AzurePowerShellCredential: PowerShell is not installed
api-server     AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authentica
api-server To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.

```

### How to reproduce

I set these values:

```yaml
# Environment variables for all airflow containers
env:
  - name: AIRFLOW_VAR_ENVIRONMENT
    value: dev
  - name: AIRFLOW__LOGGING__REMOTE_LOGGING
    value: "True"
  - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
    value: azure_blob
  - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
    value: "wasb://<container-name>@<storage-account-name>.blob.core.windows.net/airflow/logs"
```

and

```yaml
config:
  logging:
    remote_logging: "True"
    remote_log_conn_id: "azure_blob"
    remote_base_log_folder: "wasb://<container-name>@<storage-account-name>.blob.core.windows.net/airflow/logs"
```

Created the azure connection with:

```cmd
airflow connections add 'azure_blob' \
  --conn-type wasb \
  --conn-extra '{"account_name": "YOUR_ACCOUNT", "account_key": "YOUR_KEY"}'
```

### Operating System

Linux/Kubernetes

### Versions of Apache Airflow Providers

airflow@airflow-dev-api-server-9664568d6-5gkxx:/opt/airflow$ pip freeze | grep apache-airflow
apache-airflow==3.0.2
apache-airflow-core==3.0.2
apache-airflow-providers-amazon==9.8.0
apache-airflow-providers-celery==3.11.0
apache-airflow-providers-cncf-kubernetes==10.5.0
apache-airflow-providers-common-compat==1.7.0
apache-airflow-providers-common-io==1.6.0
apache-airflow-providers-common-messaging==1.0.2
apache-airflow-providers-common-sql==1.27.1
apache-airflow-providers-docker==4.4.0
apache-airflow-providers-elasticsearch==6.3.0
apache-airflow-providers-fab==2.2.0
apache-airflow-providers-ftp==3.13.0
apache-airflow-providers-git==0.0.2
apache-airflow-providers-google==15.1.0
apache-airflow-providers-grpc==3.8.0
apache-airflow-providers-hashicorp==4.2.0
apache-airflow-providers-http==5.3.0
apache-airflow-providers-microsoft-azure==12.4.0
apache-airflow-providers-mysql==6.3.0
apache-airflow-providers-odbc==4.10.0
apache-airflow-providers-openlineage==2.3.0
apache-airflow-providers-postgres==6.2.0
apache-airflow-providers-redis==4.1.0
apache-airflow-providers-sendgrid==4.1.0
apache-airflow-providers-sftp==5.3.0
apache-airflow-providers-slack==9.1.0
apache-airflow-providers-smtp==2.1.0
apache-airflow-providers-snowflake==6.3.1
apache-airflow-providers-ssh==4.1.0
apache-airflow-providers-standard==1.2.0
apache-airflow-task-sdk==1.0.2

### Deployment

Official Apache Airflow Helm Chart

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
