### ISSUE TITLE
Deal with initial username/passwords in the production docker image

### ISSUE THREAD

**Issue by potiuk** [apache/airflow#8606]
**Description**

The Bitnami Airflow Image (https://github.com/bitnami/bitnami-docker-airflow) deals nicely with initial usernames/passwords - this is when you run it through docker-compose and you want to do database initialization. It is likely we should do something similar.

**Use case / motivation**

In some environments, you would like to create an initial username/password when you start the image (after you reset the DB). It would be great to control it via environment variables.

**Related Issues**

Adding Docker Compose example - #8548 , #8605

**Comment by dinigo** [comment]
Well you can simply add a new service in the docker stack/compose to initialize  it:
```
version: '3.6'
services:
  init:
    image: apache/airflow:1.10.10
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql://airflow:airflow@mysql:3306/airflow
    entrypoint: "airflow upgradedb && airflow create_user -f none -l none -u $USER -p $PASSWORD -e $EMAIL"
  mysql:
    image: mysql
    environment:
      DB_USER: airflow
      DB_PASSWORD: airflow
      DB_NAME: airflow
```
I think something like this will do. It can be added to the entrypoint script also, but you can initialize any database with a matching version airflow installation. To initialize my airflow db for the docker stack deployments I:
1. Spin up the db
2. Setup the env variables to connect to the DB in local (fernet key and sql_alchemy_conn)
3. Init the db and create user from local environment
4 Deploy the stack with everything initialized

**Comment by resdevd** [comment]
I think the default username, password should be declared in env variables, Airflow Image's entrypoint checks for these variables and creates a user. If the user already exist, the current default behavior is a graceful "User already exist" message.

**Comment by gontcharovd** [comment]
> Well you can simply add a new service in the docker stack/compose to initialize it:
> 
> ```
> version: '3.6'
> services:
>   init:
>     image: apache/airflow:1.10.10
>     environment:
>       AIRFLOW__CORE__SQL_ALCHEMY_CONN: mysql://airflow:airflow@mysql:3306/airflow
>     entrypoint: "airflow upgradedb && airflow create_user -f none -l none -u $USER -p $PASSWORD -e $EMAIL"
>   mysql:
>     image: mysql
>     environment:
>       DB_USER: airflow
>       DB_PASSWORD: airflow
>       DB_NAME: airflow
> ```
> 
> I think something like this will do. It can be added to the entrypoint script also.
> 
> But you can initialize any database with a matching version airflow installation. To initialize my airflow db for the docker stack deployments I do the following
> 
> 1. Spin up the db
> 2. Setup the env variables to connect to the DB in local (fernet key and sql_alchemy_conn)
> 3. Init the db and create user from local environment
>    4 Deploy the stack with everything initialized

I have an issue with the `&&` in this line when I tried adding this init service to my docker-compose:

```entrypoint: "airflow upgradedb && airflow create_user -f none -l none -u $USER -p $PASSWORD -e $EMAIL"```

Did you manage to get it working in your case?
I'm still not clear on the recommended way to initialize usernames/passwords when running the containers the first time.

Are there any new recommendations about this topic?

**Comment by dinigo** [comment]
Yes. But I had to split the script from the template for the same reason

Here the service inside the Docker-Compose.yml
```yml
init:
    <<: *airflow-template
    volumes:
      - ./init-airflow.sh:/entrypoint
    depends_on:
      - database
```
And the simple script that locks like so
```bash
airflow db upgrade
if [ $(users list | grep \"${INIT_EMAIL}\") ]
then
    echo \"User ${INIT_EMAIL} already exists\"
else
    airflow users create \
        --firstname Admin \
	--lastname None \
	--email \"${INIT_EMAIL}\" \
	--password \"${INIT_PASSWORD}\" \
       	--username \"${INIT_USER}\" \
	--role Admin
fi
```

I reuse the users, password and email for several config variables that I define in the"Airflow-template" environment.

This is working
