### ISSUE TITLE
Webserver OOM killed by Kubernetes when using KubernetesExecutor

### ISSUE THREAD

**Issue by LarsAlmgren** [apache/airflow#8779]
**Apache Airflow version**: 1.10.8

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.17.5

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.6 LTS
- **Kernel** (e.g. `uname -a`): `Linux salt 4.4.0-1106-aws #117-Ubuntu SMP Wed Apr 8 09:52:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**What happened**:

We switched from `LocalExecutor` to `KubernetesExecutor` and noticed that the webserver started to get OOM killed by Kubernetes. We solved it by increasing the memory resource request / limit in Kubernetes.

**What you expected to happen**:

I did not expect the webserver to be dependent on what executor is used.

**How to reproduce it**:

We ran the webserver before using `KubernetesExecutor` with:
```
resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
```

Run the webserver with minimal resources and then switch to `KubernetesExecutor`.

**Anything else we need to know**:

We have noticed this in both environments where we started using `KubernetesExecutor`. Both environments have the same setup.
