### ISSUE TITLE
AIRFLOW__KUBERNETES__AFFINITY AIRFLOW__KUBERNETES__TOLERATIONS how to use?

### ISSUE THREAD

**Issue by KIRY4** [apache/airflow#9374]
Hello Everyone! I need some help with KubernetesExecutor. Anybody knows how exactly use these two values AIRFLOW__KUBERNETES__AFFINITY AIRFLOW__KUBERNETES__TOLERATIONS. Link from documentation is broken: https://airflow.apache.org/docs/stable/configurations-ref.html. So can anybody share with me examples of usage of this parmaters??

**Comment by KIRY4** [comment]
Example of usage:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-cm
  namespace: airflow
data:
  k8spodstolerations: '[{ "key": "type", "operator": "Equal", "value": "tool", "effect": "NoSchedule" }]'
  k8spodsaffinity: '{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"type","operator":"In","values":["tool"]}]}]}}}'
```
