### ISSUE TITLE
MySQL support in Helm airflow database config

### ISSUE THREAD

**Issue by Swalloow** [apache/airflow#9627]
**Apache Airflow version**: 1.10.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): 1.16

**Environment**:

- **Cloud provider or hardware configuration**: AWS EKS
- **OS** (e.g. from /etc/os-release): AWS EKS default AMI
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**: airflow metadata db as AWS Aurora 5.6.4+

**What happened**: 

Deploy official helm chart from master branch and update `values.yaml` file as below.
I use AWS Aurora as database.

```
# Airflow database config
data:
  # If secret names are provided, use those secrets
  metadataSecretName: ~
  resultBackendSecretName: ~

  # Otherwise pass connection values in
  # FIXME:
  metadataConnection:
    user: MYAURORA_USER
    pass: MYAURORA_PASSWORD
    host: MYAURORA_URL
    port: 3306
    db: airflow
    sslmode: disable
  resultBackendConnection:
    user: MYAURORA_USER
    pass: MYAURORA_PASSWORD
    host: MYAURORA_URL
    port: 3306
    db: airflow
    sslmode: disable
```

After install helm chart, an error occurred in scheduler initContainer phase.

```
$ kubectl get po -n airflow
NAME                                     READY   STATUS       RESTARTS   AGE
airflow-dev-create-user-v84lr            0/1     Error        1          18s
airflow-dev-scheduler-695894dbc7-jz9qx   0/2     Init:Error   1          18s
airflow-dev-statsd-7f5fbdc8c4-49487      1/1     Running      0          18s
airflow-dev-webserver-547664465f-hqh54   0/1     Init:0/1     0          18s

$ kubectl describe po -n airflow airflow-dev-scheduler-695894dbc7-jz9qx
...
Init Containers:
  run-airflow-migrations:
    Container ID:  docker://9b431e2584a68afdcdacd7f7043e6facd46c38ab577dd427f14a3a79782a934d
    Image:         apache/airflow:1.10.10.1-alpha2-python3.6
    Image ID:      docker-pullable://apache/airflow@sha256:f44d93b67f58a761aab9c4ed5804b4df2fd15050a9c561413d722eb619c064d5
    Port:          <none>
    Host Port:     <none>
    Args:
      bash
      -c
      airflow upgradedb || airflow db upgrade
    State:          Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 02 Jul 2020 18:18:09 +0900
      Finished:     Thu, 02 Jul 2020 18:18:15 +0900
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 02 Jul 2020 18:17:23 +0900
      Finished:     Thu, 02 Jul 2020 18:17:29 +0900
    Ready:          False
    Restart Count:  4
    Environment:
      AIRFLOW__CORE__FERNET_KEY:        <set to the key 'fernet-key' in secret 'airflow-dev-fernet-key'>        Optional: false
      AIRFLOW__CORE__SQL_ALCHEMY_CONN:  <set to the key 'connection' in secret 'airflow-dev-airflow-metadata'>  Optional: false
      AIRFLOW_CONN_AIRFLOW_DB:          <set to the key 'connection' in secret 'airflow-dev-airflow-metadata'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from airflow-dev-scheduler-serviceaccount-token-vh5td (ro)
```

**What you expected to happen**:

I expected to support mysql addresses as well.
However, if you look at the secret yaml file, it is fixed at db+postgresql:// address.
(`chart/templates/secrets/result-backend-connection-secret.yaml`)

**How to reproduce it**:

helm install . --name airflow --namespace airflow

**Anything else we need to know**:
