### ISSUE TITLE
Gantt chart for running dag doesn't show up in Airflow 1.10.11

### ISSUE THREAD

**Issue by hossein-jazayeri** [apache/airflow#9813]
**Apache Airflow version**: 1.10.11

**Kernel** (e.g. `uname -a`): Linux 20cb927bb9ef 5.3.0-1017-aws #18~18.04.1-Ubuntu SMP Wed Apr 8 15:12:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:
Gantt chart for running dags doesn't show up in RBAC UI & gives javascript errors:
```javascript
d3.min.js:1 Error: <rect> attribute transform: Expected number, "translate(NaN,8)".
```
![Screenshot from 2020-07-14 11-31-15](https://user-images.githubusercontent.com/1238597/87410180-3dd83f00-c5c6-11ea-87f3-34b18447e81d.png)

**How to reproduce it**:
By checking the gantt chart of a **running** dag

**Comment by kaxil** [comment]
I was not able to reproduce this. Anyone else can reproduce this, please?

@hossein-jazayeri Is this RBAC UI or Flask-admin based UI

**Comment by hossein-jazayeri** [comment]
It's RBAC UI

**Comment by potiuk** [comment]
I could not reproduce it via RBAC UI either. @hossein-jazayeri . Can you share more information about your browser and check some other browsers? This looks like a browser compatibility issue.

**Comment by hossein-jazayeri** [comment]
It's happening on both Firefox 78.0.1 (64-bit) & Chrome 83.0.4103.116 (Official Build) (64-bit)

**Comment by hossein-jazayeri** [comment]
I can see the gantt chart for not running dags btw, only it doesn't show up for running ones

**Comment by kaxil** [comment]
I am on the same version though:

```
Version 83.0.4103.116 (Official Build) (64-bit)
```

**Comment by potiuk** [comment]
Let me also try it.

**Comment by potiuk** [comment]
While running my version I also hit this problem (with locale): https://github.com/apache/airflow/issues/9100 Marking that to solve in  .12

**Comment by kaxil** [comment]
> While running my version I also hit this problem (with locale): #9100 Marking that to solve in .12

Were you able to reproduce this issue  (#9813) too?

**Comment by potiuk** [comment]
Looking at it. And BTW Just closed #9100  - it was caused by cookies. If you switch between old UI and new UI, you need to clear cookies :)

**Comment by potiuk** [comment]
Confirmed:

![Screenshot from 2020-07-15 14-29-55](https://user-images.githubusercontent.com/595491/87545423-2c676380-c6a8-11ea-97e5-f59d219e18c0.png)

**Comment by potiuk** [comment]
Static missing ?

**Comment by potiuk** [comment]
Could not reproduce :(

**Comment by waltermaldonado** [comment]
I'm also having this problem.
![image](https://user-images.githubusercontent.com/8573950/89207788-aeed8f80-d591-11ea-8fdd-95e5a4077b60.png)

**Comment by fallen-up** [comment]
@potiuk @kaxil 
We have the same issue:
airflow 1.10.11
```
[webserver]
rbac = True
```
![airflow_gantt](https://user-images.githubusercontent.com/11389898/89641181-cabaa380-d8b9-11ea-82ac-bbc3862fe3ec.png)

Tests were performed in incognito mode and in different browsers (latest stable builds of Chrome, Chromium, Brave, Firefox) with clearing cookies.
On airflow 1.10.9, 1.10.10 problems were not detected.

**Comment by thesuperzapper** [comment]
@potiuk I am still getting this on 1.10.12?

**Comment by ibotheperfect** [comment]
I have same issue too on 1.10.12

**Comment by kaxil** [comment]
Can someone here post the steps for reproduction since I and @potiuk weren't able to reproduce it?

Also please list your chrome versions

**Comment by potiuk** [comment]
Yeah. I'd also love some reproducibility path here. Maybe you can try to help us and narrow it down @thesuperzapper  @waltermaldonado @hossein-jazayeri  by trying different combinations of browsers, using different browser profiles, clearing the cache, etc. 

I saw similar things happening when - during development - you use the same URL to test 1.10* and 2.* version of Airflow for example, or simply different versions of Airflow. In such cases the scripts and cookies get cached from different versions of Airflow and you need to clear cache to try it out  - so if you could try it out on your systems that would help us to narrow down the issue.

**Comment by hossein-jazayeri** [comment]
The issue is still happening for me as well on both 1.10.11 & 1.10.12 on both Chrome, Chromium & Firehose.
I'm using **RBAC UI**
Chrome version: **Version 85.0.4183.102 (Official Build) (64-bit)**
Firehose version: **80.0.1 (64-bit)**
Chromium version (fresh install): **Version 87.0.4267.0 (Developer Build) (64-bit)**

It's happening on an incognito window as well.

Webserver log of the request:
```
[17/Sep/2020:13:20:36 +0000] "GET /static/dist/ganttChartD3v2.***.js HTTP/1.1" 304 0 "https://airflow.***/gantt?dag_id=***&root=" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4267.0 Safari/537.36"
[17/Sep/2020:13:20:36 +0000] "GET /static/appbuilder/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 404 3882 "https://airflow.***/static/appbuilder/css/bootstrap.min.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4267.0 Safari/537.36"
```

**Comment by ibotheperfect** [comment]
> Yeah. I'd also love some reproducibility path here. Maybe you can try to help us and narrow it down @thesuperzapper @waltermaldonado @hossein-jazayeri @ibotheperfect by trying different combinations of browsers, using different browser profiles, clearing the cache, etc.
> 
> I saw similar things happening when - during development - you use the same URL to test 1.10* and 2.* version of Airflow for example, or simply different versions of Airflow 1.10. In such cases the scripts and cookies get cached from different versions of Airflow and you need to clear cache to fix it - so if you could try it out on your systems that would help us to narrow down the issue.

I deployed airflow via docker by using bitnami's image. This is happening both 1.10.11 and 1.10.12 versions. I also tried both chrome and firefox. Results are same

```
version: '3'
services:
  postgresql:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  redis:
    image: 'redis:5.0.5'
 
  airflow:
    image: bitnami/airflow:1.10.12
    environment:
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow
      - AIRFLOW_DATABASE_PASSWORD=airflow
      - AIRFLOW_FERNET_KEY=****
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_PASSWORD=airflow
      - AIRFLOW_USERNAME=admin
      - AIRFLOW_LOAD_EXAMPLES=no
    ports:
      - '8080:8080'
    volumes:
      - ./logs:/opt/bitnami/airflow/logs
      - ./dags:/opt/bitnami/airflow/dags

  scheduler:
    image: bitnami/airflow-scheduler:1.10.12
    environment:
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow
      - AIRFLOW_DATABASE_PASSWORD=airflow
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_FERNET_KEY=****
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - ./logs:/opt/bitnami/airflow/logs
      - ./dags:/opt/bitnami/airflow/dags

  worker:
    image: bitnami/airflow-worker:1.10.12
    environment:
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow
      - AIRFLOW_DATABASE_PASSWORD=airflow
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_FERNET_KEY=****
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - ./logs:/opt/bitnami/airflow/logs
      - ./dags:/opt/bitnami/airflow/dags
```
